//! Noun-verb command modules for the `praxis-l4` binary.
//!
//! GENERATED by `ggen sync` from `schema/praxis.ttl` (praxis:CliCommand
//! instances with `praxis:inCrate praxis:CrateLean`). Do not edit by hand —
//! add a `CliCommand` instance to the ontology instead.
//!
//! Each file's stem is a CLI noun; each `#[verb]` fn inside is a verb under
//! that noun. Mirrors `crates/ggen/src/verbs/mod.rs`'s own generated shape.

pub mod l4;

#[linkme::distributed_slice(::clap_noun_verb::cli::registry::__NOUN_REGISTRY)]
static REGISTER_L4_NOUN: fn() = register_l4_noun;
fn register_l4_noun() {
    ::clap_noun_verb::cli::registry::CommandRegistry::register_noun(
        "l4",
        "Lean 4/Lake kernel admission gate: verify, no-sorry audit, corpus reconciliation, and receipt reporting.",
    );
}

