{application,arazzo_runner,
             [{description,"Arazzo Runner - Workflow Execution Engine wrapping air_core"},
              {vsn,"0.1.0"},
              {registered,[arazzo_runner_root_sup,arazzo_runner_sup,
                           arazzo_runner_dispatch_sup]},
              {applications,[kernel,stdlib,crypto]},
              {mod,{arazzo_runner_app,[]}},
              {env,[]},
              {modules,[arazzo_runner_app,arazzo_runner_blake3,
                        arazzo_runner_broker,arazzo_runner_dispatch_statem,
                        arazzo_runner_dispatch_sup,
                        arazzo_runner_event_receipt,arazzo_runner_identity,
                        arazzo_runner_root_sup,arazzo_runner_sup,
                        arazzo_runner_workflow]}]}.
