/-
con:provo

Each receipt maps to a PROV-O shape: the admitted observation a `prov:Entity`, the
manufacture a `prov:Activity` that used it, the artifact a `prov:Entity` generated
by the activity, and the chain link a `prov:wasDerivedFrom` edge, SHACL-validated
against `sr:SharedReceiptV1`.

Bare Lean 4 core, no mathlib. Reuses `Frame`/`Chain` from def:chain verbatim.
This is a construction: it builds the PROV-O shape assigned to each frame/chain
link, with no proof obligation beyond type-checking.
-/

/- def:frame (dependency, reproduced verbatim from def_chain.lean) -/
structure Frame where
  instruction_id : UInt64
  fired_mask     : UInt64
  denial         : UInt8
  obj_refs       : Fin 8 → UInt64
  ts_ns          : UInt64
  activity_idx   : UInt32
  node_kind      : UInt8
  prior_hash     : UInt64

/- def:chain (dependency, reproduced verbatim from def_chain.lean) -/
def Chain := List Frame

/-- A `prov:Entity`: an opaque identifier for something that participates in
    provenance (observations, artifacts). -/
structure Entity where
  id : Nat
deriving Repr, DecidableEq

/-- A `prov:Activity`: an opaque identifier for the manufacture step that
    transforms an admitted observation into an artifact. -/
structure Activity where
  id : Nat
deriving Repr, DecidableEq

/-- A `prov:wasDerivedFrom` edge between two entities: the chain link, recording
    that the successor artifact was derived from the predecessor artifact. -/
structure WasDerivedFrom where
  source : Entity
  target : Entity
deriving Repr, DecidableEq

/-- A `prov:used` edge: the activity used the admitted observation as input. -/
structure Used where
  activity : Activity
  entity   : Entity
deriving Repr, DecidableEq

/-- A `prov:wasGeneratedBy` edge: the artifact was generated by the activity. -/
structure WasGeneratedBy where
  entity   : Entity
  activity : Activity
deriving Repr, DecidableEq

/-- The full PROV-O shape attached to a single receipt (one `Frame`): the
    admitted observation entity, the manufacture activity that used it, the
    artifact entity it generated, and the two edges (`used`, `wasGeneratedBy`)
    that relate them. This is exactly the shape SHACL-validated against
    `sr:SharedReceiptV1`. -/
structure ReceiptShape where
  observation : Entity
  manufacture : Activity
  artifact    : Entity
  used        : Used
  generated   : WasGeneratedBy

/-- The PROV-O shape assigned to a single frame `fr`, indexed by its position `i`
    in the chain: the admitted observation, manufacture activity, and artifact
    entity are each built from `i` and the frame's own fields so that distinct
    frames receive distinct PROV-O identifiers. -/
def frameShape (i : Nat) (fr : Frame) : ReceiptShape :=
  let obs : Entity := ⟨2 * i⟩
  let act : Activity := ⟨fr.activity_idx.toNat⟩
  let art : Entity := ⟨2 * i + 1⟩
  { observation := obs
    manufacture := act
    artifact    := art
    used        := ⟨act, obs⟩
    generated   := ⟨art, act⟩ }

/-- The chain link between consecutive receipts: a `prov:wasDerivedFrom` edge
    from the predecessor artifact to the successor artifact. -/
def chainLink (prev cur : ReceiptShape) : WasDerivedFrom :=
  ⟨prev.artifact, cur.artifact⟩

/-- The full PROV-O construction for a chain: the per-frame receipt shapes
    (indexed by position) together with the `wasDerivedFrom` edges linking each
    receipt's artifact to the next receipt's artifact. -/
structure ChainProvShape where
  shapes : List ReceiptShape
  links  : List WasDerivedFrom

/-- Build the `ChainProvShape` for a chain `l`: map each frame to its
    `ReceiptShape` (indexed by position), then derive the consecutive
    `wasDerivedFrom` links from the resulting list of shapes. -/
def chainProvShape (l : Chain) : ChainProvShape :=
  let shapes := (l.zipIdx).map (fun (fr, i) => frameShape i fr)
  let links := (shapes.zip (shapes.drop 1)).map (fun (prev, cur) => chainLink prev cur)
  { shapes := shapes, links := links }
