/- def:lifecat
   Life is the free category on the linear quiver
     Raw --j--> Val --a--> Admd --r--> Rcpt
   with four objects and three generating arrows judge, admit, receipt.

   We model this as the free category (path category) on a linear
   quiver with four objects, represented directly as an inductive
   family of paths `LifeHom x y` indexed by the four objects, together
   with identity and composition, generated by the three arrows
   judge, admit, receipt. -/

inductive LifeObj where
  | Raw : LifeObj
  | Val : LifeObj
  | Admd : LifeObj
  | Rcpt : LifeObj

open LifeObj

/-- Morphisms of the free category on the linear quiver
    Raw → Val → Admd → Rcpt, generated by `judge`, `admit`, `receipt`,
    plus identities and their compositions. -/
inductive LifeHom : LifeObj → LifeObj → Type where
  | id       : (x : LifeObj) → LifeHom x x
  | judge    : LifeHom Raw Val
  | admit    : LifeHom Val Admd
  | receipt  : LifeHom Admd Rcpt
  | comp     : {x y z : LifeObj} → LifeHom x y → LifeHom y z → LifeHom x z

/-- The free category `Life` on the linear quiver, packaged as a
    structure bundling objects, generating arrows, and composition. -/
structure LifeCat where
  Obj := LifeObj
  Hom := LifeHom
  idHom : (x : LifeObj) → LifeHom x x := LifeHom.id
  compHom : {x y z : LifeObj} → LifeHom x y → LifeHom y z → LifeHom x z := LifeHom.comp

def Life : LifeCat := {}
