/-
def:reachcone

Let N ∈ Z^(p×|T|) have columns δ_t = m⁺_t - m⁻_t. A firing sequence with
Parikh vector x ≥ 0 reaches m = m₀ + N x. The reachable set lies in the
integer points of m₀ + cone(N).

Bare Lean 4 core formalization (no mathlib): places indexed by `Fin p`,
transitions indexed by `Fin q` (standing for `|T|`). The incidence matrix
`N` is a function `Fin q → Fin p → ℤ` (column `t` is the effect vector
`δ_t` on each place). A Parikh vector `x : Fin q → ℤ` is nonnegative if
every coordinate is. Firing `x` from marking `m₀` reaches the marking
obtained by adding the `N`-weighted combination of `x` to `m₀`.

Since mathlib is unavailable, the sum over transitions `∑_t x t * N t i`
is built from a plain structural recursion over `Fin q` (via `Nat.rec`
on the underlying index), rather than `Finset.sum`.
-/

/-- Sum `∑_{t < q} f t` for `f : Fin q → ℤ`, by recursion on `q`. -/
def finSum : (q : Nat) → (Fin q → Int) → Int
  | 0, _ => 0
  | Nat.succ n, f => finSum n (fun i => f i.castSucc) + f (Fin.last n)

/-- Nonnegativity of a Parikh vector `x : Fin q → ℤ`. -/
def NonnegParikh {q : Nat} (x : Fin q → Int) : Prop :=
  ∀ t : Fin q, 0 ≤ x t

/-- The `i`-th coordinate of the `N`-weighted combination of `x`. -/
def weighted {p q : Nat} (N : Fin q → Fin p → Int) (x : Fin q → Int)
    (i : Fin p) : Int :=
  finSum q (fun t => x t * N t i)

/-- The marking reached from `m₀` by firing Parikh vector `x` under
    incidence matrix `N : Fin q → Fin p → ℤ` (column `t` of `N` is the
    effect vector `δ_t = m⁺_t - m⁻_t`): `m = m₀ + N x`. -/
def reach {p q : Nat} (N : Fin q → Fin p → Int) (m₀ : Fin p → Int)
    (x : Fin q → Int) : Fin p → Int :=
  fun i => m₀ i + weighted N x i

/-- The integer cone generated by the columns of `N`: all nonnegative
    integer combinations `∑ x t • N t`. -/
def cone {p q : Nat} (N : Fin q → Fin p → Int) (v : Fin p → Int) : Prop :=
  ∃ x : Fin q → Int, NonnegParikh x ∧ v = fun i => weighted N x i

/-- The reachable set from `m₀` under incidence matrix `N`: all markings
    obtainable by firing some nonnegative Parikh vector, `m₀ + N x` for
    `x ≥ 0`. -/
def reachableSet {p q : Nat} (N : Fin q → Fin p → Int) (m₀ : Fin p → Int)
    (m : Fin p → Int) : Prop :=
  ∃ x : Fin q → Int, NonnegParikh x ∧ m = reach N m₀ x

/-- The reachable set lies inside `m₀ + cone(N)`: every reachable marking
    is `m₀` plus a point of the cone generated by the columns of `N`. -/
def reachSubsetConeShift {p q : Nat} (N : Fin q → Fin p → Int)
    (m₀ : Fin p → Int) : Prop :=
  ∀ m : Fin p → Int, reachableSet N m₀ m →
    ∃ v : Fin p → Int, cone N v ∧ m = fun i => m₀ i + v i
