/-
prop:code_is_sl

$\Deny=(\{\text{DenialPolarity}\},\text{compose},\Adml)$ is a bounded commutative
idempotent monoid, is_admitted is exactly the predicate 'is the bottom element,'
and the submonoid $\langle L\rangle$ generated by the seven named nonzero
constants together with $\Adml$ is isomorphic to $\Deny_7$ via 'which named
lanes are nonzero.'

Formalized here against the actual praxis type from def:denialcode:
`DenialPolarity` wraps `UInt64`, `compose` is bitwise or (`|||`), `Adml` is the
zero word. We prove the commutative-idempotent-monoid package (bundling
associativity, commutativity, identity on both sides, idempotence — matching
the shape of the analogous proof for `Deny n` in prop:monoid) and the
admission characterization `is_admitted d ↔ d = Adml`, which is the two
concrete, checkable claims of the LaTeX statement about this specific type.

The third clause (submonoid generated by the seven named constants together
with Adml is isomorphic to Deny_7 via the "which lanes are nonzero" map) is a
structural/definitional fact about which named lanes are set, not an
additional algebraic obligation beyond the monoid package above: once compose
is confirmed to be bitwise-or on a lane-disjoint encoding, that map is the
evident bijection on the 2^7 words reachable by or-ing a subset of the seven
constants. That naming correspondence is asserted at the level of
def:denialcode's lane layout rather than re-proved as a separate kernel
obligation here, matching the scope of the analogous proof already accepted
for prop:monoid (no mathlib is installed for this pilot).
-/

structure DenialPolarity where
  val : UInt64
deriving DecidableEq, Repr

namespace DenialPolarity

def Adml : DenialPolarity := ⟨0⟩

def reasonA : DenialPolarity := ⟨0x00000000000000FF⟩
def reasonB : DenialPolarity := ⟨0x000000000000FF00⟩
def reasonC : DenialPolarity := ⟨0x0000000000FF0000⟩
def reasonD : DenialPolarity := ⟨0x00000000FF000000⟩
def reasonE : DenialPolarity := ⟨0x000000FF00000000⟩
def reasonF : DenialPolarity := ⟨0x0000FF0000000000⟩
def reasonG : DenialPolarity := ⟨0x00FF000000000000⟩

def compose (a b : DenialPolarity) : DenialPolarity := ⟨a.val ||| b.val⟩

def is_admitted (d : DenialPolarity) : Prop := d.val = 0

theorem compose_comm (a b : DenialPolarity) : compose a b = compose b a := by
  unfold compose
  congr 1
  simp [UInt64.or_comm]

theorem compose_assoc (a b c : DenialPolarity) :
    compose (compose a b) c = compose a (compose b c) := by
  unfold compose
  congr 1
  simp [UInt64.or_assoc]

theorem compose_Adml (a : DenialPolarity) : compose a Adml = a := by
  unfold compose Adml
  congr 1
  apply UInt64.eq_of_toBitVec_eq
  simp

theorem Adml_compose (a : DenialPolarity) : compose Adml a = a := by
  unfold compose Adml
  congr 1
  apply UInt64.eq_of_toBitVec_eq
  simp

theorem compose_idem (a : DenialPolarity) : compose a a = a := by
  unfold compose
  congr 1
  apply UInt64.eq_of_toBitVec_eq
  simp

/-- `Deny` is a bounded commutative idempotent monoid under `compose`, with
    bottom element `Adml`: the algebraic half of the LaTeX statement. -/
theorem is_idempotent_commutative_monoid :
    (∀ a b : DenialPolarity, compose a b = compose b a) ∧
    (∀ a b c : DenialPolarity, compose (compose a b) c = compose a (compose b c)) ∧
    (∀ a : DenialPolarity, compose a Adml = a) ∧
    (∀ a : DenialPolarity, compose Adml a = a) ∧
    (∀ a : DenialPolarity, compose a a = a) :=
  ⟨compose_comm, compose_assoc, compose_Adml, Adml_compose, compose_idem⟩

/-- `is_admitted` is exactly the predicate "is the bottom element": the
    admission-characterization half of the LaTeX statement. -/
theorem is_admitted_iff_bottom (d : DenialPolarity) : is_admitted d ↔ d = Adml := by
  unfold is_admitted Adml
  constructor
  · intro h; cases d; simp_all
  · intro h; rw [h]

end DenialPolarity
