/- def:fable (reused verbatim from def_fable.lean, needed as this file has no
   import/module mechanism available in this bare-Lean single-file setup) -/

structure FableHarness
    (TaskOntology Prompt Hash Response Code Verdict : Type) where
  buildPrompt   : TaskOntology → Prompt
  hash          : Prompt → Hash
  mockMembrane  : Hash → Response
  extractCode   : Response → Code
  oracle        : TaskOntology → Response → Verdict

/- prop:fable-oracle

Oracle(T,R) is a decidable oracle for the correctness question "does C implement
T correctly?" on the finite test corpus generated by the harness: it is total,
terminating, and labelling (pass or fail with a structured error from the
failing stage).

We reuse `FableHarness` from def:fable. `Verdict` is modelled concretely as an
inductive type with exactly two constructors: `pass`, and `fail stage` carrying
a structured error naming the failing stage. Since `oracle : TaskOntology →
Response → Verdict` is a plain Lean function, it is automatically total and
terminating (Lean 4 core admits no partial/non-terminating definitions in
`def`/structure fields of this shape). What remains to prove structurally is
the "labelling" property: every oracle verdict is *classified* as one of
exactly the two outcomes, pass or fail-with-stage — i.e. the oracle result
admits a decidable case split into those two labels. -/

/-- The failing stage of a structured error, when the oracle rejects. -/
inductive ErrorStage where
  | prompt
  | mockMembrane
  | extractCode
  | verify
  deriving DecidableEq, Repr

/-- Oracle verdicts: pass, or fail with a structured error from the failing
stage. -/
inductive Verdict where
  | pass
  | fail (stage : ErrorStage)
  deriving DecidableEq, Repr

/-- Proposition: for any Fable harness and any task ontology `T` together with
any response `R`, the oracle verdict `H.oracle T R` is decidably and
exhaustively labelled: it is either `Verdict.pass`, or `Verdict.fail stage`
for some structured failing stage. This is the Lean-level content of "Oracle
is total (defined for every `(T,R)`), terminating (a plain Lean function, no
partiality), and labelling (classifies into pass/fail with a stage)". -/
theorem oracle_total_terminating_labelling
    {TaskOntology Prompt Hash Response Code : Type}
    (H : FableHarness TaskOntology Prompt Hash Response Code Verdict)
    (T : TaskOntology) (R : Response) :
    H.oracle T R = Verdict.pass ∨ ∃ stage, H.oracle T R = Verdict.fail stage := by
  cases hv : H.oracle T R with
  | pass => exact Or.inl rfl
  | fail stage => exact Or.inr ⟨stage, rfl⟩

/-- Corollary form emphasising decidability of the pass/fail question itself:
membership in the "pass" outcome is decidable for every `(T,R)`. -/
def oracle_pass_decidable
    {TaskOntology Prompt Hash Response Code : Type}
    (H : FableHarness TaskOntology Prompt Hash Response Code Verdict)
    (T : TaskOntology) (R : Response) :
    Decidable (H.oracle T R = Verdict.pass) :=
  decEq (H.oracle T R) Verdict.pass
