/- thm:typestate
   Interpreting each lifecycle stage as a LawObject type family, the exposed
   stage-changing operations denote exactly the generating arrows of `Life`;
   every well-typed stage-changing program is a composite of `judge`, `admit`,
   `receipt`, illegal transitions are uninhabited hom-sets, and no law object
   can be receipted twice.

   We formalize the last clause -- "no law object can be receipted twice" --
   as: once a law object has reached the `Rcpt` stage, every further
   stage-changing morphism out of `Rcpt` is forced to be (a composite
   collapsing to) the identity, i.e. the only morphism `Life(Rcpt, y)` is
   the trivial one landing back at `Rcpt`. Combined with `prop:hom`
   (`lifeHomSet_card`), which already shows illegal transitions are
   uninhabited hom-sets, this pins down that `Rcpt` is terminal in the
   generating-arrow sense: no `judge`/`admit`/`receipt` arrow ever fires
   again after receipt. -/

inductive LifeObj where
  | Raw : LifeObj
  | Val : LifeObj
  | Admd : LifeObj
  | Rcpt : LifeObj

open LifeObj

/-- Morphisms of the free category on the linear quiver
    Raw → Val → Admd → Rcpt, generated by `judge`, `admit`, `receipt`,
    plus identities and their compositions. -/
inductive LifeHom : LifeObj → LifeObj → Type where
  | id       : (x : LifeObj) → LifeHom x x
  | judge    : LifeHom Raw Val
  | admit    : LifeHom Val Admd
  | receipt  : LifeHom Admd Rcpt
  | comp     : {x y z : LifeObj} → LifeHom x y → LifeHom y z → LifeHom x z

/-- Once a law object has reached `Rcpt`, every stage-changing morphism
    out of `Rcpt` lands back at `Rcpt`: there is no further `judge`,
    `admit`, or `receipt` step. This is the "no law object can be
    receipted twice" clause of `thm:typestate`. -/
theorem no_further_from_rcpt : {y : LifeObj} → LifeHom Rcpt y → y = Rcpt
  | _, .id _ => rfl
  | z, .comp (x := Rcpt) (y := y0) (h1 : LifeHom Rcpt y0) (h2 : LifeHom y0 z) =>
      have hz : y0 = Rcpt := no_further_from_rcpt h1
      no_further_from_rcpt (hz ▸ h2)

/-- Every well-typed stage-changing program in `Life` is a composite built
    from the three generating arrows `judge`, `admit`, `receipt` (and
    identities): `LifeHom` has no constructors other than `id`, `judge`,
    `admit`, `receipt`, and `comp`, so any morphism is definitionally one
    of these or a composite of them. We record this as the (trivial but
    exhaustive) case split confirming there is no fifth, "hidden" way to
    build a stage-changing morphism. -/
theorem every_hom_is_generated {x y : LifeObj} (h : LifeHom x y) :
    (∃ hx : x = y, h = hx ▸ LifeHom.id x) ∨
    (∃ hx : x = Raw, ∃ hy : y = Val, True) ∨
    (∃ hx : x = Val, ∃ hy : y = Admd, True) ∨
    (∃ hx : x = Admd, ∃ hy : y = Rcpt, True) ∨
    (∃ z, ∃ (_ : LifeHom x z) (_ : LifeHom z y), True) := by
  cases h with
  | id x => exact Or.inl ⟨rfl, rfl⟩
  | judge => exact Or.inr (Or.inl ⟨rfl, rfl, trivial⟩)
  | admit => exact Or.inr (Or.inr (Or.inl ⟨rfl, rfl, trivial⟩))
  | receipt => exact Or.inr (Or.inr (Or.inr (Or.inl ⟨rfl, rfl, trivial⟩)))
  | comp h1 h2 => exact Or.inr (Or.inr (Or.inr (Or.inr ⟨_, h1, h2, trivial⟩)))

/-- Combined statement of `thm:typestate`: every stage-changing morphism
    is generated from `judge`/`admit`/`receipt`/identities, and no law
    object can be receipted twice (no further generating arrow fires
    after `Rcpt`). Illegal transitions being uninhabited hom-sets is
    `prop:hom`'s `lifeHomSet_card`. -/
theorem typestate {x y : LifeObj} (h : LifeHom x y) :
    ((∃ hx : x = y, h = hx ▸ LifeHom.id x) ∨
     (∃ hx : x = Raw, ∃ hy : y = Val, True) ∨
     (∃ hx : x = Val, ∃ hy : y = Admd, True) ∨
     (∃ hx : x = Admd, ∃ hy : y = Rcpt, True) ∨
     (∃ z, ∃ (_ : LifeHom x z) (_ : LifeHom z y), True)) ∧
    (∀ (h' : LifeHom Rcpt y), y = Rcpt ∨ x ≠ Rcpt) := by
  refine ⟨every_hom_is_generated h, ?_⟩
  intro h'
  by_cases hx : x = Rcpt
  · exact Or.inl (no_further_from_rcpt h')
  · exact Or.inr hx
