/-
thm:firedhom

$\firedmap$ is a homomorphism of bounded commutative idempotent monoids:
$\firedmap(\Adml)=\bm 0$ and $\firedmap(\text{compose}(a,b))=\firedmap(a)\lor\firedmap(b)$
for all $a,b\in\Deny$; restricted to $\langle L\rangle$ it is a monoid isomorphism onto
the seven-bit image $\{0\}\times\{0,1\}^{7}$.

Formalized against the actual praxis types from def:fired and prop:code_is_sl:
`DenialPolarity` wraps `UInt64`, `firedmap` extracts, per byte lane, the
branchless nonzero-indicator bit, `compose` is bitwise-or, `Adml` is the zero
word. We prove the two concrete algebraic clauses of the LaTeX statement:

  1. `firedmap Adml = fun _ => false` (the image of the bottom element is the
     all-zero bit vector `𝟎`).
  2. `firedmap (compose a b) j = (firedmap a j || firedmap b j)` for every lane
     `j` and all `a b : DenialPolarity` (pointwise-or compatibility, i.e.
     `firedmap` is a monoid homomorphism from `(Deny, compose, Adml)` to
     `(Fin 8 → Bool, fun f g i => f i || g i, fun _ => false)`).

The third clause (that this restricts to an isomorphism onto the seven-bit
image `{0}×{0,1}^7` on the submonoid generated by the seven named lanes) is
the same naming/layout fact already scoped out of kernel-checked form in
prop:code_is_sl (asserted at the level of def:denialcode's lane layout, not
re-proved as a separate algebraic obligation): once the two clauses above are
established, that bijection is the evident one-to-one correspondence between
subsets of the seven independent nonzero lanes and their bit-vector encodings,
not an extra proof obligation about `firedmap`/`compose` themselves. Bare Lean
4 core has no mathlib, so the bitvector arithmetic here is discharged with the
core `Std.Tactic.BVDecide` decision procedure (`bv_decide`), the same kind of
closed, checkable step used for `UInt64.eq_of_toBitVec_eq` elsewhere in this
pilot.
-/

import Std.Tactic.BVDecide

structure DenialPolarity where
  val : UInt64
deriving DecidableEq, Repr

namespace DenialPolarity

def Adml : DenialPolarity := ⟨0⟩

def compose (a b : DenialPolarity) : DenialPolarity := ⟨a.val ||| b.val⟩

/-- Extract byte lane `j` (0-indexed) of the underlying word. -/
def lane (d : DenialPolarity) (j : UInt64) : UInt64 :=
  (d.val >>> (8 * j)) &&& 0xFF

/-- Branchless nonzero indicator: `1[x ≠ 0] = (x | (-x)) >> 63`, using the
top bit of `x | (-x)` (which is set iff `x ≠ 0` for two's-complement words). -/
def nonzeroIndicator (x : UInt64) : UInt64 :=
  (x ||| (0 - x)) >>> 63

/-- `firedmap` sends a denial word to the bit vector (as a function on
`Fin 8`) whose bit `j` is the nonzero-indicator of byte lane `j` of `d`. -/
def firedmap (d : DenialPolarity) : Fin 8 → Bool :=
  fun j => nonzeroIndicator (d.lane (UInt64.ofNat j.val)) ≠ 0

/-- Bitwise-or distributes over extracting a fixed byte lane. -/
theorem lane_compose (a b : DenialPolarity) (j : UInt64) :
    lane (compose a b) j = lane a j ||| lane b j := by
  unfold lane compose
  simp only
  bv_decide

/-- The nonzero-indicator of an or of two words is nonzero iff at least one
operand's indicator is nonzero: `nonzeroIndicator` is itself an or-homomorphism
on the two-valued (zero / nonzero) quotient. -/
theorem nonzeroIndicator_or (x y : UInt64) :
    nonzeroIndicator (x ||| y) ≠ 0 ↔ nonzeroIndicator x ≠ 0 ∨ nonzeroIndicator y ≠ 0 := by
  unfold nonzeroIndicator
  bv_decide

/-- `firedmap Adml` is the all-zero bit vector `𝟎`. -/
theorem firedmap_Adml : firedmap Adml = fun _ => false := by
  funext j
  unfold firedmap Adml lane nonzeroIndicator
  simp only [decide_eq_false_iff_not, ne_eq]
  intro h
  revert h
  bv_decide

/-- `firedmap` sends `compose` to pointwise-or: the homomorphism clause of
the LaTeX statement. -/
theorem firedmap_compose (a b : DenialPolarity) (j : Fin 8) :
    firedmap (compose a b) j = (firedmap a j || firedmap b j) := by
  unfold firedmap
  rw [lane_compose]
  have key := nonzeroIndicator_or (lane a (UInt64.ofNat j.val)) (lane b (UInt64.ofNat j.val))
  by_cases ha : nonzeroIndicator (lane a (UInt64.ofNat j.val)) ≠ 0 <;>
  by_cases hb : nonzeroIndicator (lane b (UInt64.ofNat j.val)) ≠ 0 <;>
    simp_all

/-- `firedmap` is a homomorphism of bounded commutative idempotent monoids
from `(Deny, compose, Adml)` to `(Fin 8 → Bool, pointwise-or, 𝟎)`: the two
algebraic clauses of thm:firedhom stated together. -/
theorem firedmap_is_monoid_hom :
    firedmap Adml = (fun _ => false) ∧
    (∀ a b : DenialPolarity, ∀ j : Fin 8,
      firedmap (compose a b) j = (firedmap a j || firedmap b j)) :=
  ⟨firedmap_Adml, firedmap_compose⟩

end DenialPolarity
