//! SOC2 Type II audit engagement case study — Solace Cloud (v26.7.12/13).
//!
//! Drives the ENTIRE 10-phase audit engagement lifecycle (Scoping & System
//! Description through Auditor Report Handoff) through the real cng
//! manufacture chain: the 10 phase fixtures under `tests/fixtures/soc2/`
//! are domain FRAGMENTS of one shared `solace-soc2-audit-cycle` STRIPS
//! domain (each contributing that phase's 3 actions, chained by
//! phase-completion predicates), plus one problem fragment carrying the
//! single init atom and the single terminal goal atom.
//! `pipeline::import_artifacts` admits them, `generate_plan` grounds +
//! plans the full 30-step cycle, and `pipeline::hierarchical_projection`
//! groups the plan back into 10 phase children by artifact provenance —
//! the audit engagement cycle as a hierarchical POWL. This mirrors
//! `crate::bench::togaf`'s structure exactly (same pipeline, same
//! `verify_eight_constraint_split` law, reused verbatim from that module
//! rather than reimplemented here — it is already generic over
//! `AdmittedSurface`, not TOGAF-specific in its signature).
//!
//! # COMPLIANCE-OVERCLAIM FENCE (non-negotiable, structural)
//!
//! SOC2 "compliance" is an auditor's professional attestation under the
//! AICPA Trust Services Criteria (TSC), issued by a licensed CPA firm — it
//! is NOT a mathematical predicate, and NOTHING this module or the fixtures
//! it drives can ever BE SOC2 compliance or a SOC2 opinion. This case study
//! models the AUDIT ENGAGEMENT PROCESS (evidence gathering, control
//! design/operating-effectiveness evaluation, exception handling) and
//! produces EVIDENCE BUNDLES for a human auditor's professional judgment —
//! never a pass/fail compliance verdict. Enforced structurally, not just in
//! prose: the merged PDDL domain has NO action whose effect is anything
//! like `(compliant ?x)` or `(opinion-issued ?x)` — the only terminal goal
//! atom is `(evidence-bundle-complete ?x)`. `soc2_test.rs`'s
//! `no_action_effect_ever_asserts_compliance_or_opinion` test greps the
//! parsed, merged `Pddl8Domain`'s action effects mechanically for
//! "compliant"/"opinion" substrings and asserts zero matches — this is the
//! structural fence check, not a decorative comment. This mirrors a
//! parallel Lean-formalization effort (the sibling `mfact` repo) which
//! drew the identical line: no Lean theorem can ever BE SOC2 compliance,
//! only strengthen evidence for specific control points.
//!
//! Fixture vocabulary is PUBLIC-ontology-first (blank nodes +
//! `skos:notation` handles; skos / prov / dcterms / org — no public
//! OWL/RDF ontology exists for the AICPA TSC, confirmed via live web
//! search, so unlike `togaf-adm-pack`'s reuse of the public TOGAF Content
//! Metamodel OWL, every domain-specific class here is a public *general*
//! vocabulary term (`skos:Concept`, `prov:Activity`, `prov:Plan`,
//! `prov:Entity`, `org:Organization`) rather than a domain-specific public
//! ontology). Two private namespaces are in play, both disclosed in
//! `packs/soc2-audit-pack/ontology.ttl` and neither minted here: the
//! pipeline's own ABI (`urn:chatman:engine#pddlDomain`/`#pddlProblem`, the
//! PDDL text carrier, `pipeline.rs`) and the `powl2:` output vocabulary
//! (`powl.rs`). Unlike `togaf-adm-pack`, this pack does NOT union
//! `pddl-strips.ttl` via a `ggen.toml` `extra_ontologies` entry: PDDL is
//! carried only as literal text here, never as RDF structure, so no
//! extra_ontologies entry is needed (or added — root `ggen.toml`/
//! `ggen.lock` are out of scope for this stage).
//!
//! Generated by `packs/soc2-audit-pack` templates, rendered by hand/script
//! to their fixture outputs (byte-identical to the template bodies) rather
//! than via a `ggen sync` re-run in this stage.

use std::path::PathBuf;

use crate::pipeline::AdmittedSurface;
use crate::powl::CngRefusal;

/// The declared SOC2 audit-phase order: (fixture file, SKOS notation). Like
/// `togaf::ADM_PHASES`, this is a declared reference table for tests (phase
/// count, fixture enumeration) — the actual plan-step order is determined
/// by the STRIPS planner satisfying the precondition chain, not by this
/// array's order or by filesystem iteration order (`pipeline::
/// import_artifacts` visits `*.ttl` files in lexicographic order, which
/// differs from this array's phase-intended order; `merge_fragments`
/// appends actions in that lexicographic artifact order, but the search
/// that produces the plan tape only ever has one applicable action per
/// state under this pack's single-source precondition chains, so the
/// resulting plan order is the chain order regardless).
pub(super) const SOC2_PHASES: [(&str, &str); 10] = [
    ("audit-scoping.ttl", "AUDIT-SCOPING"),
    ("audit-readiness.ttl", "AUDIT-READINESS"),
    ("audit-control-design-doc.ttl", "AUDIT-CONTROL-DESIGN-DOC"),
    ("audit-design-eval.ttl", "AUDIT-DESIGN-EVAL"),
    ("audit-collection-init.ttl", "AUDIT-COLLECTION-INIT"),
    ("audit-oe-testing.ttl", "AUDIT-OE-TESTING"),
    ("audit-exception-id.ttl", "AUDIT-EXCEPTION-ID"),
    ("audit-remediation.ttl", "AUDIT-REMEDIATION"),
    ("audit-bundle-assembly.ttl", "AUDIT-BUNDLE-ASSEMBLY"),
    ("audit-report-handoff.ttl", "AUDIT-REPORT-HANDOFF"),
];

/// Directory holding the generated SOC2 audit-cycle fixtures.
pub(super) fn soc2_fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/soc2")
}

/// Structurally greps the merged, parsed `AdmittedSurface`'s action
/// effects for the two forbidden substrings the compliance-overclaim fence
/// bans: "compliant" and "opinion" (case-insensitive). This is the
/// mechanical half of the fence — the doc-comment half states the rule,
/// this function (and `soc2_test.rs`'s use of it) makes a violation
/// impossible to miss.
///
/// # Errors
/// `CNG_R05 UnsupportedConstruct` naming the first action/predicate that
/// violates the fence.
///
/// # Complexity
/// O(actions × effects) over the merged surface.
pub fn verify_no_compliance_or_opinion_effects(
    surface: &AdmittedSurface,
) -> Result<(), CngRefusal> {
    for action in &surface.domain.actions {
        for effect in action.add_effects.iter().chain(action.del_effects.iter()) {
            let lowered = effect.pred.to_ascii_lowercase();
            if lowered.contains("compliant") || lowered.contains("opinion") {
                return Err(CngRefusal::UnsupportedConstruct(format!(
                    "compliance-overclaim fence violated: action `{}` has an effect atom \
                     `{}` naming a compliance verdict or auditor opinion; the only lawful \
                     terminal deliverable is evidence-bundle-complete",
                    action.name, effect.pred
                )));
            }
        }
    }
    Ok(())
}

#[cfg(test)]
#[path = "soc2_test.rs"]
mod soc2_test;
