//! SOC2 Type II audit engagement case study — Solace Cloud (v26.7.12/13).
//!
//! Drives the ENTIRE 10-phase audit engagement lifecycle (Scoping & System
//! Description through Auditor Report Handoff) through the real cng
//! manufacture chain: the 10 phase fixtures under `tests/fixtures/soc2/`
//! are domain FRAGMENTS of one shared `solace-soc2-audit-cycle` STRIPS
//! domain (each contributing that phase's 3 actions, chained by
//! phase-completion predicates), plus one problem fragment carrying the
//! single init atom and the single terminal goal atom.
//! `pipeline::import_artifacts` admits them, `generate_plan` grounds +
//! plans the full 30-step cycle, and `pipeline::hierarchical_projection`
//! groups the plan back into 10 phase children by artifact provenance —
//! the audit engagement cycle as a hierarchical POWL. This mirrors
//! `crate::bench::togaf`'s structure exactly (same pipeline, same
//! `verify_eight_constraint_split` law, reused verbatim from that module
//! rather than reimplemented here — it is already generic over
//! `AdmittedSurface`, not TOGAF-specific in its signature).
//!
//! # COMPLIANCE-OVERCLAIM FENCE (non-negotiable, structural)
//!
//! SOC2 "compliance" is an auditor's professional attestation under the
//! AICPA Trust Services Criteria (TSC), issued by a licensed CPA firm — it
//! is NOT a mathematical predicate, and NOTHING this module or the fixtures
//! it drives can ever BE SOC2 compliance or a SOC2 opinion. This case study
//! models the AUDIT ENGAGEMENT PROCESS (evidence gathering, control
//! design/operating-effectiveness evaluation, exception handling) and
//! produces EVIDENCE BUNDLES for a human auditor's professional judgment —
//! never a pass/fail compliance verdict. Enforced structurally, not just in
//! prose: the merged PDDL domain has NO action whose effect is anything
//! like `(compliant ?x)` or `(opinion-issued ?x)` — the only terminal goal
//! atom is `(evidence-bundle-complete ?x)`. `soc2_test.rs`'s
//! `no_action_effect_ever_asserts_compliance_or_opinion` test greps the
//! parsed, merged `Pddl8Domain`'s action effects mechanically for
//! "compliant"/"opinion" substrings and asserts zero matches — this is the
//! structural fence check, not a decorative comment. This mirrors a
//! parallel Lean-formalization effort (the sibling `mfact` repo) which
//! drew the identical line: no Lean theorem can ever BE SOC2 compliance,
//! only strengthen evidence for specific control points.
//!
//! Fixture vocabulary is PUBLIC-ontology-first (blank nodes +
//! `skos:notation` handles; skos / prov / dcterms / org — no public
//! OWL/RDF ontology exists for the AICPA TSC, confirmed via live web
//! search, so unlike `togaf-adm-pack`'s reuse of the public TOGAF Content
//! Metamodel OWL, every domain-specific class here is a public *general*
//! vocabulary term (`skos:Concept`, `prov:Activity`, `prov:Plan`,
//! `prov:Entity`, `org:Organization`) rather than a domain-specific public
//! ontology). Two private namespaces are in play, both disclosed in
//! `packs/soc2-audit-pack/ontology.ttl` and neither minted here: the
//! pipeline's own ABI (`urn:chatman:engine#pddlDomain`/`#pddlProblem`, the
//! PDDL text carrier, `pipeline.rs`) and the `powl2:` output vocabulary
//! (`powl.rs`). Unlike `togaf-adm-pack`, this pack does NOT union
//! `pddl-strips.ttl` via a `ggen.toml` `extra_ontologies` entry: PDDL is
//! carried only as literal text here, never as RDF structure, so no
//! extra_ontologies entry is needed (or added — root `ggen.toml`/
//! `ggen.lock` are out of scope for this stage).
//!
//! Generated by `packs/soc2-audit-pack` templates, rendered by hand/script
//! to their fixture outputs (byte-identical to the template bodies) rather
//! than via a `ggen sync` re-run in this stage.
//!
//! # v26.7.13 Stage 3 amendment: continuous re-evidencing as F09 growth
//!
//! Stage 3 (`bench::soc2_growth`) models SOC2 Type II's defining feature —
//! evidence gathered CONTINUOUSLY over the 12-month observation period,
//! quarterly samples, as distinct from Type I's point-in-time snapshot —
//! as a real F09 "MFW Growth Operator" descent sequence
//! (`multifractal-workflow`'s `f09_mfw_growth`) at the Operating
//! Effectiveness Testing phase's socket, rather than reimplementing any
//! re-test scheduling logic in this crate. One thing learned building it,
//! amending an assumption this doc did not previously state but Stage 3's
//! own task scope did: `crates/multifractal-workflow` already depends on
//! `cng` (`features = ["bench"]`, for F20/F24's real edges) from before
//! Stage 3 existed, so a regular `cng -> multifractal-workflow` dependency
//! the other way is a hard Cargo package-dependency cycle
//! (`cargo check` refuses it outright), not merely an unbuilt wiring gap.
//! `bench::soc2_growth` resolves this the only way Cargo allows:
//! `multifractal-workflow`/`powl2-decompose` are `[dev-dependencies]` of
//! `cng` (see that block's own comment in `Cargo.toml`), so the F09
//! consumer code is real, non-fabricated, production-shaped, but
//! `#[cfg(test)]`-scoped rather than library-reachable outside a test
//! build — see `bench::soc2_growth`'s own module doc for the full
//! disclosure and `soc2_growth_test.rs`'s composed witness test for the
//! resulting honest REAL_EDGE verdict.
//!
//! Also disclosed here rather than silently left stale: as of the Stage 3
//! commit, three tests below —
//! `full_audit_cycle_plans_projects_validates_and_replays_byte_identically`,
//! `case_study_instance_data_passes_the_soc2_shapes_and_a_mutant_fails`,
//! and `soc2_evidence_metrics_measure_the_shipped_case_study_instance_data`
//! (`soc2_test.rs`) — fail against this same `HEAD`: a real, PRE-EXISTING
//! regression from the separate Fortune-5 rescale commit (Solace Cloud ->
//! Arclight Cloud Platform: renamed domain object, `solace-case-study.ttl`
//! replaced by `arclight-case-study.ttl`) landing on this file's own
//! still-"solace" `BASE_IRI`/case-study path constants below. Confirmed via
//! `git log`, not introduced by Stage 3 (Stage 3 touches neither this
//! file's constants nor `tests/fixtures/soc2/`'s phase fixtures) — left for
//! the already-tracked Solace->Arclight naming-reconciliation follow-up
//! rather than fixed here, out of Stage 3's own stated scope.

use std::fs;
use std::path::{Path, PathBuf};

use oxigraph::io::{RdfFormat, RdfParser};
use oxigraph::store::Store;

use crate::pipeline::AdmittedSurface;
use crate::powl::CngRefusal;

use super::roles::metric_count;
use super::templates::QuerySet;

/// The declared SOC2 audit-phase order: (fixture file, SKOS notation). Like
/// `togaf::ADM_PHASES`, this is a declared reference table for tests (phase
/// count, fixture enumeration) — the actual plan-step order is determined
/// by the STRIPS planner satisfying the precondition chain, not by this
/// array's order or by filesystem iteration order (`pipeline::
/// import_artifacts` visits `*.ttl` files in lexicographic order, which
/// differs from this array's phase-intended order; `merge_fragments`
/// appends actions in that lexicographic artifact order, but the search
/// that produces the plan tape only ever has one applicable action per
/// state under this pack's single-source precondition chains, so the
/// resulting plan order is the chain order regardless).
pub(super) const SOC2_PHASES: [(&str, &str); 10] = [
    ("audit-scoping.ttl", "AUDIT-SCOPING"),
    ("audit-readiness.ttl", "AUDIT-READINESS"),
    ("audit-control-design-doc.ttl", "AUDIT-CONTROL-DESIGN-DOC"),
    ("audit-design-eval.ttl", "AUDIT-DESIGN-EVAL"),
    ("audit-collection-init.ttl", "AUDIT-COLLECTION-INIT"),
    ("audit-oe-testing.ttl", "AUDIT-OE-TESTING"),
    ("audit-exception-id.ttl", "AUDIT-EXCEPTION-ID"),
    ("audit-remediation.ttl", "AUDIT-REMEDIATION"),
    ("audit-bundle-assembly.ttl", "AUDIT-BUNDLE-ASSEMBLY"),
    ("audit-report-handoff.ttl", "AUDIT-REPORT-HANDOFF"),
];

/// Directory holding the generated SOC2 audit-cycle fixtures.
pub(super) fn soc2_fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/soc2")
}

/// Structurally greps the merged, parsed `AdmittedSurface`'s action
/// effects for the two forbidden substrings the compliance-overclaim fence
/// bans: "compliant" and "opinion" (case-insensitive). This is the
/// mechanical half of the fence — the doc-comment half states the rule,
/// this function (and `soc2_test.rs`'s use of it) makes a violation
/// impossible to miss.
///
/// # Errors
/// `CNG_R05 UnsupportedConstruct` naming the first action/predicate that
/// violates the fence.
///
/// # Complexity
/// O(actions × effects) over the merged surface.
pub fn verify_no_compliance_or_opinion_effects(
    surface: &AdmittedSurface,
) -> Result<(), CngRefusal> {
    for action in &surface.domain.actions {
        for effect in action.add_effects.iter().chain(action.del_effects.iter()) {
            let lowered = effect.pred.to_ascii_lowercase();
            if lowered.contains("compliant") || lowered.contains("opinion") {
                return Err(CngRefusal::UnsupportedConstruct(format!(
                    "compliance-overclaim fence violated: action `{}` has an effect atom \
                     `{}` naming a compliance verdict or auditor opinion; the only lawful \
                     terminal deliverable is evidence-bundle-complete",
                    action.name, effect.pred
                )));
            }
        }
    }
    Ok(())
}

/// SOC2 evidence-bundle metrics (v26.7.12/13 Stage 2): two measured SELECT
/// counts over the case-study INSTANCE graph via the on-disk
/// `metric-soc2-*.rq` queries, plus one DERIVED_ARITHMETIC ratio computed in
/// Rust from those two counts. Mirrors `report.rs`'s
/// `ModeledLlmComparison`/`DerivedScaleExtrapolation` measurement-class
/// separation exactly: never merged into `RunReport`, and the derived field
/// is explicitly tagged so no reader can mistake Rust division for a third
/// SPARQL aggregate (this crate's SPARQL engine typed-refuses
/// GROUP_CONCAT/SAMPLE; ratios are computed here, never in a query).
///
/// # COMPLIANCE-OVERCLAIM FENCE
/// Every field is an evidence-bundle measurement over the engagement-process
/// graph — none is, or implies, a compliance verdict or auditor opinion. See
/// this module's top doc comment for the full fence disclosure.
#[derive(Debug, serde::Serialize)]
pub struct Soc2EvidenceMetrics {
    pub measurement_class: &'static str,
    /// metric-soc2-evidenced-controls.rq: COUNT DISTINCT control points
    /// (`prov:Plan`) carrying a complete evidentiary record (notation +
    /// design attribution + TSC-category mapping).
    pub evidenced_controls: u64,
    /// metric-soc2-exceptions.rq: COUNT DISTINCT exception-register
    /// deliverable entities generated by the Exception Identification
    /// phase activity.
    pub exception_register_artifacts: u64,
    /// metric-soc2-remediation-status.rq: COUNT DISTINCT management-
    /// response/remediation-log deliverable entities generated by the
    /// Management Response & Remediation phase activity.
    pub remediation_log_artifacts: u64,
    /// `exception_register_artifacts as f64 / evidenced_controls as f64`,
    /// computed in Rust from the two measured counts above — never a SPARQL
    /// aggregate. `0.0` when `evidenced_controls == 0` (division-by-zero
    /// refused silently would violate the no-silent-defaults invariant;
    /// `0.0` is the documented, deliberate convention this field uses when
    /// there is no denominator, not a fabricated measurement). Tagged by
    /// `derived_exception_register_ratio_class` below.
    pub derived_exception_register_ratio: f64,
    /// Machine-readable tag for `derived_exception_register_ratio`: always
    /// [`Soc2EvidenceMetrics::DERIVED_ARITHMETIC`], carried as a field (not
    /// only a doc comment) so a JSON reader of this struct's serialized form
    /// — e.g. the case-study bundle's evidence-metrics.json — cannot mistake
    /// the one derived field for a fourth measured SPARQL count, mirroring
    /// how `report.rs::DerivedScaleExtrapolation` tags its own fully-derived
    /// fields at the whole-struct level via `measurement_class`.
    pub derived_exception_register_ratio_class: &'static str,
}

impl Soc2EvidenceMetrics {
    pub const MEASUREMENT_CLASS: &'static str = "SOC2_EVIDENCE_BUNDLE_METRICS";
    /// Tag for the one field in this struct that is Rust arithmetic over
    /// two measured counts, not a third measurement.
    pub const DERIVED_ARITHMETIC: &'static str = "DERIVED_ARITHMETIC";
}

/// Loads `instance_ttl_path` (a SOC2 case-study instance-data file, e.g.
/// `tests/fixtures/soc2/solace-case-study.ttl`) into a fresh store and runs
/// the 3 on-disk `metric-soc2-*.rq` COUNT queries over it, returning the
/// measured counts plus the one Rust-computed DERIVED_ARITHMETIC ratio.
///
/// # Errors
/// `CNG_R10 IoRefused` for an unreadable file; `CNG_R01 MalformedTtl` for a
/// Turtle parse failure; `CNG_R05 UnsupportedConstruct` if a required query
/// is missing from `queries`.
///
/// # Complexity
/// O(instance graph size) parse + 3 O(graph) COUNT queries.
pub fn compute_evidence_metrics(
    instance_ttl_path: &Path,
    queries: &QuerySet,
) -> Result<Soc2EvidenceMetrics, CngRefusal> {
    let turtle = fs::read_to_string(instance_ttl_path)
        .map_err(|e| CngRefusal::IoRefused(format!("read {}: {e}", instance_ttl_path.display())))?;
    let store = Store::new().map_err(|e| CngRefusal::IoRefused(format!("store: {e}")))?;
    store
        .load_from_slice(RdfParser::from_format(RdfFormat::Turtle), turtle.as_bytes())
        .map_err(|e| {
            CngRefusal::MalformedTtl(format!(
                "{}: Turtle parse failed: {e}",
                instance_ttl_path.display()
            ))
        })?;

    let evidenced_controls = metric_count(
        &store,
        queries.get("metric-soc2-evidenced-controls")?,
        "metric-soc2-evidenced-controls",
    )?;
    let exception_register_artifacts = metric_count(
        &store,
        queries.get("metric-soc2-exceptions")?,
        "metric-soc2-exceptions",
    )?;
    let remediation_log_artifacts = metric_count(
        &store,
        queries.get("metric-soc2-remediation-status")?,
        "metric-soc2-remediation-status",
    )?;
    let derived_exception_register_ratio = if evidenced_controls == 0 {
        0.0
    } else {
        exception_register_artifacts as f64 / evidenced_controls as f64
    };

    Ok(Soc2EvidenceMetrics {
        measurement_class: Soc2EvidenceMetrics::MEASUREMENT_CLASS,
        evidenced_controls,
        exception_register_artifacts,
        remediation_log_artifacts,
        derived_exception_register_ratio,
        derived_exception_register_ratio_class: Soc2EvidenceMetrics::DERIVED_ARITHMETIC,
    })
}

#[cfg(test)]
#[path = "soc2_test.rs"]
mod soc2_test;
