//! Validate RDF/Turtle ontology graphs against praxis vocabulary constraints.
//
// GENERATED by `ggen sync` from `schema/praxis.ttl` (`praxis:CliCommand`
// instances). Do not edit by hand: routes are a pure projection of the
// ontology (mode = Overwrite); logic lives in `crate::verbs::handlers`.

use clap_noun_verb::Result;

/// Load a Turtle ontology and report parse or constraint violations.
#[clap_noun_verb_macros::verb("validate")]
fn graph_validate() -> Result<serde_json::Value> {
    crate::verbs::handlers::handle_graph_validate()
}
