//! Inspect and verify sync receipt chains (BLAKE3-hashed provenance log).
//
// GENERATED by `ggen sync` from `schema/praxis.ttl` (`praxis:CliCommand`
// instances). Do not edit by hand: routes are a pure projection of the
// ontology (mode = Overwrite); logic lives in `crate::verbs::handlers`.

use clap_noun_verb::Result;

/// Verify the full chain of sync receipts in .ggen-v2/receipt-log.jsonl.
#[clap_noun_verb_macros::verb("history")]
fn receipt_history() -> Result<serde_json::Value> {
    crate::verbs::handlers::handle_receipt_history()
}
/// Recompute and verify the BLAKE3 chain hash of a sync receipt.
#[clap_noun_verb_macros::verb("verify")]
fn receipt_verify() -> Result<serde_json::Value> {
    crate::verbs::handlers::handle_receipt_verify()
}
