//! Family F01 -- "Standing Algebra" (atlas ticket V12-001).
//!
//! Wire-phase-1 status (this pass): **MIXED, wired**. This module now carries
//! real, compiling Rust logic for the pipeline the F01 survey required --
//! `Raw Observation -> Observation Gate -> Admission Engine -> Manufacture
//! Boundary -> Standing Algebra -> Receipt Emitter -> Replay Verifier`, the
//! 7-state lifecycle (`RAW -> OBSERVED -> ADMITTED -> MANUFACTURED ->
//! STANDING -> RECEIPTED -> REPLAYABLE`, with `REFUSED` reachable only from
//! `OBSERVED`/`MANUFACTURED`), and a `SilentPromotionRefused` typed refusal
//! fired at every gate. What is genuinely reused/adapted vs. genuinely
//! hand-written is disclosed per-lens below and in each item's own doc
//! comment; nothing here claims more than what this session verified by
//! compiling and running the tests in this file.
//!
//! ## L1/L2 -- Observation Gate + Admission Engine (REUSE_ADAPT)
//!
//! [`StandingCase::admit`] reuses `praxis_graphlaw::shacl::ValidationReport`
//! directly as the conformance-evidence type, and copies the exact
//! promotion semantics of
//! [`praxis_graphlaw::chatman::closure::RecursiveSocketClosure::promote_observed_to_admitted`]
//! (promote iff `evidence.conforms`, refuse otherwise, never on say-so) --
//! generalized from that function's `WorkflowSocketId`-keyed children to
//! this family's generic per-case admission. The real function was read in
//! full this session (`crates/praxis-graphlaw/src/chatman/closure.rs:382`).
//!
//! ## L3 -- Manufacture Boundary (REUSE_ADAPT)
//!
//! [`StandingCase::manufacture`] adapts the three-check pattern of
//! `praxis_core::arazzo::admit_manufactured_arazzo`
//! (`crates/praxis-core/src/arazzo.rs:186`, read in full this session):
//! refuse with no source digest presented, refuse on artifact/claimed-digest
//! mismatch. Written generically over `&[u8]` + a caller-declared source
//! digest instead of Arazzo-specific types, since those types are not
//! domain-agnostic -- only the semantic pattern (and its BLAKE3 recompute
//! discipline) is reused.
//!
//! ## L4 -- Standing Algebra proper (REUSE_ADAPT, minimal)
//!
//! [`StandingCase::promote_to_standing`] is `A = mu(O*)`
//! (`docs/CHATMAN_EQUATION.md`) at its most reduced form: once `manufacture`
//! has verified a real digest, granting standing is the recorded lifecycle
//! transition itself -- there is no additional evidence to consult that
//! wasn't already required to reach `Manufactured`.
//!
//! ## L6/L8 -- Receipt Emitter + Replay Verifier (REUSE_ADAPT)
//!
//! [`StandingCase::emit_receipt`] calls
//! `praxis_graphlaw::chatman::abi::Receipt::from_canonical_nquads` directly
//! (real, tested BLAKE3-over-canonical-N-Quads construction; read in full
//! this session, `crates/praxis-graphlaw/src/chatman/abi.rs:217`) rather
//! than reimplementing digest/sortedness logic. [`replay_standing_chain`]
//! reuses `bcinr_powl_receipt::replay::PowlReplayVerifier` -- the identical
//! token-passing verifier `crates/praxis-core/src/replay_adapter.rs` uses
//! for its fixed 3-step judge/admit/receipt lifecycle (read in full this
//! session) -- generalized from 3 steps to F01's 7. [`verify_receipt_head`]
//! ties both together: a receipt head is durable/equivalent only if replay
//! is lawful (fitness == 1.0, Q16.16) *and* the receipt's own digest
//! recomputes (`Receipt::verify`).
//!
//! ## L6 -- Data & Provenance (GGEN_GENERATABLE)
//!
//! [`PROVENANCE_CHAIN`] (from `f01_standing_algebra_generated.rs`, `include!`d
//! below) is a real, ggen-generated pure data projection of the 7 typed
//! provenance entities the survey names (`Observation -> AdmissionDecision
//! -> ManufactureRun -> Artifact -> StandingAssertion -> Receipt ->
//! ReplayRun`), each chained to its predecessor/successor by label and
//! tagged with the [`LifecycleState`] it corresponds to. Generated by
//! `ggen sync` (`crates/ggen`, never the frozen `~/ggen`) from
//! `packs/f01-standing-algebra-pack/ontology.ttl`'s `mfwprov:ProvenanceEntity`
//! individuals via `packs/f01-standing-algebra-pack/templates/f01_standing_algebra_generated.rs.tmpl`;
//! two independent fresh runs produced byte-identical output (`shasum -a
//! 256`), confirming determinism. This is a pure data catalog, not
//! enforcement -- [`provenance_catalog_matches_lifecycle_states`] below
//! cross-checks its `lifecycle_state` strings against the real
//! [`LifecycleState`] enum so the two cannot silently drift apart.
//!
//! ## L5 -- 7-state lifecycle (HAND_WRITE_REQUIRED, new)
//!
//! [`LifecycleState`] and [`LifecycleState::can_transition_to`] are new:
//! no existing praxis code models this exact 7-state-plus-REFUSED machine.
//! The transition table is the literal encoding of the survey's invariant
//! ("REFUSED reachable only from OBSERVED/MANUFACTURED"; "OBSERVED never
//! satisfies terminal/admitted status on its own").
//!
//! ## L7 -- Concurrency/chaos (HAND_WRITE_REQUIRED, new, disclosed gap)
//!
//! [`IdempotencyLedger`] is genuinely hand-written: the F01 survey found no
//! deterministic Rust analog anywhere in this repo (the nearest thing,
//! `apps/arazzo_runner/arazzo_runner_broker.erl`'s idempotency dedup, is an
//! Erlang/OTP-restart-oriented, sha256-keyed mechanism -- a different
//! runtime and hash discipline, not portable). It covers duplicate-event and
//! stale-redelivery-after-restart rejection via a durable
//! highest-admitted-sequence-per-correlation-id ledger (`BTreeMap`, never
//! `HashMap`, for deterministic iteration). What it does **not** cover
//! (disclosed, not silently skipped): actual cross-process durability --
//! this ledger is in-memory only in this pass; wiring it to a real
//! persisted store (so it survives an actual engine restart, not just a
//! simulated one in a unit test) is undone follow-on work, same as
//! PROJ-782's fuller replay algorithm the survey flagged as BLOCKED.
//!
//! ## L8 -- Claim ceiling (HAND_WRITE_REQUIRED, new vocabulary)
//!
//! [`claim_ceiling`] is the literal implementation of the survey's claim
//! ceiling: `STANDING_ALGEBRA_ALIVE`/`ZERO_SILENT_PROMOTION`/
//! `REPLAYABLE_STANDING_CHAIN` are `true` only when every named evidence
//! flag in [`ClaimEvidence`] is independently supplied `true` by the
//! caller -- this function never derives evidence itself, only combines it.
//! This vocabulary did not exist anywhere in the repo before this pass
//! (grep-confirmed by the survey).
//!
//! Survey-cited paths for F01 (informed research from the v26.7.12 family
//! survey handed to this scaffolding session inline, not itself a checked-in
//! repo doc):
//! - /Users/sac/Downloads/v26.7.12_mermaid_atlas/families/F01_standing-algebra.md
//! - /Users/sac/praxis/docs/standing/STANDING_SCHEMA.md
//! - /Users/sac/praxis/docs/standing/STANDING_SCHEMA_MILESTONE_GAP.md
//! - /Users/sac/praxis/docs/standing/REALITY_INDEX.md
//! - /Users/sac/praxis/docs/CHATMAN_EQUATION.md
//! - /Users/sac/praxis/crates/praxis-graphlaw/src/chatman/closure.rs
//! - /Users/sac/praxis/crates/praxis-graphlaw/src/chatman/closure_test.rs
//! - /Users/sac/praxis/crates/praxis-graphlaw/src/chatman/abi.rs
//! - /Users/sac/praxis/crates/praxis-core/src/arazzo.rs
//! - /Users/sac/praxis/crates/praxis-core/src/replay_adapter.rs
//! - /Users/sac/praxis/docs/jira/v26.7.11/tickets/index.md (PROJ-782, BLOCKED)
//! - /Users/sac/bcinr/crates/bcinr-powl-receipt/src/replay.rs
//! - /Users/sac/bcinr/crates/bcinr-powl-receipt/src/conformance.rs

use std::collections::BTreeMap;

use bcinr_powl_receipt::conformance::ConformanceMetrics;
use bcinr_powl_receipt::replay::{PowlReplayFrame, PowlReplayVerifier, ReplayViolation};
use praxis_graphlaw::chatman::abi::Receipt;
use praxis_graphlaw::shacl::ValidationReport;

include!("f01_standing_algebra_generated.rs");

/// The 7-state Standing Algebra lifecycle plus the `Refused` escape state
/// (F01 survey lens L5). `Refused` is reachable only from `Observed` or
/// `Manufactured` -- see [`LifecycleState::can_transition_to`], which is
/// the literal, exhaustive encoding of that invariant (not merely a
/// comment about it).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LifecycleState {
    Raw = 0,
    Observed = 1,
    Admitted = 2,
    Manufactured = 3,
    Standing = 4,
    Receipted = 5,
    Replayable = 6,
    Refused = 7,
}

impl LifecycleState {
    /// Whether `self -> next` is a legal Standing Algebra edge.
    ///
    /// `Observed` never satisfies terminal/admitted status on its own (it
    /// can only advance to `Admitted` or exit to `Refused`); `Refused` is
    /// reachable only from `Observed` or `Manufactured` (F01 survey L5).
    ///
    /// # Complexity
    /// O(1).
    #[must_use]
    pub fn can_transition_to(self, next: LifecycleState) -> bool {
        use LifecycleState::{
            Admitted, Manufactured, Observed, Raw, Receipted, Refused, Replayable, Standing,
        };
        matches!(
            (self, next),
            (Raw, Observed)
                | (Observed, Admitted)
                | (Observed, Refused)
                | (Admitted, Manufactured)
                | (Manufactured, Standing)
                | (Manufactured, Refused)
                | (Standing, Receipted)
                | (Receipted, Replayable)
        )
    }

    /// One-hot replay token bit for this state (F01 survey L6/L8), mirroring
    /// `crates/praxis-core/src/replay_adapter.rs`'s `TOK_START`/`TOK_JUDGED`/
    /// ... pattern, generalized from that file's fixed 3-step lifecycle to
    /// this family's 7. `Refused` deliberately has no bit: it exits the
    /// lawful pipeline rather than continuing it, so it plays no part in
    /// the standing-chain replay token flow.
    ///
    /// # Complexity
    /// O(1).
    fn token_bit(self) -> u64 {
        match self {
            LifecycleState::Raw => 1 << 0,
            LifecycleState::Observed => 1 << 1,
            LifecycleState::Admitted => 1 << 2,
            LifecycleState::Manufactured => 1 << 3,
            LifecycleState::Standing => 1 << 4,
            LifecycleState::Receipted => 1 << 5,
            LifecycleState::Replayable => 1 << 6,
            LifecycleState::Refused => 0,
        }
    }
}

/// The four gates a candidate passes on its way to standing (F01 survey L1-L4).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Gate {
    ObservationGate,
    AdmissionEngine,
    ManufactureBoundary,
    StandingAlgebra,
}

/// F01's typed refusal taxonomy. `SilentPromotionRefused` is the shared
/// escape hatch the survey requires at every gate (L1-L4); the remaining
/// variants cover the lifecycle machine (L5), concurrency/chaos (L7), and
/// replay equivalence (L6/L8) lenses. Every variant carries the concrete
/// offending context, never a bare generic message.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum Refusal {
    /// A candidate failed to clear one of the four admission gates (L1-L4).
    /// Never fired silently -- every call site that can fail this way
    /// returns this variant rather than defaulting the candidate forward.
    #[error("SilentPromotionRefused at {gate:?}: {reason}")]
    SilentPromotionRefused { gate: Gate, reason: String },
    /// An attempted lifecycle transition is not one of the legal edges in
    /// [`LifecycleState::can_transition_to`].
    #[error("illegal Standing Algebra lifecycle transition {from:?} -> {to:?}")]
    IllegalLifecycleTransition {
        from: LifecycleState,
        to: LifecycleState,
    },
    /// L7: a duplicate or stale (out-of-order / post-restart re-delivered)
    /// event was refused by the idempotency+correlation gate rather than
    /// silently re-admitted.
    #[error("duplicate or stale event refused (correlation_id={correlation_id:?}): {reason}")]
    DuplicateOrStaleEvent {
        correlation_id: String,
        reason: String,
    },
    /// L6/L8: replaying the recorded standing chain did not reconstruct an
    /// equivalent consequence to the receipted one.
    #[error(
        "replay of the receipted standing chain did not reconstruct an equivalent consequence: {reason}"
    )]
    ReplayEquivalenceFailed { reason: String },
    /// The underlying `praxis_graphlaw::chatman::abi::Receipt` construction
    /// refused (e.g. empty/unsorted canonical N-Quads material); the
    /// original refusal's message is preserved verbatim in `reason`.
    #[error("receipt emission refused: {0}")]
    ReceiptEmissionRefused(String),
}

/// One correlation-scoped raw observation entering the pipeline (L1).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RawObservation {
    pub correlation_id: String,
    pub payload: String,
}

/// One case moving through the Standing Algebra pipeline: `Raw Observation
/// -> Observation Gate -> Admission Engine -> Manufacture Boundary ->
/// Standing Algebra -> Receipt Emitter -> Replay Verifier`. Every stage is
/// an explicit, typed, potentially-refusing method; there is no path that
/// advances `state` without going through one of them.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StandingCase {
    correlation_id: String,
    state: LifecycleState,
    manufactured_digest_hex: Option<String>,
    receipt: Option<Receipt>,
    transitions: Vec<(LifecycleState, LifecycleState)>,
}

impl StandingCase {
    /// Opens a new case at `Raw` for `correlation_id`.
    ///
    /// # Complexity
    /// O(1).
    #[must_use]
    pub fn new(correlation_id: impl Into<String>) -> Self {
        StandingCase {
            correlation_id: correlation_id.into(),
            state: LifecycleState::Raw,
            manufactured_digest_hex: None,
            receipt: None,
            transitions: Vec::new(),
        }
    }

    /// Current lifecycle state.
    #[must_use]
    pub fn state(&self) -> LifecycleState {
        self.state
    }

    /// The lawful transition history recorded so far, in order taken. Feeds
    /// [`replay_standing_chain`]/[`verify_receipt_head`].
    #[must_use]
    pub fn transitions(&self) -> &[(LifecycleState, LifecycleState)] {
        &self.transitions
    }

    /// The receipt this case emitted, if [`Self::emit_receipt`] has run.
    #[must_use]
    pub fn receipt(&self) -> Option<&Receipt> {
        self.receipt.as_ref()
    }

    /// Advances `state` to `next` iff it is a legal edge, recording the
    /// transition for later replay.
    ///
    /// # Complexity
    /// O(1).
    fn transition(&mut self, next: LifecycleState) -> Result<(), Refusal> {
        if !self.state.can_transition_to(next) {
            return Err(Refusal::IllegalLifecycleTransition {
                from: self.state,
                to: next,
            });
        }
        self.transitions.push((self.state, next));
        self.state = next;
        Ok(())
    }

    /// L1 Observation Gate: `Raw -> Observed`. Refuses an empty payload
    /// rather than silently observing nothing.
    ///
    /// # Errors
    /// [`Refusal::SilentPromotionRefused`] if `raw.payload` is empty, or
    /// [`Refusal::IllegalLifecycleTransition`] if this case is not `Raw`.
    ///
    /// # Complexity
    /// O(1).
    pub fn observe(&mut self, raw: &RawObservation) -> Result<(), Refusal> {
        if raw.payload.is_empty() {
            return Err(Refusal::SilentPromotionRefused {
                gate: Gate::ObservationGate,
                reason: "raw observation payload is empty; nothing to observe".to_string(),
            });
        }
        self.transition(LifecycleState::Observed)
    }

    /// L2 Admission Engine: `Observed -> Admitted`, gated on real SHACL
    /// conformance evidence. Adapted from
    /// `RecursiveSocketClosure::promote_observed_to_admitted`'s exact
    /// semantics: promotion iff `evidence.conforms`, never on say-so.
    ///
    /// # Errors
    /// [`Refusal::SilentPromotionRefused`] if `evidence.conforms` is
    /// `false` -- the case stays at `Observed` (L5: observation never
    /// self-promotes to admitted).
    ///
    /// # Complexity
    /// O(1) (the evidence is pre-computed by the caller; this only
    /// inspects `evidence.conforms`/`evidence.results.len()`).
    pub fn admit(&mut self, evidence: &ValidationReport) -> Result<(), Refusal> {
        if !evidence.conforms {
            return Err(Refusal::SilentPromotionRefused {
                gate: Gate::AdmissionEngine,
                reason: format!(
                    "SHACL conformance evidence does not conform ({} validation result(s)); \
                     observation is not promoted to admission",
                    evidence.results.len()
                ),
            });
        }
        self.transition(LifecycleState::Admitted)
    }

    /// L3 Manufacture Boundary: `Admitted -> Manufactured`. Adapted from
    /// `praxis_core::arazzo::admit_manufactured_arazzo`'s three-check
    /// pattern (no source digest presented / digest mismatch), generalized
    /// over an arbitrary artifact byte string and caller-declared source
    /// digest instead of Arazzo-specific types.
    ///
    /// # Errors
    /// [`Refusal::SilentPromotionRefused`] if `source_digest_hex` is empty
    /// (no admitted source bound), or if `artifact_bytes` does not
    /// recompute to `claimed_artifact_digest_hex` (the artifact does not
    /// match its own claimed digest).
    ///
    /// # Complexity
    /// O(b) where b = `artifact_bytes.len()` (one BLAKE3 pass).
    pub fn manufacture(
        &mut self,
        artifact_bytes: &[u8],
        source_digest_hex: &str,
        claimed_artifact_digest_hex: &str,
    ) -> Result<(), Refusal> {
        if source_digest_hex.is_empty() {
            return Err(Refusal::SilentPromotionRefused {
                gate: Gate::ManufactureBoundary,
                reason: "no source digest presented; manufacture without an admitted source \
                         is refused"
                    .to_string(),
            });
        }
        let recomputed = hex::encode(blake3::hash(artifact_bytes).as_bytes());
        if recomputed != claimed_artifact_digest_hex {
            return Err(Refusal::SilentPromotionRefused {
                gate: Gate::ManufactureBoundary,
                reason: format!(
                    "presented artifact recomputes to {recomputed}, but the claimed digest is \
                     {claimed_artifact_digest_hex}; the artifact does not attest this claim"
                ),
            });
        }
        self.manufactured_digest_hex = Some(recomputed);
        self.transition(LifecycleState::Manufactured)
    }

    /// L4 Standing Algebra proper: `Manufactured -> Standing`. This is
    /// `A = mu(O*)` at its most reduced form: once `manufacture` has
    /// verified a real digest, granting standing is the recorded lifecycle
    /// transition itself.
    ///
    /// # Errors
    /// [`Refusal::SilentPromotionRefused`] if no manufactured digest is on
    /// record (a case cannot reach `Manufactured` without passing L3, so
    /// this only fires if called out of order and `transition` itself
    /// would also refuse).
    ///
    /// # Complexity
    /// O(1).
    pub fn promote_to_standing(&mut self) -> Result<(), Refusal> {
        if self.manufactured_digest_hex.is_none() {
            return Err(Refusal::SilentPromotionRefused {
                gate: Gate::StandingAlgebra,
                reason: "no manufactured artifact digest on record; standing cannot be granted \
                         without a manufactured artifact"
                    .to_string(),
            });
        }
        self.transition(LifecycleState::Standing)
    }

    /// L6 Receipt Emitter: `Standing -> Receipted`. Reuses
    /// `Receipt::from_canonical_nquads` directly (real, tested BLAKE3-over-
    /// canonical-N-Quads construction).
    ///
    /// # Errors
    /// [`Refusal::ReceiptEmissionRefused`] if the underlying receipt
    /// construction refuses (empty/unsorted material, per
    /// `Receipt::from_canonical_nquads`'s own contract).
    ///
    /// # Complexity
    /// O(n) for the underlying sortedness check plus O(bytes) for the
    /// BLAKE3 digest, n = number of N-Quads lines.
    pub fn emit_receipt(
        &mut self,
        witness: &str,
        replay_hint: &str,
        canon_nquads: &str,
    ) -> Result<Receipt, Refusal> {
        let subject = format!("urn:multifractal-workflow:f01:{}", self.correlation_id);
        let receipt = Receipt::from_canonical_nquads(&subject, witness, replay_hint, canon_nquads)
            .map_err(|e| Refusal::ReceiptEmissionRefused(e.to_string()))?;
        self.transition(LifecycleState::Receipted)?;
        self.receipt = Some(receipt.clone());
        Ok(receipt)
    }

    /// L6/L8 Replay Verifier: `Receipted -> Replayable`. Callers should
    /// have already confirmed [`verify_receipt_head`] on
    /// [`Self::transitions`] before calling this -- this method itself only
    /// records the final lifecycle edge, it does not re-run replay.
    ///
    /// # Errors
    /// [`Refusal::IllegalLifecycleTransition`] if this case is not
    /// `Receipted`.
    ///
    /// # Complexity
    /// O(1).
    pub fn mark_replayable(&mut self) -> Result<(), Refusal> {
        self.transition(LifecycleState::Replayable)
    }

    /// Exits to `Refused` from `Observed` or `Manufactured` (the only two
    /// legal `Refused` predecessors, F01 survey L5).
    ///
    /// # Errors
    /// [`Refusal::IllegalLifecycleTransition`] from any other state.
    ///
    /// # Complexity
    /// O(1).
    pub fn refuse(&mut self) -> Result<(), Refusal> {
        self.transition(LifecycleState::Refused)
    }
}

/// L7: an atomic idempotency+correlation gate (survey: HAND_WRITE_REQUIRED,
/// no deterministic Rust analog found elsewhere in this repo). Tracks the
/// highest admitted sequence number per correlation id in a `BTreeMap`
/// (never `HashMap`, for deterministic iteration); admits an event iff its
/// sequence number is strictly newer than the last admitted one for that
/// correlation id, refusing duplicates and stale/out-of-order re-delivery
/// (including the "process/engine restart re-delivers an old event" case,
/// provided the ledger itself is consulted rather than reset -- this pass's
/// ledger is in-memory only; persisting it across a real process restart is
/// an undone follow-on, disclosed here rather than silently assumed).
#[derive(Debug, Clone, Default)]
pub struct IdempotencyLedger {
    seen: BTreeMap<String, u64>,
}

impl IdempotencyLedger {
    /// An empty ledger.
    #[must_use]
    pub fn new() -> Self {
        IdempotencyLedger::default()
    }

    /// Admits `(correlation_id, sequence)` iff it is strictly newer than any
    /// previously admitted sequence for that correlation id.
    ///
    /// # Errors
    /// [`Refusal::DuplicateOrStaleEvent`] if `sequence` is less than or
    /// equal to the last admitted sequence for `correlation_id`.
    ///
    /// # Complexity
    /// O(log n), n = distinct correlation ids seen so far.
    pub fn admit(&mut self, correlation_id: &str, sequence: u64) -> Result<(), Refusal> {
        if let Some(prev) = self.seen.get(correlation_id).copied() {
            if sequence <= prev {
                return Err(Refusal::DuplicateOrStaleEvent {
                    correlation_id: correlation_id.to_string(),
                    reason: format!(
                        "sequence {sequence} is not newer than the last admitted sequence \
                         {prev} for this correlation id"
                    ),
                });
            }
        }
        self.seen.insert(correlation_id.to_string(), sequence);
        Ok(())
    }
}

/// L6/L8: replays a recorded lawful transition history through
/// [`PowlReplayVerifier`] and returns the real conformance metrics, or the
/// first violation encountered. A lawful, in-order Standing Algebra chain
/// (`Raw -> Observed -> Admitted -> Manufactured -> Standing -> Receipted ->
/// Replayable`) replays to `fitness == 0x0001_0000` (1.0, Q16.16), matching
/// `crates/praxis-core/src/replay_adapter.rs`'s own judge/admit/receipt
/// precedent.
///
/// # Errors
/// The first [`ReplayViolation`] encountered (out-of-order or unknown-node
/// transition).
///
/// # Complexity
/// O(t) over `transitions`, t = chain length (each frame is O(1)).
pub fn replay_standing_chain(
    transitions: &[(LifecycleState, LifecycleState)],
) -> Result<ConformanceMetrics, ReplayViolation> {
    let mut verifier = PowlReplayVerifier::new(LifecycleState::Raw.token_bit());
    for (idx, (from, to)) in transitions.iter().enumerate() {
        let frame = PowlReplayFrame {
            node_id: *to as u32,
            node_bit: to.token_bit(),
            required_tokens: from.token_bit(),
            produces_tokens: to.token_bit(),
            activity: format!("{from:?}->{to:?}"),
            ts_ns: idx as u64,
            object_ids: Vec::new(),
        };
        verifier.replay_frame(&frame)?;
    }
    Ok(verifier.finalize())
}

/// L6/L8: verifies that replaying `transitions` reconstructs a consequence
/// equivalent to `receipt` -- the receipt head and the replay must agree,
/// not merely both exist. "Equivalent" means: replay is lawful (fitness ==
/// 1.0, Q16.16) *and* the receipt's own digest recomputes
/// ([`Receipt::verify`]).
///
/// # Errors
/// [`Refusal::ReplayEquivalenceFailed`] if replay is a
/// [`ReplayViolation`], if fitness is not `0x0001_0000`, or if
/// `receipt.verify()` fails.
///
/// # Complexity
/// O(t) for the replay plus O(bytes) for the receipt digest recompute.
pub fn verify_receipt_head(
    transitions: &[(LifecycleState, LifecycleState)],
    receipt: &Receipt,
) -> Result<ConformanceMetrics, Refusal> {
    let metrics = replay_standing_chain(transitions).map_err(|violation| {
        Refusal::ReplayEquivalenceFailed {
            reason: format!("{violation:?}"),
        }
    })?;
    if metrics.fitness != 0x0001_0000 {
        return Err(Refusal::ReplayEquivalenceFailed {
            reason: format!(
                "replay fitness {:#010x} is not 1.0; the standing chain does not reconstruct \
                 equivalently",
                metrics.fitness
            ),
        });
    }
    receipt
        .verify()
        .map_err(|e| Refusal::ReplayEquivalenceFailed {
            reason: e.to_string(),
        })?;
    Ok(metrics)
}

/// L8: the independently-supplied evidence flags [`claim_ceiling`] combines.
/// None of these ever defaults to `true`; every field must be set by the
/// caller from real evidence gathered elsewhere, never derived by
/// `claim_ceiling` itself.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct ClaimEvidence {
    pub source_and_graph_evidence_present: bool,
    pub unit_and_negative_fixtures_present: bool,
    pub production_reachability_trace_present: bool,
    pub chaos_recovery_evidence_present: bool,
    pub receipt_replay_equivalence_verified: bool,
}

/// L8: the only three claims this family may ever emit. New vocabulary --
/// none of these three names existed anywhere in this repo before this
/// pass (grep-confirmed by the F01 survey).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ClaimCeiling {
    pub standing_algebra_alive: bool,
    pub zero_silent_promotion: bool,
    pub replayable_standing_chain: bool,
}

/// Computes the L8 claim ceiling from independently-supplied evidence. All
/// three claims require every [`ClaimEvidence`] flag to be `true`;
/// `replayable_standing_chain` additionally re-checks
/// `receipt_replay_equivalence_verified` explicitly (redundant with the
/// combined check today, but kept as its own named condition so a future
/// loosening of the combined gate cannot silently loosen this specific
/// claim too).
///
/// # Complexity
/// O(1).
#[must_use]
pub fn claim_ceiling(evidence: ClaimEvidence) -> ClaimCeiling {
    let all_present = evidence.source_and_graph_evidence_present
        && evidence.unit_and_negative_fixtures_present
        && evidence.production_reachability_trace_present
        && evidence.chaos_recovery_evidence_present
        && evidence.receipt_replay_equivalence_verified;
    ClaimCeiling {
        standing_algebra_alive: all_present,
        zero_silent_promotion: all_present,
        replayable_standing_chain: all_present && evidence.receipt_replay_equivalence_verified,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn conforming_evidence() -> ValidationReport {
        ValidationReport {
            conforms: true,
            results: Vec::new(),
        }
    }

    fn non_conforming_evidence() -> ValidationReport {
        ValidationReport {
            conforms: false,
            results: Vec::new(),
        }
    }

    #[test]
    fn lawful_pipeline_reaches_replayable_and_receipt_verifies() {
        let mut case = StandingCase::new("case-1");
        case.observe(&RawObservation {
            correlation_id: "case-1".to_string(),
            payload: "raw payload".to_string(),
        })
        .expect("observe must succeed on non-empty payload");
        case.admit(&conforming_evidence())
            .expect("admit must succeed on conforming evidence");
        let artifact = b"manufactured artifact bytes";
        let digest = hex::encode(blake3::hash(artifact).as_bytes());
        case.manufacture(artifact, "source-digest-abc", &digest)
            .expect("manufacture must succeed when digest matches");
        case.promote_to_standing()
            .expect("promote_to_standing must succeed after manufacture");
        let receipt = case
            .emit_receipt("witness-1", "replay-hint-1", "<urn:a> <urn:b> <urn:c> .\n")
            .expect("emit_receipt must succeed on valid canonical N-Quads");
        case.mark_replayable()
            .expect("mark_replayable must succeed after Receipted");
        assert_eq!(case.state(), LifecycleState::Replayable);

        let metrics = verify_receipt_head(case.transitions(), &receipt)
            .expect("lawful chain + valid receipt must verify");
        assert_eq!(metrics.fitness, 0x0001_0000);
    }

    #[test]
    fn observe_refuses_empty_payload() {
        let mut case = StandingCase::new("case-2");
        let result = case.observe(&RawObservation {
            correlation_id: "case-2".to_string(),
            payload: String::new(),
        });
        assert!(matches!(
            result,
            Err(Refusal::SilentPromotionRefused {
                gate: Gate::ObservationGate,
                ..
            })
        ));
        assert_eq!(case.state(), LifecycleState::Raw);
    }

    #[test]
    fn admit_refuses_non_conforming_evidence_and_stays_observed() {
        let mut case = StandingCase::new("case-3");
        case.observe(&RawObservation {
            correlation_id: "case-3".to_string(),
            payload: "raw".to_string(),
        })
        .expect("observe must succeed");
        let result = case.admit(&non_conforming_evidence());
        assert!(matches!(
            result,
            Err(Refusal::SilentPromotionRefused {
                gate: Gate::AdmissionEngine,
                ..
            })
        ));
        // L5: OBSERVED never satisfies terminal/admitted status on its own.
        assert_eq!(case.state(), LifecycleState::Observed);
    }

    #[test]
    fn manufacture_refuses_digest_mismatch() {
        let mut case = StandingCase::new("case-4");
        case.observe(&RawObservation {
            correlation_id: "case-4".to_string(),
            payload: "raw".to_string(),
        })
        .expect("observe must succeed");
        case.admit(&conforming_evidence())
            .expect("admit must succeed");
        let result = case.manufacture(b"real bytes", "source-digest", "wrong-digest-hex");
        assert!(matches!(
            result,
            Err(Refusal::SilentPromotionRefused {
                gate: Gate::ManufactureBoundary,
                ..
            })
        ));
        assert_eq!(case.state(), LifecycleState::Admitted);
    }

    #[test]
    fn manufacture_refuses_empty_source_digest() {
        let mut case = StandingCase::new("case-4b");
        case.observe(&RawObservation {
            correlation_id: "case-4b".to_string(),
            payload: "raw".to_string(),
        })
        .expect("observe must succeed");
        case.admit(&conforming_evidence())
            .expect("admit must succeed");
        let artifact = b"bytes";
        let digest = hex::encode(blake3::hash(artifact).as_bytes());
        let result = case.manufacture(artifact, "", &digest);
        assert!(matches!(
            result,
            Err(Refusal::SilentPromotionRefused {
                gate: Gate::ManufactureBoundary,
                ..
            })
        ));
    }

    #[test]
    fn refused_only_reachable_from_observed_or_manufactured() {
        // From Raw: illegal.
        let mut raw_case = StandingCase::new("case-5a");
        assert!(matches!(
            raw_case.refuse(),
            Err(Refusal::IllegalLifecycleTransition {
                from: LifecycleState::Raw,
                to: LifecycleState::Refused,
            })
        ));

        // From Observed: legal.
        let mut observed_case = StandingCase::new("case-5b");
        observed_case
            .observe(&RawObservation {
                correlation_id: "case-5b".to_string(),
                payload: "raw".to_string(),
            })
            .expect("observe must succeed");
        assert!(observed_case.refuse().is_ok());
        assert_eq!(observed_case.state(), LifecycleState::Refused);

        // From Manufactured: legal.
        let mut manufactured_case = StandingCase::new("case-5c");
        manufactured_case
            .observe(&RawObservation {
                correlation_id: "case-5c".to_string(),
                payload: "raw".to_string(),
            })
            .expect("observe must succeed");
        manufactured_case
            .admit(&conforming_evidence())
            .expect("admit must succeed");
        let artifact = b"bytes-for-5c";
        let digest = hex::encode(blake3::hash(artifact).as_bytes());
        manufactured_case
            .manufacture(artifact, "source-digest", &digest)
            .expect("manufacture must succeed");
        assert!(manufactured_case.refuse().is_ok());
        assert_eq!(manufactured_case.state(), LifecycleState::Refused);
    }

    #[test]
    fn promote_to_standing_out_of_order_is_illegal_transition() {
        let mut case = StandingCase::new("case-6");
        let result = case.promote_to_standing();
        assert!(matches!(
            result,
            Err(Refusal::SilentPromotionRefused {
                gate: Gate::StandingAlgebra,
                ..
            })
        ));
    }

    #[test]
    fn idempotency_ledger_admits_strictly_increasing_sequence() {
        let mut ledger = IdempotencyLedger::new();
        assert!(ledger.admit("corr-1", 1).is_ok());
        assert!(ledger.admit("corr-1", 2).is_ok());
        assert!(ledger.admit("corr-2", 1).is_ok());
    }

    #[test]
    fn idempotency_ledger_refuses_duplicate_event() {
        let mut ledger = IdempotencyLedger::new();
        ledger.admit("corr-1", 5).expect("first admit must succeed");
        let result = ledger.admit("corr-1", 5);
        assert!(matches!(result, Err(Refusal::DuplicateOrStaleEvent { .. })));
    }

    #[test]
    fn idempotency_ledger_refuses_stale_redelivery_after_restart() {
        // Simulates a process restart re-delivering an older event: a
        // fresh admit() call against the same durable ledger state must
        // still refuse, since the ledger (not in-process memory) is what's
        // consulted.
        let mut ledger = IdempotencyLedger::new();
        ledger.admit("corr-1", 10).expect("must admit sequence 10");
        let stale_redelivery = ledger.admit("corr-1", 3);
        assert!(matches!(
            stale_redelivery,
            Err(Refusal::DuplicateOrStaleEvent { .. })
        ));
    }

    #[test]
    fn replay_standing_chain_out_of_order_is_violation() {
        // `replay_standing_chain` seeds the verifier with only `Raw`'s
        // token enabled. A frame requiring `Observed`'s token (i.e. one
        // that never went through `Raw -> Observed` first) must be
        // rejected, not silently accepted.
        let transitions = [(LifecycleState::Observed, LifecycleState::Admitted)];
        let result = replay_standing_chain(&transitions);
        assert!(matches!(
            result,
            Err(ReplayViolation::TokenNotEnabled { .. })
        ));
    }

    #[test]
    fn claim_ceiling_is_false_unless_all_evidence_present() {
        let none = claim_ceiling(ClaimEvidence::default());
        assert!(!none.standing_algebra_alive);
        assert!(!none.zero_silent_promotion);
        assert!(!none.replayable_standing_chain);

        let partial = claim_ceiling(ClaimEvidence {
            source_and_graph_evidence_present: true,
            unit_and_negative_fixtures_present: true,
            production_reachability_trace_present: true,
            chaos_recovery_evidence_present: true,
            receipt_replay_equivalence_verified: false,
        });
        assert!(!partial.standing_algebra_alive);

        let full = claim_ceiling(ClaimEvidence {
            source_and_graph_evidence_present: true,
            unit_and_negative_fixtures_present: true,
            production_reachability_trace_present: true,
            chaos_recovery_evidence_present: true,
            receipt_replay_equivalence_verified: true,
        });
        assert!(full.standing_algebra_alive);
        assert!(full.zero_silent_promotion);
        assert!(full.replayable_standing_chain);
    }

    #[test]
    fn verify_receipt_head_refuses_on_unlawful_replay() {
        // A receipt built from unrelated material, checked against an
        // empty (vacuously "lawful" per PowlReplayVerifier::finalize's
        // zero-denominator convention, fitness defaults to 1.0) transition
        // list still must pass the receipt.verify() digest check; corrupt
        // the receipt's carried material to prove the digest check fires.
        let receipt = Receipt::from_canonical_nquads(
            "urn:test:subject",
            "witness",
            "replay-hint",
            "<urn:a> <urn:b> <urn:c> .\n",
        )
        .expect("receipt construction must succeed");
        // Build a second receipt whose envelope digest does not match its
        // own canon_nquads field, simulating a tampered/stale receipt head.
        let tampered = Receipt {
            envelope: receipt.envelope.clone(),
            canon_nquads: "<urn:x> <urn:y> <urn:z> .\n".to_string(),
        };
        let result = verify_receipt_head(&[], &tampered);
        assert!(matches!(
            result,
            Err(Refusal::ReplayEquivalenceFailed { .. })
        ));
    }

    /// Cross-checks the ggen-generated [`PROVENANCE_CHAIN`]'s
    /// `lifecycle_state` strings against the real, hand-written
    /// [`LifecycleState`] enum by exact `Debug`-name match, so the
    /// generated catalog and the enforcement enum cannot silently drift
    /// apart (same discipline as F04/F15's own catalog-vs-enum
    /// cross-checks).
    #[test]
    fn provenance_catalog_matches_lifecycle_states() {
        let known_state_names: std::collections::BTreeSet<String> = [
            LifecycleState::Raw,
            LifecycleState::Observed,
            LifecycleState::Admitted,
            LifecycleState::Manufactured,
            LifecycleState::Standing,
            LifecycleState::Receipted,
            LifecycleState::Replayable,
            LifecycleState::Refused,
        ]
        .iter()
        .map(|s| format!("{s:?}"))
        .collect();
        for entry in PROVENANCE_CHAIN {
            assert!(
                known_state_names.contains(entry.lifecycle_state),
                "PROVENANCE_CHAIN entry {:?} names lifecycle_state {:?}, which is not a real \
                 LifecycleState variant",
                entry.name,
                entry.lifecycle_state
            );
        }
    }

    /// The 7-entity chain is in strict `chain_order` 0..6, and every
    /// interior link's `generates_next`/`derived_from` pair agrees with
    /// its neighbor's own `name` -- the ggen-projected chain is internally
    /// consistent, not just individually well-formed rows.
    #[test]
    fn provenance_chain_links_are_internally_consistent() {
        assert_eq!(PROVENANCE_CHAIN.len(), 7);
        for (i, entry) in PROVENANCE_CHAIN.iter().enumerate() {
            assert_eq!(entry.chain_order as usize, i);
        }
        assert_eq!(PROVENANCE_CHAIN[0].derived_from, "");
        assert_eq!(PROVENANCE_CHAIN[6].generates_next, "");
        for i in 0..PROVENANCE_CHAIN.len() - 1 {
            assert_eq!(
                PROVENANCE_CHAIN[i].generates_next,
                PROVENANCE_CHAIN[i + 1].name
            );
            assert_eq!(
                PROVENANCE_CHAIN[i + 1].derived_from,
                PROVENANCE_CHAIN[i].name
            );
        }
    }
}
