// F01 Standing Algebra (V12-001) L6 Data & Provenance projection --
// GENERATED by `ggen sync` from `packs/f01-standing-algebra-pack/ontology.ttl`
// (`mfwprov:ProvenanceEntity` individuals). Do not edit by hand: this file
// is a pure data projection of the ontology, `include!`d (not `mod` -- so
// `//!` inner-doc comments are not legal here) into `f01_standing_algebra.rs`,
// which carries the module-level doc comment and all real pipeline/gate/
// refusal/replay logic. Add `ggen:local-override` to the template
// frontmatter to freeze regeneration.
//
// Regenerate from a scratch ggen project referencing this pack (does not
// touch the shared root `ggen.toml`), e.g.:
// ```text
// mkdir -p /tmp/f01-ggen-scratch/templates
// # [ontology].source must be a relative path (ggen refuses absolute paths,
// # FM-CONFIG-003) -- this project's own ontology.ttl can be a near-empty
// placeholder: at sync time ggen unions in every resolved pack's own
// # ontology.ttl into the same graph, and this pack's individuals live
// # entirely in packs/f01-standing-algebra-pack/ontology.ttl.
// cat > /tmp/f01-ggen-scratch/ontology.ttl <<'EOF'
// @prefix owl: <http://www.w3.org/2002/07/owl#> .
// <http://seanchatmangpt.github.io/praxis/multifractal-workflow/f01-scratch#> a owl:Ontology .
// EOF
// cat > /tmp/f01-ggen-scratch/ggen.toml <<'EOF'
// [project]
// name = "f01-ggen-scratch"
// [ontology]
// source = "ontology.ttl"
// [packs]
// f01-standing-algebra-pack = { path = "/Users/sac/praxis/packs/f01-standing-algebra-pack" }
// [templates]
// dir = "templates"
// EOF
// (cd /tmp/f01-ggen-scratch && ggen sync run)
// cp /tmp/f01-ggen-scratch/generated/f01_standing_algebra_generated.rs \
//    /Users/sac/praxis/crates/multifractal-workflow/src/
// ```
//
// Regenerated this session with the recipe above; two independent fresh
// runs (in separate scratch dirs) produced byte-identical output (verified
// via `shasum -a 256`), confirming determinism.

/// One node of the F01 L6 provenance chain (`mfwprov:ProvenanceEntity`):
/// `Observation -> AdmissionDecision -> ManufactureRun -> Artifact ->
/// StandingAssertion -> Receipt -> ReplayRun`. Pure data projection --
/// `derived_from`/`generates_next` are `""` at the chain's boundaries,
/// never a magic sentinel that could collide with a real entity name.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ProvenanceEntityCatalogEntry {
    pub name: &'static str,
    pub comment: &'static str,
    pub chain_order: u8,
    /// The `f01_standing_algebra::LifecycleState` variant name this entity
    /// corresponds to producing (cross-checked against the real enum by
    /// `provenance_catalog_lifecycle_states_match_enum` in
    /// `f01_standing_algebra.rs`).
    pub lifecycle_state: &'static str,
    pub derived_from: &'static str,
    pub generates_next: &'static str,
}

/// The fixed 7-entity provenance chain, in chain order.
pub const PROVENANCE_CHAIN: &[ProvenanceEntityCatalogEntry] = &[
    ProvenanceEntityCatalogEntry {
        name: "Observation",
        comment: "A raw observation admitted past the Observation Gate (L1); corresponds to LifecycleState::Observed.",
        chain_order: 0,
        lifecycle_state: "Observed",
        derived_from: "",
        generates_next: "AdmissionDecision",
    },
    ProvenanceEntityCatalogEntry {
        name: "AdmissionDecision",
        comment: "The Admission Engine's verdict (L2) on an Observation, gated on SHACL conformance evidence; corresponds to LifecycleState::Admitted.",
        chain_order: 1,
        lifecycle_state: "Admitted",
        derived_from: "Observation",
        generates_next: "ManufactureRun",
    },
    ProvenanceEntityCatalogEntry {
        name: "ManufactureRun",
        comment: "One Manufacture Boundary execution (L3) that recomputes and checks an artifact digest against its admitted source; corresponds to the transition into LifecycleState::Manufactured.",
        chain_order: 2,
        lifecycle_state: "Manufactured",
        derived_from: "AdmissionDecision",
        generates_next: "Artifact",
    },
    ProvenanceEntityCatalogEntry {
        name: "Artifact",
        comment: "The manufactured artifact (A) itself -- A = mu(O*), docs/CHATMAN_EQUATION.md -- once its digest has been verified.",
        chain_order: 3,
        lifecycle_state: "Manufactured",
        derived_from: "ManufactureRun",
        generates_next: "StandingAssertion",
    },
    ProvenanceEntityCatalogEntry {
        name: "StandingAssertion",
        comment: "The grant of standing to a manufactured Artifact (L4); corresponds to LifecycleState::Standing.",
        chain_order: 4,
        lifecycle_state: "Standing",
        derived_from: "Artifact",
        generates_next: "Receipt",
    },
    ProvenanceEntityCatalogEntry {
        name: "Receipt",
        comment: "The BLAKE3-over-canonical-N-Quads receipt (R = receipt(A)) emitted for a StandingAssertion (L6); corresponds to LifecycleState::Receipted.",
        chain_order: 5,
        lifecycle_state: "Receipted",
        derived_from: "StandingAssertion",
        generates_next: "ReplayRun",
    },
    ProvenanceEntityCatalogEntry {
        name: "ReplayRun",
        comment: "A Replay Verifier execution (L6/L8) that reconstructs the standing chain and checks it against the Receipt; corresponds to LifecycleState::Replayable.",
        chain_order: 6,
        lifecycle_state: "Replayable",
        derived_from: "Receipt",
        generates_next: "",
    },
];
