// F04 GraphLaw Dialect Registry (V12-004) -- GENERATED by `ggen sync` from
// `packs/f04-dialect-registry-pack/ontology.ttl` (`mfwreg:DialectEntry` and
// `mfwreg:DialectLifecycleState` individuals). Do not edit by hand: this
// file is a pure data projection of the ontology, `include!`d (not `mod`
// -- so `//!` inner-doc comments are not legal here) into
// `f04_dialect_registry.rs`, which carries the module-level doc comment,
// the SHACL closed-shape validation, the receipt/hash computation, and the
// lifecycle transition guards. Add `ggen:local-override` to the template
// frontmatter to freeze regeneration.
//
// Regenerate with (from a scratch ggen project referencing this pack):
// `ggen sync run` -- see `f04_dialect_registry.rs` module docs for the
// exact scratch-project recipe used to produce this file.

/// One entry of the F04 dialect catalog -- a pure data projection of an
/// `mfwreg:DialectEntry` individual's eight mandatory registry fields plus
/// `rdfs:label`/`rdfs:comment`. Field values are informational strings
/// carried straight from the ontology; nothing here is enforcement.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DialectEntry {
    pub name: &'static str,
    pub comment: &'static str,
    pub admitted_inputs: &'static str,
    pub manufactured_outputs: &'static str,
    pub authority_boundary: &'static str,
    pub quarantine_boundary: &'static str,
    pub refusal_vocabulary: &'static str,
    pub receipt_schema: &'static str,
    pub replay_semantics: &'static str,
    pub executable_routing: &'static str,
}

/// The generated catalog: one [`DialectEntry`] per `mfwreg:DialectEntry`
/// individual in the pack ontology, in `?entry` IRI order (matches the
/// `ORDER BY ?entry` of the generating SPARQL SELECT, so regeneration is
/// deterministic).
pub const CATALOG: &[DialectEntry] = &[
    DialectEntry {
        name: "Datalog",
        comment: "Stratified Datalog rule dialect for deterministic fact materialization to fixpoint.",
        admitted_inputs: "Stratified Datalog rules over admitted RDF facts",
        manufactured_outputs: "Derived facts materialized to fixpoint via semi-naive evaluation",
        authority_boundary: "Derived facts are authoritative inside the admitted graph; no external actuation",
        quarantine_boundary: "None beyond graph admission; rules with unsupported constructs are refused at compile",
        refusal_vocabulary: "UnsupportedFeature, UnknownVocabulary, stratification-cycle refusals",
        receipt_schema: "BLAKE3 receipt over canonical sorted N-Quads of the materialized closure",
        replay_semantics: "Deterministic re-materialization from admitted inputs; byte-identical receipt required",
        executable_routing: "not yet bound: praxis-graphlaw reasoner materialization route is the candidate target (V12-004 Wire-phase-2)",
    },
    DialectEntry {
        name: "N3",
        comment: "Notation3 rule dialect. Quarantined to the cold route; mirrors the praxis-graphlaw chatman router's N3ActuationRefused law.",
        admitted_inputs: "N3 rules and formulas over admitted graphs",
        manufactured_outputs: "Derived facts in a quarantined cold-route graph",
        authority_boundary: "Advisory only; N3 derivations never carry actuation authority",
        quarantine_boundary: "cold route only; never actuation",
        refusal_vocabulary: "N3ActuationRefused (chatman router), unsupported-builtin refusals",
        receipt_schema: "BLAKE3 receipt over sorted cold-route derivations",
        replay_semantics: "Deterministic cold-route re-derivation from the same inputs",
        executable_routing: "not yet bound: crates/praxis-graphlaw/src/chatman/router.rs DialectRouter is the candidate target (V12-004 Wire-phase-2; see F06 N3 Quarantine family for the fuller bridge)",
    },
    DialectEntry {
        name: "SHACL",
        comment: "SHACL shape validation dialect; closed-shape law packs gate admission. This registry's own closed-shape law (dialect-registry.shape.ttl) is itself an instance of this dialect.",
        admitted_inputs: "SHACL NodeShapes/PropertyShapes (closed-shape law packs) plus data graphs to validate",
        manufactured_outputs: "Validation reports (conforms flag plus violation results as facts)",
        authority_boundary: "Validation verdicts gate admission; a violation blocks the gated operation",
        quarantine_boundary: "Shapes cannot mutate data; validation is read-only over the target graph",
        refusal_vocabulary: "DialectRegistryRefused::MissingField, DialectRegistryRefused::ClosedShapeViolation",
        receipt_schema: "BLAKE3 receipt over the canonical validation report facts",
        replay_semantics: "Re-validation of the same data and shapes graphs yields an identical report",
        executable_routing: "bound: f04_dialect_registry::validate_registry_turtle (this module, live)",
    },
    DialectEntry {
        name: "SPARQL SELECT",
        comment: "Read-only SPARQL SELECT query dialect with deterministic ordering discipline.",
        admitted_inputs: "SPARQL SELECT queries (file-shipped .rq, never inline) over admitted graphs",
        manufactured_outputs: "Solution bindings (rows), deterministically ordered via explicit ORDER BY",
        authority_boundary: "Read-only; results feed metrics and gates but never mutate the graph",
        quarantine_boundary: "Queries without deterministic ordering are nonconforming to house style",
        refusal_vocabulary: "Query-parse and unknown-vocabulary refusals",
        receipt_schema: "BLAKE3 receipt over the ordered result rows in canonical serialization",
        replay_semantics: "Re-execution over the same fixed graph yields byte-identical ordered rows",
        executable_routing: "bound: registry/queries/*.rq executed via oxigraph in validate_registry_turtle",
    },
];

/// The eight mandatory registry field names, in the fixed order the closed
/// SHACL shape (`registry/dialect-registry.shape.ttl`) declares them.
pub const REGISTRY_FIELDS: [&str; 8] = [
    "admittedInputs",
    "manufacturedOutputs",
    "authorityBoundary",
    "quarantineBoundary",
    "refusalVocabulary",
    "receiptSchema",
    "replaySemantics",
    "executableRouting",
];

/// F04-L5's fixed 7-state lifecycle ladder plus the off-ladder `Refused`
/// terminal, projected from `mfwreg:DialectLifecycleState` individuals
/// (ordered by `mfwreg:stateOrder`). Distinct from cng's 8-state
/// `dreg:HookStanding` -- see `f04_dialect_registry.rs` module docs.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[allow(non_camel_case_types)] // variant names mirror mfwreg: individual labels verbatim
pub enum DialectLifecycleState {
    /// Entry exists as a declaration only (not yet loaded from RDF).
    DECLARED,
    /// Entry Turtle parsed into the store; not yet shape-checked.
    LOADED,
    /// Entry passed the closed-shape SHACL law (no missing field, no closedness violation).
    SHAPE_VALID,
    /// Entry's authorityBoundary/quarantineBoundary have been bound to an enforcement target.
    AUTHORITY_BOUND,
    /// Entry's receiptSchema has been bound to a computed receipt path.
    RECEIPT_BOUND,
    /// Entry's replaySemantics have been bound to a verified replay surface.
    REPLAY_BOUND,
    /// Entry is fully bound and admitted for live executableRouting.
    ACTIVE,
    /// Terminal off-ladder state: a typed `DialectRegistryRefused` was raised
    /// at the `LOADED` or `AUTHORITY_BOUND` gate (`mfwreg:REFUSED`, `mfwreg:stateOrder -1`).
    Refused,
}

impl DialectLifecycleState {
    /// Ladder position; `Refused` carries `-1` (off-ladder terminal), matching
    /// `mfwreg:stateOrder` in the ontology.
    #[must_use]
    pub const fn order(self) -> i8 {
        match self {
            Self::DECLARED => 0,
            Self::LOADED => 1,
            Self::SHAPE_VALID => 2,
            Self::AUTHORITY_BOUND => 3,
            Self::RECEIPT_BOUND => 4,
            Self::REPLAY_BOUND => 5,
            Self::ACTIVE => 6,
            Self::Refused => -1,
        }
    }
}
