//! Family F04 -- "GraphLaw Dialect Registry" (atlas ticket V12-004).
//!
//! Wire-phase-1 status (this pass): **PARTIAL**, not ALREADY_BUILT and not a
//! decorative stub. What is real and exercised by the tests in this file,
//! this session, via `cargo test -p multifractal-workflow`:
//!
//! - A real RDF-declared dialect catalog (`registry/`, four representative
//!   dialects: Datalog, N3, SHACL, SPARQL SELECT) with a real closed-shape
//!   SHACL law (`registry/dialect-registry.shape.ttl`, `sh:closed true`,
//!   the eight mandatory fields F04-L1 names) enforced at runtime by
//!   [`validate_registry_turtle`] via two real, file-shipped, shape-driven
//!   SPARQL SELECTs (`registry/queries/*.rq`) executed over a real oxigraph
//!   `Store` -- not asserted, not mocked. A malformed entry (missing field,
//!   or an undeclared/extra property) is refused with a typed
//!   [`DialectRegistryRefused`], never silently admitted.
//! - The F04-L5 fixed 7-state lifecycle ladder
//!   (`DECLARED -> LOADED -> SHAPE_VALID -> AUTHORITY_BOUND -> RECEIPT_BOUND
//!   -> REPLAY_BOUND -> ACTIVE`, plus the off-ladder `Refused` terminal
//!   reachable only from `LOADED` or `AUTHORITY_BOUND`) as its own,
//!   distinct-from-cng's-8-state-`dreg:HookStanding`, state set, with a
//!   real, tested [`transition`] guard function -- illegal steps (skipping
//!   a rung, transitioning out of `Refused`, or reaching `Refused` from any
//!   state other than `LOADED`/`AUTHORITY_BOUND`) are refused, not silently
//!   allowed.
//! - A [`RegistryReceipt`] whose `content_hash` is a real BLAKE3 digest
//!   (never a wall-clock value, never asserted) over this module's own
//!   canonical Turtle serialization of the catalog ([`catalog_to_turtle`]:
//!   entries sorted by name, fields in a fixed order) -- **not** a full
//!   RDF canonicalization (RDFC-1.0/URDNA2015) of the loaded graph, which
//!   this module does not implement; that distinction is deliberate, not
//!   hidden.
//!
//! What is honestly **NOT** built here (HAND_WRITE_REQUIRED, tracked under
//! V12-004, not claimed done -- do not read the presence of this file as
//! F04 being complete):
//!
//! - The five named F04-L2 pipeline components as live subsystems -- Dialect
//!   Loader (beyond this module's own load-into-oxigraph step), Authority
//!   Matrix, Quarantine Matrix, Receipt Schema Resolver, Replay Surface
//!   Resolver, Executable authority registry. Only the `authorityBoundary`
//!   / `quarantineBoundary` / `receiptSchema` / `replaySemantics` /
//!   `executableRouting` *fields* exist, as catalog data (informational
//!   strings); no code enforces or resolves them yet. Bridging into
//!   `praxis-graphlaw::chatman::router::DialectRouter`'s real enforced
//!   authority/quarantine masks (survey-cited, REUSE_ADAPT-flagged) is
//!   future Wire-phase-2 work, not attempted in this pass.
//! - F04-L6's typed provenance graph (distinct, `prov:wasDerivedFrom`-linked
//!   `DialectDeclaration -> AuthorityGrant -> QuarantinePolicy ->
//!   RefusalCatalog -> ReceiptSchema -> ReplaySurface -> RegistryReceipt`
//!   entities). [`RegistryReceipt`] here is a flat struct, not that chain.
//! - F04-L7's duplicate-load/restart/stale-result idempotency+correlation
//!   gate and durable receipt head.
//! - F04-L8's claim ceiling: this module sets none of `GRAPHLAW_DIALECT_CLOSURE`,
//!   `NO_AMBIENT_AUTHORITY`, or `DIALECT_REGISTRY_REPLAYABLE` -- those
//!   require the L2/L6/L7 work above plus chaos evidence, none of which
//!   exists yet.
//!
//! # Provenance
//!
//! REUSE_ADAPT: the closed-shape SHACL pattern and the two shape-driven
//! SPARQL queries are adapted from the real, committed, git-clean
//! `crates/cng/hooks/dialect-registry.{ttl,shape.ttl}` and
//! `crates/cng/queries/registry-{missing-fields,closed-violations}.rq`
//! (PROJ-613, `CngRefusal::DialectRegistryRefused` / `CNG_R14`) -- adapted
//! rather than depended-on because `validate_dialect_registry` there is a
//! private `fn` inside `crates/cng/src/bench/hooks.rs`, entangled with
//! `bench`-only `QuerySet`/`select_rows` helpers, not a reusable public API.
//! The two `.rq` files are shape-driven and generic (no hardcoded `dreg:`
//! prefix), so they are reused here near-verbatim; the `.ttl`/`.shape.ttl`
//! content is re-namespaced under this crate's own `mfwreg:` vocabulary
//! (kept distinct from cng's private `dreg:` IRI) and reduced to four
//! entries. See `registry/*.ttl`/`registry/queries/*.rq` file headers for
//! the field-by-field provenance note.
//!
//! GGEN_GENERATABLE: [`DialectEntry`], [`CATALOG`], [`REGISTRY_FIELDS`], and
//! [`DialectLifecycleState`] (plus its [`DialectLifecycleState::order`]
//! table) are generated by `ggen sync` from
//! `packs/f04-dialect-registry-pack/ontology.ttl` via
//! `packs/f04-dialect-registry-pack/templates/f04_dialect_registry_generated.rs.tmpl`
//! and committed as `src/f04_dialect_registry_generated.rs` (`include!`d
//! below) -- see that file's own doc comment. Regenerated this session with
//! `ggen sync run` from a scratch project (`[packs].f04-dialect-registry-pack
//! = { path = "/Users/sac/praxis/packs/f04-dialect-registry-pack" }`)
//! pointed at that pack; two independent fresh runs produced byte-identical
//! output (verified via `shasum`), confirming determinism.
//!
//! HAND_WRITE_REQUIRED (done in this pass, real, not decorative):
//! [`DialectRegistryRefused`], [`RegistryReceipt`], [`catalog_to_turtle`],
//! [`validate_registry_turtle`], [`validate_catalog`], and [`transition`].
//!
//! Survey-cited paths (from the V12-004 family survey handed to this Wire
//! session; re-verified in this pass by direct read, not taken on faith):
//! - `/Users/sac/Downloads/v26.7.12_mermaid_atlas/families/F04_dialect-registry.md`
//! - `/Users/sac/praxis/docs/standing/SEMANTIC_PROFILE_DOCTRINE.md`
//! - `/Users/sac/praxis/crates/praxis-graphlaw/src/chatman/router.rs`
//! - `/Users/sac/praxis/crates/praxis-graphlaw/src/chatman/quarantine.rs`
//! - `/Users/sac/praxis/crates/cng/hooks/dialect-registry.ttl`
//! - `/Users/sac/praxis/crates/cng/hooks/dialect-registry.shape.ttl`
//! - `/Users/sac/praxis/crates/cng/queries/registry-missing-fields.rq`
//! - `/Users/sac/praxis/crates/cng/queries/registry-closed-violations.rq`
//! - `/Users/sac/praxis/crates/cng/src/bench/hooks.rs`
//! - `/Users/sac/praxis/crates/cng/src/powl.rs`

use std::collections::BTreeMap;
use std::fmt;

use oxigraph::io::{RdfFormat, RdfParser};
use oxigraph::model::Term;
use oxigraph::sparql::{QueryResults, SparqlEvaluator};
use oxigraph::store::Store;

include!("f04_dialect_registry_generated.rs");

/// Embedded closed-shape SHACL law. See `registry/dialect-registry.shape.ttl`.
const SHAPE_TTL: &str = include_str!("../registry/dialect-registry.shape.ttl");
/// Embedded shape-driven SPARQL SELECT: rows are (entry, missing field).
const MISSING_FIELDS_QUERY: &str = include_str!("../registry/queries/registry-missing-fields.rq");
/// Embedded shape-driven SPARQL SELECT: rows are (entry, undeclared field).
const CLOSED_VIOLATIONS_QUERY: &str =
    include_str!("../registry/queries/registry-closed-violations.rq");
/// Embedded SPARQL SELECT: distinct `mfwreg:DialectEntry` individuals,
/// used only to compute [`RegistryReceipt::entry_count`] after both
/// closed-shape checks above have already passed.
const ENTRY_COUNT_QUERY: &str = include_str!("../registry/queries/registry-entry-count.rq");

/// `mfwreg:` vocabulary namespace IRI (see `registry/dialect-registry.shape.ttl`
/// and `packs/f04-dialect-registry-pack/ontology.ttl`).
pub const MFWREG_NS: &str =
    "http://seanchatmangpt.github.io/praxis/multifractal-workflow/dialect-registry#";

/// Typed refusal for the F04 Dialect Registry. Every variant here is raised
/// by real code in this module (never asserted, never a placeholder) and
/// covered by a negative test below.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DialectRegistryRefused {
    /// A registry entry is missing one of the eight mandatory fields
    /// (`registry/dialect-registry.shape.ttl` `sh:minCount 1` violation).
    MissingField {
        /// The registry entry IRI (as bound by the SPARQL query).
        entry: String,
        /// The missing required field IRI.
        field: String,
    },
    /// A registry entry carries a property outside the eight mandatory
    /// fields plus `rdf:type`/`rdfs:label`/`rdfs:comment` (`sh:closed true`
    /// violation).
    ClosedShapeViolation {
        /// The registry entry IRI.
        entry: String,
        /// The undeclared property IRI.
        field: String,
    },
    /// An F04-L5 lifecycle step was refused: either not the next rung on
    /// the fixed ladder, an attempt to leave the terminal `Refused` state,
    /// or an attempt to reach `Refused` from a state other than `LOADED`
    /// or `AUTHORITY_BOUND`.
    IllegalTransition {
        /// The state the entry was in.
        from: DialectLifecycleState,
        /// The state the transition attempted to reach.
        to: DialectLifecycleState,
    },
    /// The registry or shape Turtle failed to parse, or a query returned a
    /// shape other than expected (missing an expected binding, or not a
    /// `Solutions` result) -- fail-closed, never a silent empty result.
    MalformedTtl(String),
    /// Store construction or another I/O-adjacent oxigraph operation failed.
    IoRefused(String),
}

impl fmt::Display for DialectRegistryRefused {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::MissingField { entry, field } => write!(
                f,
                "DialectRegistryRefused::MissingField: entry {entry} is missing required field {field}"
            ),
            Self::ClosedShapeViolation { entry, field } => write!(
                f,
                "DialectRegistryRefused::ClosedShapeViolation: entry {entry} carries undeclared property {field}"
            ),
            Self::IllegalTransition { from, to } => write!(
                f,
                "DialectRegistryRefused::IllegalTransition: {from:?} -> {to:?} is not a lawful F04-L5 ladder step"
            ),
            Self::MalformedTtl(msg) => write!(f, "DialectRegistryRefused::MalformedTtl: {msg}"),
            Self::IoRefused(msg) => write!(f, "DialectRegistryRefused::IoRefused: {msg}"),
        }
    }
}

impl std::error::Error for DialectRegistryRefused {}

/// Evidence a successful registry admission returns. See the module docs
/// for exactly what this does and does not cover (not the full F04-L6
/// provenance graph).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RegistryReceipt {
    /// Number of distinct `mfwreg:DialectEntry` individuals admitted.
    pub entry_count: usize,
    /// BLAKE3 hex digest over the canonical Turtle bytes that were
    /// validated (see [`catalog_to_turtle`] for the canonicalization rule).
    pub content_hash: String,
}

/// Turtle string-literal escaping: backslash, double-quote, CR, LF. Applied
/// to every field before it is embedded in generated Turtle so a future
/// catalog entry containing one of these characters fails safely (a Turtle
/// parse error surfaced as `DialectRegistryRefused::MalformedTtl`) rather
/// than producing a syntactically broken or semantically corrupted graph.
fn turtle_escape(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\r', "\\r")
        .replace('\n', "\\n")
}

/// Deterministic IRI local-name slug for a catalog entry's `name` field:
/// lowercase, non-alphanumeric runs collapsed to a single `-`, no
/// leading/trailing `-`.
///
/// # Complexity
/// O(n) in the length of `name`.
fn slugify(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut last_was_dash = false;
    for c in name.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_lowercase());
            last_was_dash = false;
        } else if !last_was_dash && !out.is_empty() {
            out.push('-');
            last_was_dash = true;
        }
    }
    while out.ends_with('-') {
        out.pop();
    }
    out
}

/// Serializes a catalog slice to canonical `mfwreg:DialectEntry` Turtle:
/// entries sorted by `name` (never insertion order, so this is stable
/// regardless of how the caller built the slice), fields in the fixed
/// [`REGISTRY_FIELDS`] order. This is the canonicalization
/// [`validate_registry_turtle`]'s `content_hash` is computed over -- it is
/// a fixed serialization rule of this module, not a general RDF
/// canonicalization (RDFC-1.0/URDNA2015) of the resulting graph.
///
/// # Complexity
/// O(n log n) for the sort plus O(total field bytes) for serialization,
/// where n = `catalog.len()`.
#[must_use]
pub fn catalog_to_turtle(catalog: &[DialectEntry]) -> String {
    let mut sorted: Vec<&DialectEntry> = catalog.iter().collect();
    sorted.sort_by_key(|e| e.name);
    let mut out = String::new();
    out.push_str("@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n");
    out.push_str(&format!("@prefix mfwreg: <{MFWREG_NS}> .\n\n"));
    for e in sorted {
        let slug = slugify(e.name);
        out.push_str(&format!(
            "mfwreg:{slug} a mfwreg:DialectEntry ;\n  rdfs:label \"{label}\" ;\n  rdfs:comment \"{comment}\" ;\n  mfwreg:admittedInputs \"{ai}\" ;\n  mfwreg:manufacturedOutputs \"{mo}\" ;\n  mfwreg:authorityBoundary \"{ab}\" ;\n  mfwreg:quarantineBoundary \"{qb}\" ;\n  mfwreg:refusalVocabulary \"{rv}\" ;\n  mfwreg:receiptSchema \"{rs}\" ;\n  mfwreg:replaySemantics \"{rp}\" ;\n  mfwreg:executableRouting \"{er}\" .\n\n",
            label = turtle_escape(e.name),
            comment = turtle_escape(e.comment),
            ai = turtle_escape(e.admitted_inputs),
            mo = turtle_escape(e.manufactured_outputs),
            ab = turtle_escape(e.authority_boundary),
            qb = turtle_escape(e.quarantine_boundary),
            rv = turtle_escape(e.refusal_vocabulary),
            rs = turtle_escape(e.receipt_schema),
            rp = turtle_escape(e.replay_semantics),
            er = turtle_escape(e.executable_routing),
        ));
    }
    out
}

/// Runs one SPARQL SELECT against `store`, returning each solution row as a
/// `var -> value` map (`NamedNode`s as their IRI string, `Literal`s as
/// their lexical value). Adapted from the identical helper in
/// `crates/cng/src/bench/roles.rs::select_rows` (same oxigraph 0.5 API
/// shape); reimplemented here rather than imported because that helper is
/// `pub(super)` inside `cng`'s private `bench` module.
///
/// # Errors
/// `DialectRegistryRefused::MalformedTtl` on query parse failure, query
/// execution failure, or a non-`Solutions` result.
fn select_rows(
    store: &Store,
    query: &str,
) -> Result<Vec<BTreeMap<String, String>>, DialectRegistryRefused> {
    let prepared = SparqlEvaluator::new()
        .parse_query(query)
        .map_err(|e| DialectRegistryRefused::MalformedTtl(format!("query parse: {e}")))?;
    match prepared.on_store(store).execute() {
        Ok(QueryResults::Solutions(solutions)) => {
            let mut rows = Vec::new();
            for solution in solutions {
                let solution = solution.map_err(|e| {
                    DialectRegistryRefused::MalformedTtl(format!("query eval: {e}"))
                })?;
                let mut row = BTreeMap::new();
                for (var, term) in solution.iter() {
                    row.insert(var.as_str().to_string(), term_value(&term.clone()));
                }
                rows.push(row);
            }
            Ok(rows)
        }
        Ok(_) => Err(DialectRegistryRefused::MalformedTtl(
            "query did not yield solutions".to_string(),
        )),
        Err(e) => Err(DialectRegistryRefused::MalformedTtl(format!(
            "query execution failed: {e}"
        ))),
    }
}

/// Plain-string value of a bound SPARQL term (IRI string for a `NamedNode`,
/// lexical value for a `Literal`).
fn term_value(term: &Term) -> String {
    match term {
        Term::NamedNode(n) => n.as_str().to_string(),
        Term::Literal(l) => l.value().to_string(),
        other => other.to_string(),
    }
}

/// Validates `registry_ttl` (a `mfwreg:DialectEntry` catalog, e.g. the
/// output of [`catalog_to_turtle`]) against the embedded closed-shape SHACL
/// law: loads both into one oxigraph store and runs the two shape-driven
/// structural SELECTs (missing-required-field, then closedness violation).
///
/// # Errors
/// `DialectRegistryRefused::MissingField` or `::ClosedShapeViolation`
/// naming the first violating `(entry, field)` pair (missing-field checked
/// before closedness); `::IoRefused`/`::MalformedTtl` on load/parse
/// failure.
///
/// # Complexity
/// O(registry + shape triples) load, plus three SELECTs over the fixed
/// graph (two closed-shape checks, one entry count).
pub fn validate_registry_turtle(
    registry_ttl: &str,
) -> Result<RegistryReceipt, DialectRegistryRefused> {
    let store = Store::new()
        .map_err(|e| DialectRegistryRefused::IoRefused(format!("store construction: {e}")))?;
    for ttl in [registry_ttl, SHAPE_TTL] {
        store
            .load_from_slice(RdfParser::from_format(RdfFormat::Turtle), ttl.as_bytes())
            .map_err(|e| DialectRegistryRefused::MalformedTtl(format!("registry load: {e}")))?;
    }
    for (is_missing_field, query) in [
        (true, MISSING_FIELDS_QUERY),
        (false, CLOSED_VIOLATIONS_QUERY),
    ] {
        let rows = select_rows(&store, query)?;
        if let Some(row) = rows.first() {
            let bound = |var: &str| -> Result<String, DialectRegistryRefused> {
                row.get(var).cloned().ok_or_else(|| {
                    DialectRegistryRefused::MalformedTtl(format!("query row missing ?{var}"))
                })
            };
            let entry = bound("entry")?;
            let field = bound("field")?;
            return Err(if is_missing_field {
                DialectRegistryRefused::MissingField { entry, field }
            } else {
                DialectRegistryRefused::ClosedShapeViolation { entry, field }
            });
        }
    }
    let entry_count = select_rows(&store, ENTRY_COUNT_QUERY)?.len();
    let content_hash = blake3::hash(registry_ttl.as_bytes()).to_hex().to_string();
    Ok(RegistryReceipt {
        entry_count,
        content_hash,
    })
}

/// Convenience: validates the ggen-generated [`CATALOG`] via
/// [`catalog_to_turtle`] + [`validate_registry_turtle`].
///
/// # Errors
/// See [`validate_registry_turtle`].
pub fn validate_catalog() -> Result<RegistryReceipt, DialectRegistryRefused> {
    validate_registry_turtle(&catalog_to_turtle(CATALOG))
}

/// F04-L5 lifecycle transition guard: the ladder only moves forward one
/// rung at a time (`DECLARED -> LOADED -> SHAPE_VALID -> AUTHORITY_BOUND ->
/// RECEIPT_BOUND -> REPLAY_BOUND -> ACTIVE`); `Refused` is reachable only
/// from `LOADED` or `AUTHORITY_BOUND` and, once reached, is terminal (no
/// further transitions of any kind).
///
/// # Errors
/// `DialectRegistryRefused::IllegalTransition` for any step that is not the
/// next rung, any attempt to leave `Refused`, or any attempt to reach
/// `Refused` from a state other than `LOADED`/`AUTHORITY_BOUND`.
///
/// # Complexity
/// O(1).
pub fn transition(
    current: DialectLifecycleState,
    target: DialectLifecycleState,
) -> Result<DialectLifecycleState, DialectRegistryRefused> {
    if current == DialectLifecycleState::Refused {
        return Err(DialectRegistryRefused::IllegalTransition {
            from: current,
            to: target,
        });
    }
    if target == DialectLifecycleState::Refused {
        return if matches!(
            current,
            DialectLifecycleState::LOADED | DialectLifecycleState::AUTHORITY_BOUND
        ) {
            Ok(DialectLifecycleState::Refused)
        } else {
            Err(DialectRegistryRefused::IllegalTransition {
                from: current,
                to: target,
            })
        };
    }
    if i16::from(target.order()) == i16::from(current.order()) + 1 {
        Ok(target)
    } else {
        Err(DialectRegistryRefused::IllegalTransition {
            from: current,
            to: target,
        })
    }
}

#[cfg(test)]
mod tests {
    //! `DialectRegistryRefused::IoRefused` -- raised only at the
    //! `Store::new()` call in [`validate_registry_turtle`] -- has no
    //! dedicated negative test below, unlike `MissingField`,
    //! `ClosedShapeViolation`, and `IllegalTransition` (each of which does).
    //! This is disclosed, not an oversight: oxigraph 0.5.9's in-memory path
    //! (`Store::new` -> `storage::Storage::new` -> `MemoryStorage::new`) is
    //! unconditionally infallible in-process -- `Storage::new`'s own body is
    //! annotated `#[expect(clippy::unnecessary_wraps)]` upstream, i.e.
    //! oxigraph itself documents that the `Result` never carries an `Err`
    //! for the in-memory backend. There is no safe-Rust way to force that
    //! call to fail from a unit test (no fault-injection seam, no I/O, no
    //! OS resource to exhaust deterministically), so a "negative test" here
    //! would have to fabricate a trigger that cannot occur, which this
    //! module declines to do. `IoRefused`'s `Store::new()?` line is instead
    //! exercised implicitly on its success path by every test below that
    //! calls [`validate_registry_turtle`] or [`validate_catalog`] (the same
    //! `?`-gated call site every one of them runs through), matching the
    //! precedent already disclosed for
    //! `ObservationAdmissionRefused::LedgerUnavailable` in
    //! `f02_observation_admission.rs`'s own tests module doc and for
    //! `ShaclValidatorError`/`ReplayMismatch` in
    //! `f07_shape_admission.rs`'s.

    use super::*;

    /// Not a trigger for [`DialectRegistryRefused::IoRefused`] (see the
    /// module-doc disclosure above for why none exists) -- this asserts the
    /// positive half of that disclosure stays true: `Store::new()` really
    /// is infallible for oxigraph's in-memory backend, so the `IoRefused`
    /// arm in [`validate_registry_turtle`] is dead-on-success-path-only by
    /// construction, not merely by convention. If a future oxigraph
    /// upgrade ever makes in-memory `Store::new()` fallible, this is the
    /// test that would start failing and prompt revisiting the disclosure.
    #[test]
    fn store_new_is_infallible_for_in_memory_backend() {
        for _ in 0..8 {
            assert!(
                oxigraph::store::Store::new().is_ok(),
                "in-memory oxigraph Store::new() must not fail; if this ever \
                 flips, DialectRegistryRefused::IoRefused has become \
                 triggerable and deserves a real negative test"
            );
        }
    }

    #[test]
    fn generated_catalog_validates_against_closed_shape() {
        let receipt = validate_catalog().expect("generated CATALOG must be closed-shape valid");
        assert_eq!(receipt.entry_count, CATALOG.len());
        assert_eq!(
            CATALOG.len(),
            4,
            "F04 wire-phase-1 ships 4 representative dialects"
        );
    }

    #[test]
    fn catalog_to_turtle_is_deterministic() {
        let a = catalog_to_turtle(CATALOG);
        let b = catalog_to_turtle(CATALOG);
        assert_eq!(a, b, "same catalog must serialize to byte-identical Turtle");
        let receipt_a = validate_registry_turtle(&a).expect("valid");
        let receipt_b = validate_registry_turtle(&b).expect("valid");
        assert_eq!(
            receipt_a.content_hash, receipt_b.content_hash,
            "receipt content_hash must be a pure function of catalog content"
        );
    }

    #[test]
    fn missing_field_entry_refuses() {
        let ttl = format!(
            "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n@prefix mfwreg: <{MFWREG_NS}> .\n\nmfwreg:broken a mfwreg:DialectEntry ;\n  rdfs:label \"Broken\" ;\n  rdfs:comment \"Missing replaySemantics on purpose.\" ;\n  mfwreg:admittedInputs \"x\" ;\n  mfwreg:manufacturedOutputs \"x\" ;\n  mfwreg:authorityBoundary \"x\" ;\n  mfwreg:quarantineBoundary \"x\" ;\n  mfwreg:refusalVocabulary \"x\" ;\n  mfwreg:receiptSchema \"x\" ;\n  mfwreg:executableRouting \"x\" .\n"
        );
        match validate_registry_turtle(&ttl) {
            Err(DialectRegistryRefused::MissingField { entry, field }) => {
                assert!(entry.ends_with("broken"));
                assert!(field.ends_with("replaySemantics"));
            }
            other => panic!("expected MissingField, got {other:?}"),
        }
    }

    #[test]
    fn closed_shape_violation_refuses() {
        let ttl = format!(
            "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n@prefix mfwreg: <{MFWREG_NS}> .\n\nmfwreg:extra a mfwreg:DialectEntry ;\n  rdfs:label \"Extra\" ;\n  rdfs:comment \"Carries an undeclared property.\" ;\n  mfwreg:admittedInputs \"x\" ;\n  mfwreg:manufacturedOutputs \"x\" ;\n  mfwreg:authorityBoundary \"x\" ;\n  mfwreg:quarantineBoundary \"x\" ;\n  mfwreg:refusalVocabulary \"x\" ;\n  mfwreg:receiptSchema \"x\" ;\n  mfwreg:replaySemantics \"x\" ;\n  mfwreg:executableRouting \"x\" ;\n  mfwreg:notARegistryField \"surprise\" .\n"
        );
        match validate_registry_turtle(&ttl) {
            Err(DialectRegistryRefused::ClosedShapeViolation { entry, field }) => {
                assert!(entry.ends_with("extra"));
                assert!(field.ends_with("notARegistryField"));
            }
            other => panic!("expected ClosedShapeViolation, got {other:?}"),
        }
    }

    #[test]
    fn lifecycle_ladder_forward_step_ok() {
        use DialectLifecycleState::{
            ACTIVE, AUTHORITY_BOUND, DECLARED, LOADED, RECEIPT_BOUND, REPLAY_BOUND, SHAPE_VALID,
        };
        let ladder = [
            DECLARED,
            LOADED,
            SHAPE_VALID,
            AUTHORITY_BOUND,
            RECEIPT_BOUND,
            REPLAY_BOUND,
            ACTIVE,
        ];
        for pair in ladder.windows(2) {
            assert_eq!(transition(pair[0], pair[1]), Ok(pair[1]));
        }
    }

    #[test]
    fn lifecycle_skip_is_refused() {
        use DialectLifecycleState::{DECLARED, SHAPE_VALID};
        assert_eq!(
            transition(DECLARED, SHAPE_VALID),
            Err(DialectRegistryRefused::IllegalTransition {
                from: DECLARED,
                to: SHAPE_VALID
            })
        );
    }

    #[test]
    fn refused_reachable_only_from_loaded_or_authority_bound() {
        use DialectLifecycleState::{
            Refused, ACTIVE, AUTHORITY_BOUND, DECLARED, LOADED, SHAPE_VALID,
        };
        assert_eq!(transition(LOADED, Refused), Ok(Refused));
        assert_eq!(transition(AUTHORITY_BOUND, Refused), Ok(Refused));
        assert!(transition(DECLARED, Refused).is_err());
        assert!(transition(SHAPE_VALID, Refused).is_err());
        assert!(transition(ACTIVE, Refused).is_err());
    }

    #[test]
    fn refused_is_terminal() {
        use DialectLifecycleState::{Refused, DECLARED};
        assert!(transition(Refused, DECLARED).is_err());
        assert!(transition(Refused, Refused).is_err());
    }
}
