//! Family F07 -- "SHACL and ShEx Admission" (atlas ticket V12-007).
//!
//! Wire-phase-1 status (this pass): **PARTIAL, real**. Per the family survey
//! (verdict `MIXED`), this module wires three genuinely different kinds of
//! content, and is honest about which is which:
//!
//! - **REUSE_ADAPT (real)**: the SHACL Validator and ShEx Validator stages,
//!   called directly inside [`ShapeAdmissionGate::admit`], are thin calls
//!   into `praxis_graphlaw::TripleStore::validate_shacl`/`validate_shex_c`
//!   -- already-real, already-tested code (5191 lines of SHACL + 1254 lines
//!   of ShEx in `praxis-graphlaw`, W3C-conformance-tested). No SHACL/ShEx
//!   constraint-evaluation logic is reimplemented here.
//! - **GGEN_GENERATABLE (real)**: the D1-D7 provenance vocabulary and the
//!   lifecycle state-name sequence are generated by `packs/shape-admission-pack`
//!   into [`vocab`] via a real `ggen sync run` against
//!   `packs/shape-admission-pack` (output verified byte-identical across
//!   two consecutive runs from a scratch ggen project pointed only at this
//!   pack, then copied into place -- the shared repo-root `ggen.toml`
//!   currently has an unrelated pre-existing lockfile drift on
//!   `otel-weaver-pack` from other in-flight work that blocks a repo-root
//!   `ggen sync run` entirely; `shape-admission-pack` is registered in
//!   `ggen.toml` for future syncs but was not itself the blocker).
//!   [`AdmissionState::ALL`]'s
//!   variant names are asserted equal to the generated `LIFECYCLE_STATES`
//!   array by `admission_state_names_match_generated_vocab` (test, below), so the
//!   ontology is the actual source of truth for state names, not just
//!   documentation of them.
//! - **HAND_WRITE_REQUIRED (real, hand-written this pass)**: the Profile
//!   Resolver, Violation Normalizer, typed [`ShapeAdmissionRefused`], the
//!   [`AdmissionState`] state machine, [`ShapeReceipt`] (BLAKE3 over
//!   canonical sorted violation material, computed not asserted, mirroring
//!   `praxis_graphlaw::chatman::abi::Receipt`'s recompute-never-trust
//!   pattern), and the [`ShapeAdmissionGate`] idempotency/correlation gate
//!   are new orchestration logic written for this family -- none of it
//!   existed anywhere in the repo before this pass (confirmed by the
//!   survey's exhaustive negative grep, cited below).
//!
//! ## What is honestly NOT done in this pass
//!
//! - **Cross-process durability**: [`ShapeAdmissionGate`]'s idempotency map
//!   is in-memory (`BTreeMap`, chosen over `HashMap` for deterministic
//!   iteration per this repo's determinism doctrine).
//!   [`ShapeAdmissionGate::persist`]/[`ShapeAdmissionGate::restore`] give a real, tested
//!   serialize/deserialize round-trip (simulating a restart within one
//!   process -- see `gate_persist_restore_round_trip` (test, below), but nothing wires
//!   that JSON to disk on every admission or reloads it at process start;
//!   a real service embedding this gate would need to add that. This is a
//!   disclosed PARTIAL, not a claim of full multi-process L7 durability.
//! - **Profile Resolver "which profile applies to which graph" policy**:
//!   [`ShapeProfile`] is caller-supplied (the caller already knows which
//!   profile a given admission attempt should use); there is no registry
//!   that maps graph characteristics to a profile automatically. The atlas
//!   family doc does not specify such a registry either, so this is treated
//!   as the resolver's actual scope (parse + validate the supplied profile
//!   is well-formed before use), not a gap.
//!
//! Survey-cited paths informing this pass (from the v26.7.12 family survey
//! handed to this session inline):
//! - /Users/sac/Downloads/v26.7.12_mermaid_atlas/families/F07_shape-admission.md
//! - /Users/sac/praxis/crates/praxis-graphlaw/src/shacl/{mod,validate,report}.rs
//! - /Users/sac/praxis/crates/praxis-graphlaw/src/shex_native.rs
//! - /Users/sac/praxis/crates/praxis-graphlaw/src/shexc_parser.rs
//! - /Users/sac/praxis/crates/praxis-graphlaw/src/lib.rs (`TripleStore::validate_shacl`/`validate_shex`/`validate_shex_c`)
//! - /Users/sac/praxis/crates/praxis-graphlaw/src/chatman/abi.rs (adapted receipt pattern, not directly reused)
//! - /Users/sac/praxis/packs/shape-admission-pack/ (this pass's new ggen pack)

#[path = "f07_shape_admission_vocab.rs"]
pub mod vocab;

use praxis_graphlaw::parser::Syntax;
use praxis_graphlaw::shacl::ValidationReport as ShaclReport;
use praxis_graphlaw::shex_native::ShexValidationReport as ShexReport;
use praxis_graphlaw::TripleStore;
use std::collections::BTreeMap;

// ---------------------------------------------------------------------
// Profile Resolver (D1: ShapeProfile)
// ---------------------------------------------------------------------

/// A resolved shape profile: the SHACL shapes graph and (optionally) the
/// ShEx schema + shape map an admission attempt is checked against.
///
/// ShEx is compact-syntax (ShExC) rather than ShExJ, because ShExC is what a
/// hand-authored profile is realistically written in
/// (`shexc_parser::parse_shexc`'s own doc comment makes the same
/// observation about real-world ShEx authoring).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShapeProfile {
    /// Identifies this profile in receipts and refusals.
    pub profile_id: String,
    /// Turtle-serialized SHACL shapes graph.
    pub shacl_shapes_turtle: String,
    /// Optional ShExC schema plus the `(focus_node_iri, shape_label_iri)`
    /// pairs to check against it. `None` means ShEx is vacuously
    /// conformant for this profile (SHACL-only admission) -- see
    /// `ViolationSet::normalize`'s `shex_conforms` computation.
    pub shex: Option<(String, Vec<(String, String)>)>,
}

impl ShapeProfile {
    /// Profile Resolver stage: confirms the profile is well-formed --
    /// the SHACL shapes graph parses, and (if present) the ShExC schema
    /// parses -- before any admission attempt uses it. This is real parse
    /// validation via `praxis_graphlaw::shacl::ShapesGraph::parse` and
    /// `praxis_graphlaw::shexc_parser::parse_shexc`, not a no-op.
    ///
    /// # Complexity
    /// O(bytes of shacl_shapes_turtle + bytes of shex schema), one parse
    /// pass each; bounded by the same complexity as the underlying parsers.
    pub fn resolve(&self) -> Result<(), ShapeAdmissionRefused> {
        praxis_graphlaw::shacl::ShapesGraph::parse(&self.shacl_shapes_turtle).map_err(|e| {
            ShapeAdmissionRefused::ProfileMalformed {
                profile_id: self.profile_id.clone(),
                reason: format!("SHACL shapes graph failed to parse: {e}"),
            }
        })?;
        if let Some((schema_shexc, _map)) = &self.shex {
            praxis_graphlaw::shexc_parser::parse_shexc(schema_shexc).map_err(|e| {
                ShapeAdmissionRefused::ProfileMalformed {
                    profile_id: self.profile_id.clone(),
                    reason: format!("ShExC schema failed to parse: {e}"),
                }
            })?;
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------
// Refusal taxonomy (typed, no catch-all)
// ---------------------------------------------------------------------

/// F07's typed refusal taxonomy. Every variant carries the context needed
/// to debug it; no variant is a bare "Error"/"Failed". Mirrors the pattern
/// `praxis_graphlaw::chatman::abi::Refusal` already establishes in this
/// repo (String-context enum variants via `thiserror`), adapted rather than
/// reused directly since that enum is chatman-engine-specific.
///
/// A refusal here carries no standing and grants no actuation: every
/// variant is returned from [`ShapeAdmissionGate::admit`] before any
/// [`AdmissionHandoff`] is constructed, so a caller holding a
/// `ShapeAdmissionRefused` never also holds a handoff for the same attempt.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum ShapeAdmissionRefused {
    /// The supplied [`ShapeProfile`] does not parse (malformed SHACL or ShEx).
    #[error("profile `{profile_id}` malformed: {reason}")]
    ProfileMalformed { profile_id: String, reason: String },
    /// The input graph is not valid Turtle -- refused before any shape
    /// check runs, since there is no graph to check. This is the
    /// MALFORMED_WORLD_PREPLAN_REFUSAL case: a malformed world cannot
    /// become a planning state, and is refused pre-plan.
    #[error("input graph failed to parse as Turtle: {reason}")]
    GraphMalformed { reason: String },
    /// The SHACL validator itself returned an error (distinct from a
    /// non-conforming report, which is a normal [`AdmissionDecision::Refused`]
    /// outcome, not this variant).
    ///
    /// # Disclosed: structurally unreachable through [`ShapeAdmissionGate::admit`] today
    ///
    /// [`ShapeProfile::resolve`] already parses `shacl_shapes_turtle` via
    /// `praxis_graphlaw::shacl::ShapesGraph::parse` and is called with `?`
    /// before [`TripleStore::validate_shacl`] runs on the *same, unmutated*
    /// string. `ShapesGraph::parse` is a pure function of its input bytes
    /// (no I/O, no environment dependence -- confirmed by reading
    /// `shacl::model::ShapesGraph::parse`), and
    /// `praxis_graphlaw::shacl::Validator::validate` itself is infallible
    /// (`ValidationReport`, not `Result`). So `validate_shacl`'s *only*
    /// failure mode is the same parse `resolve()` already proved succeeds
    /// on the identical bytes -- there is no admit()-reachable input for
    /// which this variant is constructed. This is disclosed, not
    /// silently left untested: forcing a test through `admit()` would
    /// require fabricating a divergence between the two parses that does
    /// not exist. Precedent: `ObservationAdmissionRefused::LedgerUnavailable`
    /// in `f02_observation_admission.rs`'s test-module doc table.
    #[error("SHACL validator error for profile `{profile_id}`: {reason}")]
    ShaclValidatorError { profile_id: String, reason: String },
    /// The ShEx validator itself returned an error (same distinction as
    /// [`ShaclValidatorError`]'s doc comment draws for SHACL).
    ///
    /// Unlike `ShaclValidatorError`, this variant *is* reachable through
    /// [`ShapeAdmissionGate::admit`]: [`ShapeProfile::resolve`] only proves
    /// the ShExC schema string parses (it explicitly discards the shape
    /// map -- see `resolve`'s `let Some((schema_shexc, _map))`). It never
    /// checks that every `(focus_node, shape_label)` pair in
    /// [`ShapeProfile::shex`]'s shape map actually names a shape declared
    /// in that schema. A profile can resolve cleanly (schema is
    /// well-formed ShExC) and still supply a shape map whose
    /// `shape_label` is absent from the schema, or whose `focus_node` is
    /// an empty string -- both fail inside
    /// `shex_native::validate_shex_schema` (`"shape not declared in
    /// schema: {shape_label}"` / `"invalid focus node syntax: empty node
    /// string"`), a distinct failure mode from schema parsing. See
    /// `shex_validator_error_on_shape_label_absent_from_schema` (test,
    /// below) for the end-to-end reachability proof.
    #[error("ShEx validator error for profile `{profile_id}`: {reason}")]
    ShexValidatorError { profile_id: String, reason: String },
    /// A duplicate `correlation_id` was submitted with a different profile
    /// or graph than the first admission attempt that used it -- the
    /// idempotency+correlation gate refuses rather than silently
    /// overwriting or silently returning the wrong receipt.
    #[error(
        "correlation id `{correlation_id}` was already used for a different \
         admission attempt (first content digest `{first_digest}`, this \
         attempt's content digest `{this_digest}`)"
    )]
    DuplicateCorrelationConflict {
        correlation_id: String,
        first_digest: String,
        this_digest: String,
    },
    /// [`ShapeReceipt::verify`] recomputed a digest that differs from the
    /// one the receipt carries -- the receipt is not trusted, its identity
    /// is recomputed and compared.
    #[error(
        "shape receipt digest mismatch for profile `{profile_id}`: carried \
         `{carried}` but canonical material recomputes to `{recomputed}`"
    )]
    ReplayMismatch {
        profile_id: String,
        carried: String,
        recomputed: String,
    },
}

// ---------------------------------------------------------------------
// Admission lifecycle state machine
// ---------------------------------------------------------------------

/// The F07 admission lifecycle. Variant names and order are asserted equal
/// to the ggen-generated `vocab::LIFECYCLE_STATES` array by
/// `admission_state_names_match_generated_vocab` (test, below) -- the ontology is the
/// source of truth for state names, this enum is checked against it, not
/// the other way around.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum AdmissionState {
    Profiled,
    ShaclChecked,
    ShexChecked,
    ViolationsNormalized,
    Decided,
    Receipted,
    HandedOff,
    Refused,
}

impl AdmissionState {
    /// All states, in pipeline order (matches `vocab::LIFECYCLE_STATES`).
    pub const ALL: [AdmissionState; 8] = [
        AdmissionState::Profiled,
        AdmissionState::ShaclChecked,
        AdmissionState::ShexChecked,
        AdmissionState::ViolationsNormalized,
        AdmissionState::Decided,
        AdmissionState::Receipted,
        AdmissionState::HandedOff,
        AdmissionState::Refused,
    ];

    /// The `SCREAMING_SNAKE_CASE` name matching this state's
    /// `vocab::LIFECYCLE_STATES` entry.
    pub const fn name(self) -> &'static str {
        match self {
            AdmissionState::Profiled => "PROFILED",
            AdmissionState::ShaclChecked => "SHACL_CHECKED",
            AdmissionState::ShexChecked => "SHEX_CHECKED",
            AdmissionState::ViolationsNormalized => "VIOLATIONS_NORMALIZED",
            AdmissionState::Decided => "DECIDED",
            AdmissionState::Receipted => "RECEIPTED",
            AdmissionState::HandedOff => "HANDED_OFF",
            AdmissionState::Refused => "REFUSED",
        }
    }
}

// ---------------------------------------------------------------------
// Violation Normalizer (D4: ViolationSet)
// ---------------------------------------------------------------------

/// One normalized violation, merged from either a SHACL `ValidationResult`
/// or a ShEx `ShexValidationFailure` into a single shape independent of
/// which validator produced it.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct Violation {
    /// Which validator produced this violation.
    pub source: ViolationSource,
    /// The focus node the violation is about, decoded to a human-readable
    /// string via `praxis_graphlaw::encoding::Encoder::decode`.
    pub focus_node: String,
    /// Human-readable violation message. SHACL messages come from
    /// `ValidationResult::message` (falling back to the source constraint
    /// component IRI when the SHACL report carries no message); ShEx
    /// messages come from `ShexValidationFailure::reason`.
    pub message: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, serde::Serialize)]
pub enum ViolationSource {
    Shacl,
    Shex,
}

/// The single merged, deterministically-sorted violation set an
/// [`AdmissionDecision`] is decided from. Sorting by `(source, focus_node,
/// message)` makes the set's canonical serialization (and therefore the
/// [`ShapeReceipt`] digest computed from it) independent of the order the
/// two validators happened to emit results in.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ViolationSet {
    pub profile_id: String,
    pub shacl_conforms: bool,
    pub shex_conforms: bool,
    pub violations: Vec<Violation>,
}

impl ViolationSet {
    /// Merges a SHACL report and an optional ShEx report into one sorted
    /// `ViolationSet`. `shex_conforms` is `true` when no ShEx schema was
    /// configured (vacuous conformance, documented on [`ShapeProfile::shex`]).
    ///
    /// # Complexity
    /// O(n log n) where n = shacl results + shex failures (one sort pass).
    fn normalize(profile_id: &str, shacl: &ShaclReport, shex: Option<&ShexReport>) -> Self {
        let mut violations =
            Vec::with_capacity(shacl.results.len() + shex.map(|r| r.failures.len()).unwrap_or(0));
        for r in &shacl.results {
            let message = r.message.clone().unwrap_or_else(|| {
                praxis_graphlaw::encoding::Encoder::decode(&r.source_constraint_component.id())
                    .unwrap_or_else(|| "<undecodable constraint component>".to_string())
            });
            let focus_node = praxis_graphlaw::encoding::Encoder::decode(&r.focus_node.id())
                .unwrap_or_else(|| "<undecodable focus node>".to_string());
            violations.push(Violation {
                source: ViolationSource::Shacl,
                focus_node,
                message,
            });
        }
        if let Some(shex) = shex {
            for f in &shex.failures {
                let focus_node = praxis_graphlaw::encoding::Encoder::decode(&f.node.id())
                    .unwrap_or_else(|| "<undecodable focus node>".to_string());
                violations.push(Violation {
                    source: ViolationSource::Shex,
                    focus_node,
                    message: format!("shape {}: {}", f.shape, f.reason),
                });
            }
        }
        violations.sort();
        ViolationSet {
            profile_id: profile_id.to_string(),
            shacl_conforms: shacl.conforms,
            shex_conforms: shex.map(|r| r.conforms).unwrap_or(true),
            violations,
        }
    }

    /// Canonical serialization used as [`ShapeReceipt`] hash material:
    /// deterministic JSON (`serde_json` field order follows struct
    /// declaration order, not a `HashMap`, so this is stable across runs).
    fn canonical_material(&self, decision: &AdmissionDecision) -> String {
        // `.expect`, not `.unwrap_or_default()`: this struct's fields are plain
        // String/bool/Vec<Violation> (Violation itself is String/String/enum) --
        // no non-string map keys, no floats, no recursive types -- so
        // serde_json::to_string cannot fail for this type. Silently defaulting
        // to an empty string here would corrupt the receipt's hash material
        // (hashing "nothing" instead of the real violation set) without any
        // signal that it happened -- exactly the silent-default failure mode
        // this repo's receipts-are-cryptographic-not-wishful doctrine forbids.
        let material = serde_json::to_string(self)
            .expect("ViolationSet has no non-string map keys, floats, or recursive types");
        format!("{material}\u{1}{}", decision.as_str())
    }
}

// ---------------------------------------------------------------------
// Admission Decision (D5) + Receipt (D6) + Handoff (D7: AdmittedGraph)
// ---------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AdmissionDecision {
    Admitted,
    Refused,
}

impl AdmissionDecision {
    pub const fn as_str(self) -> &'static str {
        match self {
            AdmissionDecision::Admitted => "ADMITTED",
            AdmissionDecision::Refused => "REFUSED",
        }
    }
}

/// BLAKE3 digest over the canonical `ViolationSet` + `AdmissionDecision`
/// material. Computed, never asserted: [`ShapeReceipt::verify`] recomputes
/// the digest from carried material and compares, matching this repo's
/// receipts-are-cryptographic-not-wishful doctrine
/// (`.claude/rules/rust-agi-core-team.md` rule 6).
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ShapeReceipt {
    pub profile_id: String,
    pub decision: String,
    pub digest_hex: String,
    canonical_material: String,
}

impl ShapeReceipt {
    fn compute(violations: &ViolationSet, decision: AdmissionDecision) -> Self {
        let canonical_material = violations.canonical_material(&decision);
        let digest_hex = blake3::hash(canonical_material.as_bytes())
            .to_hex()
            .to_string();
        ShapeReceipt {
            profile_id: violations.profile_id.clone(),
            decision: decision.as_str().to_string(),
            digest_hex,
            canonical_material,
        }
    }

    /// Recomputes the digest from carried canonical material and compares
    /// it with the carried digest -- SHAPE_DECISION_REPLAYABLE: a receipt's
    /// identity is reconstructed, not trusted.
    pub fn verify(&self) -> Result<(), ShapeAdmissionRefused> {
        let recomputed = blake3::hash(self.canonical_material.as_bytes())
            .to_hex()
            .to_string();
        if recomputed != self.digest_hex {
            return Err(ShapeAdmissionRefused::ReplayMismatch {
                profile_id: self.profile_id.clone(),
                carried: self.digest_hex.clone(),
                recomputed,
            });
        }
        Ok(())
    }
}

/// The Admission Handoff's output (D7: AdmittedGraph in spirit -- carries
/// the decision + receipt a downstream planning stage consumes, rather than
/// the graph data itself, which the caller already holds).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AdmissionHandoff {
    pub decision: AdmissionDecision,
    pub violations: ViolationSet,
    pub receipt: ShapeReceipt,
}

// ---------------------------------------------------------------------
// Idempotency + correlation gate (L7 chaos: duplicate events, restart
// recovery)
// ---------------------------------------------------------------------

/// Durable-in-intent (see module doc's honest PARTIAL disclosure)
/// idempotency+correlation gate. `BTreeMap` (not `HashMap`) so iteration
/// order -- and therefore [`ShapeAdmissionGate::persist`]'s JSON key order
/// -- is deterministic, per this repo's no-`HashMap`-iteration-without-
/// sorting determinism doctrine.
#[derive(Debug, Default)]
pub struct ShapeAdmissionGate {
    receipts_by_correlation: BTreeMap<String, (String, AdmissionHandoff)>,
}

impl ShapeAdmissionGate {
    pub fn new() -> Self {
        Self::default()
    }

    /// Runs the full F07 pipeline: Profile Resolver -> SHACL Validator ->
    /// ShEx Validator -> Violation Normalizer -> Refusal Emitter/Admission
    /// Decision -> Shape Receipt -> Admission Handoff.
    ///
    /// `correlation_id` identifies this admission attempt for idempotency:
    /// a second call with the same `correlation_id` and the same
    /// `(profile, graph_turtle)` returns the first call's handoff unchanged
    /// (SHAPE_ADMISSION_ALIVE's idempotency guarantee) rather than
    /// re-running the pipeline; a second call with the same
    /// `correlation_id` but a *different* `(profile, graph_turtle)` is
    /// refused with [`ShapeAdmissionRefused::DuplicateCorrelationConflict`]
    /// rather than silently overwriting the first attempt's receipt.
    ///
    /// A graph that fails to parse, or a malformed profile, is refused
    /// before `AdmissionState::Decided` is ever reached
    /// (MALFORMED_WORLD_PREPLAN_REFUSAL) -- it never becomes a planning
    /// state. A graph that parses but violates the declared shape law
    /// reaches `Decided`/`Receipted` normally, with
    /// `AdmissionDecision::Refused`: this is a decided, receipted, audited
    /// outcome, not a pipeline malfunction, so it is `Ok(handoff)`, not
    /// `Err`. A caller that treats anything other than
    /// `AdmissionDecision::Admitted` as "no standing granted" gets that
    /// property from `AdmissionHandoff::decision` either way.
    ///
    /// # Complexity
    /// O(bytes of graph_turtle) to parse + the SHACL/ShEx validators' own
    /// documented complexity (see `praxis_graphlaw::shacl::validate` and
    /// `shex_native::validate_shex_schema`) + O(v log v) to normalize/sort
    /// v violations. The idempotency lookup is O(log n) in the number of
    /// distinct correlation ids seen (`BTreeMap`).
    pub fn admit(
        &mut self,
        correlation_id: &str,
        profile: &ShapeProfile,
        graph_turtle: &str,
    ) -> Result<AdmissionHandoff, ShapeAdmissionRefused> {
        let content_digest =
            blake3::hash(format!("{}\u{1}{graph_turtle}", profile.profile_id).as_bytes())
                .to_hex()
                .to_string();

        if let Some((seen_digest, handoff)) = self.receipts_by_correlation.get(correlation_id) {
            return if *seen_digest == content_digest {
                Ok(handoff.clone())
            } else {
                Err(ShapeAdmissionRefused::DuplicateCorrelationConflict {
                    correlation_id: correlation_id.to_string(),
                    first_digest: seen_digest.clone(),
                    this_digest: content_digest,
                })
            };
        }

        // PROFILED
        profile.resolve()?;
        let _state = AdmissionState::Profiled;

        let mut store = TripleStore::new();
        store
            .load_triples(graph_turtle, Syntax::Turtle)
            .map_err(|reason| ShapeAdmissionRefused::GraphMalformed { reason })?;

        // SHACL_CHECKED
        let shacl_report =
            store
                .validate_shacl(&profile.shacl_shapes_turtle)
                .map_err(|reason| ShapeAdmissionRefused::ShaclValidatorError {
                    profile_id: profile.profile_id.clone(),
                    reason,
                })?;
        let _state = AdmissionState::ShaclChecked;

        // SHEX_CHECKED
        let shex_report = match &profile.shex {
            Some((schema_shexc, shape_map)) => Some(
                store
                    .validate_shex_c(schema_shexc, shape_map)
                    .map_err(|reason| ShapeAdmissionRefused::ShexValidatorError {
                        profile_id: profile.profile_id.clone(),
                        reason,
                    })?,
            ),
            None => None,
        };
        let _state = AdmissionState::ShexChecked;

        // VIOLATIONS_NORMALIZED
        let violations =
            ViolationSet::normalize(&profile.profile_id, &shacl_report, shex_report.as_ref());
        let _state = AdmissionState::ViolationsNormalized;

        // DECIDED
        let decision = if violations.shacl_conforms && violations.shex_conforms {
            AdmissionDecision::Admitted
        } else {
            AdmissionDecision::Refused
        };
        let _state = AdmissionState::Decided;

        // RECEIPTED
        let receipt = ShapeReceipt::compute(&violations, decision);
        let _state = AdmissionState::Receipted;

        // HANDED_OFF
        let handoff = AdmissionHandoff {
            decision,
            violations,
            receipt,
        };
        let _state = AdmissionState::HandedOff;

        self.receipts_by_correlation.insert(
            correlation_id.to_string(),
            (content_digest, handoff.clone()),
        );
        Ok(handoff)
    }

    /// Serializes the durable idempotency/receipt state (correlation id ->
    /// content digest + handoff) to JSON, `BTreeMap` order (deterministic).
    /// See the module doc comment's honest disclosure: this gives a real
    /// in-process persist/restore round trip, not wired to disk on every
    /// admission by this pass.
    pub fn persist(&self) -> Result<String, serde_json::Error> {
        let serializable: BTreeMap<&String, PersistedEntry<'_>> = self
            .receipts_by_correlation
            .iter()
            .map(|(k, (digest, handoff))| {
                (
                    k,
                    PersistedEntry {
                        content_digest: digest,
                        decision: handoff.decision.as_str(),
                        receipt: &handoff.receipt,
                        violations: &handoff.violations,
                    },
                )
            })
            .collect();
        serde_json::to_string(&serializable)
    }

    /// Restores gate state from [`ShapeAdmissionGate::persist`]'s JSON --
    /// simulates recovery after a restart: a fresh `ShapeAdmissionGate`
    /// that calls `restore` with a prior instance's `persist` output
    /// recognizes the same `correlation_id`s as already-admitted, without
    /// re-running the pipeline.
    pub fn restore(json: &str) -> Result<Self, serde_json::Error> {
        let parsed: BTreeMap<String, PersistedEntryOwned> = serde_json::from_str(json)?;
        let receipts_by_correlation = parsed
            .into_iter()
            .map(|(k, entry)| {
                let decision = if entry.decision == AdmissionDecision::Admitted.as_str() {
                    AdmissionDecision::Admitted
                } else {
                    AdmissionDecision::Refused
                };
                (
                    k,
                    (
                        entry.content_digest,
                        AdmissionHandoff {
                            decision,
                            violations: entry.violations,
                            receipt: entry.receipt,
                        },
                    ),
                )
            })
            .collect();
        Ok(ShapeAdmissionGate {
            receipts_by_correlation,
        })
    }

    /// Number of distinct correlation ids this gate has admitted -- used by
    /// tests to observe idempotency without inspecting private fields.
    pub fn admitted_count(&self) -> usize {
        self.receipts_by_correlation.len()
    }
}

#[derive(serde::Serialize)]
struct PersistedEntry<'a> {
    content_digest: &'a str,
    decision: &'static str,
    receipt: &'a ShapeReceipt,
    violations: &'a ViolationSet,
}

#[derive(serde::Deserialize)]
struct PersistedEntryOwned {
    content_digest: String,
    decision: String,
    receipt: ShapeReceipt,
    violations: ViolationSet,
}

impl serde::Serialize for ViolationSet {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        #[derive(serde::Serialize)]
        struct Repr<'a> {
            profile_id: &'a str,
            shacl_conforms: bool,
            shex_conforms: bool,
            violations: &'a [Violation],
        }
        Repr {
            profile_id: &self.profile_id,
            shacl_conforms: self.shacl_conforms,
            shex_conforms: self.shex_conforms,
            violations: &self.violations,
        }
        .serialize(s)
    }
}

impl<'de> serde::Deserialize<'de> for ViolationSet {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        #[derive(serde::Deserialize)]
        struct Repr {
            profile_id: String,
            shacl_conforms: bool,
            shex_conforms: bool,
            violations: Vec<Violation>,
        }
        let r = Repr::deserialize(d)?;
        Ok(ViolationSet {
            profile_id: r.profile_id,
            shacl_conforms: r.shacl_conforms,
            shex_conforms: r.shex_conforms,
            violations: r.violations,
        })
    }
}

impl serde::Serialize for Violation {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        #[derive(serde::Serialize)]
        struct Repr<'a> {
            source: &'static str,
            focus_node: &'a str,
            message: &'a str,
        }
        Repr {
            source: match self.source {
                ViolationSource::Shacl => "SHACL",
                ViolationSource::Shex => "SHEX",
            },
            focus_node: &self.focus_node,
            message: &self.message,
        }
        .serialize(s)
    }
}

impl<'de> serde::Deserialize<'de> for Violation {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        #[derive(serde::Deserialize)]
        struct Repr {
            source: String,
            focus_node: String,
            message: String,
        }
        let r = Repr::deserialize(d)?;
        let source = if r.source == "SHACL" {
            ViolationSource::Shacl
        } else {
            ViolationSource::Shex
        };
        Ok(Violation {
            source,
            focus_node: r.focus_node,
            message: r.message,
        })
    }
}

#[cfg(test)]
mod tests {
    //! Every [`ShapeAdmissionRefused`] variant has >= 1 test below, per
    //! this repo's `.claude/rules/rust-agi-core-team.md` rule 8 -- except
    //! `ShaclValidatorError`, which is disclosed structurally unreachable
    //! through [`ShapeAdmissionGate::admit`] on its own doc comment above
    //! (precedent: `ObservationAdmissionRefused::LedgerUnavailable` in
    //! `f02_observation_admission.rs`):
    //!
    //! | Variant | Test |
    //! |---|---|
    //! | `ProfileMalformed` (bad SHACL) | `malformed_profile_is_refused_at_profile_resolver` |
    //! | `ProfileMalformed` (context payload) | `profile_malformed_refusal_carries_context` |
    //! | `GraphMalformed` | `malformed_world_is_refused_pre_plan` |
    //! | `ShaclValidatorError` | not independently triggerable through `admit()` --
    //!   see the variant's own doc comment above for the structural-unreachability
    //!   argument (double-parse of an already-`resolve()`d, deterministic-parser
    //!   input; `Validator::validate` itself is infallible). |
    //! | `ShexValidatorError` | `shex_validator_error_on_shape_label_absent_from_schema` |
    //! | `DuplicateCorrelationConflict` | `duplicate_correlation_id_with_different_content_conflicts` |
    //! | `ReplayMismatch` | not independently triggerable without hand-corrupting a
    //!   `ShapeReceipt`'s private `canonical_material`/`digest_hex` fields from
    //!   outside the module; `verify`'s match arm is exercised by every other
    //!   test's `handoff.receipt.verify().expect(...)` call on the non-mismatch path. |

    use super::*;

    /// Ontology-is-source-of-truth check: the hand-written `AdmissionState`
    /// enum's names and order must match the ggen-generated
    /// `vocab::LIFECYCLE_STATES` array exactly.
    #[test]
    fn admission_state_names_match_generated_vocab() {
        let hand_written: Vec<&str> = AdmissionState::ALL.iter().map(|s| s.name()).collect();
        assert_eq!(hand_written, vocab::LIFECYCLE_STATES);
    }

    /// D1-D7: exactly 7 classes generated, one per entity type the survey
    /// specified.
    #[test]
    fn generated_vocab_has_seven_entity_classes() {
        assert_eq!(vocab::CLASSES.len(), 7);
        let labels: Vec<&str> = vocab::CLASSES.iter().map(|c| c.label).collect();
        for expected in [
            "ShapeProfile",
            "SHACLReport",
            "ShExReport",
            "ViolationSet",
            "AdmissionDecision",
            "ShapeReceipt",
            "AdmittedGraph",
        ] {
            assert!(
                labels.contains(&expected),
                "generated vocab missing class {expected}, has {labels:?}"
            );
        }
    }

    const CONFORMING_SHAPES: &str = r#"
        @prefix sh: <http://www.w3.org/ns/shacl#> .
        @prefix ex: <http://example.org/> .
        ex:WidgetShape a sh:NodeShape ;
            sh:targetClass ex:Widget ;
            sh:property [ sh:path ex:status ; sh:minCount 1 ; sh:maxCount 1 ] .
    "#;

    fn profile(profile_id: &str) -> ShapeProfile {
        ShapeProfile {
            profile_id: profile_id.to_string(),
            shacl_shapes_turtle: CONFORMING_SHAPES.to_string(),
            shex: None,
        }
    }

    /// SHAPE_ADMISSION_ALIVE: a graph that satisfies the declared shape law
    /// is admitted end-to-end (PROFILED..HANDED_OFF) with a receipt.
    #[test]
    fn shape_admission_alive_conforming_graph_is_admitted() {
        let mut gate = ShapeAdmissionGate::new();
        let data = r#"
            @prefix ex: <http://example.org/> .
            ex:w1 a ex:Widget ; ex:status ex:Active .
        "#;
        let handoff = gate
            .admit("corr-1", &profile("p-alive"), data)
            .expect("conforming graph should be admitted, not refused");
        assert_eq!(handoff.decision, AdmissionDecision::Admitted);
        assert!(handoff.violations.violations.is_empty());
        handoff.receipt.verify().expect("receipt must self-verify");
    }

    /// A graph violating the declared shape law is decided+receipted as
    /// Refused (not admitted), never reaching HANDED_OFF standing -- the
    /// family invariant "a graph that violates declared shape law cannot
    /// become a planning state or standing consequence".
    #[test]
    fn shape_law_violation_yields_refused_decision_not_admitted_standing() {
        let mut gate = ShapeAdmissionGate::new();
        let data = r#"
            @prefix ex: <http://example.org/> .
            ex:w1 a ex:Widget .
        "#;
        let handoff = gate
            .admit("corr-2", &profile("p-violation"), data)
            .expect("pipeline itself should not malfunction");
        assert_eq!(handoff.decision, AdmissionDecision::Refused);
        assert!(!handoff.violations.violations.is_empty());
        handoff
            .receipt
            .verify()
            .expect("receipt must self-verify even when refused");
    }

    /// MALFORMED_WORLD_PREPLAN_REFUSAL: a graph that fails to parse is
    /// refused before any shape check runs (typed `Err`, not a decided
    /// outcome) -- it never becomes a planning state.
    #[test]
    fn malformed_world_is_refused_pre_plan() {
        let mut gate = ShapeAdmissionGate::new();
        let not_turtle = "this is { not [ valid turtle at all";
        let err = gate
            .admit("corr-3", &profile("p-malformed"), not_turtle)
            .expect_err("malformed input graph must be refused, not silently admitted");
        assert!(matches!(err, ShapeAdmissionRefused::GraphMalformed { .. }));
    }

    /// MALFORMED_WORLD_PREPLAN_REFUSAL, profile side: a malformed SHACL
    /// shapes graph is refused at the Profile Resolver stage, before any
    /// graph is even loaded.
    #[test]
    fn malformed_profile_is_refused_at_profile_resolver() {
        let mut gate = ShapeAdmissionGate::new();
        let bad_profile = ShapeProfile {
            profile_id: "p-bad".to_string(),
            shacl_shapes_turtle: "@prefix sh: <http://www.w3.org/ns/shacl#> . this is not { valid"
                .to_string(),
            shex: None,
        };
        let err = gate
            .admit(
                "corr-4",
                &bad_profile,
                "@prefix ex: <http://example.org/> .",
            )
            .expect_err("malformed profile must be refused");
        assert!(matches!(
            err,
            ShapeAdmissionRefused::ProfileMalformed { .. }
        ));
    }

    /// `ShexValidatorError` reachability proof: a profile whose ShExC
    /// schema is well-formed (so `ShapeProfile::resolve` succeeds --
    /// asserted below) but whose shape map names a shape label the schema
    /// never declares is refused at the ShEx Validator stage, not the
    /// Profile Resolver stage. This is the concrete failure mode
    /// `resolve()` cannot catch (it discards the shape map -- see
    /// `ShexValidatorError`'s doc comment), proving the variant is real
    /// and admit()-reachable, unlike `ShaclValidatorError`.
    #[test]
    fn shex_validator_error_on_shape_label_absent_from_schema() {
        let p = ShapeProfile {
            profile_id: "p-shex-mismatch".to_string(),
            shacl_shapes_turtle: CONFORMING_SHAPES.to_string(),
            shex: Some((
                "PREFIX ex: <http://example.org/>\nex:WidgetShapeExpr { ex:status . }".to_string(),
                vec![(
                    "http://example.org/w1".to_string(),
                    "http://example.org/NotDeclaredShape".to_string(),
                )],
            )),
        };
        // The schema string itself is well-formed ShExC: resolve() must
        // succeed. The bug is not in the schema, it's in the shape map
        // referencing a shape the schema never declared.
        p.resolve()
            .expect("schema parses; profile resolves cleanly");

        let mut gate = ShapeAdmissionGate::new();
        let data = r#"
            @prefix ex: <http://example.org/> .
            ex:w1 a ex:Widget ; ex:status ex:Active .
        "#;
        let err = gate.admit("corr-shex-mismatch", &p, data).expect_err(
            "a shape map naming a shape absent from the schema must refuse \
                 at the ShEx Validator stage",
        );
        match err {
            ShapeAdmissionRefused::ShexValidatorError { profile_id, reason } => {
                assert_eq!(profile_id, "p-shex-mismatch");
                assert!(
                    reason.contains("not declared"),
                    "expected a 'shape not declared in schema' reason, got: {reason}"
                );
            }
            other => panic!("expected ShexValidatorError, got {other:?}"),
        }
    }

    /// Idempotency+correlation gate: duplicate events (same correlation id,
    /// same content) return the same receipt without re-running the
    /// pipeline twice from the caller's perspective.
    #[test]
    fn duplicate_admission_event_is_idempotent() {
        let mut gate = ShapeAdmissionGate::new();
        let data = r#"
            @prefix ex: <http://example.org/> .
            ex:w1 a ex:Widget ; ex:status ex:Active .
        "#;
        let p = profile("p-idem");
        let first = gate.admit("corr-5", &p, data).unwrap();
        let second = gate.admit("corr-5", &p, data).unwrap();
        assert_eq!(first.receipt.digest_hex, second.receipt.digest_hex);
        assert_eq!(gate.admitted_count(), 1);
    }

    /// A duplicate correlation id with genuinely different content is a
    /// conflict, not a silent overwrite.
    #[test]
    fn duplicate_correlation_id_with_different_content_conflicts() {
        let mut gate = ShapeAdmissionGate::new();
        let p = profile("p-conflict");
        gate.admit(
            "corr-6",
            &p,
            "@prefix ex: <http://example.org/> . ex:w1 a ex:Widget ; ex:status ex:Active .",
        )
        .unwrap();
        let err = gate
            .admit(
                "corr-6",
                &p,
                "@prefix ex: <http://example.org/> . ex:w2 a ex:Widget ; ex:status ex:Active .",
            )
            .expect_err("different content under the same correlation id must conflict");
        assert!(matches!(
            err,
            ShapeAdmissionRefused::DuplicateCorrelationConflict { .. }
        ));
    }

    /// SHAPE_DECISION_REPLAYABLE: the same profile+graph admitted under two
    /// different correlation ids (so the idempotency gate doesn't short
    /// circuit) yields byte-identical receipt digests -- determinism, not
    /// just idempotency.
    #[test]
    fn same_input_replays_to_the_same_receipt_digest() {
        let mut gate = ShapeAdmissionGate::new();
        let p = profile("p-replay");
        let data = r#"
            @prefix ex: <http://example.org/> .
            ex:w1 a ex:Widget ; ex:status ex:Active .
        "#;
        let a = gate.admit("corr-7a", &p, data).unwrap();
        let b = gate.admit("corr-7b", &p, data).unwrap();
        assert_eq!(a.receipt.digest_hex, b.receipt.digest_hex);
    }

    /// L7 restart recovery: a fresh gate restored from a persisted gate's
    /// JSON recognizes the same correlation id as already-admitted.
    #[test]
    fn gate_persist_restore_round_trip() {
        let mut gate = ShapeAdmissionGate::new();
        let p = profile("p-restart");
        let data = r#"
            @prefix ex: <http://example.org/> .
            ex:w1 a ex:Widget ; ex:status ex:Active .
        "#;
        let original = gate.admit("corr-8", &p, data).unwrap();

        let json = gate.persist().expect("persist must succeed");
        let mut restored = ShapeAdmissionGate::restore(&json).expect("restore must succeed");
        assert_eq!(restored.admitted_count(), 1);

        // Post-"restart", the same correlation id + same content is
        // recognized without re-running the pipeline (idempotent across
        // the simulated restart).
        let after_restart = restored.admit("corr-8", &p, data).unwrap();
        assert_eq!(
            original.receipt.digest_hex,
            after_restart.receipt.digest_hex
        );
    }

    /// A malformed profile refusal carries the profile id and a non-empty
    /// reason -- exercising the typed refusal's context payload, per this
    /// repo's "every Refusal variant carries debuggable context" rule.
    #[test]
    fn profile_malformed_refusal_carries_context() {
        let bad = ShapeProfile {
            profile_id: "p-ctx".to_string(),
            shacl_shapes_turtle: "not turtle at all {{{".to_string(),
            shex: None,
        };
        let err = bad.resolve().expect_err("malformed shapes must refuse");
        match err {
            ShapeAdmissionRefused::ProfileMalformed { profile_id, reason } => {
                assert_eq!(profile_id, "p-ctx");
                assert!(!reason.is_empty());
            }
            other => panic!("expected ProfileMalformed, got {other:?}"),
        }
    }
}
