//! GENERATED by `ggen sync` from `packs/shape-admission-pack/ontology.ttl` --
//! do not edit by hand. Source of truth for the F07 "SHACL and ShEx
//! Admission" (V12-007) D1-D7 provenance vocabulary and lifecycle state
//! names; consumed by the hand-written `super` module
//! (`f07_shape_admission.rs`), which implements the actual admission
//! pipeline, state machine, and receipt logic this file only documents.

/// One D1-D7 entity-type class: `(label, iri, comment)`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ClassDef {
    pub label: &'static str,
    pub iri: &'static str,
    pub comment: &'static str,
}

/// The 7 RDF entity types in the F07 provenance data model, sorted by label.
pub const CLASSES: &[ClassDef] = &[
ClassDef { label: "AdmissionDecision", iri: "https://ggen.io/ontology/shape-admission#AdmissionDecision", comment: "Admitted or Refused, decided from exactly one ViolationSet." },
ClassDef { label: "AdmittedGraph", iri: "https://ggen.io/ontology/shape-admission#AdmittedGraph", comment: "The Admission Handoff's output: a graph that has passed the declared structural profile, carrying its ShapeReceipt." },
ClassDef { label: "SHACLReport", iri: "https://ggen.io/ontology/shape-admission#SHACLReport", comment: "The SHACL Validator's sh:ValidationReport (conforms + results) for one admission attempt." },
ClassDef { label: "ShExReport", iri: "https://ggen.io/ontology/shape-admission#ShExReport", comment: "The ShEx Validator's ShexValidationReport (conforms + failures) for one admission attempt." },
ClassDef { label: "ShapeProfile", iri: "https://ggen.io/ontology/shape-admission#ShapeProfile", comment: "Resolved (SHACL shapes graph, optional ShEx schema + shape map) bound to a profile id; the Profile Resolver's output." },
ClassDef { label: "ShapeReceipt", iri: "https://ggen.io/ontology/shape-admission#ShapeReceipt", comment: "BLAKE3 digest over the canonical ViolationSet + AdmissionDecision material; binds a replay identity." },
ClassDef { label: "ViolationSet", iri: "https://ggen.io/ontology/shape-admission#ViolationSet", comment: "The Violation Normalizer's single merged, sorted set of violations drawn from both the SHACLReport and ShExReport." },
];

/// `(from_label, to_label)` pairs: `from` `prov:wasDerivedFrom` `to`, i.e.
/// `from` cannot exist without `to` already having been computed.
pub const DERIVATION_EDGES: &[(&str, &str)] = &[
    ("AdmissionDecision", "ViolationSet"),
    ("AdmittedGraph", "ShapeReceipt"),
    ("SHACLReport", "ShapeProfile"),
    ("ShExReport", "ShapeProfile"),
    ("ShapeReceipt", "AdmissionDecision"),
    ("ViolationSet", "SHACLReport"),
    ("ViolationSet", "ShExReport"),
];

/// Admission lifecycle state names, in ordinal (pipeline) order. Index 0 is
/// the first state after profile resolution begins; `"REFUSED"` (last) is
/// the terminal off-ramp reachable from any non-terminal state, not a
/// pipeline stage in sequence with the rest.
pub const LIFECYCLE_STATES: &[&str] = &[
    "PROFILED",
    "SHACL_CHECKED",
    "SHEX_CHECKED",
    "VIOLATIONS_NORMALIZED",
    "DECIDED",
    "RECEIPTED",
    "HANDED_OFF",
    "REFUSED",
];
