// F19 Hook Registry and Machine-First Actuation (V12-019) -- GENERATED by
// `ggen sync` from `packs/f19-hooks-pack/ontology.ttl`
// (`mfwhook:ProvChainEntity` individuals). Do not edit by hand: this file is
// a pure data projection of the L6 PROV chain, `include!`d (not `mod` -- so
// `//!` inner-doc comments are not legal here) into `f19_hooks.rs`, which
// carries the module-level doc comment, the real SHACL-catalog reuse, the
// capability matcher, the execution classifier, the 8-state
// HookResolutionState lifecycle, and the HookResolutionRefused taxonomy.
// Add `ggen:local-override` to the template frontmatter to freeze
// regeneration.
//
// Regenerate with (from a scratch ggen project referencing this pack):
// `ggen sync run` -- see `f19_hooks.rs` module docs for the exact
// scratch-project recipe used to produce this file.

/// One entity in F19's L6 provenance chain -- a pure data projection of an
/// `mfwhook:ProvChainEntity` individual. Field values are informational
/// strings/integers carried straight from the ontology; nothing here is
/// enforcement (the real pipeline logic lives in `f19_hooks.rs`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ProvChainEntity {
    pub name: &'static str,
    pub comment: &'static str,
    pub chain_order: u8,
    pub pipeline_stage: &'static str,
    pub derived_from: &'static str,
}

/// The generated L6 PROV chain: one [`ProvChainEntity`] per
/// `mfwhook:ProvChainEntity` individual in the pack ontology, in
/// `?order` order (matches the `ORDER BY ?order` of the generating SPARQL
/// SELECT, so regeneration is deterministic). `HookDeclaration -> ... ->
/// HookReceipt`, a straight-line chain (each entity's `derived_from` names
/// exactly its predecessor; the head carries `"none"`).
pub const PROV_CHAIN: &[ProvChainEntity] = &[
    ProvChainEntity {
        name: "HookDeclaration",
        comment: "The admitted kh:Hook RDF individual as parsed from an admitted hook-pack Turtle document, before any shape/authority/schedule judgment. Chain head: nothing precedes it.",
        chain_order: 1,
        pipeline_stage: "Hook RDF Catalog",
        derived_from: "none",
    },
    ProvChainEntity {
        name: "HookShapeReport",
        comment: "The SHACL validation report (conforms flag plus violation results) produced by validating a HookDeclaration against kh:HookShape (praxis-graphlaw's real, already-tested closed-shape law pack).",
        chain_order: 2,
        pipeline_stage: "Hook SHACL",
        derived_from: "HookDeclaration",
    },
    ProvChainEntity {
        name: "ActionEffect",
        comment: "A grounded PDDL action (pddl-index's Pddl8GroundAction: schema_name, preconditions, add_effects, del_effects) admitted as the candidate the hook resolution pipeline must bind to a declared capability.",
        chain_order: 3,
        pipeline_stage: "Capability Matcher (input)",
        derived_from: "HookShapeReport",
    },
    ProvChainEntity {
        name: "CapabilityBinding",
        comment: "The exact, non-fictional binding of one ActionEffect's schema_name to exactly one shape-valid hook whose kh:effect is ground-action and whose kh:action IRI local name matches — produced by the Capability Matcher. Zero or more-than-one matching hooks refuse rather than guess.",
        chain_order: 4,
        pipeline_stage: "Capability Matcher (output)",
        derived_from: "ActionEffect",
    },
    ProvChainEntity {
        name: "ExecutionClass",
        comment: "The three-way LocalActuation / ExternalMachineDispatch / ExternalHumanDispatch classification of a CapabilityBinding's bound hook, plus its bound declared-authority string (non-empty required to pass the Classified conformance gate).",
        chain_order: 5,
        pipeline_stage: "Authority Binder + Execution Classifier",
        derived_from: "CapabilityBinding",
    },
    ProvChainEntity {
        name: "RecoveryPolicy",
        comment: "The declarative-only retry/compensation law attached to a Classified hook resolution before scheduling. Declarative only: no executing retry loop exists in this module (disclosed limitation, mirrors cng dispatch.rs's own retry_law doc comment).",
        chain_order: 6,
        pipeline_stage: "Retry Compensation Binder",
        derived_from: "ExecutionClass",
    },
    ProvChainEntity {
        name: "HookSchedule",
        comment: "The Kahn's-algorithm topological placement of a policy-bound hook resolution, produced by praxis-graphlaw's real, already-tested schedule_hooks (ID-based, (priority, HookId) tie-break).",
        chain_order: 7,
        pipeline_stage: "Hook Scheduler",
        derived_from: "RecoveryPolicy",
    },
    ProvChainEntity {
        name: "HookReceipt",
        comment: "The BLAKE3/SHA-256-hashed, replayable receipt (praxis-graphlaw's real HookReceipt/HookVerdictRecord/hook_hash) for a scheduled hook resolution, admitted through the atomic idempotency+correlation gate before being marked REPLAYABLE. Chain tail: nothing derives from it.",
        chain_order: 8,
        pipeline_stage: "Hook Receipt Store",
        derived_from: "HookSchedule",
    },
];
