// F22 Timeout Retry Escalation and Compensation (V12-022) -- GENERATED by
// `ggen sync` from `packs/f22-recovery-pack/ontology.ttl`
// (`mfwrec:ProvChainEntity` / `mfwrec:RecoveryStateEntity` /
// `mfwrec:RefusalKind` individuals). Do not edit by hand: this file is a
// pure data projection of the L6 PROV chain, L5 state catalog, and refusal
// catalog, `include!`d (not `mod` -- so `//!` inner-doc comments are not
// legal here) into `f22_compensation.rs`, which carries the module-level
// doc comment, the real compensation re-exports, and the honest
// not-yet-implemented stubs for the timeout/retry/escalation/broker-dispatch
// stages. Add `ggen:local-override` to the template frontmatter to freeze
// regeneration.
//
// Regenerate from a scratch ggen project referencing this pack (does not
// touch the shared root `ggen.toml`), e.g.:
// ```text
// mkdir -p /tmp/f22-ggen-scratch/templates
// cat > /tmp/f22-ggen-scratch/ggen.toml <<'EOF'
// [project]
// name = "f22-ggen-scratch"
// [ontology]
// source = "/Users/sac/praxis/packs/f22-recovery-pack/ontology.ttl"
// [packs]
// f22-recovery-pack = { path = "/Users/sac/praxis/packs/f22-recovery-pack" }
// [templates]
// dir = "templates"
// EOF
// (cd /tmp/f22-ggen-scratch && ggen sync run)
// cp /tmp/f22-ggen-scratch/generated/f22_compensation_generated.rs \
//    /Users/sac/praxis/crates/multifractal-workflow/src/
// ```

/// One entity in F22's L6 provenance chain -- a pure data projection of an
/// `mfwrec:ProvChainEntity` individual. Field values are informational
/// strings/integers carried straight from the ontology; nothing here is
/// enforcement (the real pipeline logic, where it exists, lives in
/// `f22_compensation.rs`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ProvChainEntity {
    pub name: &'static str,
    pub chain_order: u8,
    pub pipeline_stage: &'static str,
    pub derived_from: &'static str,
    pub realized_by: &'static str,
}

/// The generated L6 PROV chain: one [`ProvChainEntity`] per
/// `mfwrec:ProvChainEntity` individual in the pack ontology, in `?order`
/// order. `FailureObservation -> ... -> RecoveryReceipt`, a straight-line
/// chain (each entity's `derived_from` names exactly its predecessor; the
/// head carries `"none"`).
pub const PROV_CHAIN: &[ProvChainEntity] = &[
    ProvChainEntity {
        name: "FailureObservation",
        chain_order: 1,
        pipeline_stage: "Timeout Detector",
        derived_from: "none",
        realized_by: "FailureObservation { remediates: PriorActuationRef, observed_at_tick, failure_kind } is a real Rust data-carrier struct; detect_timeout() that would produce one from a live invocation always returns F22Refusal::NotYetImplemented -- no live invocation-tick clock or still-running determination exists anywhere in praxis-graphlaw or this crate (repo-wide grep, survey time).",
    },
    ProvChainEntity {
        name: "RetryPolicy",
        chain_order: 2,
        pipeline_stage: "Retry Policy",
        derived_from: "FailureObservation",
        realized_by: "RetryPolicy { max_attempts, backoff_ticks } is a real Rust data-carrier struct; evaluate_retry_policy() that would bound a real retry decision against a FailureObservation always returns F22Refusal::NotYetImplemented -- no bounded-retry runtime state tracker exists anywhere in the repo (repo-wide grep, survey time).",
    },
    ProvChainEntity {
        name: "EscalationPolicy",
        chain_order: 3,
        pipeline_stage: "Escalation Resolver",
        derived_from: "RetryPolicy",
        realized_by: "EscalationPolicy { escalation_threshold, escalate_to_role } is a real Rust data-carrier struct; resolve_escalation() always returns F22Refusal::NotYetImplemented -- no escalation-threshold policy engine exists anywhere in the repo (repo-wide grep, survey time).",
    },
    ProvChainEntity {
        name: "CompensationKind",
        chain_order: 4,
        pipeline_stage: "Compensation Catalog",
        derived_from: "EscalationPolicy",
        realized_by: "Unchanged re-export of praxis_graphlaw::chatman::compensation::CompensationKind (7 PRD-named variants, per-kind field validation). REAL: verified this session via `just praxis-graphlaw-test-lib 'test(chatman::compensation)'`.",
    },
    ProvChainEntity {
        name: "CompensationWorkflow",
        chain_order: 5,
        pipeline_stage: "Compensation Manufacturer",
        derived_from: "CompensationKind",
        realized_by: "Unchanged re-export of praxis_graphlaw::chatman::compensation::{CompensationWorkflow, manufacture_compensation_workflow} -- sole constructor, BLAKE3 dispatch digest + canonical N-Quads receipt. REAL: verified this session.",
    },
    ProvChainEntity {
        name: "RecoveryDispatch",
        chain_order: 6,
        pipeline_stage: "Broker Recovery Dispatch",
        derived_from: "CompensationWorkflow",
        realized_by: "praxis_graphlaw::chatman::compensation::CompensationDispatch (re-exported) is a real sealed PASSIVE dispatch envelope (digest + invocation_id), not the ACTIVE broker the atlas names. dispatch_broker_recovery() -- an active broker call that would route a manufactured CompensationWorkflow to a live recovery broker -- always returns F22Refusal::NotYetImplemented; no broker-dispatch caller exists anywhere in the repo (repo-wide grep, survey time).",
    },
    ProvChainEntity {
        name: "HistoryEntry",
        chain_order: 7,
        pipeline_stage: "Append-only History",
        derived_from: "RecoveryDispatch",
        realized_by: "The ledger itself (praxis_graphlaw::chatman::compensation::CompensationLedger, re-exported: append() is its only mutator, no remove/clear/pop) is REAL, verified this session. HistoryEntry as a distinct per-entry record type is a new, real, hand-written struct in f22_compensation.rs (ledger position + workflow reference), not a praxis-graphlaw type.",
    },
    ProvChainEntity {
        name: "RecoveryReceipt",
        chain_order: 8,
        pipeline_stage: "Recovery Receipt",
        derived_from: "HistoryEntry",
        realized_by: "Unchanged re-export of praxis_graphlaw::chatman::abi::Receipt, reused as-is by CompensationWorkflow::receipt(). REAL; no F22-specific receipt wrapper is added.",
    },
];

/// One state in F22's L5 state-machine catalog -- a pure data projection of
/// an `mfwrec:RecoveryStateEntity` individual. `legal_transitions` is
/// informational only: no transition function in `f22_compensation.rs`
/// enforces these edges yet (HAND_WRITE_REQUIRED, not implemented).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RecoveryStateCatalogEntry {
    pub name: &'static str,
    pub state_order: u8,
    pub legal_transitions: &'static str,
}

/// The fixed 9-entry L5 lifecycle catalog (8 declared states plus REFUSED),
/// in `?order` order. Cross-checked by `f22_compensation.rs`'s own tests
/// against the hand-written `RecoveryState` enum so the two cannot silently
/// drift.
pub const RECOVERY_STATE_CATALOG: &[RecoveryStateCatalogEntry] = &[
    RecoveryStateCatalogEntry {
        name: "FAILURE_OBSERVED",
        state_order: 1,
        legal_transitions: "RETRY_EVALUATED",
    },
    RecoveryStateCatalogEntry {
        name: "RETRY_EVALUATED",
        state_order: 2,
        legal_transitions: "RETRYING,REFUSED",
    },
    RecoveryStateCatalogEntry {
        name: "RETRYING",
        state_order: 3,
        legal_transitions: "ESCALATING",
    },
    RecoveryStateCatalogEntry {
        name: "ESCALATING",
        state_order: 4,
        legal_transitions: "COMPENSATION_SELECTED",
    },
    RecoveryStateCatalogEntry {
        name: "COMPENSATION_SELECTED",
        state_order: 5,
        legal_transitions: "COMPENSATING,REFUSED",
    },
    RecoveryStateCatalogEntry {
        name: "COMPENSATING",
        state_order: 6,
        legal_transitions: "RECOVERED",
    },
    RecoveryStateCatalogEntry {
        name: "RECOVERED",
        state_order: 7,
        legal_transitions: "BLOCKED",
    },
    RecoveryStateCatalogEntry {
        name: "BLOCKED",
        state_order: 8,
        legal_transitions: "none (terminal)",
    },
    RecoveryStateCatalogEntry {
        name: "REFUSED",
        state_order: 9,
        legal_transitions: "none (terminal)",
    },
];

/// One catalogued `F22Refusal` variant (`mfwrec:RefusalKind`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RefusalCatalogEntry {
    pub name: &'static str,
    pub meaning: &'static str,
    pub invariant: &'static str,
    pub status: &'static str,
}

/// The full `F22Refusal` catalog, alphabetical by variant name.
/// `f22_compensation.rs`'s own tests cross-check this catalog's names
/// against the hand-written `F22Refusal` enum so the two cannot silently
/// drift.
pub const REFUSAL_CATALOG: &[RefusalCatalogEntry] = &[
    RefusalCatalogEntry {
        name: "NotYetImplemented",
        meaning: "A pipeline stage that is genuinely HAND_WRITE_REQUIRED and not yet built (timeout detection, retry evaluation, escalation resolution, active broker dispatch, L5 state transitions, L7 idempotency/correlation gate) was reached; fails loud instead of faking success.",
        invariant: "Every failed branch terminates in a declared recovery state with receipt and replay -- cannot be honored until these stages exist.",
        status: "NOT_YET_IMPLEMENTED (by design; this is the honest refusal, not a bug)",
    },
    RefusalCatalogEntry {
        name: "RecoveryPolicyRefused",
        meaning: "An invalid or unauthorized recovery policy decision was reached (atlas L5: branches from RETRY_EVALUATED and COMPENSATION_SELECTED; atlas L2: REUSE from Retry Policy, Compensation Catalog, and Recovery Receipt stages).",
        invariant: "Unauthorized or invalid recovery policy is a typed RecoveryPolicyRefused refusal, never a silent default.",
        status: "DECLARED_ONLY (the variant is a real, typed F22Refusal member matching the atlas's own vocabulary; no real authority/conformance-check logic path returns it yet, since the stages that would produce a genuine invalid-policy verdict -- Retry Policy, Escalation Resolver -- are themselves NotYetImplemented)",
    },
];
