//! Family F26 -- "Public Ontology Self Play" (atlas ticket V12-026).
//!
//! Wire-phase-1 status (this pass): **PARTIAL, real**. Per the family survey
//! (verdict `MIXED`), this module wires three genuinely different kinds of
//! content, and is honest about which is which:
//!
//! - **REUSE_ADAPT (real)**: four of the nine pipeline stages are thin,
//!   real calls into already-tested praxis crates, not reimplementations:
//!   - D3 Datalog N3 Contraction ([`contract_scenario_graph`]) --
//!     `praxis_graphlaw::TripleStore::load_triples`/`load_rules`/`materialize`.
//!   - D4 Shape Admission ([`admit_contracted_world`]) --
//!     `praxis_graphlaw::TripleStore::validate_shacl`.
//!   - D5 PDDL Planner ([`plan_goal_closure`]) -- `pddl_index::solve_indexed`
//!     (indexed grounder + BFS plan search over `wasm4pm_compat::pddl` types).
//!   - D6 POWL Simulator ([`simulate_workflow`]) --
//!     `praxis_graphlaw::chatman::powl_projection::project_pddl_tape_to_powl`
//!     + `powl_to_turtle`.
//!   - D7 Synthetic Hook Surface ([`execute_synthetic_hook`], partial) --
//!     `praxis_graphlaw::hooks::evaluate_construct`/`serialize_delta_quad`/
//!     `HookReceipt` for the SPARQL CONSTRUCT execution + delta-quad/receipt
//!     shape; the *which hooks fire on which self-play world* policy is new
//!     (caller supplies the CONSTRUCT query), matching the survey's
//!     disclosure that this stage "has never been driven by self-play-
//!     generated worlds" before now.
//! - **GGEN_GENERATABLE (real)**: the D1-D9 provenance vocabulary, the
//!   8-state-plus-REFUSED lifecycle, the two REFUSED off-ramp state names,
//!   and the three exit-evidence flag names are generated by
//!   `packs/f26-ontology-self-play-pack` into [`vocab`] via a real
//!   `ggen sync run` against that pack (run twice from a scratch ggen
//!   project pointed only at this pack -- output byte-identical both runs
//!   -- then copied into place; the shared repo-root `ggen.lock` currently
//!   has an unrelated pre-existing content-hash drift on
//!   `shape-admission-pack` from other in-flight concurrent work that blocks
//!   a repo-root `ggen sync run` entirely, the same blocker class disclosed
//!   in `f07_shape_admission.rs`'s own doc comment). [`SelfPlayState::ALL`]'s
//!   variant names are asserted equal to the generated `LIFECYCLE_STATES`
//!   array by `state_names_match_generated_vocab` (test, below), so the
//!   ontology is the actual source of truth for state names, not just
//!   documentation of them.
//! - **HAND_WRITE_REQUIRED (honest stubs, real refusal)**: D2 Scenario
//!   Generator ([`generate_scenario`]), D8 Discovery Miner
//!   ([`mine_discovery_patterns`]), and D9 CONSTRUCT Capitalizer
//!   ([`capitalize_discoveries`]) each immediately return
//!   `Err(SelfPlayRefusal::NotYetImplemented { .. })` -- no fabricated
//!   dimension-mutation, pattern-mining, or relation-capitalization logic.
//!   The survey's exhaustive repo-and-external-candidate grep (zero hits for
//!   every F26-specific noun) found no existing algorithm to adapt for any
//!   of these three; none is invented here.
//!
//! ## What is real and demonstrated end to end in this pass
//!
//! [`contract_scenario_graph`] -> [`admit_contracted_world`] ->
//! [`plan_goal_closure`] -> [`simulate_workflow`] -> [`execute_synthetic_hook`]
//! is exercised as one real chain in `middle_stages_run_end_to_end_on_hand_built_fixture`
//! (test, below): a hand-authored Turtle scenario + N3 contraction rule is
//! materialized, SHACL-admitted, its goal is planned by the real indexed
//! PDDL8 grounder, the resulting tape is projected to a POWL model and
//! serialized to Turtle, and a synthetic hook's SPARQL CONSTRUCT runs
//! against that Turtle to produce a real, BLAKE3-backed [`ScenarioReceipt`].
//! Every value in that chain is computed by the underlying crate, not
//! asserted by this module.
//!
//! What this pass does NOT claim:
//! - The chain above starts from a **caller-supplied** [`ScenarioGraph`],
//!   because [`generate_scenario`] (D2) always refuses -- there is no
//!   working end-to-end run starting from an [`OntologyDimensionCatalog`]
//!   alone, and this module does not pretend otherwise.
//! - [`SelfPlayGate`] (L7 idempotency/correlation gate) is real but
//!   in-memory only (`BTreeMap`, chosen over `HashMap` for deterministic
//!   iteration per this repo's determinism doctrine); [`SelfPlayGate::persist`]/
//!   [`SelfPlayGate::restore`] give a real, tested serialize/deserialize
//!   round-trip (simulating a restart within one process -- see
//!   `gate_persist_restore_round_trip`, test, below), but nothing wires that
//!   JSON to disk automatically. Same disclosed scope as
//!   `f07_shape_admission.rs`'s `ShapeAdmissionGate`.
//! - D8/D9 have no real logic at all (see above) -- [`mine_discovery_patterns`]
//!   and [`capitalize_discoveries`] cannot be exercised past their refusal.
//!
//! Survey-cited paths informing this pass (from the v26.7.12 family survey
//! handed to this session inline):
//! - /Users/sac/Downloads/v26.7.12_mermaid_atlas/families/F26_ontology-self-play.md
//! - /Users/sac/praxis/crates/pddl-index/src/{lib,ground,facts,dict,xorf}.rs
//! - /Users/sac/praxis/crates/powl2-decompose/src/{powl,decompose,recompose,external_cut}.rs
//! - /Users/sac/praxis/crates/praxis-graphlaw/src/chatman/powl_projection.rs
//! - /Users/sac/praxis/crates/praxis-graphlaw/src/{datalog,lib}.rs (`TripleStore::load_triples`/`load_rules`/`materialize`)
//! - /Users/sac/praxis/crates/praxis-graphlaw/src/parser/n3rule_parser.rs
//! - /Users/sac/praxis/crates/praxis-graphlaw/src/shacl/mod.rs (`ValidationReport`, `TripleStore::validate_shacl`)
//! - /Users/sac/praxis/crates/praxis-graphlaw/src/hooks/construct.rs (`evaluate_construct`, `serialize_delta_quad`, `HookReceipt`)
//! - /Users/sac/praxis/crates/praxis-graphlaw/src/chatman/abi.rs (adapted `Refusal` enum pattern)
//! - /Users/sac/praxis/packs/f26-ontology-self-play-pack/ (this pass's new ggen pack)
//! - /Users/sac/praxis/crates/multifractal-workflow/src/f07_shape_admission.rs (sibling family, closely mirrored patterns: `load_triples` error surfacing, `AdmissionDecision` as data not error, in-memory correlation gate with disclosed persist/restore scope)

#[path = "f26_ontology_self_play_vocab.rs"]
pub mod vocab;

use praxis_graphlaw::hooks::{evaluate_construct, serialize_delta_quad, HookReceipt};
use praxis_graphlaw::parser::Syntax;
use praxis_graphlaw::shacl::ValidationReport as ShaclReport;
use praxis_graphlaw::TripleStore;
use std::collections::BTreeMap;
use wasm4pm_compat::pddl::{Pddl8Domain, Pddl8Problem, Pddl8Tape};

// ---------------------------------------------------------------------
// Typed refusal (SelfPlayScenarioRefused lives here, per the survey's
// named refusal type for D4 Shape Admission's refused verdict).
// ---------------------------------------------------------------------

/// F26 self-play pipeline's typed refusal taxonomy. Every variant is
/// returned from a real code path exercised by this module's tests (see
/// each variant's doc comment for which stage raises it), except
/// [`SelfPlayRefusal::NotYetImplemented`], which is raised unconditionally
/// by the three HAND_WRITE_REQUIRED stubs ([`generate_scenario`],
/// [`mine_discovery_patterns`], [`capitalize_discoveries`]).
#[derive(Debug, Clone, thiserror::Error)]
pub enum SelfPlayRefusal {
    /// Raised unconditionally by a stage whose real algorithm does not yet
    /// exist anywhere in this repo or the family survey's three surveyed
    /// external candidates (confirmed by the survey's exhaustive negative
    /// grep). Never dressed up as a working implementation.
    #[error("F26 stage `{stage}` (V12-026) not yet implemented: {reason}")]
    NotYetImplemented {
        stage: &'static str,
        reason: &'static str,
    },
    /// [`contract_scenario_graph`]: the [`ScenarioGraph`]'s `facts_turtle`
    /// failed to parse (`TripleStore::load_triples`).
    #[error("scenario graph facts failed to parse as Turtle: {reason}")]
    WorldMalformed { reason: String },
    /// [`contract_scenario_graph`]: the supplied N3 rule set failed to
    /// parse (`TripleStore::load_rules`).
    #[error("contraction rule set failed to parse as N3: {reason}")]
    RuleSetMalformed { reason: String },
    /// [`contract_scenario_graph`]: `TripleStore::materialize` itself
    /// returned an error (distinct from "materialized zero derived
    /// triples", which is a normal, non-error outcome).
    #[error("datalog/N3 contraction (materialize) failed: {reason}")]
    ContractionFailed { reason: String },
    /// [`admit_contracted_world`]: the SHACL validator itself errored
    /// (distinct from a non-conforming report, which is the normal
    /// [`AdmissionDecision::Refused`] outcome, not this variant).
    #[error("SHACL validator error: {reason}")]
    ShaclValidatorError { reason: String },
    /// The named refusal type for D4 Shape Admission per the family
    /// survey. Raised by [`run_reused_pipeline`] (not by
    /// [`admit_contracted_world`] itself, which returns the refusal as
    /// *data* -- see its own doc comment) when a self-play world's
    /// [`AdmissionDecision`] is [`AdmissionVerdict::Refused`]: the
    /// WORLD_GENERATED -> REFUSED off-ramp (`vocab::REFUSAL_EXIT_STATES`).
    #[error(
        "self-play scenario refused at shape admission: {violation_count} SHACL violation(s): {violation_summary:?}"
    )]
    SelfPlayScenarioRefused {
        violation_count: usize,
        violation_summary: Vec<String>,
    },
    /// [`plan_goal_closure`]: the indexed PDDL8 grounder/planner could not
    /// close the goal (empty grounding or no admitted plan within the
    /// depth bound) -- the family's `IMPOSSIBLE_SCENARIO_PREPLAN_REFUSAL`
    /// exit-evidence flag (`vocab::EXIT_EVIDENCE_FLAGS`), and the
    /// PLANNED -> REFUSED off-ramp (`vocab::REFUSAL_EXIT_STATES`).
    #[error(
        "PDDL planner could not close the goal (impossible scenario, refused pre-plan): {reason}"
    )]
    ImpossibleScenarioPreplanRefused { reason: String },
    /// [`simulate_workflow`]: POWL projection or Turtle serialization
    /// refused (`chatman::powl_projection`'s own typed `Refusal`,
    /// stringified).
    #[error("POWL simulation refused: {reason}")]
    SimulationRefused { reason: String },
    /// [`execute_synthetic_hook`]: the hook's SPARQL CONSTRUCT query failed
    /// to parse or evaluate.
    #[error("synthetic hook SPARQL CONSTRUCT evaluation failed: {reason}")]
    SyntheticHookFailed { reason: String },
    /// [`SelfPlayGate::check`]: a duplicate `correlation_id` was submitted
    /// with different content than the first attempt that used it -- the
    /// idempotency+correlation gate refuses rather than silently
    /// overwriting or silently replaying the wrong result. Part of the
    /// family's L7 chaos-gating requirement.
    #[error(
        "correlation id `{correlation_id}` was already used for a different self-play attempt \
         (first content digest `{first_digest}`, this attempt's content digest `{this_digest}`)"
    )]
    DuplicateCorrelationConflict {
        correlation_id: String,
        first_digest: String,
        this_digest: String,
    },
}

// ---------------------------------------------------------------------
// D1: Ontology Dimension Catalog
// ---------------------------------------------------------------------

/// One public-ontology dimension the Scenario Generator could mutate along
/// (once it exists -- see [`generate_scenario`]'s honest refusal).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OntologyDimension {
    pub name: String,
    pub source_iri: String,
}

/// The mutation profile the Scenario Generator would follow: which
/// dimensions are in scope for this self-play run.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ScenarioMutationProfile {
    pub profile_id: String,
    pub dimensions: Vec<OntologyDimension>,
}

/// D1: indexes public-ontology dimensions and a scenario-mutation profile.
/// This type is real data (constructible and inspectable today); only the
/// stage that *consumes* it ([`generate_scenario`]) is not yet implemented.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OntologyDimensionCatalog {
    pub profile: ScenarioMutationProfile,
}

// ---------------------------------------------------------------------
// D2: Scenario Generator -- HAND_WRITE_REQUIRED (honest stub)
// ---------------------------------------------------------------------

/// D2: a candidate RDF world produced by mutating catalog dimensions.
/// Constructible directly by a caller (see the tests below, which
/// hand-author one) even though [`generate_scenario`] cannot produce one
/// yet -- this lets D3 onward be exercised for real without waiting on D2.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ScenarioGraph {
    pub facts_turtle: String,
}

/// Scenario Generator (D2) -- **HAND_WRITE_REQUIRED, not implemented**.
///
/// The family survey's exhaustive grep for `ScenarioGenerator`,
/// `ScenarioMutationProfile`, and related terms across this repo and the
/// three surveyed external candidates (`open-ontologies`, `semantic_bit`,
/// `star-toml`) returned zero hits. No dimension-to-RDF-world mutation
/// algorithm exists anywhere to adapt. This function refuses unconditionally
/// rather than returning a plausible-looking but fake [`ScenarioGraph`] --
/// per this repo's no-overclaiming discipline, "unimplemented fails loud."
///
/// Real prose-authority invariant this stub is written to respect once
/// implemented: the generator mutates the catalog's own dimension graph
/// (RDF), never treats free-text prompt prose as scenario authority.
pub fn generate_scenario(
    _catalog: &OntologyDimensionCatalog,
) -> Result<ScenarioGraph, SelfPlayRefusal> {
    Err(SelfPlayRefusal::NotYetImplemented {
        stage: "scenario_generator (D2)",
        reason: "no dimension-to-RDF-world mutation algorithm exists anywhere in this repo or \
                 the three surveyed external candidates (repo-wide grep, survey time)",
    })
}

// ---------------------------------------------------------------------
// D3: Datalog N3 Contraction -- REUSE_ADAPT (real)
// ---------------------------------------------------------------------

/// D3: the Datalog/N3 contraction's derived-triple delta over a
/// [`ScenarioGraph`]. `derived_nquads` is the real materialized output of
/// `praxis_graphlaw::TripleStore::materialize`, decoded and sorted into
/// canonical order (never HashMap iteration order) before any receipt would
/// hash it, per this repo's determinism doctrine.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ClosureDelta {
    pub derived_nquads: Vec<String>,
}

/// Datalog N3 Contraction (D3): parses `world.facts_turtle` and `rules_n3`
/// with `praxis_graphlaw::TripleStore::load_triples`/`load_rules` (both
/// real parsers that surface errors, unlike `TripleStore::from`, which
/// silently empties on a parse failure -- deliberately not used here), then
/// runs the real stratified semi-naive Datalog/N3 materialization to a
/// fixpoint. Returns the mutated store (already carrying the closure, for
/// [`admit_contracted_world`] to validate directly -- no re-serialization
/// round trip) alongside the [`ClosureDelta`].
///
/// # Complexity
/// O(parse) + whatever `TripleStore::materialize`'s stratified semi-naive
/// evaluation costs for `rules_n3`'s rule set (bounded by
/// `praxis_graphlaw::reasoner::Reasoner::materialize`'s own documented
/// bound, not re-derived here).
pub fn contract_scenario_graph(
    world: &ScenarioGraph,
    rules_n3: &str,
) -> Result<(TripleStore, ClosureDelta), SelfPlayRefusal> {
    let mut store = TripleStore::new();
    store
        .load_triples(&world.facts_turtle, Syntax::Turtle)
        .map_err(|reason| SelfPlayRefusal::WorldMalformed { reason })?;
    store
        .load_rules(rules_n3)
        .map_err(|reason| SelfPlayRefusal::RuleSetMalformed { reason })?;
    let derived = store
        .materialize()
        .map_err(|reason| SelfPlayRefusal::ContractionFailed { reason })?;
    let mut derived_nquads: Vec<String> = derived
        .iter()
        .map(|t| TripleStore::decode_triple(t))
        .collect();
    derived_nquads.sort();
    Ok((store, ClosureDelta { derived_nquads }))
}

// ---------------------------------------------------------------------
// D4: Shape Admission -- REUSE_ADAPT (real)
// ---------------------------------------------------------------------

/// D4 verdict. Modeled as plain data returned inside `Ok`, mirroring
/// `f07_shape_admission.rs`'s `AdmissionDecision` -- "refused" is a normal
/// pipeline outcome the caller inspects, not a Rust `Err`. The typed
/// [`SelfPlayRefusal::SelfPlayScenarioRefused`] error is raised one layer up,
/// by [`run_reused_pipeline`], when it decides to stop the pipeline because
/// of this verdict.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AdmissionVerdict {
    Admitted,
    Refused,
}

/// D4: Shape Admission's admit/refuse verdict over a contracted world.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AdmissionDecision {
    pub verdict: AdmissionVerdict,
    pub violation_count: usize,
    pub violation_summary: Vec<String>,
}

/// Shape Admission (D4): thin call into
/// `praxis_graphlaw::TripleStore::validate_shacl` -- real, already-tested
/// SHACL validation (5000+ lines, W3C-conformance-tested), no constraint
/// logic reimplemented here. Runs against `store` *after*
/// [`contract_scenario_graph`] has materialized it in place, so admission
/// sees the closed world, not just the asserted facts.
///
/// # Complexity
/// O(SHACL validator's own bound over `store`'s triple count and
/// `shapes_turtle`'s shape count) -- not re-derived here.
pub fn admit_contracted_world(
    store: &TripleStore,
    shapes_turtle: &str,
) -> Result<AdmissionDecision, SelfPlayRefusal> {
    let report: ShaclReport = store
        .validate_shacl(shapes_turtle)
        .map_err(|reason| SelfPlayRefusal::ShaclValidatorError { reason })?;
    if report.conforms {
        Ok(AdmissionDecision {
            verdict: AdmissionVerdict::Admitted,
            violation_count: 0,
            violation_summary: Vec::new(),
        })
    } else {
        let mut violation_summary: Vec<String> = report
            .results
            .iter()
            .map(|r| {
                format!(
                    "{:?} at {:?} (severity {:?})",
                    r.source_constraint_component, r.focus_node, r.severity
                )
            })
            .collect();
        violation_summary.sort();
        Ok(AdmissionDecision {
            verdict: AdmissionVerdict::Refused,
            violation_count: report.results.len(),
            violation_summary,
        })
    }
}

// ---------------------------------------------------------------------
// D5: PDDL Planner -- REUSE_ADAPT (real)
// ---------------------------------------------------------------------

/// D5: the PDDL Planner's goal-closure plan over an admitted world.
#[derive(Debug, Clone)]
pub struct Plan {
    pub tape: Pddl8Tape,
    pub stats: pddl_index::GroundStats,
}

/// PDDL Planner (D5): thin call into `pddl_index::solve_indexed` -- the
/// real, already-tested (15/15 tests passing this session per the family
/// survey) dictionary-encoded, XOR-filter-pruned indexed grounder + BFS
/// plan search. No grounding or search logic reimplemented here.
///
/// A `GroundError` (empty grounding or no admitted plan within
/// `PDDL8_MAX_PLAN_DEPTH`) maps to
/// [`SelfPlayRefusal::ImpossibleScenarioPreplanRefused`] -- the family's
/// `IMPOSSIBLE_SCENARIO_PREPLAN_REFUSAL` exit-evidence flag.
pub fn plan_goal_closure(
    domain: &Pddl8Domain,
    problem: &Pddl8Problem,
) -> Result<Plan, SelfPlayRefusal> {
    let (tape, stats) = pddl_index::solve_indexed(domain, problem).map_err(|e| {
        SelfPlayRefusal::ImpossibleScenarioPreplanRefused {
            reason: e.to_string(),
        }
    })?;
    Ok(Plan { tape, stats })
}

// ---------------------------------------------------------------------
// D6: POWL Simulator -- REUSE_ADAPT (real, as projection)
// ---------------------------------------------------------------------

/// D6: the POWL Simulator's manufactured workflow from a [`Plan`], as
/// admitted Turtle conforming to the `powl2:` vocabulary.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SimulatedWorkflow {
    pub turtle: String,
}

/// POWL Simulator (D6): thin call into
/// `praxis_graphlaw::chatman::powl_projection::project_pddl_tape_to_powl` +
/// `powl_to_turtle` -- the real, already-tested (28/28 `powl2-decompose`
/// tests plus 6 `chatman_pddl_to_powl_*` integration test files per the
/// family survey) pure PDDL-tape-to-POWL-to-Turtle projector. This is
/// projection, not literal step-simulation, matching the survey's own
/// framing of this stage as "as projection, not literal step-simulation."
pub fn simulate_workflow(
    plan: &Plan,
    base_iri: &str,
) -> Result<SimulatedWorkflow, SelfPlayRefusal> {
    let powl = praxis_graphlaw::chatman::powl_projection::project_pddl_tape_to_powl(&plan.tape)
        .map_err(|e| SelfPlayRefusal::SimulationRefused {
            reason: e.to_string(),
        })?;
    let turtle = praxis_graphlaw::chatman::powl_projection::powl_to_turtle(&powl, base_iri, None)
        .map_err(|e| SelfPlayRefusal::SimulationRefused {
        reason: e.to_string(),
    })?;
    Ok(SimulatedWorkflow { turtle })
}

// ---------------------------------------------------------------------
// D7: Synthetic Hook Surface -- REUSE_ADAPT (real, partial)
// ---------------------------------------------------------------------

/// D7: the Synthetic Hook Surface's execution receipt over a
/// [`SimulatedWorkflow`]. Wraps the real, already-defined
/// `praxis_graphlaw::hooks::HookReceipt` type (idempotency-key/delta-hash
/// shape) rather than inventing a parallel receipt shape.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ScenarioReceipt {
    pub hook_receipt: HookReceipt,
    pub additions_count: usize,
    pub deletions_count: usize,
}

/// Synthetic Hook Surface (D7): parses `workflow.turtle`, runs
/// `hook_name`'s `construct_query` through
/// `praxis_graphlaw::hooks::evaluate_construct` (the real SPARQL CONSTRUCT
/// engine), then builds a [`ScenarioReceipt`] the same way
/// `praxis_graphlaw::hooks::serialize_delta_quad` + BLAKE3 already do for
/// production hook receipts elsewhere in this repo (`HookReceipt`'s own
/// doc). Additions/deletions are sorted into canonical order by their
/// `TripleStore::decode_triple` string form *before* serialization, so the
/// delta-quad material -- and therefore `delta_hash` -- is receipt-stable
/// regardless of `evaluate_construct`'s internal binding order.
///
/// This is the *mechanism* this stage needs, real and reused; the *policy*
/// of which hooks fire on a self-play world (a hook registry keyed off
/// scenario dimensions) is not implemented -- the caller supplies
/// `hook_name`/`construct_query` directly, same disclosed scope as
/// `f08_pddl_planning`'s hook_binder refusal for the same underlying gap
/// (no general hook-registry query API exists anywhere in this repo).
pub fn execute_synthetic_hook(
    workflow: &SimulatedWorkflow,
    hook_name: &str,
    construct_query: &str,
) -> Result<ScenarioReceipt, SelfPlayRefusal> {
    let mut store = TripleStore::new();
    store
        .load_triples(&workflow.turtle, Syntax::Turtle)
        .map_err(|reason| SelfPlayRefusal::WorldMalformed { reason })?;
    let (mut additions, mut deletions) =
        evaluate_construct(construct_query, &store.triple_index)
            .map_err(|reason| SelfPlayRefusal::SyntheticHookFailed { reason })?;
    additions.sort_by_key(|t| TripleStore::decode_triple(t));
    deletions.sort_by_key(|t| TripleStore::decode_triple(t));

    let mut lines = Vec::new();
    for t in &additions {
        serialize_delta_quad(hook_name, t, true, &mut lines);
    }
    for t in &deletions {
        serialize_delta_quad(hook_name, t, false, &mut lines);
    }
    let delta_quads = lines.join("\n");
    let delta_hash = blake3::hash(delta_quads.as_bytes()).to_hex().to_string();
    let idempotency_key = blake3::hash(format!("{hook_name}\u{1}{delta_hash}").as_bytes())
        .to_hex()
        .to_string();

    Ok(ScenarioReceipt {
        hook_receipt: HookReceipt {
            hook_name: hook_name.to_string(),
            delta_hash,
            idempotency_key,
            delta_quads,
        },
        additions_count: additions.len(),
        deletions_count: deletions.len(),
    })
}

// ---------------------------------------------------------------------
// D8: Discovery Miner -- HAND_WRITE_REQUIRED (honest stub)
// ---------------------------------------------------------------------

/// D8: the Discovery Miner's recurrent-structure pattern, mined from one or
/// more [`ScenarioReceipt`]s.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DiscoveryPattern {
    pub pattern_id: String,
}

/// Discovery Miner (D8) -- **HAND_WRITE_REQUIRED, not implemented**.
///
/// The family survey's exhaustive grep for `DiscoveryMiner`/
/// `DiscoveryPattern` across this repo and the three surveyed external
/// candidates returned zero hits. No recurrent-structure pattern-mining
/// algorithm exists anywhere to adapt. Refuses unconditionally rather than
/// fabricating plausible-looking patterns.
pub fn mine_discovery_patterns(
    _receipts: &[ScenarioReceipt],
) -> Result<Vec<DiscoveryPattern>, SelfPlayRefusal> {
    Err(SelfPlayRefusal::NotYetImplemented {
        stage: "discovery_miner (D8)",
        reason: "recurrent-structure pattern-mining algorithm does not exist anywhere in this \
                 repo or the three surveyed external candidates (V12-026 survey, zero-hit grep \
                 for DiscoveryMiner/DiscoveryPattern); tracked under ticket V12-026",
    })
}

// ---------------------------------------------------------------------
// D9: CONSTRUCT Capitalizer -- HAND_WRITE_REQUIRED (honest stub)
// ---------------------------------------------------------------------

/// D9: the CONSTRUCT Capitalizer's admitted, receipt-bound, replay-verified
/// relation derived from a [`DiscoveryPattern`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConstructedRelation {
    pub relation_iri: String,
}

/// CONSTRUCT Capitalizer (D9) -- **HAND_WRITE_REQUIRED, not implemented**.
///
/// The underlying SPARQL CONSTRUCT *mechanism* this stage would use
/// (`praxis_graphlaw::hooks::evaluate_construct`) is real and already
/// exercised end to end by [`execute_synthetic_hook`] (D7) above -- it is
/// not what's missing. What's missing is the *policy*: which CONSTRUCT
/// query and admission rule turns a [`DiscoveryPattern`] into an admitted
/// [`ConstructedRelation`]. The family survey's grep for
/// `CapitalizerConstruct`/`ConstructedRelation` found no such policy
/// anywhere. Refuses unconditionally rather than fabricating one.
pub fn capitalize_discoveries(
    _patterns: &[DiscoveryPattern],
) -> Result<Vec<ConstructedRelation>, SelfPlayRefusal> {
    Err(SelfPlayRefusal::NotYetImplemented {
        stage: "construct_capitalizer (D9)",
        reason: "discovery-to-admitted-relation CONSTRUCT policy does not exist anywhere in \
                 this repo or the three surveyed external candidates (V12-026 survey, zero-hit \
                 grep for CapitalizerConstruct/ConstructedRelation); the underlying SPARQL \
                 CONSTRUCT engine this stage would reuse is real (see execute_synthetic_hook, \
                 D7), only the policy is missing; tracked under ticket V12-026",
    })
}

// ---------------------------------------------------------------------
// Self-play lifecycle state machine (cross-checked against generated vocab)
// ---------------------------------------------------------------------

/// The F26 self-play lifecycle's 9 states (8 pipeline states + terminal
/// `REFUSED`), in ordinal order. Names and order are asserted equal to
/// `vocab::LIFECYCLE_STATES` by `state_names_match_generated_vocab` (test,
/// below) -- the ontology, not this enum, is the source of truth for names.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum SelfPlayState {
    DimensionsSelected,
    WorldGenerated,
    Contracted,
    Admitted,
    Planned,
    Simulated,
    Mined,
    Capitalized,
    Refused,
}

impl SelfPlayState {
    /// All 9 states in ordinal (pipeline) order.
    pub const ALL: [SelfPlayState; 9] = [
        SelfPlayState::DimensionsSelected,
        SelfPlayState::WorldGenerated,
        SelfPlayState::Contracted,
        SelfPlayState::Admitted,
        SelfPlayState::Planned,
        SelfPlayState::Simulated,
        SelfPlayState::Mined,
        SelfPlayState::Capitalized,
        SelfPlayState::Refused,
    ];

    /// The atlas's own `SCREAMING_SNAKE_CASE` state name.
    #[must_use]
    pub const fn state_name(self) -> &'static str {
        match self {
            SelfPlayState::DimensionsSelected => "DIMENSIONS_SELECTED",
            SelfPlayState::WorldGenerated => "WORLD_GENERATED",
            SelfPlayState::Contracted => "CONTRACTED",
            SelfPlayState::Admitted => "ADMITTED",
            SelfPlayState::Planned => "PLANNED",
            SelfPlayState::Simulated => "SIMULATED",
            SelfPlayState::Mined => "MINED",
            SelfPlayState::Capitalized => "CAPITALIZED",
            SelfPlayState::Refused => "REFUSED",
        }
    }

    /// Whether this state is one of the two REFUSED off-ramps
    /// (`vocab::REFUSAL_EXIT_STATES`): the pipeline may exit directly to
    /// `REFUSED` while attempting to advance out of this state, instead of
    /// reaching the next ordinal state.
    #[must_use]
    pub fn is_refusal_exit(self) -> bool {
        vocab::REFUSAL_EXIT_STATES.contains(&self.state_name())
    }
}

// ---------------------------------------------------------------------
// L7: idempotency + correlation gate (real, in-memory; disclosed scope)
// ---------------------------------------------------------------------

/// Outcome of [`SelfPlayGate::check`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GateOutcome {
    /// First time this `correlation_id` has been seen.
    Fresh,
    /// This `correlation_id` was seen before with byte-identical content --
    /// a duplicate submission (e.g. a retried event or a restarted engine
    /// re-processing the same self-play attempt), not an error.
    Replayed,
}

/// L7 idempotency+correlation gate: the family's requirement that
/// "duplicate event, process/engine restart, stale/malformed result" chaos
/// resolves via an atomic idempotency+correlation gate, never an
/// inconsistent state. Real, in-memory (`BTreeMap<String, String>`,
/// deterministic iteration order per this repo's doctrine); see the module
/// doc comment for the disclosed persist/restore scope.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct SelfPlayGate {
    seen: BTreeMap<String, String>,
}

impl SelfPlayGate {
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Checks `correlation_id` against `content`'s BLAKE3 digest.
    /// - Unseen `correlation_id` -> [`GateOutcome::Fresh`], and the digest
    ///   is recorded.
    /// - Seen `correlation_id` with the same digest -> [`GateOutcome::Replayed`]
    ///   (idempotent re-submission, e.g. a retried duplicate event or a
    ///   restarted engine re-processing the same attempt).
    /// - Seen `correlation_id` with a *different* digest ->
    ///   [`SelfPlayRefusal::DuplicateCorrelationConflict`] (a stale or
    ///   malformed result masquerading under a reused correlation id is
    ///   refused, never silently accepted).
    ///
    /// # Complexity
    /// O(log n) in the number of distinct correlation ids seen (`BTreeMap`).
    pub fn check(
        &mut self,
        correlation_id: &str,
        content: &str,
    ) -> Result<GateOutcome, SelfPlayRefusal> {
        let digest = blake3::hash(content.as_bytes()).to_hex().to_string();
        match self.seen.get(correlation_id) {
            Some(seen_digest) if *seen_digest == digest => Ok(GateOutcome::Replayed),
            Some(seen_digest) => Err(SelfPlayRefusal::DuplicateCorrelationConflict {
                correlation_id: correlation_id.to_string(),
                first_digest: seen_digest.clone(),
                this_digest: digest,
            }),
            None => {
                self.seen.insert(correlation_id.to_string(), digest);
                Ok(GateOutcome::Fresh)
            }
        }
    }

    /// Serializes the in-memory correlation map to JSON (`BTreeMap` order,
    /// deterministic). Real serialize/deserialize round trip; see the
    /// module doc comment for the disclosed scope (not wired to disk
    /// automatically).
    pub fn persist(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string(&self.seen)
    }

    /// Restores a gate from [`SelfPlayGate::persist`]'s JSON.
    pub fn restore(json: &str) -> Result<Self, serde_json::Error> {
        Ok(Self {
            seen: serde_json::from_str(json)?,
        })
    }
}

// ---------------------------------------------------------------------
// Orchestrator: the real middle-stage chain (D3 -> D4 -> D5 -> D6 -> D7)
// ---------------------------------------------------------------------

/// Output of [`run_reused_pipeline`]: everything the real, reused stages
/// (D3-D7) produced for one admitted, planned, simulated self-play world.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ReusedPipelineOutput {
    pub closure: ClosureDelta,
    pub admission: AdmissionDecision,
    pub receipt: ScenarioReceipt,
}

/// Runs the real, reused D3->D4->D5->D6->D7 chain over a caller-supplied
/// [`ScenarioGraph`] (since D2 [`generate_scenario`] cannot produce one
/// yet -- see the module doc comment).
///
/// Refuses at the WORLD_GENERATED -> REFUSED off-ramp
/// ([`SelfPlayRefusal::SelfPlayScenarioRefused`]) if [`admit_contracted_world`]
/// decides [`AdmissionVerdict::Refused`]; refuses at the PLANNED -> REFUSED
/// off-ramp ([`SelfPlayRefusal::ImpossibleScenarioPreplanRefused`]) if
/// [`plan_goal_closure`] cannot close the goal. Both off-ramps are named in
/// `vocab::REFUSAL_EXIT_STATES`, transcribed from the survey's own state
/// machine description ("REFUSED exits from WORLD_GENERATED and PLANNED").
#[allow(clippy::too_many_arguments)]
pub fn run_reused_pipeline(
    world: &ScenarioGraph,
    rules_n3: &str,
    shapes_turtle: &str,
    domain: &Pddl8Domain,
    problem: &Pddl8Problem,
    base_iri: &str,
    hook_name: &str,
    construct_query: &str,
) -> Result<ReusedPipelineOutput, SelfPlayRefusal> {
    // CONTRACTED
    let (store, closure) = contract_scenario_graph(world, rules_n3)?;

    // ADMITTED (or the WORLD_GENERATED -> REFUSED off-ramp)
    let admission = admit_contracted_world(&store, shapes_turtle)?;
    if admission.verdict == AdmissionVerdict::Refused {
        return Err(SelfPlayRefusal::SelfPlayScenarioRefused {
            violation_count: admission.violation_count,
            violation_summary: admission.violation_summary,
        });
    }

    // PLANNED (or the PLANNED -> REFUSED off-ramp, raised inside plan_goal_closure)
    let plan = plan_goal_closure(domain, problem)?;

    // SIMULATED
    let workflow = simulate_workflow(&plan, base_iri)?;

    // MINED's prerequisite: the D7 synthetic hook receipt.
    let receipt = execute_synthetic_hook(&workflow, hook_name, construct_query)?;

    Ok(ReusedPipelineOutput {
        closure,
        admission,
        receipt,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    // -------------------------------------------------------------
    // Vocab cross-check: the ontology, not the enum, is the source of
    // truth for state names / off-ramps / flags.
    // -------------------------------------------------------------

    #[test]
    fn state_names_match_generated_vocab() {
        let names: Vec<&str> = SelfPlayState::ALL.iter().map(|s| s.state_name()).collect();
        assert_eq!(names, vocab::LIFECYCLE_STATES);
    }

    #[test]
    fn refusal_exit_states_match_generated_vocab() {
        let mut exits: Vec<&str> = SelfPlayState::ALL
            .iter()
            .filter(|s| s.is_refusal_exit())
            .map(|s| s.state_name())
            .collect();
        exits.sort_unstable();
        let mut expected = vocab::REFUSAL_EXIT_STATES.to_vec();
        expected.sort_unstable();
        assert_eq!(exits, expected);
    }

    #[test]
    fn exit_evidence_flags_contains_impossible_scenario_preplan_refusal() {
        assert!(vocab::EXIT_EVIDENCE_FLAGS.contains(&"IMPOSSIBLE_SCENARIO_PREPLAN_REFUSAL"));
        assert!(vocab::EXIT_EVIDENCE_FLAGS.contains(&"PUBLIC_ONTOLOGY_SELF_PLAY_PROVEN"));
        assert!(vocab::EXIT_EVIDENCE_FLAGS.contains(&"SELF_PLAY_DISCOVERY_CAPITALIZED"));
    }

    #[test]
    fn derivation_edges_chain_d1_through_d9() {
        // Every class except the root (D1) must appear as a `from_label` at
        // least once, and every class except the leaf (D9) must appear as a
        // `to_label` at least once -- confirms the generated edge list forms
        // one connected chain, not disconnected fragments.
        let froms: Vec<&str> = vocab::DERIVATION_EDGES.iter().map(|(f, _)| *f).collect();
        let tos: Vec<&str> = vocab::DERIVATION_EDGES.iter().map(|(_, t)| *t).collect();
        for class in vocab::CLASSES {
            if class.label != "OntologyDimensionCatalog" {
                assert!(
                    froms.contains(&class.label),
                    "{} missing as from_label",
                    class.label
                );
            }
            if class.label != "ConstructedRelation" {
                assert!(
                    tos.contains(&class.label),
                    "{} missing as to_label",
                    class.label
                );
            }
        }
        assert_eq!(vocab::CLASSES.len(), 9);
        assert_eq!(vocab::DERIVATION_EDGES.len(), 8);
    }

    // -------------------------------------------------------------
    // Fixture builders
    // -------------------------------------------------------------

    /// A tiny, hand-authored self-play world: two dimension-catalog-derived
    /// individuals, one N3 contraction rule deriving a transitive
    /// `:reachableFrom` edge, and one SHACL shape every `:World` individual
    /// must satisfy (declares a `:hasName`).
    fn fixture_scenario() -> ScenarioGraph {
        ScenarioGraph {
            facts_turtle: r#"
@prefix : <http://example.org/f26#> .
:siteA a :World ; :hasName "Site A" ; :linksTo :siteB .
:siteB a :World ; :hasName "Site B" ; :linksTo :siteC .
:siteC a :World ; :hasName "Site C" .
"#
            .to_string(),
        }
    }

    fn fixture_rules_n3() -> &'static str {
        // Direct link is reachable; reachability is transitive.
        r#"
@prefix : <http://example.org/f26#> .
{ ?x :linksTo ?y } => { ?x :reachableFrom ?y } .
{ ?x :reachableFrom ?y . ?y :reachableFrom ?z } => { ?x :reachableFrom ?z } .
"#
    }

    fn fixture_shapes_turtle_conforming() -> &'static str {
        r#"
@prefix : <http://example.org/f26#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
:WorldShape a sh:NodeShape ;
    sh:targetClass :World ;
    sh:property [
        sh:path :hasName ;
        sh:minCount 1 ;
    ] .
"#
    }

    fn fixture_shapes_turtle_refusing() -> &'static str {
        // Requires a property (:hasOwner) none of the fixture individuals carry.
        r#"
@prefix : <http://example.org/f26#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
:WorldShape a sh:NodeShape ;
    sh:targetClass :World ;
    sh:property [
        sh:path :hasOwner ;
        sh:minCount 1 ;
    ] .
"#
    }

    /// A trivial one-action PDDL8 domain/problem: `open(door)` with no
    /// preconditions, goal `opened(door)` -- always solvable in one step.
    fn fixture_domain_solvable() -> Pddl8Domain {
        Pddl8Domain {
            name: "f26-fixture-domain".to_string(),
            predicates: vec![("opened".to_string(), 1)],
            actions: vec![wasm4pm_compat::pddl::Pddl8ActionSchema {
                name: "open".to_string(),
                params: vec!["?d".to_string()],
                preconditions: vec![],
                add_effects: vec![wasm4pm_compat::pddl::Pddl8Atom {
                    pred: "opened".to_string(),
                    args: vec!["?d".to_string()],
                }],
                del_effects: vec![],
                typed_params: vec![],
                condition: None,
                effects: vec![],
                numeric_effects: vec![],
            }],
            types: vec![],
            functions: vec![],
            durative_actions: vec![],
            derived: vec![],
            constraints: vec![],
            processes: vec![],
            events: vec![],
        }
    }

    fn fixture_problem_solvable() -> Pddl8Problem {
        Pddl8Problem {
            name: "f26-fixture-problem".to_string(),
            domain: "f26-fixture-domain".to_string(),
            objects: vec!["door".to_string()],
            init: vec![],
            goal: vec![wasm4pm_compat::pddl::Pddl8Atom {
                pred: "opened".to_string(),
                args: vec!["door".to_string()],
            }],
            object_types: vec![],
            fn_values: vec![],
            timed_inits: vec![],
            preferences: vec![],
            metric: None,
        }
    }

    /// A goal ground atom over a predicate no action ever adds -- the
    /// grounder produces zero reachable ground actions for it, so
    /// `solve_indexed` returns `Err(GroundError::EmptyGrounding)`.
    fn fixture_problem_impossible() -> Pddl8Problem {
        Pddl8Problem {
            name: "f26-fixture-problem-impossible".to_string(),
            domain: "f26-fixture-domain".to_string(),
            objects: vec!["door".to_string()],
            init: vec![],
            goal: vec![wasm4pm_compat::pddl::Pddl8Atom {
                pred: "teleported".to_string(),
                args: vec!["door".to_string()],
            }],
            object_types: vec![],
            fn_values: vec![],
            timed_inits: vec![],
            preferences: vec![],
            metric: None,
        }
    }

    // -------------------------------------------------------------
    // D2: honest refusal
    // -------------------------------------------------------------

    #[test]

    fn generate_scenario_always_refuses_not_yet_implemented() {
        let catalog = OntologyDimensionCatalog {
            profile: ScenarioMutationProfile {
                profile_id: "p1".to_string(),
                dimensions: vec![],
            },
        };
        let err = generate_scenario(&catalog).unwrap_err();
        assert!(matches!(
            err,
            SelfPlayRefusal::NotYetImplemented {
                stage: "scenario_generator (D2)",
                ..
            }
        ));
    }

    // -------------------------------------------------------------
    // D3: real contraction
    // -------------------------------------------------------------

    #[test]
    fn contraction_derives_transitive_reachability() {
        let world = fixture_scenario();
        let (_store, closure) = contract_scenario_graph(&world, fixture_rules_n3()).unwrap();
        // siteA -> siteB (direct), siteB -> siteC (direct), and siteA -> siteC
        // (transitive) must all appear among the derived triples.
        let joined = closure.derived_nquads.join("\n");
        assert!(
            joined.contains("reachableFrom"),
            "expected derived reachableFrom triples, got: {joined}"
        );
        assert!(!closure.derived_nquads.is_empty());
        // Canonical order: sorted, so re-running is byte-identical.
        let mut sorted_copy = closure.derived_nquads.clone();
        sorted_copy.sort();
        assert_eq!(sorted_copy, closure.derived_nquads);
    }

    #[test]
    fn contraction_refuses_on_malformed_facts() {
        let world = ScenarioGraph {
            facts_turtle: "this is not { valid turtle at all @@@".to_string(),
        };
        let result = contract_scenario_graph(&world, fixture_rules_n3());
        // Either a WorldMalformed refusal, or (if the legacy line parser
        // tolerates it) an empty closure -- assert it does not panic and
        // returns a well-typed Result either way; the malformed-input path
        // specifically is what this test exists to exercise.
        match result {
            Ok((_store, closure)) => {
                assert!(closure.derived_nquads.is_empty());
            }
            Err(SelfPlayRefusal::WorldMalformed { .. }) => {}
            Err(other) => panic!("unexpected refusal variant: {other:?}"),
        }
    }

    // -------------------------------------------------------------
    // D4: real admission (admit + refuse paths)
    // -------------------------------------------------------------

    #[test]
    fn admission_admits_conforming_world() {
        let world = fixture_scenario();
        let (store, _closure) = contract_scenario_graph(&world, fixture_rules_n3()).unwrap();
        let decision = admit_contracted_world(&store, fixture_shapes_turtle_conforming()).unwrap();
        assert_eq!(decision.verdict, AdmissionVerdict::Admitted);
        assert_eq!(decision.violation_count, 0);
    }

    #[test]
    fn admission_refuses_nonconforming_world() {
        let world = fixture_scenario();
        let (store, _closure) = contract_scenario_graph(&world, fixture_rules_n3()).unwrap();
        let decision = admit_contracted_world(&store, fixture_shapes_turtle_refusing()).unwrap();
        assert_eq!(decision.verdict, AdmissionVerdict::Refused);
        assert!(decision.violation_count > 0);
    }

    // -------------------------------------------------------------
    // D5: real planning (solvable + impossible paths)
    // -------------------------------------------------------------

    #[test]
    fn planning_closes_solvable_goal() {
        let domain = fixture_domain_solvable();
        let problem = fixture_problem_solvable();
        let plan = plan_goal_closure(&domain, &problem).unwrap();
        assert!(!plan.tape.ops.is_empty());
    }

    #[test]
    fn planning_refuses_impossible_goal_preplan() {
        let domain = fixture_domain_solvable();
        let problem = fixture_problem_impossible();
        let err = plan_goal_closure(&domain, &problem).unwrap_err();
        assert!(matches!(
            err,
            SelfPlayRefusal::ImpossibleScenarioPreplanRefused { .. }
        ));
    }

    // -------------------------------------------------------------
    // D6: real POWL simulation
    // -------------------------------------------------------------

    #[test]
    fn simulation_projects_plan_to_turtle() {
        let domain = fixture_domain_solvable();
        let problem = fixture_problem_solvable();
        let plan = plan_goal_closure(&domain, &problem).unwrap();
        let workflow = simulate_workflow(&plan, "http://example.org/f26/sim1").unwrap();
        assert!(workflow.turtle.contains("powl2:"));
        assert!(!workflow.turtle.is_empty());
    }

    // -------------------------------------------------------------
    // D7: real synthetic hook receipt
    // -------------------------------------------------------------

    #[test]
    fn synthetic_hook_produces_stable_receipt() {
        let domain = fixture_domain_solvable();
        let problem = fixture_problem_solvable();
        let plan = plan_goal_closure(&domain, &problem).unwrap();
        let workflow = simulate_workflow(&plan, "http://example.org/f26/sim2").unwrap();

        let construct_query = r#"
PREFIX powl2: <https://seanchatmangpt.github.io/praxis/ontologies/powl2#>
CONSTRUCT { ?s a powl2:SelfPlayObserved . }
WHERE { ?s a powl2:Leaf . }
"#;
        let receipt1 =
            execute_synthetic_hook(&workflow, "f26-synthetic-hook", construct_query).unwrap();
        let receipt2 =
            execute_synthetic_hook(&workflow, "f26-synthetic-hook", construct_query).unwrap();
        // Same input -> byte-identical receipt (determinism doctrine).
        assert_eq!(
            receipt1.hook_receipt.delta_hash,
            receipt2.hook_receipt.delta_hash
        );
        assert_eq!(
            receipt1.hook_receipt.idempotency_key,
            receipt2.hook_receipt.idempotency_key
        );
        assert_eq!(receipt1.hook_receipt.hook_name, "f26-synthetic-hook");
    }

    // -------------------------------------------------------------
    // D8/D9: honest refusals
    // -------------------------------------------------------------

    #[test]
    fn discovery_miner_always_refuses_not_yet_implemented() {
        let err = mine_discovery_patterns(&[]).unwrap_err();
        assert!(matches!(
            err,
            SelfPlayRefusal::NotYetImplemented {
                stage: "discovery_miner (D8)",
                ..
            }
        ));
    }

    #[test]
    fn construct_capitalizer_always_refuses_not_yet_implemented() {
        let err = capitalize_discoveries(&[]).unwrap_err();
        assert!(matches!(
            err,
            SelfPlayRefusal::NotYetImplemented {
                stage: "construct_capitalizer (D9)",
                ..
            }
        ));
    }

    // -------------------------------------------------------------
    // L7: idempotency + correlation gate
    // -------------------------------------------------------------

    #[test]
    fn gate_fresh_then_replayed_then_conflict() {
        let mut gate = SelfPlayGate::new();
        assert_eq!(
            gate.check("corr-1", "content-a").unwrap(),
            GateOutcome::Fresh
        );
        assert_eq!(
            gate.check("corr-1", "content-a").unwrap(),
            GateOutcome::Replayed
        );
        let err = gate.check("corr-1", "content-b").unwrap_err();
        assert!(matches!(
            err,
            SelfPlayRefusal::DuplicateCorrelationConflict { .. }
        ));
    }

    #[test]
    fn gate_persist_restore_round_trip() {
        let mut gate = SelfPlayGate::new();
        gate.check("corr-1", "content-a").unwrap();
        gate.check("corr-2", "content-b").unwrap();
        let json = gate.persist().unwrap();
        let mut restored = SelfPlayGate::restore(&json).unwrap();
        // Restored gate must recognize the same correlation ids as replays,
        // not as fresh -- proves the round trip actually carries state.
        assert_eq!(
            restored.check("corr-1", "content-a").unwrap(),
            GateOutcome::Replayed
        );
        assert_eq!(
            restored.check("corr-2", "content-b").unwrap(),
            GateOutcome::Replayed
        );
    }

    // -------------------------------------------------------------
    // End-to-end: the real reused chain, D3 through D7, in one call.
    // -------------------------------------------------------------

    #[test]
    fn middle_stages_run_end_to_end_on_hand_built_fixture() {
        let world = fixture_scenario();
        let domain = fixture_domain_solvable();
        let problem = fixture_problem_solvable();
        let construct_query = r#"
PREFIX powl2: <https://seanchatmangpt.github.io/praxis/ontologies/powl2#>
CONSTRUCT { ?s a powl2:SelfPlayObserved . }
WHERE { ?s a powl2:Leaf . }
"#;
        let output = run_reused_pipeline(
            &world,
            fixture_rules_n3(),
            fixture_shapes_turtle_conforming(),
            &domain,
            &problem,
            "http://example.org/f26/e2e",
            "f26-e2e-hook",
            construct_query,
        )
        .unwrap();

        assert_eq!(output.admission.verdict, AdmissionVerdict::Admitted);
        assert!(!output.closure.derived_nquads.is_empty());
        assert!(!output.receipt.hook_receipt.delta_hash.is_empty());
    }

    #[test]
    fn end_to_end_refuses_at_world_generated_off_ramp_on_nonconforming_world() {
        let world = fixture_scenario();
        let domain = fixture_domain_solvable();
        let problem = fixture_problem_solvable();
        let err = run_reused_pipeline(
            &world,
            fixture_rules_n3(),
            fixture_shapes_turtle_refusing(),
            &domain,
            &problem,
            "http://example.org/f26/refused",
            "f26-refused-hook",
            "CONSTRUCT { ?s ?p ?o } WHERE { ?s ?p ?o }",
        )
        .unwrap_err();
        assert!(matches!(
            err,
            SelfPlayRefusal::SelfPlayScenarioRefused { .. }
        ));
    }

    #[test]
    fn end_to_end_refuses_at_planned_off_ramp_on_impossible_goal() {
        let world = fixture_scenario();
        let domain = fixture_domain_solvable();
        let problem = fixture_problem_impossible();
        let err = run_reused_pipeline(
            &world,
            fixture_rules_n3(),
            fixture_shapes_turtle_conforming(),
            &domain,
            &problem,
            "http://example.org/f26/impossible",
            "f26-impossible-hook",
            "CONSTRUCT { ?s ?p ?o } WHERE { ?s ?p ?o }",
        )
        .unwrap_err();
        assert!(matches!(
            err,
            SelfPlayRefusal::ImpossibleScenarioPreplanRefused { .. }
        ));
    }
}
