//! Family F30 -- "GGEN Dynamic Project State and Release Admission" (atlas
//! ticket V12-030).
//!
//! Wire-phase-1 status (this pass): **MIXED, wired**. This module now
//! carries real, compiling Rust logic for the pipeline the F30 survey and
//! `v26.7.12_mermaid_atlas/families/F30_ggen-release-state.md` require:
//! `Project State RDF -> Status CONSTRUCT -> Dependency SPARQL -> Claim
//! Ceiling Query -> Mermaid Atlas Projector -> Verifier Aggregator -> Tera
//! Renderers -> Release Gate`, the 9-state lifecycle (`OBSERVATIONS_ADMITTED
//! -> STATUS_CONSTRUCTED -> DEPENDENCIES_DERIVED -> CLAIMS_BOUNDED ->
//! DIAGRAMS_PROJECTED -> VERIFIER_LIVE -> DOCS_RENDERED -> RELEASE_ADMITTED`,
//! with `REFUSED` reachable only from `STATUS_CONSTRUCTED` and
//! `DIAGRAMS_PROJECTED` per the atlas's own L5 `stateDiagram-v2`), and a
//! typed [`ReleaseAdmissionRefused`] fired at every gate. What is genuinely
//! reused/adapted/generated vs. genuinely hand-written vs. still disclosed
//! as undone is itemized per-lens below; nothing here claims more than what
//! this session verified by compiling and running the tests in this file.
//!
//! ## L1/L2 -- Project State RDF (REUSE_ADAPT, engine ALREADY_BUILT)
//!
//! [`ProjectStateGraph`] thinly wraps `ggen::graph::DeterministicGraph`
//! (`crates/ggen/src/graph.rs`, read in full this session) -- the real,
//! already-tested in-memory oxigraph store with Turtle loading, SPARQL
//! querying, and canonical-BLAKE3 `state_hash`. [`ProjectStateGraph::admit_observations`]
//! is the Project State RDF component (C1): it inserts caller-supplied
//! Turtle observation facts and fails closed
//! (`ReleaseAdmissionRefused::ObservationGraphMalformed`) on parse error --
//! no fact ever silently drops.
//!
//! ## L2 -- Status CONSTRUCT + Dependency SPARQL (HAND_WRITE_REQUIRED query text, REUSE_ADAPT mechanism)
//!
//! [`ProjectStateGraph::construct_status`] runs the real CONSTRUCT query at
//! `queries/f30-status-construct.rq` (ggen-synced from
//! `packs/f30-ggen-release-state-pack/`) via
//! `ggen::graph::GraphEngine::query`, deriving each admitted Ticket's
//! `mfwrel:derivedStatus` purely from `mfwrel:observationResult` evidence
//! (BLOCKED if any FAIL observation exists, else ALIVE if any PASS exists,
//! else UNVERIFIED) -- **never** hand-typed, which is F30's core invariant
//! and the exact defect the family survey found both `jira-tracking-pack`
//! and `post-release-pack` currently commit. [`ProjectStateGraph::derive_dependencies`]
//! runs `queries/f30-dependency-select.rq`, a direct REUSE_ADAPT of
//! `packs/jira-tracking-pack/templates/jira-deps.rq.tmpl`'s proven SPARQL
//! 1.1 `+` property-path pattern (`mfwrel:dependsOn+` in place of
//! `jira:dependsOn+`) -- only the prefix/predicate names changed.
//!
//! ## L5 -- 9-state lifecycle (HAND_WRITE_REQUIRED, new; catalog GGEN_GENERATABLE)
//!
//! [`ReleaseLifecycleState`] and [`ReleaseLifecycleState::can_transition_to`]
//! are new hand-written logic -- no existing praxis code models this exact
//! state machine. `can_transition_to` is backed by
//! [`LIFECYCLE_TRANSITIONS`] (from `f30_ggen_release_state_generated.rs`,
//! `include!`d below), a real ggen-generated projection of the atlas's own
//! L5 `stateDiagram-v2` edges (9 edges: 7 lawful chain + 2 REFUSED
//! branches), generated by `ggen sync` from
//! `packs/f30-ggen-release-state-pack/ontology.ttl`'s
//! `mfwrel:LifecycleTransition` individuals; two independent fresh runs
//! produced byte-identical output (`shasum -a 256`), confirming
//! determinism. [`lifecycle_catalog_states_match_enum`] and
//! [`lifecycle_transitions_match_atlas_edges`] below cross-check the
//! generated catalog against both the hand-written enum and the atlas
//! document text itself, so the two representations cannot silently drift
//! apart.
//!
//! ## L8 -- Claim Ceiling Query (HAND_WRITE_REQUIRED, new)
//!
//! [`bound_claim`] implements the atlas's L8 gate: five boolean evidence
//! inputs (source/graph evidence, unit+negative fixtures, production
//! reachability trace, chaos/recovery evidence, receipt/replay
//! equivalence) bound the highest [`ClaimLevel`] the pipeline may emit --
//! `Alive` only if all five hold, `Partial` if source evidence plus test
//! fixtures hold, `Unverified` otherwise (the no-overclaiming default,
//! never rounded up). This mirrors the honest-downgrade philosophy of
//! `scripts/verifier_report.py` (REAL_PASS / REAL_FAIL /
//! NOT_YET_AVAILABLE, read in full this session) without porting its
//! Python or its ticket-table-regex parsing, which is architecturally
//! unrelated to this graph-backed pipeline. [`VerifierAggregate::ceiling`]
//! extends the same bounding rule across multiple named verifier fields,
//! deterministically (fields are sorted by name before folding, so
//! `HashMap`/caller iteration order never affects the result -- repo
//! invariant #5).
//!
//! ## L6 -- Mermaid Atlas Projector + Tera Renderers (HAND_WRITE_REQUIRED projector; REUSE Tera engine)
//!
//! [`project_mermaid`] is a real, non-decorative function: it walks
//! [`LIFECYCLE_TRANSITIONS`] (the same ggen-generated table
//! `can_transition_to` consults, never a second hand-typed copy) and
//! renders a genuine `stateDiagram-v2` Mermaid document, annotating
//! whichever state the caller names as current. [`render_docs`] uses the
//! real `tera` crate (`Tera::default().render_str`, the same idiom
//! `crates/ggen/src/template.rs` uses) to interpolate already-computed
//! [`StatusFact`]/[`DependencyEdge`]/[`ClaimLevel`] values into a Markdown
//! doc template -- the template contains no conditional logic that could
//! decide status; it only prints what the CONSTRUCT/Claim-Ceiling stages
//! already computed, honoring F30's "Tera does not decide release state"
//! invariant literally.
//!
//! ## L7 -- Concurrency/Recovery/Chaos (PARTIAL, hand-written, disclosed gap)
//!
//! [`ReceiptHead`] implements the atomic idempotency + correlation gate
//! the atlas's L7 diagram requires: [`ReceiptHead::admit_or_replay`]
//! replays the prior [`ReleaseReceipt`] content hash for a duplicate event
//! (same `correlation_id`, same content hash) rather than recomputing, and
//! refuses [`ReleaseAdmissionRefused::ConcurrentDrift`] for a conflicting
//! one (same `correlation_id`, different hash). [`ReceiptHead::open`]
//! genuinely persists this as a newline-delimited JSON journal on disk
//! (`serde_json`, already a dependency) and reloads it on construction --
//! `receipt_head_survives_restart` below proves a fresh `ReceiptHead`
//! opened against the same path after the original struct is dropped
//! still recognizes a prior correlation id as a replay, which is the
//! literal "process or engine restart" scenario the atlas's L7 diagram
//! names. Disclosed gap, not glossed over: this journal is a local file,
//! not a networked/multi-writer durable store, so true multi-process
//! concurrent-writer chaos (two engines racing on the same journal file)
//! is not exercised or guaranteed safe this pass -- `std::fs::OpenOptions`
//! append is not cross-process-atomic on all platforms. A production
//! deployment would need a real lock or a transactional store; that
//! remains HAND_WRITE_REQUIRED.
//!
//! ## Release Gate (HAND_WRITE_REQUIRED, new)
//!
//! [`admit_release`] is the orchestration: it walks every lawful edge of
//! [`LIFECYCLE_TRANSITIONS`] via [`require_transition`] (never assumes the
//! linear order silently), refuses at the two atlas-declared REFUSED
//! branches (`STATUS_CONSTRUCTED` on a malformed CONSTRUCT result,
//! `DIAGRAMS_PROJECTED` on a stale caller-declared state hash), computes
//! [`ReleaseReceipt::content_hash`] as a BLAKE3 digest over a *sorted*
//! concatenation of every derived fact (repo invariant #2: sorted before
//! hashing, verified by `admit_release_end_to_end_happy_path`'s
//! byte-identical-across-two-calls assertion), and gates the final
//! admission through [`ReceiptHead`]. Disclosed scope boundary: the
//! Verifier Aggregator component this Release Gate consults
//! ([`VerifierAggregate`]) does not itself spawn `cargo test` / `just
//! verify-all` -- it consumes already-collected [`VerifierField`] results.
//! Building a live, sandboxed, command-spawning verifier is real
//! additional scope (security-sensitive: arbitrary process execution) and
//! remains HAND_WRITE_REQUIRED, named here rather than silently absent.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use ggen::graph::{DeterministicGraph, EngineQueryResults, GraphEngine};

include!("f30_ggen_release_state_generated.rs");

/// F30-L2 component C2's real CONSTRUCT query body, ggen-synced verbatim
/// from `packs/f30-ggen-release-state-pack/templates/f30-status-construct.rq.tmpl`
/// into `queries/f30-status-construct.rq` and embedded here so the binary
/// carries no runtime filesystem dependency on the queries directory.
const STATUS_CONSTRUCT_QUERY: &str = include_str!("../queries/f30-status-construct.rq");
const STATUS_CONSTRUCT_QUERY_PATH: &str = "queries/f30-status-construct.rq";

/// F30-L2 component C3's real SELECT query body, ggen-synced verbatim from
/// `packs/f30-ggen-release-state-pack/templates/f30-dependency-select.rq.tmpl`.
const DEPENDENCY_SELECT_QUERY: &str = include_str!("../queries/f30-dependency-select.rq");
const DEPENDENCY_SELECT_QUERY_PATH: &str = "queries/f30-dependency-select.rq";

// ---------------------------------------------------------------------------
// L5 -- 9-state lifecycle
// ---------------------------------------------------------------------------

/// F30-L5's 9-state machine, mirroring [`LIFECYCLE_STATES`] one-for-one
/// (crosschecked by `lifecycle_catalog_states_match_enum` below).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ReleaseLifecycleState {
    ObservationsAdmitted,
    StatusConstructed,
    DependenciesDerived,
    ClaimsBounded,
    DiagramsProjected,
    VerifierLive,
    DocsRendered,
    ReleaseAdmitted,
    Refused,
}

impl ReleaseLifecycleState {
    /// The exact atlas name (`LIFECYCLE_STATES[*].name`) for this state.
    pub const fn atlas_name(self) -> &'static str {
        match self {
            Self::ObservationsAdmitted => "OBSERVATIONS_ADMITTED",
            Self::StatusConstructed => "STATUS_CONSTRUCTED",
            Self::DependenciesDerived => "DEPENDENCIES_DERIVED",
            Self::ClaimsBounded => "CLAIMS_BOUNDED",
            Self::DiagramsProjected => "DIAGRAMS_PROJECTED",
            Self::VerifierLive => "VERIFIER_LIVE",
            Self::DocsRendered => "DOCS_RENDERED",
            Self::ReleaseAdmitted => "RELEASE_ADMITTED",
            Self::Refused => "REFUSED",
        }
    }

    /// Inverse of [`Self::atlas_name`]; `None` for any name not in the
    /// atlas's declared 9-state catalog.
    pub fn from_atlas_name(name: &str) -> Option<Self> {
        ALL_STATES.iter().copied().find(|s| s.atlas_name() == name)
    }

    /// Real transition check, backed by [`LIFECYCLE_TRANSITIONS`]
    /// (ggen-generated, not a second hand-typed copy of the atlas's edge
    /// list) -- so an atlas edit that adds/removes an edge is caught by
    /// regenerating the pack, not silently missed by a duplicated Rust
    /// match arm.
    pub fn can_transition_to(self, next: Self) -> bool {
        LIFECYCLE_TRANSITIONS
            .iter()
            .any(|t| t.from == self.atlas_name() && t.to == next.atlas_name())
    }
}

/// Every [`ReleaseLifecycleState`] variant, for catalog crosschecks and
/// [`ReleaseLifecycleState::from_atlas_name`]'s lookup.
const ALL_STATES: &[ReleaseLifecycleState] = &[
    ReleaseLifecycleState::ObservationsAdmitted,
    ReleaseLifecycleState::StatusConstructed,
    ReleaseLifecycleState::DependenciesDerived,
    ReleaseLifecycleState::ClaimsBounded,
    ReleaseLifecycleState::DiagramsProjected,
    ReleaseLifecycleState::VerifierLive,
    ReleaseLifecycleState::DocsRendered,
    ReleaseLifecycleState::ReleaseAdmitted,
    ReleaseLifecycleState::Refused,
];

/// Fails closed with [`ReleaseAdmissionRefused::UnauthorizedTransition`]
/// unless `from -> to` is a real edge in [`LIFECYCLE_TRANSITIONS`]. The
/// Release Gate calls this at every step of [`admit_release`] instead of
/// assuming the linear chain order.
fn require_transition(
    from: ReleaseLifecycleState,
    to: ReleaseLifecycleState,
) -> Result<(), ReleaseAdmissionRefused> {
    if from.can_transition_to(to) {
        Ok(())
    } else {
        Err(ReleaseAdmissionRefused::UnauthorizedTransition {
            from: from.atlas_name(),
            to: to.atlas_name(),
        })
    }
}

// ---------------------------------------------------------------------------
// Typed refusal
// ---------------------------------------------------------------------------

/// F30's typed refusal taxonomy. Every variant has >=1 end-to-end test in
/// this file's `tests` module (repo invariant #1 / #8, and the F30 survey's
/// own invariant #5).
#[derive(Debug, thiserror::Error)]
pub enum ReleaseAdmissionRefused {
    /// The observation Turtle failed to parse, or the in-memory graph could
    /// not be constructed/hashed. Refused pre-`OBSERVATIONS_ADMITTED`: a
    /// malformed world never reaches the first lifecycle state at all
    /// (the same MALFORMED_WORLD_PREPLAN_REFUSAL discipline
    /// `f07_shape_admission.rs` documents for its own graph admission).
    #[error("observation graph malformed: {reason}")]
    ObservationGraphMalformed { reason: String },

    /// The Status CONSTRUCT query (`{query_path}`) either failed to
    /// evaluate or did not evaluate to CONSTRUCT/DESCRIBE triples --
    /// F30-L5's `STATUS_CONSTRUCTED -> REFUSED: invalid` branch.
    #[error("Status CONSTRUCT `{query_path}` invalid: {reason}")]
    StatusConstructMalformed {
        query_path: &'static str,
        reason: String,
    },

    /// The Dependency SELECT query (`{query_path}`) either failed to
    /// evaluate or did not evaluate to SELECT rows.
    #[error("Dependency SELECT `{query_path}` invalid: {reason}")]
    DependencySelectMalformed {
        query_path: &'static str,
        reason: String,
    },

    /// The caller declared an `expected_state_hash` that no longer matches
    /// the live graph's `state_hash()` -- a concurrent workflow admitted
    /// new observations between the caller's read and this admission
    /// attempt. F30-L5's `DIAGRAMS_PROJECTED -> REFUSED: authority or
    /// conformance failure` branch.
    #[error(
        "project state is stale: caller declared state_hash {declared}, live graph state_hash is {live}"
    )]
    StaleProjectState { declared: String, live: String },

    /// An orchestration step attempted a `from -> to` pair that is not a
    /// real edge in [`LIFECYCLE_TRANSITIONS`].
    #[error("illegal lifecycle transition: {from} -> {to} is not a lawful F30-L5 edge")]
    UnauthorizedTransition {
        from: &'static str,
        to: &'static str,
    },

    /// L7 atomic idempotency + correlation gate: `correlation_id` was
    /// already admitted with a different content hash -- concurrent-edit
    /// drift, refused rather than silently overwritten.
    #[error(
        "correlation id `{correlation_id}` already admitted with a different content hash (first {first_hash}, this attempt {this_hash})"
    )]
    ConcurrentDrift {
        correlation_id: String,
        first_hash: String,
        this_hash: String,
    },

    /// The durable receipt-head journal at `path` could not be read or
    /// written.
    #[error("receipt head journal at `{path}` unreadable/unwritable: {reason}")]
    ReceiptHeadJournalError { path: String, reason: String },

    /// A Tera render of a release doc failed. The template itself is
    /// fixed, static, and contains no state-deciding logic (F30's own
    /// invariant); this variant only fires on a genuine Tera engine error
    /// (e.g. malformed template syntax), never a "status" decision.
    #[error("release doc render failed: {reason}")]
    DocRenderFailed { reason: String },
}

// ---------------------------------------------------------------------------
// L1/L2 -- Project State RDF, Status CONSTRUCT, Dependency SPARQL
// ---------------------------------------------------------------------------

/// One `mfwrel:Ticket`'s CONSTRUCT-derived status
/// (`mfwrel:derivedStatus`) -- never hand-typed, only ever produced by
/// [`ProjectStateGraph::construct_status`].
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize)]
pub struct StatusFact {
    pub ticket: String,
    pub status: String,
}

/// One `(ticket, transitive dependency)` edge from the Dependency SELECT.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize)]
pub struct DependencyEdge {
    pub ticket: String,
    pub depends_on: String,
}

/// F30-L2 component C1 (Project State RDF): a thin wrapper over
/// `ggen::graph::DeterministicGraph` carrying this family's own typed
/// refusal at every fallible boundary.
pub struct ProjectStateGraph {
    graph: DeterministicGraph,
}

impl ProjectStateGraph {
    /// Real, empty in-memory oxigraph-backed graph.
    pub fn new() -> Result<Self, ReleaseAdmissionRefused> {
        let graph = DeterministicGraph::new().map_err(|e| {
            ReleaseAdmissionRefused::ObservationGraphMalformed {
                reason: e.to_string(),
            }
        })?;
        Ok(Self { graph })
    }

    /// Admits Turtle observation facts. Fails closed on malformed Turtle --
    /// no partial/silent admission.
    pub fn admit_observations(&self, turtle: &str) -> Result<usize, ReleaseAdmissionRefused> {
        self.graph.insert_turtle(turtle).map_err(|e| {
            ReleaseAdmissionRefused::ObservationGraphMalformed {
                reason: e.to_string(),
            }
        })
    }

    /// Canonical BLAKE3 state hash of the currently-admitted facts (sorted
    /// N-Quads, `ggen::graph::DeterministicGraph::state_hash`).
    pub fn state_hash(&self) -> Result<[u8; 32], ReleaseAdmissionRefused> {
        self.graph
            .state_hash()
            .map_err(|e| ReleaseAdmissionRefused::ObservationGraphMalformed {
                reason: e.to_string(),
            })
    }

    /// F30-L2 component C2: runs the real Status CONSTRUCT query and
    /// derives each admitted Ticket's status purely as a graph consequence.
    pub fn construct_status(&self) -> Result<Vec<StatusFact>, ReleaseAdmissionRefused> {
        let results = GraphEngine::query(&self.graph, STATUS_CONSTRUCT_QUERY).map_err(|e| {
            ReleaseAdmissionRefused::StatusConstructMalformed {
                query_path: STATUS_CONSTRUCT_QUERY_PATH,
                reason: e.to_string(),
            }
        })?;
        parse_status_construct_result(results)
    }

    /// F30-L2 component C3: runs the real Dependency SELECT query
    /// (`mfwrel:dependsOn+`), returning every transitive `(ticket, dep)`
    /// pair.
    pub fn derive_dependencies(&self) -> Result<Vec<DependencyEdge>, ReleaseAdmissionRefused> {
        let results = GraphEngine::query(&self.graph, DEPENDENCY_SELECT_QUERY).map_err(|e| {
            ReleaseAdmissionRefused::DependencySelectMalformed {
                query_path: DEPENDENCY_SELECT_QUERY_PATH,
                reason: e.to_string(),
            }
        })?;
        parse_dependency_select_result(results)
    }
}

/// Extracted from [`ProjectStateGraph::construct_status`] so it is
/// unit-testable against hand-built [`EngineQueryResults`] fixtures without
/// needing a live SPARQL evaluation for the negative (wrong-shape) path.
fn parse_status_construct_result(
    results: EngineQueryResults,
) -> Result<Vec<StatusFact>, ReleaseAdmissionRefused> {
    let EngineQueryResults::Graph(triples) = results else {
        return Err(ReleaseAdmissionRefused::StatusConstructMalformed {
            query_path: STATUS_CONSTRUCT_QUERY_PATH,
            reason: "query did not evaluate to CONSTRUCT/DESCRIBE triples".to_string(),
        });
    };
    let mut facts: Vec<StatusFact> = triples
        .iter()
        .filter(|t| t.predicate.ends_with("#derivedStatus>"))
        .map(|t| StatusFact {
            ticket: local_name(&t.subject),
            status: t.object_value.clone(),
        })
        .collect();
    // Sorted before any hashing/rendering consumes this (repo invariant #2).
    facts.sort_by(|a, b| {
        (a.ticket.as_str(), a.status.as_str()).cmp(&(b.ticket.as_str(), b.status.as_str()))
    });
    Ok(facts)
}

/// Extracted from [`ProjectStateGraph::derive_dependencies`], same rationale
/// as [`parse_status_construct_result`].
fn parse_dependency_select_result(
    results: EngineQueryResults,
) -> Result<Vec<DependencyEdge>, ReleaseAdmissionRefused> {
    let EngineQueryResults::Solutions(rows) = results else {
        return Err(ReleaseAdmissionRefused::DependencySelectMalformed {
            query_path: DEPENDENCY_SELECT_QUERY_PATH,
            reason: "query did not evaluate to SELECT rows".to_string(),
        });
    };
    let mut edges: Vec<DependencyEdge> = rows
        .iter()
        .filter_map(|row| {
            let id = row.get("id")?.clone();
            let dep = row.get("dep")?.clone();
            Some(DependencyEdge {
                ticket: id,
                depends_on: dep,
            })
        })
        .collect();
    edges.sort_by(|a, b| {
        (a.ticket.as_str(), a.depends_on.as_str()).cmp(&(b.ticket.as_str(), b.depends_on.as_str()))
    });
    Ok(edges)
}

/// N-Triples subject/predicate is `<full#Iri>` or a plain literal; take the
/// fragment/last-segment as a readable label, falling back to the raw
/// (bracket-stripped) string if there is no `#`/`/` to split on.
fn local_name(ntriples_term: &str) -> String {
    let stripped = ntriples_term.trim_start_matches('<').trim_end_matches('>');
    stripped
        .rsplit(['#', '/'])
        .next()
        .unwrap_or(stripped)
        .to_string()
}

// ---------------------------------------------------------------------------
// L8 -- Claim Ceiling Query
// ---------------------------------------------------------------------------

/// The 5 inputs F30-L8's `CEIL{"Claim ceiling satisfied?"}` gate consults,
/// named identically to the atlas diagram's own boxes (SRC/TEST/REACH/
/// CHAOS/RECEIPT).
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct ClaimEvidence {
    pub source_and_graph_evidence: bool,
    pub unit_and_negative_fixtures: bool,
    pub production_reachability_trace: bool,
    pub chaos_and_recovery_evidence: bool,
    pub receipt_and_replay_equivalence: bool,
}

impl ClaimEvidence {
    /// `true` iff every one of the 5 inputs holds -- the atlas's `CEIL`
    /// "yes" branch.
    pub const fn ceiling_satisfied(&self) -> bool {
        self.source_and_graph_evidence
            && self.unit_and_negative_fixtures
            && self.production_reachability_trace
            && self.chaos_and_recovery_evidence
            && self.receipt_and_replay_equivalence
    }
}

/// The no-overclaiming vocabulary (`.claude/rules/no-overclaiming.md`),
/// reused verbatim as this family's release-claim vocabulary rather than
/// inventing a parallel one.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ClaimLevel {
    Alive,
    Partial,
    Blocked,
    Mocked,
    Refused,
    Unverified,
}

impl std::fmt::Display for ClaimLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            Self::Alive => "ALIVE",
            Self::Partial => "PARTIAL",
            Self::Blocked => "BLOCKED",
            Self::Mocked => "MOCKED",
            Self::Refused => "REFUSED",
            Self::Unverified => "UNVERIFIED",
        };
        f.write_str(s)
    }
}

/// Severity rank for [`VerifierAggregate::ceiling`]'s "worst field bounds
/// the whole aggregate" fold -- higher rank means a more permissive
/// (claims-more) level; the ceiling is the *minimum* rank present.
const fn claim_level_rank(level: ClaimLevel) -> u8 {
    match level {
        ClaimLevel::Alive => 5,
        ClaimLevel::Partial => 4,
        ClaimLevel::Unverified => 3,
        ClaimLevel::Mocked => 2,
        ClaimLevel::Blocked => 1,
        ClaimLevel::Refused => 0,
    }
}

/// F30-L2 component C4 (Claim Ceiling Query): the highest [`ClaimLevel`]
/// the pipeline may emit given `evidence`. `Alive` requires all 5 inputs;
/// `Partial` requires at least source/graph evidence plus test fixtures
/// (a claim with real evidence and real tests, but not yet a production
/// reachability/chaos/replay trace, is a legitimate PARTIAL, not a
/// fabricated ALIVE); anything less is `Unverified`, the no-overclaiming
/// default -- this function never returns `Alive` on partial evidence, and
/// never silently rounds up.
pub const fn bound_claim(evidence: &ClaimEvidence) -> ClaimLevel {
    if !evidence.source_and_graph_evidence {
        return ClaimLevel::Unverified;
    }
    if evidence.ceiling_satisfied() {
        return ClaimLevel::Alive;
    }
    if evidence.unit_and_negative_fixtures {
        return ClaimLevel::Partial;
    }
    ClaimLevel::Unverified
}

/// One named field of the F30-L2 component C6 (Verifier Aggregator) --
/// consumes an already-collected verifier result. Disclosed scope
/// boundary: nothing in this module spawns the underlying command itself
/// (see module doc's Release Gate section).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VerifierField {
    pub name: &'static str,
    pub status: ClaimLevel,
    pub detail: String,
}

/// A collected set of [`VerifierField`]s.
#[derive(Debug, Clone, Default)]
pub struct VerifierAggregate {
    pub fields: Vec<VerifierField>,
}

impl VerifierAggregate {
    /// The bounding [`ClaimLevel`] across every field: the single worst
    /// (least-permissive) field's level, computed deterministically
    /// (fields sorted by name first, so caller/collection iteration order
    /// can never change the result). An aggregate with zero fields bounds
    /// to `Unverified` -- "nothing was checked" must never read as ALIVE.
    pub fn ceiling(&self) -> ClaimLevel {
        let mut fields = self.fields.clone();
        fields.sort_by_key(|f| f.name);
        // `.min_by_key` on an empty Vec is `None`, not an error -- this is
        // the "no verifier fields collected" case, and Unverified is the
        // correct, honest default for it (not a Result being swallowed).
        fields
            .iter()
            .map(|f| f.status)
            .min_by_key(|lvl| claim_level_rank(*lvl))
            .unwrap_or(ClaimLevel::Unverified)
    }
}

// ---------------------------------------------------------------------------
// L6 -- Mermaid Atlas Projector
// ---------------------------------------------------------------------------

/// F30-L2 component C5: projects the *real* [`LIFECYCLE_TRANSITIONS`] table
/// (the same one [`ReleaseLifecycleState::can_transition_to`] consults)
/// into a genuine Mermaid `stateDiagram-v2` document, marking `current` and
/// (if present) noting the refusal that halted the pipeline there.
pub fn project_mermaid(
    current: ReleaseLifecycleState,
    refusal: Option<&ReleaseAdmissionRefused>,
) -> String {
    use std::fmt::Write as _;
    let mut out = String::from("stateDiagram-v2\n    [*] --> OBSERVATIONS_ADMITTED\n");
    for t in LIFECYCLE_TRANSITIONS {
        let _ = writeln!(out, "    {} --> {}: {}", t.from, t.to, t.label);
    }
    let _ = writeln!(out, "    RELEASE_ADMITTED --> [*]");
    let _ = writeln!(out, "    REFUSED --> [*]: typed ReleaseAdmissionRefused");
    let _ = writeln!(
        out,
        "    note right of {}: current state",
        current.atlas_name()
    );
    if let Some(r) = refusal {
        let note = r.to_string().replace(['\n', ':', '"'], " ");
        let _ = writeln!(out, "    note right of REFUSED: {note}");
    }
    out
}

// ---------------------------------------------------------------------------
// L6 -- Tera Renderers
// ---------------------------------------------------------------------------

/// C7's fixed release-status document template. Contains no `{% if %}`
/// branch that could *decide* status -- only loops that print already-
/// computed facts, honoring F30's "Tera does not decide release state"
/// invariant.
const RELEASE_STATUS_MD_TEMPLATE: &str = r#"# Release Status

Lifecycle state: {{ lifecycle_state }}
Claim ceiling: {{ claim_level }}

## Ticket status (graph-derived, never hand-typed)
{% for f in status_facts %}- {{ f.ticket }}: {{ f.status }}
{% endfor %}
## Dependencies (graph-derived)
{% for d in dependencies %}- {{ d.ticket }} depends on {{ d.depends_on }}
{% endfor %}"#;

/// F30-L2 component C7: renders [`RenderedReleaseDoc`]s from already-
/// computed facts. `Tera::default().render_str` matches the idiom
/// `crates/ggen/src/template.rs` itself uses.
pub fn render_docs(
    lifecycle_state: ReleaseLifecycleState,
    claim_level: ClaimLevel,
    status_facts: &[StatusFact],
    dependencies: &[DependencyEdge],
) -> Result<Vec<RenderedReleaseDoc>, ReleaseAdmissionRefused> {
    let mut context = tera::Context::new();
    context.insert("lifecycle_state", lifecycle_state.atlas_name());
    context.insert("claim_level", &claim_level.to_string());
    context.insert("status_facts", status_facts);
    context.insert("dependencies", dependencies);
    let rendered = tera::Tera::default()
        .render_str(RELEASE_STATUS_MD_TEMPLATE, &context)
        .map_err(|e| ReleaseAdmissionRefused::DocRenderFailed {
            reason: e.to_string(),
        })?;
    Ok(vec![RenderedReleaseDoc {
        name: "RELEASE_STATUS.md".to_string(),
        content: rendered,
    }])
}

/// One rendered document (D7 `RenderedReleaseDocs` in F30-L6's data flow).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RenderedReleaseDoc {
    pub name: String,
    pub content: String,
}

// ---------------------------------------------------------------------------
// Release Gate + ReleaseReceipt
// ---------------------------------------------------------------------------

/// D8 in F30-L6's data flow: the bound artifact of a successful
/// [`admit_release`] call.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ReleaseReceipt {
    pub lifecycle_state: ReleaseLifecycleState,
    pub claim_level: ClaimLevel,
    /// Hex-encoded BLAKE3 digest over a sorted canonical concatenation of
    /// every derived fact (repo invariant #2).
    pub content_hash: String,
    pub mermaid: String,
    pub docs: Vec<RenderedReleaseDoc>,
}

/// BLAKE3 over a *sorted* concatenation of every fact the receipt covers
/// (repo invariant #2: sorted before hashing). `status_facts`/`dependencies`
/// are already caller-sorted by their producing functions; this sorts the
/// full assembled line-set again regardless, so the hash never depends on
/// any caller-supplied ordering either.
fn compute_receipt_hash(
    lifecycle_state: ReleaseLifecycleState,
    claim_level: ClaimLevel,
    status_facts: &[StatusFact],
    dependencies: &[DependencyEdge],
    mermaid: &str,
    docs: &[RenderedReleaseDoc],
) -> String {
    let mut lines: Vec<String> = Vec::new();
    lines.push(format!("lifecycle_state={}", lifecycle_state.atlas_name()));
    lines.push(format!("claim_level={claim_level}"));
    for f in status_facts {
        lines.push(format!("status:{}:{}", f.ticket, f.status));
    }
    for d in dependencies {
        lines.push(format!("dep:{}:{}", d.ticket, d.depends_on));
    }
    for d in docs {
        lines.push(format!("doc:{}:{}", d.name, d.content));
    }
    lines.push(format!("mermaid:{mermaid}"));
    lines.sort();
    blake3::hash(lines.join("\n").as_bytes())
        .to_hex()
        .to_string()
}

/// One JSONL entry of the L7 durable receipt-head journal.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
struct ReceiptHeadEntry {
    correlation_id: String,
    content_hash: String,
    lifecycle_state: String,
    claim_level: String,
}

/// F30-L7's "atomic idempotency and correlation gate" + "durable receipt
/// head". See module doc's L7 section for what is genuinely durable vs.
/// the disclosed multi-process-safety gap.
pub struct ReceiptHead {
    path: Option<PathBuf>,
    entries: HashMap<String, ReceiptHeadEntry>,
}

impl ReceiptHead {
    /// In-memory only -- no restart recovery. For callers/tests that don't
    /// need L7 durability.
    pub fn in_memory() -> Self {
        Self {
            path: None,
            entries: HashMap::new(),
        }
    }

    /// Real durable journal: loads existing entries from `path` if present
    /// (a prior process's receipt head genuinely survives restart),
    /// appending new entries synchronously thereafter.
    pub fn open(path: &Path) -> Result<Self, ReleaseAdmissionRefused> {
        let mut entries = HashMap::new();
        match std::fs::read_to_string(path) {
            Ok(raw) => {
                for line in raw.lines().filter(|l| !l.trim().is_empty()) {
                    let entry: ReceiptHeadEntry = serde_json::from_str(line).map_err(|e| {
                        ReleaseAdmissionRefused::ReceiptHeadJournalError {
                            path: path.display().to_string(),
                            reason: format!("malformed journal line: {e}"),
                        }
                    })?;
                    entries.insert(entry.correlation_id.clone(), entry);
                }
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
            Err(e) => {
                return Err(ReleaseAdmissionRefused::ReceiptHeadJournalError {
                    path: path.display().to_string(),
                    reason: e.to_string(),
                });
            }
        }
        Ok(Self {
            path: Some(path.to_path_buf()),
            entries,
        })
    }

    /// The atomic idempotency + correlation gate: a duplicate event (same
    /// `correlation_id`, same `content_hash`) replays (`Ok(true)`) rather
    /// than being treated as new; a conflicting event (same
    /// `correlation_id`, different `content_hash`) is concurrent-edit
    /// drift and refuses.
    pub fn admit_or_replay(
        &mut self,
        correlation_id: &str,
        content_hash: &str,
        lifecycle_state: ReleaseLifecycleState,
        claim_level: ClaimLevel,
    ) -> Result<bool, ReleaseAdmissionRefused> {
        if let Some(prior) = self.entries.get(correlation_id) {
            if prior.content_hash == content_hash {
                return Ok(true);
            }
            return Err(ReleaseAdmissionRefused::ConcurrentDrift {
                correlation_id: correlation_id.to_string(),
                first_hash: prior.content_hash.clone(),
                this_hash: content_hash.to_string(),
            });
        }
        let entry = ReceiptHeadEntry {
            correlation_id: correlation_id.to_string(),
            content_hash: content_hash.to_string(),
            lifecycle_state: lifecycle_state.atlas_name().to_string(),
            claim_level: claim_level.to_string(),
        };
        if let Some(path) = &self.path {
            use std::io::Write as _;
            let line = serde_json::to_string(&entry).map_err(|e| {
                ReleaseAdmissionRefused::ReceiptHeadJournalError {
                    path: path.display().to_string(),
                    reason: e.to_string(),
                }
            })?;
            let mut file = std::fs::OpenOptions::new()
                .create(true)
                .append(true)
                .open(path)
                .map_err(|e| ReleaseAdmissionRefused::ReceiptHeadJournalError {
                    path: path.display().to_string(),
                    reason: e.to_string(),
                })?;
            writeln!(file, "{line}").map_err(|e| {
                ReleaseAdmissionRefused::ReceiptHeadJournalError {
                    path: path.display().to_string(),
                    reason: e.to_string(),
                }
            })?;
        }
        self.entries.insert(correlation_id.to_string(), entry);
        Ok(false)
    }
}

/// Everything [`admit_release`] needs from its caller.
pub struct ReleaseAdmissionInput<'a> {
    pub observation_turtle: &'a str,
    pub claim_evidence: ClaimEvidence,
    pub correlation_id: &'a str,
    /// If `Some`, the caller's last-known graph state hash; a mismatch
    /// against the live hash after admission refuses
    /// [`ReleaseAdmissionRefused::StaleProjectState`] (F30-L5's
    /// `DIAGRAMS_PROJECTED -> REFUSED` branch).
    pub expected_state_hash: Option<[u8; 32]>,
}

/// The Release Gate (F30-L2 component C8): walks every stage of the
/// pipeline, consulting [`require_transition`] at each lifecycle step
/// rather than assuming the linear order, and returns `(receipt,
/// is_replay)` -- `is_replay` is `true` when [`ReceiptHead::admit_or_replay`]
/// recognized this exact `(correlation_id, content_hash)` pair as a
/// duplicate event rather than a new admission.
pub fn admit_release(
    input: &ReleaseAdmissionInput<'_>,
    receipt_head: &mut ReceiptHead,
) -> Result<(ReleaseReceipt, bool), ReleaseAdmissionRefused> {
    // OBSERVATIONS_ADMITTED
    let graph = ProjectStateGraph::new()?;
    graph.admit_observations(input.observation_turtle)?;
    let live_hash = graph.state_hash()?;

    require_transition(
        ReleaseLifecycleState::ObservationsAdmitted,
        ReleaseLifecycleState::StatusConstructed,
    )?;
    // STATUS_CONSTRUCTED (may refuse: invalid)
    let status_facts = graph.construct_status()?;

    require_transition(
        ReleaseLifecycleState::StatusConstructed,
        ReleaseLifecycleState::DependenciesDerived,
    )?;
    // DEPENDENCIES_DERIVED
    let dependencies = graph.derive_dependencies()?;

    require_transition(
        ReleaseLifecycleState::DependenciesDerived,
        ReleaseLifecycleState::ClaimsBounded,
    )?;
    // CLAIMS_BOUNDED
    let claim_level = bound_claim(&input.claim_evidence);

    require_transition(
        ReleaseLifecycleState::ClaimsBounded,
        ReleaseLifecycleState::DiagramsProjected,
    )?;
    // DIAGRAMS_PROJECTED (may refuse: authority or conformance failure --
    // checked here, before the projector runs, so a stale caller-declared
    // hash never reaches it)
    if let Some(expected) = input.expected_state_hash {
        if expected != live_hash {
            return Err(ReleaseAdmissionRefused::StaleProjectState {
                declared: hex::encode(expected),
                live: hex::encode(live_hash),
            });
        }
    }
    let mermaid = project_mermaid(ReleaseLifecycleState::DiagramsProjected, None);

    require_transition(
        ReleaseLifecycleState::DiagramsProjected,
        ReleaseLifecycleState::VerifierLive,
    )?;
    // VERIFIER_LIVE -- see module doc's Release Gate section for the
    // disclosed scope boundary (no live command-spawning verifier this
    // pass; claim_level from CLAIMS_BOUNDED is the only signal folded in).

    require_transition(
        ReleaseLifecycleState::VerifierLive,
        ReleaseLifecycleState::DocsRendered,
    )?;
    // DOCS_RENDERED
    let docs = render_docs(
        ReleaseLifecycleState::ReleaseAdmitted,
        claim_level,
        &status_facts,
        &dependencies,
    )?;

    require_transition(
        ReleaseLifecycleState::DocsRendered,
        ReleaseLifecycleState::ReleaseAdmitted,
    )?;
    // RELEASE_ADMITTED, gated by the L7 atomic idempotency + correlation gate
    let content_hash = compute_receipt_hash(
        ReleaseLifecycleState::ReleaseAdmitted,
        claim_level,
        &status_facts,
        &dependencies,
        &mermaid,
        &docs,
    );
    let is_replay = receipt_head.admit_or_replay(
        input.correlation_id,
        &content_hash,
        ReleaseLifecycleState::ReleaseAdmitted,
        claim_level,
    )?;

    Ok((
        ReleaseReceipt {
            lifecycle_state: ReleaseLifecycleState::ReleaseAdmitted,
            claim_level,
            content_hash,
            mermaid,
            docs,
        },
        is_replay,
    ))
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // -- L5 catalog crosschecks --

    #[test]
    fn lifecycle_catalog_states_match_enum() {
        assert_eq!(LIFECYCLE_STATES.len(), ALL_STATES.len());
        for entry in LIFECYCLE_STATES {
            let state = ReleaseLifecycleState::from_atlas_name(entry.name).unwrap_or_else(|| {
                panic!("catalog name `{}` has no matching enum variant", entry.name)
            });
            assert_eq!(state.atlas_name(), entry.name);
        }
        for state in ALL_STATES {
            assert!(
                LIFECYCLE_STATES
                    .iter()
                    .any(|e| e.name == state.atlas_name()),
                "enum variant `{:?}` has no matching catalog entry",
                state
            );
        }
    }

    #[test]
    fn lifecycle_transitions_match_atlas_edges() {
        // Locks this crate's generated table to the exact 9 edges declared
        // in v26.7.12_mermaid_atlas/families/F30_ggen-release-state.md's
        // L5 stateDiagram-v2, read and transcribed by hand this session.
        let expected: &[(&str, &str, &str)] = &[
            (
                "OBSERVATIONS_ADMITTED",
                "STATUS_CONSTRUCTED",
                "lawful transition",
            ),
            (
                "STATUS_CONSTRUCTED",
                "DEPENDENCIES_DERIVED",
                "lawful transition",
            ),
            ("STATUS_CONSTRUCTED", "REFUSED", "invalid"),
            (
                "DEPENDENCIES_DERIVED",
                "CLAIMS_BOUNDED",
                "lawful transition",
            ),
            ("CLAIMS_BOUNDED", "DIAGRAMS_PROJECTED", "lawful transition"),
            ("DIAGRAMS_PROJECTED", "VERIFIER_LIVE", "lawful transition"),
            (
                "DIAGRAMS_PROJECTED",
                "REFUSED",
                "authority or conformance failure",
            ),
            ("VERIFIER_LIVE", "DOCS_RENDERED", "lawful transition"),
            ("DOCS_RENDERED", "RELEASE_ADMITTED", "lawful transition"),
        ];
        assert_eq!(LIFECYCLE_TRANSITIONS.len(), expected.len());
        for (t, (from, to, label)) in LIFECYCLE_TRANSITIONS.iter().zip(expected.iter()) {
            assert_eq!((t.from, t.to, t.label), (*from, *to, *label));
        }
    }

    #[test]
    fn can_transition_to_rejects_illegal_jump() {
        assert!(!ReleaseLifecycleState::ObservationsAdmitted
            .can_transition_to(ReleaseLifecycleState::ReleaseAdmitted));
        assert!(ReleaseLifecycleState::ObservationsAdmitted
            .can_transition_to(ReleaseLifecycleState::StatusConstructed));
        let err = require_transition(
            ReleaseLifecycleState::ObservationsAdmitted,
            ReleaseLifecycleState::ReleaseAdmitted,
        )
        .unwrap_err();
        assert!(matches!(
            err,
            ReleaseAdmissionRefused::UnauthorizedTransition { .. }
        ));
    }

    // -- Project State RDF / Status CONSTRUCT / Dependency SPARQL --

    #[test]
    fn admit_observations_rejects_malformed_turtle() {
        let graph = ProjectStateGraph::new().unwrap();
        let err = graph
            .admit_observations("this is not { valid turtle @@@")
            .unwrap_err();
        assert!(matches!(
            err,
            ReleaseAdmissionRefused::ObservationGraphMalformed { .. }
        ));
    }

    const TEST_TURTLE_PREFIX: &str = r#"
@prefix mfwrel: <http://seanchatmangpt.github.io/praxis/multifractal-workflow/release-state#> .
@prefix ex: <http://example.org/f30-test#> .
"#;

    #[test]
    fn construct_status_derives_alive_blocked_unverified() {
        let graph = ProjectStateGraph::new().unwrap();
        let turtle = format!(
            r#"{TEST_TURTLE_PREFIX}
ex:T1 a mfwrel:Ticket ; mfwrel:id "T1" ; mfwrel:hasObservation ex:Obs1 .
ex:Obs1 mfwrel:observationResult "PASS" .

ex:T2 a mfwrel:Ticket ; mfwrel:id "T2" ; mfwrel:hasObservation ex:Obs2 .
ex:Obs2 mfwrel:observationResult "FAIL" .

ex:T3 a mfwrel:Ticket ; mfwrel:id "T3" .
"#
        );
        graph.admit_observations(&turtle).unwrap();
        let facts = graph.construct_status().unwrap();
        assert_eq!(facts.len(), 3);
        let status_of = |ticket: &str| {
            facts
                .iter()
                .find(|f| f.ticket == ticket)
                .map(|f| f.status.as_str())
        };
        assert_eq!(status_of("T1"), Some("ALIVE"));
        assert_eq!(status_of("T2"), Some("BLOCKED"));
        assert_eq!(status_of("T3"), Some("UNVERIFIED"));
    }

    #[test]
    fn construct_status_fails_closed_on_wrong_result_shape() {
        // A SELECT result fed into the CONSTRUCT parser must refuse, not
        // silently coerce.
        let mut rows = Vec::new();
        rows.push(std::collections::BTreeMap::new());
        let err = parse_status_construct_result(EngineQueryResults::Solutions(rows)).unwrap_err();
        assert!(matches!(
            err,
            ReleaseAdmissionRefused::StatusConstructMalformed { .. }
        ));
    }

    #[test]
    fn dependency_select_fails_closed_on_wrong_result_shape() {
        let err = parse_dependency_select_result(EngineQueryResults::Boolean(true)).unwrap_err();
        assert!(matches!(
            err,
            ReleaseAdmissionRefused::DependencySelectMalformed { .. }
        ));
    }

    #[test]
    fn derive_dependencies_transitive_chain() {
        let graph = ProjectStateGraph::new().unwrap();
        let turtle = format!(
            r#"{TEST_TURTLE_PREFIX}
ex:A a mfwrel:Ticket ; mfwrel:id "A" ; mfwrel:dependsOn ex:B .
ex:B a mfwrel:Ticket ; mfwrel:id "B" ; mfwrel:dependsOn ex:C .
ex:C a mfwrel:Ticket ; mfwrel:id "C" .
"#
        );
        graph.admit_observations(&turtle).unwrap();
        let edges = graph.derive_dependencies().unwrap();
        let pairs: Vec<(&str, &str)> = edges
            .iter()
            .map(|e| (e.ticket.as_str(), e.depends_on.as_str()))
            .collect();
        assert_eq!(pairs, vec![("A", "B"), ("A", "C"), ("B", "C")]);
    }

    // -- Claim Ceiling Query --

    #[test]
    fn bound_claim_requires_all_five_for_alive() {
        let all_true = ClaimEvidence {
            source_and_graph_evidence: true,
            unit_and_negative_fixtures: true,
            production_reachability_trace: true,
            chaos_and_recovery_evidence: true,
            receipt_and_replay_equivalence: true,
        };
        assert_eq!(bound_claim(&all_true), ClaimLevel::Alive);

        let missing_replay = ClaimEvidence {
            receipt_and_replay_equivalence: false,
            ..all_true
        };
        assert_eq!(bound_claim(&missing_replay), ClaimLevel::Partial);

        let no_evidence = ClaimEvidence::default();
        assert_eq!(bound_claim(&no_evidence), ClaimLevel::Unverified);

        let evidence_no_tests = ClaimEvidence {
            source_and_graph_evidence: true,
            unit_and_negative_fixtures: false,
            ..ClaimEvidence::default()
        };
        assert_eq!(bound_claim(&evidence_no_tests), ClaimLevel::Unverified);
    }

    #[test]
    fn verifier_aggregate_ceiling_is_worst_field_order_independent() {
        let f_alive = VerifierField {
            name: "a_field",
            status: ClaimLevel::Alive,
            detail: String::new(),
        };
        let f_blocked = VerifierField {
            name: "b_field",
            status: ClaimLevel::Blocked,
            detail: String::new(),
        };
        let f_partial = VerifierField {
            name: "c_field",
            status: ClaimLevel::Partial,
            detail: String::new(),
        };

        let agg1 = VerifierAggregate {
            fields: vec![f_alive.clone(), f_blocked.clone(), f_partial.clone()],
        };
        let agg2 = VerifierAggregate {
            fields: vec![f_partial, f_blocked, f_alive],
        };
        assert_eq!(agg1.ceiling(), ClaimLevel::Blocked);
        assert_eq!(agg2.ceiling(), ClaimLevel::Blocked);

        assert_eq!(
            VerifierAggregate::default().ceiling(),
            ClaimLevel::Unverified
        );
    }

    // -- Mermaid Atlas Projector / Tera Renderers --

    #[test]
    fn mermaid_projector_contains_every_state_and_edge() {
        let out = project_mermaid(ReleaseLifecycleState::DiagramsProjected, None);
        assert!(out.starts_with("stateDiagram-v2\n"));
        for state in ALL_STATES {
            assert!(
                out.contains(state.atlas_name()),
                "missing state {}",
                state.atlas_name()
            );
        }
        assert!(out.contains("STATUS_CONSTRUCTED --> REFUSED: invalid"));
        assert!(out.contains("current state"));
    }

    #[test]
    fn mermaid_projector_notes_refusal_when_present() {
        let refusal = ReleaseAdmissionRefused::StaleProjectState {
            declared: "aa".to_string(),
            live: "bb".to_string(),
        };
        let out = project_mermaid(ReleaseLifecycleState::DiagramsProjected, Some(&refusal));
        assert!(out.contains("note right of REFUSED"));
    }

    #[test]
    fn render_docs_prints_only_precomputed_facts() {
        let status_facts = vec![StatusFact {
            ticket: "T1".to_string(),
            status: "ALIVE".to_string(),
        }];
        let dependencies = vec![DependencyEdge {
            ticket: "T1".to_string(),
            depends_on: "T0".to_string(),
        }];
        let docs = render_docs(
            ReleaseLifecycleState::ReleaseAdmitted,
            ClaimLevel::Partial,
            &status_facts,
            &dependencies,
        )
        .unwrap();
        assert_eq!(docs.len(), 1);
        assert_eq!(docs[0].name, "RELEASE_STATUS.md");
        assert!(docs[0].content.contains("T1: ALIVE"));
        assert!(docs[0].content.contains("T1 depends on T0"));
        assert!(docs[0].content.contains("Claim ceiling: PARTIAL"));
        // Never Alive in the rendered doc unless the caller's already-
        // computed claim_level said so -- Tera only printed what it was given.
        assert!(!docs[0].content.contains("Claim ceiling: ALIVE"));
    }

    // -- L7 idempotency / correlation / restart recovery --

    #[test]
    fn receipt_head_duplicate_event_replays_without_recompute() {
        let mut head = ReceiptHead::in_memory();
        let is_replay_1 = head
            .admit_or_replay(
                "corr-1",
                "hash-a",
                ReleaseLifecycleState::ReleaseAdmitted,
                ClaimLevel::Alive,
            )
            .unwrap();
        assert!(!is_replay_1);
        let is_replay_2 = head
            .admit_or_replay(
                "corr-1",
                "hash-a",
                ReleaseLifecycleState::ReleaseAdmitted,
                ClaimLevel::Alive,
            )
            .unwrap();
        assert!(is_replay_2);
    }

    #[test]
    fn receipt_head_concurrent_drift_refuses() {
        let mut head = ReceiptHead::in_memory();
        head.admit_or_replay(
            "corr-1",
            "hash-a",
            ReleaseLifecycleState::ReleaseAdmitted,
            ClaimLevel::Alive,
        )
        .unwrap();
        let err = head
            .admit_or_replay(
                "corr-1",
                "hash-b",
                ReleaseLifecycleState::ReleaseAdmitted,
                ClaimLevel::Alive,
            )
            .unwrap_err();
        assert!(matches!(
            err,
            ReleaseAdmissionRefused::ConcurrentDrift { .. }
        ));
    }

    #[test]
    fn receipt_head_survives_restart() {
        let dir = std::env::temp_dir().join(format!(
            "f30-receipt-head-test-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_nanos())
                .unwrap_or(0)
        ));
        std::fs::create_dir_all(&dir).unwrap();
        let journal_path = dir.join("receipt-head.jsonl");

        {
            let mut head = ReceiptHead::open(&journal_path).unwrap();
            let is_replay = head
                .admit_or_replay(
                    "corr-restart",
                    "hash-restart",
                    ReleaseLifecycleState::ReleaseAdmitted,
                    ClaimLevel::Alive,
                )
                .unwrap();
            assert!(!is_replay);
        } // `head` dropped here -- simulates process/engine restart.

        {
            let mut head = ReceiptHead::open(&journal_path).unwrap();
            let is_replay = head
                .admit_or_replay(
                    "corr-restart",
                    "hash-restart",
                    ReleaseLifecycleState::ReleaseAdmitted,
                    ClaimLevel::Alive,
                )
                .unwrap();
            assert!(
                is_replay,
                "a fresh ReceiptHead::open on the same path must recognize the prior admission"
            );
        }

        let _ = std::fs::remove_dir_all(&dir);
    }

    // -- Release Gate end to end --

    fn happy_path_input(correlation_id: &'static str) -> String {
        format!(
            r#"{TEST_TURTLE_PREFIX}
ex:T1 a mfwrel:Ticket ; mfwrel:id "T1" ; mfwrel:hasObservation ex:Obs1 .
ex:Obs1 mfwrel:observationResult "PASS" .
ex:T1 mfwrel:dependsOn ex:T0 .
ex:T0 a mfwrel:Ticket ; mfwrel:id "T0" .
"#,
        ) + correlation_id.trim_start_matches("unused-") // no-op, keeps signature simple
    }

    #[test]
    fn admit_release_end_to_end_happy_path_is_deterministic_and_idempotent() {
        let turtle = happy_path_input("");
        let evidence = ClaimEvidence {
            source_and_graph_evidence: true,
            unit_and_negative_fixtures: true,
            production_reachability_trace: false,
            chaos_and_recovery_evidence: false,
            receipt_and_replay_equivalence: false,
        };
        let mut head = ReceiptHead::in_memory();

        let input1 = ReleaseAdmissionInput {
            observation_turtle: &turtle,
            claim_evidence: evidence,
            correlation_id: "release-corr-1",
            expected_state_hash: None,
        };
        let (receipt1, replay1) = admit_release(&input1, &mut head).unwrap();
        assert!(!replay1);
        assert_eq!(
            receipt1.lifecycle_state,
            ReleaseLifecycleState::ReleaseAdmitted
        );
        assert_eq!(receipt1.claim_level, ClaimLevel::Partial);

        // Re-admitting the identical input under the same correlation id
        // must be recognized as a duplicate event (L7) and must produce a
        // byte-identical content hash (determinism, repo invariant #5).
        let input2 = ReleaseAdmissionInput {
            observation_turtle: &turtle,
            claim_evidence: evidence,
            correlation_id: "release-corr-1",
            expected_state_hash: None,
        };
        let (receipt2, replay2) = admit_release(&input2, &mut head).unwrap();
        assert!(replay2);
        assert_eq!(receipt1.content_hash, receipt2.content_hash);
    }

    #[test]
    fn admit_release_stale_project_state_refuses() {
        let turtle = happy_path_input("");
        let evidence = ClaimEvidence::default();
        let mut head = ReceiptHead::in_memory();
        let bogus_hash = [0xAAu8; 32];
        let input = ReleaseAdmissionInput {
            observation_turtle: &turtle,
            claim_evidence: evidence,
            correlation_id: "release-corr-stale",
            expected_state_hash: Some(bogus_hash),
        };
        let err = admit_release(&input, &mut head).unwrap_err();
        assert!(matches!(
            err,
            ReleaseAdmissionRefused::StaleProjectState { .. }
        ));
    }

    #[test]
    fn admit_release_malformed_observations_refuses_before_any_state() {
        let evidence = ClaimEvidence::default();
        let mut head = ReceiptHead::in_memory();
        let input = ReleaseAdmissionInput {
            observation_turtle: "not turtle at all {{{",
            claim_evidence: evidence,
            correlation_id: "release-corr-malformed",
            expected_state_hash: None,
        };
        let err = admit_release(&input, &mut head).unwrap_err();
        assert!(matches!(
            err,
            ReleaseAdmissionRefused::ObservationGraphMalformed { .. }
        ));
    }
}
