//! Generated by ggen from packs/chatman-engine-pack/ontology.ttl. Do not edit.
//!
//! Harness: https://praxis.chatman.io/ontology/ceng#HooksHarness
//! Fixture schema: crates/praxis-graphlaw/tests/chatman_engine_acceptance/schemas/hooks_fixture.schema.json

use praxis_graphlaw::chatman::Refusal;

#[path = "chatman_engine_acceptance/harness/mod.rs"]
mod harness;

#[test]
fn acceptance_accept_deterministic_operator_without_receipt() {
    let fixture = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/chatman_engine_acceptance/fixtures/hooks/deterministic_operator_without_receipt.json"
    );
    // `run_fixture` takes `&Path`; the fixture path here is a `&'static str`
    // (from `concat!`), which does not coerce to `&Path` at a call site, so
    // it is wrapped explicitly.
    let result = harness::run_fixture(std::path::Path::new(fixture));
    // `run_fixture` returns `Result<harness::AdmittedOutcome, Refusal>`, not
    // `Result<&str, Refusal>`, so the acceptance behavior tag
    // (`deterministic_operator_admitted`) is documentation carried by the
    // fixture, not a literal engine return value to pattern-match via
    // `as_deref()`. Only admission itself is asserted here.
    assert!(
        result.is_ok(),
        "acceptance case Accept_DeterministicOperatorWithoutReceipt must be accepted (expected behavior: \
         `deterministic_operator_admitted`), got {result:?}"
    );
}

#[test]
fn acceptance_accept_hook_pattern_admitted() {
    let fixture = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/chatman_engine_acceptance/fixtures/hooks/hook_pattern_admitted.json"
    );
    // `run_fixture` takes `&Path`; the fixture path here is a `&'static str`
    // (from `concat!`), which does not coerce to `&Path` at a call site, so
    // it is wrapped explicitly.
    let result = harness::run_fixture(std::path::Path::new(fixture));
    // `run_fixture` returns `Result<harness::AdmittedOutcome, Refusal>`, not
    // `Result<&str, Refusal>`, so the acceptance behavior tag
    // (`hook_pattern_admitted`) is documentation carried by the
    // fixture, not a literal engine return value to pattern-match via
    // `as_deref()`. Only admission itself is asserted here.
    assert!(
        result.is_ok(),
        "acceptance case Accept_HookPatternAdmitted must be accepted (expected behavior: \
         `hook_pattern_admitted`), got {result:?}"
    );
}


#[test]
fn falsification_falsify_hook_pattern_not_admitted() {
    let fixture = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/chatman_engine_acceptance/fixtures/hooks/hook_pattern_not_admitted.json"
    );
    let result = harness::run_fixture(std::path::Path::new(fixture));
    assert!(
        matches!(result, Err(Refusal::HookPatternNotAdmitted(_))),
        "mutation Register a hook whose trigger pattern uses a predicate outside the admitted set. must refuse with Refusal::HookPatternNotAdmitted, got {result:?}"
    );
}

#[test]
fn falsification_falsify_nondeterministic_operator_requires_receipt() {
    let fixture = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/chatman_engine_acceptance/fixtures/hooks/nondeterministic_operator_requires_receipt.json"
    );
    let result = harness::run_fixture(std::path::Path::new(fixture));
    assert!(
        matches!(result, Err(Refusal::NondeterministicOperatorRequiresReceipt(_))),
        "mutation Invoke a nondeterministic operator without attaching the required receipt. must refuse with Refusal::NondeterministicOperatorRequiresReceipt, got {result:?}"
    );
}

