//! Generated by ggen from packs/chatman-engine-pack/ontology.ttl. Do not edit.
//!
//! Harness: https://praxis.chatman.io/ontology/ceng#ReceiptsHarness
//! Fixture schema: crates/praxis-graphlaw/tests/chatman_engine_acceptance/schemas/receipts_fixture.schema.json

use praxis_graphlaw::chatman::Refusal;

#[path = "chatman_engine_acceptance/harness/mod.rs"]
mod harness;

#[test]
fn acceptance_accept_boundary_request_carries_receipt() {
    let fixture = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/chatman_engine_acceptance/fixtures/receipts/boundary_request_carries_receipt.json"
    );
    // `run_fixture` takes `&Path`; the fixture path here is a `&'static str`
    // (from `concat!`), which does not coerce to `&Path` at a call site, so
    // it is wrapped explicitly.
    let result = harness::run_fixture(std::path::Path::new(fixture));
    // `run_fixture` returns `Result<harness::AdmittedOutcome, Refusal>`, not
    // `Result<&str, Refusal>`, so the acceptance behavior tag
    // (`boundary_receipt_present`) is documentation carried by the
    // fixture, not a literal engine return value to pattern-match via
    // `as_deref()`. Only admission itself is asserted here.
    assert!(
        result.is_ok(),
        "acceptance case Accept_BoundaryRequestCarriesReceipt must be accepted (expected behavior: \
         `boundary_receipt_present`), got {result:?}"
    );
}

#[test]
fn acceptance_accept_profile_hash_matches() {
    let fixture = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/chatman_engine_acceptance/fixtures/receipts/profile_hash_matches.json"
    );
    // `run_fixture` takes `&Path`; the fixture path here is a `&'static str`
    // (from `concat!`), which does not coerce to `&Path` at a call site, so
    // it is wrapped explicitly.
    let result = harness::run_fixture(std::path::Path::new(fixture));
    // `run_fixture` returns `Result<harness::AdmittedOutcome, Refusal>`, not
    // `Result<&str, Refusal>`, so the acceptance behavior tag
    // (`profile_hash_verified`) is documentation carried by the
    // fixture, not a literal engine return value to pattern-match via
    // `as_deref()`. Only admission itself is asserted here.
    assert!(
        result.is_ok(),
        "acceptance case Accept_ProfileHashMatches must be accepted (expected behavior: \
         `profile_hash_verified`), got {result:?}"
    );
}

#[test]
fn acceptance_accept_projection_hash_matches() {
    let fixture = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/chatman_engine_acceptance/fixtures/receipts/projection_hash_matches.json"
    );
    // `run_fixture` takes `&Path`; the fixture path here is a `&'static str`
    // (from `concat!`), which does not coerce to `&Path` at a call site, so
    // it is wrapped explicitly.
    let result = harness::run_fixture(std::path::Path::new(fixture));
    // `run_fixture` returns `Result<harness::AdmittedOutcome, Refusal>`, not
    // `Result<&str, Refusal>`, so the acceptance behavior tag
    // (`projection_hash_verified`) is documentation carried by the
    // fixture, not a literal engine return value to pattern-match via
    // `as_deref()`. Only admission itself is asserted here.
    assert!(
        result.is_ok(),
        "acceptance case Accept_ProjectionHashMatches must be accepted (expected behavior: \
         `projection_hash_verified`), got {result:?}"
    );
}

#[test]
fn falsification_falsify_boundary_request_missing_receipt() {
    let fixture = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/chatman_engine_acceptance/fixtures/receipts/boundary_request_missing_receipt.json"
    );
    let result = harness::run_fixture(std::path::Path::new(fixture));
    assert!(
        matches!(result, Err(Refusal::BoundaryRequestMissingReceipt(_))),
        "mutation Strip the receipt field from an otherwise well-formed boundary request. must refuse with Refusal::BoundaryRequestMissingReceipt, got {result:?}"
    );
}

#[test]
fn falsification_falsify_profile_hash_mismatch() {
    let fixture = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/chatman_engine_acceptance/fixtures/receipts/profile_hash_mismatch.json"
    );
    let result = harness::run_fixture(std::path::Path::new(fixture));
    assert!(
        matches!(result, Err(Refusal::ProfileHashMismatch(_))),
        "mutation Substitute a different profile document behind an unchanged profile hash claim. must refuse with Refusal::ProfileHashMismatch, got {result:?}"
    );
}

#[test]
fn falsification_falsify_projection_hash_mismatch() {
    let fixture = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/chatman_engine_acceptance/fixtures/receipts/projection_hash_mismatch.json"
    );
    let result = harness::run_fixture(std::path::Path::new(fixture));
    assert!(
        matches!(result, Err(Refusal::ProjectionHashMismatch(_))),
        "mutation Flip one byte of the projection payload after its hash was recorded. must refuse with Refusal::ProjectionHashMismatch, got {result:?}"
    );
}

/// Deterministic OCEL evidence seal: replays every fixture of this suite
/// sequentially in sorted order on one thread and seals the suite's
/// `.cargo-cicd/ocel/chatman/<suite>.{ocel,receipt}.json` exactly once —
/// the only OCEL emission path (per-case tests above are assertion-only,
/// because their parallel interleaving would make event order racy).
#[test]
fn zz_ocel_evidence_sealed() {
    harness::seal_suite_evidence(&[
        "fixtures/receipts/boundary_request_carries_receipt.json",
        "fixtures/receipts/boundary_request_missing_receipt.json",
        "fixtures/receipts/profile_hash_matches.json",
        "fixtures/receipts/profile_hash_mismatch.json",
        "fixtures/receipts/projection_hash_matches.json",
        "fixtures/receipts/projection_hash_mismatch.json",
    ]);
}
