//! Genesis Creation Week: many admitted PDDL Turtle planning artifacts
//! become one POWL v2 Turtle workflow artifact.
//!
//! Chatman Equation framing: `A = μ(O*)` where `O*` is God's plan admitted
//! as fourteen per-day PDDL Turtle artifacts (`day-0i.domain.ttl` /
//! `day-0i.problem.ttl`), `μ` is the lawful projection from admitted
//! planning artifacts into a workflow artifact, and `A` is the exported
//! `creation-week.powl.ttl`:
//! `creation-week.powl.ttl = μ({*.domain.ttl, *.problem.ttl}*)`.
//! Days are planning artifacts, not workflows — the seven-day plan becomes
//! the workflow. God's plan is the modeled source; any CLI in front of this
//! pipeline is only the human artifact handle. Formal process example using
//! Genesis as a recognizable planning-to-workflow narrative — it argues no
//! doctrine and makes no historical or scientific claim.
//!
//! Artifact boundary: Turtle/PDDL is imported from committed `.ttl` files
//! (`tests/pddl_to_powl/genesis/`) and exported to one generated `.ttl` file
//! (`target/chatman/powl/creation-week.powl.ttl`); no Turtle or PDDL is
//! embedded in Rust strings; the POWL output is generated by the pipeline,
//! never hand-authored.
//!
//! Many-to-one composition: each day fragment is loaded as its own snapshot;
//! `ChatmanEngine::plan_tape_for_snapshots` merges the parsed fragments
//! structurally (shared domain name `creation-week`, deduplicated unions,
//! conjunctive goal across every day's problem — so every problem artifact
//! is load-bearing) and plans ONCE: one combined seven-day plan, projected
//! into one linear `Powl::PartialOrder` (the projection supports linear
//! plans only; no branching/loops/choices are claimed).

use chicago_tdd_tools::prelude::*;

use std::fs;
use std::path::PathBuf;

use oxigraph::io::{RdfFormat, RdfParser};
use oxigraph::store::Store;
use powl2_decompose::Powl;

use bcinr_pddl::Pddl8Tape;
use praxis_graphlaw::chatman::abi::{GraphSnapshotId, ProfileId, Refusal};
use praxis_graphlaw::chatman::engine::{AdmissionSpec, ChatmanEngine, EngineProfile};
use praxis_graphlaw::chatman::powl_projection::{powl_to_turtle, project_pddl_tape_to_powl};
use praxis_graphlaw::chatman::router::ProfileGates;
use praxis_graphlaw::chatman::triple8::ProfileSymbolTable;

const PROFILE_IRI: &str = "profile:genesis-week-projection-test";
/// Provenance target for `powl2:derivedFrom`: the combined seven-day plan.
const PLAN_SOURCE_IRI: &str = "urn:chatman:plan:genesis-week";
/// Base IRI under which the serializer mints deterministic structural IRIs.
const BASE_IRI: &str = "urn:chatman:powl:creation-week";
const EXPORT_FILE: &str = "creation-week.powl.ttl";

/// The seven day artifact stems, in day order; each contributes a
/// `<stem>.domain.ttl` and `<stem>.problem.ttl` planning fragment.
const DAYS: [&str; 7] = [
    "day-01-light",
    "day-02-expanse",
    "day-03-land-vegetation",
    "day-04-luminaries-time",
    "day-05-sea-sky-life",
    "day-06-land-life-humanity",
    "day-07-rest-sanctification",
];
/// Source-sensitivity variant of the day-03 domain fragment
/// (bring-forth-vegetation renamed to bring-forth-plants).
const DAY_03_VARIANT: &str = "day-03-land-vegetation.domain.variant.ttl";

/// The 16 expected creation steps, in plan order across the week.
const EXPECTED_STEPS: [&str; 16] = [
    "begin-creation",
    "create-light",
    "separate-light-darkness",
    "form-expanse",
    "separate-waters",
    "gather-waters",
    "reveal-land",
    "bring-forth-vegetation",
    "appoint-luminaries",
    "fill-waters",
    "fill-sky",
    "create-land-animals",
    "create-humanity",
    "complete-work",
    "bless-seventh-day",
    "rest",
];
/// C(16,2): closed order-pair count for the 16-step linear chain.
const EXPECTED_ORDER_PAIRS: usize = 120;

fn genesis_fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("pddl_to_powl")
        .join("genesis")
}

/// Repo-local generated-artifact directory (`<repo>/target/chatman/powl`).
fn powl_output_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("target")
        .join("chatman")
        .join("powl")
}

fn build_profile() -> Result<EngineProfile, Refusal> {
    let profile_id = ProfileId::new(PROFILE_IRI);
    let gates = ProfileGates::new(profile_id.clone(), ProfileGates::DEFAULT_ENABLED_MASK, 0, 8)?;
    let symbol_table = ProfileSymbolTable::build(
        profile_id,
        vec![
            "<urn:chatman:t0>".to_string(),
            "<urn:chatman:t1>".to_string(),
        ],
    )?;
    Ok(EngineProfile {
        gates,
        symbol_table,
        admission: AdmissionSpec {
            constraint_names: vec!["c0".to_string()],
            required_mask: 0,
            forbidden_mask: 0,
            set_on_admit: 0,
            clear_on_admit: 0,
        },
        breed_permits: Vec::new(),
    })
}

/// The full canonical artifact set: every day's domain and problem fragment,
/// in day order, with an optional substitution.
fn canonical_artifact_set(substitute: Option<(&str, &str)>) -> Vec<String> {
    let mut files = Vec::with_capacity(DAYS.len() * 2);
    for day in DAYS {
        for suffix in ["domain", "problem"] {
            let default_name = format!("{day}.{suffix}.ttl");
            files.push(match substitute {
                Some((from, to)) if from == default_name => to.to_string(),
                _ => default_name,
            });
        }
    }
    files
}

/// Imports the artifact set from disk (the only route Turtle enters this
/// test), loads each file as its own snapshot in one engine, prints the
/// `IMPORTED_PDDL_TTL_PATHS=` marker, and generates the ONE combined
/// seven-day plan via the engine's many-to-one side-door, printing
/// `GENERATED_PLAN_ID=` (BLAKE3 over the ordered plan-step labels).
fn generate_combined_plan(substitute: Option<(&str, &str)>) -> Result<Pddl8Tape, Refusal> {
    let mut engine = ChatmanEngine::in_memory(build_profile()?)?;
    let file_names = canonical_artifact_set(substitute);
    let mut snapshot_ids = Vec::with_capacity(file_names.len());
    let mut paths = Vec::with_capacity(file_names.len());
    for file_name in &file_names {
        let path = genesis_fixture_dir().join(file_name);
        let path = path
            .canonicalize()
            .unwrap_or_else(|e| panic!("artifact {file_name} must canonicalize: {e}"));
        let turtle = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("artifact {file_name} must be readable: {e}"));
        let snapshot_id = GraphSnapshotId::new(format!("urn:chatman:snapshot:genesis:{file_name}"));
        engine.load_snapshot(&snapshot_id, &turtle)?;
        snapshot_ids.push(snapshot_id);
        paths.push(path.display().to_string());
    }
    println!("IMPORTED_PDDL_TTL_PATHS={}", paths.join(","));
    let tape = engine.plan_tape_for_snapshots(&snapshot_ids)?;
    let labels: Vec<&str> = tape.ops.iter().map(|op| op.label.as_str()).collect();
    let plan_id = blake3::hash(labels.join("\n").as_bytes()).to_hex();
    println!("GENERATED_PLAN_ID=blake3:{plan_id}");
    Ok(tape)
}

/// Exports the generated POWL Turtle artifact and prints its canonical
/// absolute path with the `GENERATED_POWL_TTL_PATH=` marker.
fn export_powl(file_name: &str, turtle: &str) -> PathBuf {
    let dir = powl_output_dir();
    fs::create_dir_all(&dir).expect("POWL output directory must be creatable");
    let file_path = dir.join(file_name);
    fs::write(&file_path, turtle).expect("exported POWL Turtle must be writable");
    let path = file_path
        .canonicalize()
        .expect("exported POWL Turtle path must canonicalize");
    println!("GENERATED_POWL_TTL_PATH={}", path.display());
    path
}

test!(
    genesis_artifact_set_generates_one_plan_and_one_partial_order,
    {
        // Arrange + Act: import all fourteen day fragments, generate ONE
        // combined seven-day plan, and project it to POWL.
        let tape = generate_combined_plan(None)?;
        assert_eq!(
            tape.ops.len(),
            EXPECTED_STEPS.len(),
            "the seven day fragments must merge into one 16-step creation-week plan"
        );
        let model = project_pddl_tape_to_powl(&tape)?;

        // Assert: one PartialOrder, 16 leaves, C(16,2)=120 closed order pairs,
        // leaf i carrying the expected creation step in order.
        match model {
            Powl::PartialOrder { children, order } => {
                assert_eq!(
                    children.len(),
                    EXPECTED_STEPS.len(),
                    "expected one POWL child per creation step"
                );
                assert_eq!(
                    order.len(),
                    EXPECTED_ORDER_PAIRS,
                    "expected the full transitively-closed chain order (C(16,2) = 120)"
                );
                for (i, child) in children.iter().enumerate() {
                    match child {
                        Powl::Leaf(Some(label)) => {
                            assert!(
                                label.contains(EXPECTED_STEPS[i]),
                                "leaf {i} label {label:?} must carry creation step {:?}",
                                EXPECTED_STEPS[i]
                            );
                        }
                        other => {
                            panic!("expected Powl::Leaf(Some(_)) for every child, got {other:?}")
                        }
                    }
                }
            }
            other => panic!("expected Powl::PartialOrder, got {other:?}"),
        }

        Ok::<(), Refusal>(())
    }
);

test!(creation_week_powl_exports_parses_and_is_deterministic, {
    // Arrange: regenerate the combined plan and model.
    let tape = generate_combined_plan(None)?;
    let model = project_pddl_tape_to_powl(&tape)?;

    // Act: serialize twice with provenance pointing at the combined plan,
    // then export the one creation-week workflow artifact.
    let turtle_a = powl_to_turtle(&model, BASE_IRI, Some(PLAN_SOURCE_IRI))?;
    let turtle_b = powl_to_turtle(&model, BASE_IRI, Some(PLAN_SOURCE_IRI))?;
    let exported = export_powl(EXPORT_FILE, &turtle_a);

    // Assert: exported bytes equal the serialized Turtle; serialization is
    // byte-identical across repeated calls; parsing runs on the file content
    // read back from disk.
    let exported_turtle = fs::read_to_string(&exported)
        .expect("exported POWL artifact must be readable back from disk");
    assert_eq!(
        exported_turtle, turtle_a,
        "exported artifact bytes must equal the serialized Turtle"
    );
    assert_eq!(
        turtle_a, turtle_b,
        "powl_to_turtle must produce byte-identical output across repeated calls"
    );

    let store = Store::new().expect("in-memory oxigraph store construction must not fail");
    store
        .load_from_slice(
            RdfParser::from_format(RdfFormat::Turtle),
            exported_turtle.as_bytes(),
        )
        .expect("exported POWL Turtle must parse as valid Turtle");

    // Assert non-vacuity against the *parsed* RDF via SPARQL counts.
    let solution_count = |query: &str| -> usize {
        let prepared = oxigraph::sparql::SparqlEvaluator::new()
            .parse_query(query)
            .expect("test SPARQL query must parse");
        match prepared.on_store(&store).execute() {
            Ok(oxigraph::sparql::QueryResults::Solutions(solutions)) => solutions.count(),
            _ => panic!("SPARQL query must return solutions: {query}"),
        }
    };
    let count_of = |class_iri: &str| -> usize {
        solution_count(&format!(
            "SELECT ?s WHERE {{ ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://truex.io/ontology/powl2#{class_iri}> }}"
        ))
    };
    assert_eq!(count_of("Model"), 1, "exactly one powl2:Model root node");
    assert_eq!(
        count_of("PartialOrder"),
        1,
        "exactly one powl2:PartialOrder — one creation-week workflow, not one per day"
    );
    assert_eq!(
        count_of("ActivityLeaf"),
        EXPECTED_STEPS.len(),
        "exactly one powl2:ActivityLeaf per creation step"
    );
    assert_eq!(
        count_of("ChildBinding"),
        EXPECTED_STEPS.len(),
        "exactly one powl2:ChildBinding per creation step"
    );
    let count_predicate = |pred_iri: &str| -> usize {
        solution_count(&format!(
            "SELECT ?s WHERE {{ ?s <https://truex.io/ontology/powl2#{pred_iri}> ?o }}"
        ))
    };
    assert_eq!(
        count_predicate("precedes"),
        EXPECTED_ORDER_PAIRS,
        "the closed order relation for 16 steps is C(16,2) = 120 precedes triples"
    );
    assert_eq!(
        count_predicate("derivedFrom"),
        1,
        "the root model node carries exactly one powl2:derivedFrom provenance triple"
    );

    // Recognizable creation steps must appear among the parsed labels — the
    // workflow is derived from the plan artifacts, not hand-authored.
    for step in ["create-light", "create-humanity", "rest"] {
        let labelled = solution_count(&format!(
            "SELECT ?s WHERE {{ ?s <https://truex.io/ontology/powl2#activityLabel> ?l . FILTER(CONTAINS(STR(?l), \"{step}\")) }}"
        ));
        assert!(
            labelled >= 1,
            "creation step {step:?} must appear among the parsed activityLabel values"
        );
    }

    Ok::<(), Refusal>(())
});

test!(changing_one_day_artifact_changes_the_powl, {
    // Arrange + Act: the same fourteen-artifact flow, once canonical and
    // once with the day-03 domain fragment substituted by its variant.
    let tape_a = generate_combined_plan(None)?;
    let tape_b =
        generate_combined_plan(Some(("day-03-land-vegetation.domain.ttl", DAY_03_VARIANT)))?;
    let turtle_a = powl_to_turtle(
        &project_pddl_tape_to_powl(&tape_a)?,
        BASE_IRI,
        Some(PLAN_SOURCE_IRI),
    )?;
    let turtle_b = powl_to_turtle(
        &project_pddl_tape_to_powl(&tape_b)?,
        BASE_IRI,
        Some(PLAN_SOURCE_IRI),
    )?;

    // Assert: changing one source artifact changes the generated POWL — a
    // hardcoded canned document would be identical for both inputs.
    assert_ne!(
        turtle_a, turtle_b,
        "substituting one day fragment must change the generated POWL Turtle bytes"
    );
    assert!(
        turtle_a.contains("bring-forth-vegetation") && !turtle_a.contains("bring-forth-plants"),
        "canonical output must carry the canonical day-03 action label"
    );
    assert!(
        turtle_b.contains("bring-forth-plants") && !turtle_b.contains("bring-forth-vegetation"),
        "variant output must carry the variant day-03 action label"
    );

    // Assert: both generated documents parse as valid RDF/Turtle.
    for turtle in [&turtle_a, &turtle_b] {
        let store = Store::new().expect("in-memory oxigraph store construction must not fail");
        store
            .load_from_slice(RdfParser::from_format(RdfFormat::Turtle), turtle.as_bytes())
            .expect("every generated POWL Turtle document must parse as valid Turtle");
    }

    Ok::<(), Refusal>(())
});
