//! Generated by ggen from packs/chatman-engine-pack/ontology.ttl. Do not edit.
//!
//! Harness: https://praxis.chatman.io/ontology/ceng#ReplayHarness
//! Fixture schema: crates/praxis-graphlaw/tests/chatman_engine_acceptance/schemas/replay_fixture.schema.json

use praxis_graphlaw::chatman::Refusal;

#[path = "chatman_engine_acceptance/harness/mod.rs"]
mod harness;

#[test]
fn acceptance_accept_graph_snapshot_replays_byte_identical() {
    let fixture = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/chatman_engine_acceptance/fixtures/replay/graph_snapshot_replays_byte_identical.json"
    );
    // `run_fixture` takes `&Path`; the fixture path here is a `&'static str`
    // (from `concat!`), which does not coerce to `&Path` at a call site, so
    // it is wrapped explicitly.
    let result = harness::run_fixture(std::path::Path::new(fixture));
    // `run_fixture` returns `Result<harness::AdmittedOutcome, Refusal>`, not
    // `Result<&str, Refusal>`, so the acceptance behavior tag
    // (`snapshot_replay_verified`) is documentation carried by the
    // fixture, not a literal engine return value to pattern-match via
    // `as_deref()`. Only admission itself is asserted here.
    assert!(
        result.is_ok(),
        "acceptance case Accept_GraphSnapshotReplaysByteIdentical must be accepted (expected behavior: \
         `snapshot_replay_verified`), got {result:?}"
    );
}

#[test]
fn acceptance_accept_profile_symbol_table_aligned() {
    let fixture = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/chatman_engine_acceptance/fixtures/replay/profile_symbol_table_aligned.json"
    );
    // `run_fixture` takes `&Path`; the fixture path here is a `&'static str`
    // (from `concat!`), which does not coerce to `&Path` at a call site, so
    // it is wrapped explicitly.
    let result = harness::run_fixture(std::path::Path::new(fixture));
    // `run_fixture` returns `Result<harness::AdmittedOutcome, Refusal>`, not
    // `Result<&str, Refusal>`, so the acceptance behavior tag
    // (`symbol_table_aligned`) is documentation carried by the
    // fixture, not a literal engine return value to pattern-match via
    // `as_deref()`. Only admission itself is asserted here.
    assert!(
        result.is_ok(),
        "acceptance case Accept_ProfileSymbolTableAligned must be accepted (expected behavior: \
         `symbol_table_aligned`), got {result:?}"
    );
}

#[test]
fn falsification_falsify_graph_snapshot_mismatch() {
    let fixture = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/chatman_engine_acceptance/fixtures/replay/graph_snapshot_mismatch.json"
    );
    let result = harness::run_fixture(std::path::Path::new(fixture));
    assert!(
        matches!(result, Err(Refusal::GraphSnapshotMismatch(_))),
        "mutation Reorder two quads in the stored snapshot so the replay hash diverges. must refuse with Refusal::GraphSnapshotMismatch, got {result:?}"
    );
}

#[test]
fn falsification_falsify_profile_symbol_table_mismatch() {
    let fixture = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/chatman_engine_acceptance/fixtures/replay/profile_symbol_table_mismatch.json"
    );
    let result = harness::run_fixture(std::path::Path::new(fixture));
    assert!(
        matches!(result, Err(Refusal::ProfileSymbolTableMismatch(_))),
        "mutation Swap two symbol ids in the profile symbol table against the pinned interning. must refuse with Refusal::ProfileSymbolTableMismatch, got {result:?}"
    );
}

/// Deterministic OCEL evidence seal: replays every fixture of this suite
/// sequentially in sorted order on one thread and seals the suite's
/// `.cargo-cicd/ocel/chatman/<suite>.{ocel,receipt}.json` exactly once —
/// the only OCEL emission path (per-case tests above are assertion-only,
/// because their parallel interleaving would make event order racy).
#[test]
fn zz_ocel_evidence_sealed() {
    harness::seal_suite_evidence(&[
        "fixtures/replay/graph_snapshot_mismatch.json",
        "fixtures/replay/graph_snapshot_replays_byte_identical.json",
        "fixtures/replay/profile_symbol_table_aligned.json",
        "fixtures/replay/profile_symbol_table_mismatch.json",
    ]);
}
