//! Generated by ggen from packs/chatman-engine-pack/ontology.ttl. Do not edit.
//!
//! Harness: https://praxis.chatman.io/ontology/ceng#AgentsHarness
//! Fixture schema: crates/praxis-graphlaw/tests/chatman_engine_acceptance/schemas/agents_fixture.schema.json

use praxis_graphlaw::chatman::Refusal;

#[path = "chatman_engine_acceptance/harness/mod.rs"]
mod harness;

#[test]
fn acceptance_accept_agent_acts_within_permits() {
    let fixture = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/chatman_engine_acceptance/fixtures/agents/agent_acts_within_permits.json"
    );
    // `run_fixture` takes `&Path`; the fixture path here is a `&'static str`
    // (from `concat!`), which does not coerce to `&Path` at a call site, so
    // it is wrapped explicitly.
    let result = harness::run_fixture(std::path::Path::new(fixture));
    // `run_fixture` returns `Result<harness::AdmittedOutcome, Refusal>`, not
    // `Result<&str, Refusal>`, so the acceptance behavior tag
    // (`agent_action_permitted`) is documentation carried by the
    // fixture, not a literal engine return value to pattern-match via
    // `as_deref()`. Only admission itself is asserted here.
    assert!(
        result.is_ok(),
        "acceptance case Accept_AgentActsWithinPermits must be accepted (expected behavior: \
         `agent_action_permitted`), got {result:?}"
    );
}

#[test]
fn acceptance_accept_permitted_breed_executes() {
    let fixture = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/chatman_engine_acceptance/fixtures/agents/permitted_breed_executes.json"
    );
    // `run_fixture` takes `&Path`; the fixture path here is a `&'static str`
    // (from `concat!`), which does not coerce to `&Path` at a call site, so
    // it is wrapped explicitly.
    let result = harness::run_fixture(std::path::Path::new(fixture));
    // `run_fixture` returns `Result<harness::AdmittedOutcome, Refusal>`, not
    // `Result<&str, Refusal>`, so the acceptance behavior tag
    // (`breed_execution_permitted`) is documentation carried by the
    // fixture, not a literal engine return value to pattern-match via
    // `as_deref()`. Only admission itself is asserted here.
    assert!(
        result.is_ok(),
        "acceptance case Accept_PermittedBreedExecutes must be accepted (expected behavior: \
         `breed_execution_permitted`), got {result:?}"
    );
}

#[test]
fn acceptance_accept_witness_observes_only() {
    let fixture = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/chatman_engine_acceptance/fixtures/agents/witness_observes_only.json"
    );
    // `run_fixture` takes `&Path`; the fixture path here is a `&'static str`
    // (from `concat!`), which does not coerce to `&Path` at a call site, so
    // it is wrapped explicitly.
    let result = harness::run_fixture(std::path::Path::new(fixture));
    // `run_fixture` returns `Result<harness::AdmittedOutcome, Refusal>`, not
    // `Result<&str, Refusal>`, so the acceptance behavior tag
    // (`witness_observation_recorded`) is documentation carried by the
    // fixture, not a literal engine return value to pattern-match via
    // `as_deref()`. Only admission itself is asserted here.
    assert!(
        result.is_ok(),
        "acceptance case Accept_WitnessObservesOnly must be accepted (expected behavior: \
         `witness_observation_recorded`), got {result:?}"
    );
}

#[test]
fn falsification_falsify_agent_override_denied() {
    let fixture = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/chatman_engine_acceptance/fixtures/agents/agent_override_denied.json"
    );
    let result = harness::run_fixture(std::path::Path::new(fixture));
    assert!(
        matches!(result, Err(Refusal::AgentOverrideDenied(_))),
        "mutation Have the agent claim an override flag on a decision it holds no permit for. must refuse with Refusal::AgentOverrideDenied, got {result:?}"
    );
}

#[test]
fn falsification_falsify_breed_unpermitted() {
    let fixture = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/chatman_engine_acceptance/fixtures/agents/breed_unpermitted.json"
    );
    let result = harness::run_fixture(std::path::Path::new(fixture));
    assert!(
        matches!(result, Err(Refusal::BreedUnpermitted(_))),
        "mutation Dispatch work to an agent breed absent from the permit list. must refuse with Refusal::BreedUnpermitted, got {result:?}"
    );
}

#[test]
fn falsification_falsify_witness_not_authority() {
    let fixture = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/chatman_engine_acceptance/fixtures/agents/witness_not_authority.json"
    );
    let result = harness::run_fixture(std::path::Path::new(fixture));
    assert!(
        matches!(result, Err(Refusal::WitnessNotAuthority(_))),
        "mutation Have a witness role attempt to author an authoritative decision triple. must refuse with Refusal::WitnessNotAuthority, got {result:?}"
    );
}

/// Deterministic OCEL evidence seal: replays every fixture of this suite
/// sequentially in sorted order on one thread and seals the suite's
/// `.cargo-cicd/ocel/chatman/<suite>.{ocel,receipt}.json` exactly once —
/// the only OCEL emission path (per-case tests above are assertion-only,
/// because their parallel interleaving would make event order racy).
#[test]
fn zz_ocel_evidence_sealed() {
    harness::seal_suite_evidence(&[
        "fixtures/agents/agent_acts_within_permits.json",
        "fixtures/agents/agent_override_denied.json",
        "fixtures/agents/breed_unpermitted.json",
        "fixtures/agents/permitted_breed_executes.json",
        "fixtures/agents/witness_not_authority.json",
        "fixtures/agents/witness_observes_only.json",
    ]);
}
