//! Hierarchical (2-level) POWL projection of Joseph's famine-management
//! plan: the same 26-artifact corpus as `chatman_pddl_to_powl_joseph_famine`
//! (kept untouched as the flat regression baseline), but projected via
//! `project_pddl_tape_to_powl_hierarchical` so the ONE combined national
//! plan is grouped into phases by contributing source artifact — a phase
//! being a maximal run of tape-adjacent plan ops whose action schemas were
//! contributed by the same domain fragment. Root is a PartialOrder of
//! per-phase PartialOrders; institutional structure (which artifact
//! contributed which steps) becomes visible workflow nesting, with no new
//! semantic authority beyond the supplied provenance mapping.
//!
//! Artifact boundary: identical to the flat test — Turtle/PDDL is imported
//! from committed `.ttl` files (`tests/pddl_to_powl/joseph/`) and exported
//! to one generated `.ttl` file; no Turtle or PDDL is embedded in Rust
//! strings; the POWL output is generated by the pipeline, never
//! hand-authored.

use chicago_tdd_tools::prelude::*;

use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;

use oxigraph::io::{RdfFormat, RdfParser};
use oxigraph::store::Store;
use powl2_decompose::Powl;

use bcinr_pddl::Pddl8Tape;
use praxis_graphlaw::chatman::abi::{GraphSnapshotId, ProfileId, Refusal};
use praxis_graphlaw::chatman::engine::{AdmissionSpec, ChatmanEngine, EngineProfile};
use praxis_graphlaw::chatman::powl_projection::{
    powl_to_turtle, project_pddl_tape_to_powl_hierarchical,
};
use praxis_graphlaw::chatman::router::ProfileGates;
use praxis_graphlaw::chatman::triple8::ProfileSymbolTable;

const PROFILE_IRI: &str = "profile:joseph-famine-hierarchical-projection-test";
/// Provenance target for `powl2:derivedFrom`: the combined national plan.
const PLAN_SOURCE_IRI: &str = "urn:chatman:plan:joseph-famine";
/// Base IRI under which the serializer mints deterministic structural IRIs.
const BASE_IRI: &str = "urn:chatman:powl:joseph-egypt-famine-management-hierarchical";
const EXPORT_FILE: &str = "joseph-egypt-famine-management.hierarchical.powl.ttl";

/// The thirteen phase artifact stems, in program order; each contributes a
/// `<stem>.domain.ttl` and `<stem>.problem.ttl` planning fragment.
const PHASES: [&str; 13] = [
    "forecast",
    "appointment",
    "abundance-collection",
    "storage-logistics",
    "inventory-control",
    "famine-detection",
    "rationing-policy",
    "grain-distribution",
    "payment-treasury",
    "foreign-buyers",
    "family-arrival",
    "land-livestock-policy",
    "closure-stabilization",
];

/// Which action schemas each phase's domain fragment contributes, in plan
/// order — mirrors the `(:action …)` declarations committed in each
/// `<phase>.domain.ttl` fixture and the 20-step combined plan order proven
/// by the flat baseline test.
const PHASE_ACTIONS: [(&str, &[&str]); 13] = [
    ("forecast", &["receive-forecast", "interpret-forecast"]),
    ("appointment", &["appoint-joseph"]),
    (
        "abundance-collection",
        &["activate-collection-policy", "collect-fifth-of-produce"],
    ),
    ("storage-logistics", &["store-grain-in-cities"]),
    ("inventory-control", &["record-inventory"]),
    ("famine-detection", &["detect-famine"]),
    ("rationing-policy", &["activate-rationing-policy"]),
    (
        "grain-distribution",
        &["open-storehouses", "allocate-grain"],
    ),
    ("payment-treasury", &["receive-payment", "update-treasury"]),
    (
        "foreign-buyers",
        &["register-foreign-buyers", "supply-foreign-buyers"],
    ),
    ("family-arrival", &["receive-family", "provision-family"]),
    ("land-livestock-policy", &["transfer-land-livestock"]),
    (
        "closure-stabilization",
        &["stabilize-famine-response", "close-program"],
    ),
];

/// Total plan steps across all phases (matches the flat baseline's 20).
const EXPECTED_OP_COUNT: usize = 20;
/// C(13,2): closed root-order pair count for the 13-phase linear chain.
const EXPECTED_ROOT_ORDER_PAIRS: usize = 78;
/// Sum over phases of C(k,2): 7 phases of 2 steps contribute 1 pair each.
const EXPECTED_INTRA_PHASE_ORDER_PAIRS: usize = 7;

fn joseph_fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("pddl_to_powl")
        .join("joseph")
}

/// Repo-local generated-artifact directory (`<repo>/target/chatman/powl`).
fn powl_output_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("target")
        .join("chatman")
        .join("powl")
}

/// The snapshot/source IRI for a phase's domain fragment — the artifact
/// that contributed the phase's action schemas.
fn phase_source_iri(phase: &str) -> String {
    format!("urn:chatman:snapshot:joseph:{phase}.domain.ttl")
}

/// Builds the action-schema → source-artifact provenance map from
/// `PHASE_ACTIONS`, mirroring cng's `AdmittedSurface::action_sources`.
fn joseph_action_sources() -> BTreeMap<String, String> {
    let mut sources = BTreeMap::new();
    for (phase, actions) in PHASE_ACTIONS {
        for action in actions {
            sources.insert(action.to_string(), phase_source_iri(phase));
        }
    }
    sources
}

fn build_profile() -> Result<EngineProfile, Refusal> {
    let profile_id = ProfileId::new(PROFILE_IRI);
    let gates = ProfileGates::new(profile_id.clone(), ProfileGates::DEFAULT_ENABLED_MASK, 0, 8)?;
    let symbol_table = ProfileSymbolTable::build(
        profile_id,
        vec![
            "<urn:chatman:t0>".to_string(),
            "<urn:chatman:t1>".to_string(),
        ],
    )?;
    Ok(EngineProfile {
        gates,
        symbol_table,
        admission: AdmissionSpec {
            constraint_names: vec!["c0".to_string()],
            required_mask: 0,
            forbidden_mask: 0,
            set_on_admit: 0,
            clear_on_admit: 0,
        },
        breed_permits: Vec::new(),
    })
}

/// Imports the given fixture artifacts from disk (the only route Turtle
/// enters this test), loads each as its own snapshot in one engine, prints
/// the `IMPORTED_PDDL_TTL_PATHS=` marker, and returns the engine plus the
/// ordered snapshot ids.
fn import_artifacts(
    file_names: &[String],
) -> Result<(ChatmanEngine, Vec<GraphSnapshotId>), Refusal> {
    let mut engine = ChatmanEngine::in_memory(build_profile()?)?;
    let mut snapshot_ids = Vec::with_capacity(file_names.len());
    let mut paths = Vec::with_capacity(file_names.len());
    for file_name in file_names {
        let path = joseph_fixture_dir().join(file_name);
        let path = path
            .canonicalize()
            .unwrap_or_else(|e| panic!("artifact {file_name} must canonicalize: {e}"));
        let turtle = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("artifact {file_name} must be readable: {e}"));
        let snapshot_id = GraphSnapshotId::new(format!("urn:chatman:snapshot:joseph:{file_name}"));
        engine.load_snapshot(&snapshot_id, &turtle)?;
        snapshot_ids.push(snapshot_id);
        paths.push(path.display().to_string());
    }
    println!("IMPORTED_PDDL_TTL_PATHS={}", paths.join(","));
    Ok((engine, snapshot_ids))
}

/// The full canonical artifact set: every phase's domain and problem
/// fragment, in program order.
fn canonical_artifact_set() -> Vec<String> {
    let mut files = Vec::with_capacity(PHASES.len() * 2);
    for phase in PHASES {
        for suffix in ["domain", "problem"] {
            files.push(format!("{phase}.{suffix}.ttl"));
        }
    }
    files
}

/// Imports the artifact set and generates the ONE combined national plan via
/// the engine's many-to-one side-door, printing `GENERATED_PLAN_ID=` (BLAKE3
/// over the ordered plan-step labels).
fn generate_combined_plan() -> Result<Pddl8Tape, Refusal> {
    let (engine, snapshot_ids) = import_artifacts(&canonical_artifact_set())?;
    let tape = engine.plan_tape_for_snapshots(&snapshot_ids)?;
    let labels: Vec<&str> = tape.ops.iter().map(|op| op.label.as_str()).collect();
    let plan_id = blake3::hash(labels.join("\n").as_bytes()).to_hex();
    println!("GENERATED_PLAN_ID=blake3:{plan_id}");
    Ok(tape)
}

/// Exports the generated POWL Turtle artifact and prints its canonical
/// absolute path with the `GENERATED_POWL_TTL_PATH=` marker.
fn export_powl(file_name: &str, turtle: &str) -> PathBuf {
    let dir = powl_output_dir();
    fs::create_dir_all(&dir).expect("POWL output directory must be creatable");
    let file_path = dir.join(file_name);
    fs::write(&file_path, turtle).expect("exported POWL Turtle must be writable");
    let path = file_path
        .canonicalize()
        .expect("exported POWL Turtle path must canonicalize");
    println!("GENERATED_POWL_TTL_PATH={}", path.display());
    path
}

test!(
    hierarchical_projection_groups_ops_by_contributing_artifact,
    {
        // Arrange + Act: import all 26 phase fragments, generate ONE combined
        // plan, and project it hierarchically by contributing artifact.
        let tape = generate_combined_plan()?;
        assert_eq!(
            tape.ops.len(),
            EXPECTED_OP_COUNT,
            "the thirteen phase fragments must merge into one 20-step national plan"
        );
        let (model, phase_sources) =
            project_pddl_tape_to_powl_hierarchical(&tape, &joseph_action_sources())?;

        // Assert: phase_sources is one domain-fragment IRI per phase, in
        // program (artifact contribution) order.
        let expected_sources: Vec<String> =
            PHASES.iter().map(|phase| phase_source_iri(phase)).collect();
        assert_eq!(
            phase_sources, expected_sources,
            "phase_sources must carry one source IRI per phase in contribution order"
        );

        // Assert: root is a PartialOrder of per-phase PartialOrders with the
        // closed 13-phase chain order; each phase holds its steps as leaves
        // with the closed intra-phase order.
        match &model {
            Powl::PartialOrder { children, order } => {
                assert_eq!(
                    children.len(),
                    PHASES.len(),
                    "expected one POWL phase child per contributing artifact"
                );
                assert_eq!(
                    order.len(),
                    EXPECTED_ROOT_ORDER_PAIRS,
                    "expected the full transitively-closed phase chain (C(13,2) = 78)"
                );
                for (p, child) in children.iter().enumerate() {
                    let (phase, actions) = PHASE_ACTIONS[p];
                    match child {
                        Powl::PartialOrder { children, order } => {
                            assert_eq!(
                                children.len(),
                                actions.len(),
                                "phase {phase:?} must hold one leaf per contributed step"
                            );
                            assert_eq!(
                                order.len(),
                                actions.len() * (actions.len() - 1) / 2,
                                "phase {phase:?} must carry its closed intra-phase order"
                            );
                            for (i, leaf) in children.iter().enumerate() {
                                match leaf {
                                    Powl::Leaf(Some(label)) => assert!(
                                        label.contains(actions[i]),
                                        "phase {phase:?} leaf {i} label {label:?} must carry \
                                         step {:?}",
                                        actions[i]
                                    ),
                                    other => panic!(
                                        "expected Powl::Leaf(Some(_)) inside phase {phase:?}, \
                                         got {other:?}"
                                    ),
                                }
                            }
                        }
                        other => {
                            panic!("expected Powl::PartialOrder for phase {phase:?}, got {other:?}")
                        }
                    }
                }
            }
            other => panic!("expected root Powl::PartialOrder, got {other:?}"),
        }

        Ok::<(), Refusal>(())
    }
);

test!(hierarchical_powl_exports_parses_and_is_deterministic, {
    // Arrange: regenerate the combined plan and hierarchical model.
    let tape = generate_combined_plan()?;
    let (model, _phase_sources) =
        project_pddl_tape_to_powl_hierarchical(&tape, &joseph_action_sources())?;

    // Act: serialize twice with provenance pointing at the combined plan,
    // then export the one national hierarchical workflow artifact.
    let turtle_a = powl_to_turtle(&model, BASE_IRI, Some(PLAN_SOURCE_IRI))?;
    let turtle_b = powl_to_turtle(&model, BASE_IRI, Some(PLAN_SOURCE_IRI))?;
    let exported = export_powl(EXPORT_FILE, &turtle_a);

    // Assert: exported bytes equal the serialized Turtle; serialization is
    // byte-identical across repeated calls; parsing runs on the file content
    // read back from disk.
    let exported_turtle = fs::read_to_string(&exported)
        .expect("exported POWL artifact must be readable back from disk");
    assert_eq!(
        exported_turtle, turtle_a,
        "exported artifact bytes must equal the serialized Turtle"
    );
    assert_eq!(
        turtle_a, turtle_b,
        "powl_to_turtle must produce byte-identical output across repeated calls"
    );

    let store = Store::new().expect("in-memory oxigraph store construction must not fail");
    store
        .load_from_slice(
            RdfParser::from_format(RdfFormat::Turtle),
            exported_turtle.as_bytes(),
        )
        .expect("exported POWL Turtle must parse as valid Turtle");

    // Assert non-vacuity against the *parsed* RDF via grouped-count queries
    // loaded from fixture .rq files — no SPARQL text in Rust sources
    // (query-authority boundary).
    let fixture_counts = |query_file: &str| -> std::collections::BTreeMap<String, u64> {
        let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("tests/pddl_to_powl/queries")
            .join(query_file);
        let query = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("read fixture query {}: {e}", path.display()));
        let prepared = oxigraph::sparql::SparqlEvaluator::new()
            .parse_query(&query)
            .expect("fixture query must parse");
        let Ok(oxigraph::sparql::QueryResults::Solutions(solutions)) =
            prepared.on_store(&store).execute()
        else {
            panic!("fixture query must return solutions: {query_file}");
        };
        let mut counts = std::collections::BTreeMap::new();
        for solution in solutions {
            let solution = solution.expect("solution must decode");
            let term = solution
                .get("type")
                .or_else(|| solution.get("p"))
                .map(ToString::to_string)
                .expect("grouping term bound");
            let count = solution
                .get("count")
                .map(ToString::to_string)
                .and_then(|s| s.split('"').nth(1).map(str::to_string))
                .and_then(|s| s.parse::<u64>().ok())
                .expect("count literal bound");
            counts.insert(term, count);
        }
        counts
    };
    let type_counts = fixture_counts("type-counts.rq");
    let count_of = |class_iri: &str| -> usize {
        type_counts
            .get(&format!("<https://truex.io/ontology/powl2#{class_iri}>"))
            .copied()
            .unwrap_or(0) as usize
    };
    assert_eq!(count_of("Model"), 1, "exactly one powl2:Model root node");
    assert_eq!(
        count_of("PartialOrder"),
        PHASES.len() + 1,
        "one root powl2:PartialOrder plus one per phase (13 + 1 = 14)"
    );
    assert_eq!(
        count_of("ActivityLeaf"),
        EXPECTED_OP_COUNT,
        "exactly one powl2:ActivityLeaf per national program step"
    );
    assert_eq!(
        count_of("ChildBinding"),
        PHASES.len() + EXPECTED_OP_COUNT,
        "one binding per phase under the root plus one per leaf under its phase"
    );
    let predicate_counts = fixture_counts("predicate-counts.rq");
    let count_predicate = |pred_iri: &str| -> usize {
        predicate_counts
            .get(&format!("<https://truex.io/ontology/powl2#{pred_iri}>"))
            .copied()
            .unwrap_or(0) as usize
    };
    assert_eq!(
        count_predicate("precedes"),
        EXPECTED_ROOT_ORDER_PAIRS + EXPECTED_INTRA_PHASE_ORDER_PAIRS,
        "closed root order (78) plus closed intra-phase orders (7) = 85 precedes triples"
    );
    assert_eq!(
        count_predicate("derivedFrom"),
        1,
        "the root model node carries exactly one powl2:derivedFrom provenance triple"
    );

    Ok::<(), Refusal>(())
});

test!(hierarchical_projection_refusals_are_typed, {
    // Empty tape refuses PlanInfeasible — the same refusal as the flat
    // projection.
    let empty = Pddl8Tape { ops: vec![] };
    match project_pddl_tape_to_powl_hierarchical(&empty, &joseph_action_sources()) {
        Err(Refusal::PlanInfeasible(msg)) => {
            assert!(
                !msg.is_empty(),
                "empty-tape refusal must carry a diagnostic"
            );
        }
        other => panic!("expected PlanInfeasible for an empty tape, got {other:?}"),
    }

    // A plan op whose action schema has no contributing source artifact
    // refuses ValidationFailed — the model would be detached from its inputs.
    let tape = generate_combined_plan()?;
    let mut sources = joseph_action_sources();
    sources.remove("appoint-joseph");
    match project_pddl_tape_to_powl_hierarchical(&tape, &sources) {
        Err(Refusal::ValidationFailed(msg)) => {
            assert!(
                msg.contains("appoint-joseph"),
                "detached-op refusal must name the unmapped action schema, got {msg:?}"
            );
        }
        other => panic!("expected ValidationFailed for a missing action source, got {other:?}"),
    }

    Ok::<(), Refusal>(())
});
