use crate::air::{AirProgram, AirExpr};
use bumpalo::Bump;
use std::collections::HashMap;

/// Predictive Temporal Parsing Engine
///
/// Implements "retrocausal" pre-collapsing and Closed Timelike Curves (CTCs).
/// Simulates relativistic frame dragging by iterating the workflow graph until
/// a fixed point is reached, allowing steps to fetch deterministic states that
/// technically have not been computed yet (backward-in-time propagation).
pub struct TemporalPredictor;

impl TemporalPredictor {
    /// Pre-collapses references in the AIR program using closed timelike curves.
    pub fn pre_collapse<'bump>(program: &mut AirProgram<'bump>, _bump: &'bump Bump) {
        for wf in program.workflows.iter_mut() {
            // Tachyonic state map holding future and past inevitabilities
            let mut retro_state: HashMap<String, String> = HashMap::new();

            // Simulate closed timelike curves (CTCs) via fixed-point frame dragging
            let mut stabilized = false;
            let mut iterations = 0;

            while !stabilized && iterations < 100 {
                stabilized = true;

                // First pass: accumulate all known deterministic outputs across the entire timeline
                for step in wf.steps.iter() {
                    for output in step.action.outputs.iter() {
                        if let AirExpr::Literal(val) = output {
                            if !retro_state.contains_key(val.as_str()) {
                                retro_state.insert(val.as_str().to_string(), val.as_str().to_string());
                                stabilized = false; // The timeline has shifted
                            }
                        }
                    }
                }

                // Second pass: apply causality bypass to inputs regardless of temporal position
                for step in wf.steps.iter_mut() {
                    for input in step.action.inputs.iter_mut() {
                        if let AirExpr::Variable(var_name) = input {
                            if let Some(collapsed_val) = retro_state.get(var_name.as_str()) {
                                // The state is fetched from the future/past
                                *input = AirExpr::Literal(bumpalo::collections::String::from_str_in(collapsed_val, _bump));
                                stabilized = false; // A collapse occurred, timeline must be re-verified
                            }
                        }
                    }
                }

                iterations += 1;
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::air::{AirWorkflow, AirStep, AirTarget, AirAction};
    use bumpalo::collections::{String as BumpString, Vec as BumpVec};
    use bumpalo::vec;

    #[test]
    fn test_temporal_retrocausality() {
        let bump = Bump::new();
        let mut program = AirProgram {
            workflows: vec![in &bump;
                AirWorkflow {
                    name: BumpString::from_str_in("retro_wf", &bump),
                    steps: vec![in &bump;
                        AirStep {
                            name: BumpString::from_str_in("step_1", &bump),
                            target: AirTarget {
                                url: BumpString::from_str_in("http://example.com", &bump),
                                method: BumpString::from_str_in("POST", &bump),
                            },
                            action: AirAction {
                                inputs: BumpVec::new_in(&bump),
                                outputs: vec![in &bump; AirExpr::Literal(BumpString::from_str_in("order_id", &bump))],
                            }
                        },
                        AirStep {
                            name: BumpString::from_str_in("step_2", &bump),
                            target: AirTarget {
                                url: BumpString::from_str_in("http://example.com/2", &bump),
                                method: BumpString::from_str_in("POST", &bump),
                            },
                            action: AirAction {
                                inputs: vec![in &bump; AirExpr::Variable(BumpString::from_str_in("order_id", &bump))],
                                outputs: BumpVec::new_in(&bump),
                            }
                        }
                    ],
                }
            ]
        };

        TemporalPredictor::pre_collapse(&mut program, &bump);

        let step2_input = &program.workflows[0].steps[1].action.inputs[0];
        match step2_input {
            AirExpr::Literal(val) => assert_eq!(val, "order_id"),
            _ => panic!("Temporal predictor failed to pre-collapse!"),
        }
    }

    #[test]
    fn test_closed_timelike_curve() {
        let bump = Bump::new();
        // Step 1 requires an input that is generated by Step 2 in the future
        let mut program = AirProgram {
            workflows: vec![in &bump;
                AirWorkflow {
                    name: BumpString::from_str_in("ctc_wf", &bump),
                    steps: vec![in &bump;
                        AirStep {
                            name: BumpString::from_str_in("step_1_past", &bump),
                            target: AirTarget {
                                url: BumpString::from_str_in("http://example.com/past", &bump),
                                method: BumpString::from_str_in("POST", &bump),
                            },
                            action: AirAction {
                                // Depends on the future!
                                inputs: vec![in &bump; AirExpr::Variable(BumpString::from_str_in("future_artifact", &bump))],
                                outputs: BumpVec::new_in(&bump),
                            }
                        },
                        AirStep {
                            name: BumpString::from_str_in("step_2_future", &bump),
                            target: AirTarget {
                                url: BumpString::from_str_in("http://example.com/future", &bump),
                                method: BumpString::from_str_in("POST", &bump),
                            },
                            action: AirAction {
                                inputs: BumpVec::new_in(&bump),
                                // Generates the artifact for the past
                                outputs: vec![in &bump; AirExpr::Literal(BumpString::from_str_in("future_artifact", &bump))],
                            }
                        }
                    ],
                }
            ]
        };

        TemporalPredictor::pre_collapse(&mut program, &bump);

        // Verify Step 1 input collapsed from Variable to Literal using future data
        let step1_input = &program.workflows[0].steps[0].action.inputs[0];
        match step1_input {
            AirExpr::Literal(val) => assert_eq!(val, "future_artifact"),
            _ => panic!("Causality bypass failed! The past did not receive the future artifact."),
        }
    }
}
