//! `jira` noun-verb routes — GENERATED by `ggen sync` from the
//! `jira-tracking-pack` ontology (`cnv:Command` individuals scoped to
//! `cnv:noun "jira"`, per PROJ-tracking's own `schema.ttl`). Do not edit by
//! hand: routes are a pure projection of the ontology; logic lives in
//! `cng::jira::handlers`. (Freezing regeneration is configured in the
//! template frontmatter's `skip_if` key itself, not spelled out verbatim
//! here, so this generated body never accidentally self-matches its own
//! freeze marker on the next `ggen sync run` — see this file's `.tmpl`
//! source for the actual mechanism.)
//!
//! Adapted from `clap-noun-verb-pack`'s `clap_noun_verb_routes.rs.tmpl`
//! mechanism (SPARQL SELECT over `cnv:Command` individuals -> Tera loop ->
//! `#[verb]`-attributed fn) but NOT copied verbatim: that pack's own
//! generated output has zero real callers anywhere in this repo (its
//! `#[clap_noun_verb_macros::verb("verb")]` single-argument form and
//! `crate::verbs::handlers::` module path have never been compiled against
//! this workspace's actual `clap-noun-verb 26.7.4`). This template instead
//! matches `crates/cng/src/main.rs`'s own real, compiling convention:
//! `#[verb("verb", "noun")]` (two positional args, unqualified `verb`
//! import) and a call into the library crate's `cng::jira::handlers`
//! module (this file lives in the `cng` BINARY crate, declared via `mod
//! jira_routes;` in `main.rs`, so `crate::jira` would resolve in the
//! binary's own module tree, not the library's — hence the fully
//! qualified `cng::jira::handlers::` path).
//!
//! Per-verb parameter shape (id: required String for show/status/deps;
//! optional status/section filters for list; term: required String for
//! search; none for report) is branched on `cmd.verb` below rather than
//! derived generically from the ontology — a deliberate, disclosed scope
//! limit for this fixed 6-verb command set, not a claim that ggen infers
//! arbitrary CLI arities from RDF alone.

use clap_noun_verb::Result;
use clap_noun_verb_macros::verb;

/// Print the full transitive dependency chain for one ticket id (SPARQL 1.1 property path jira:dependsOn+).
#[verb("deps", "jira")]
fn jira_deps(id: String) -> Result<cng::jira::TicketDeps> {
    cng::jira::handlers::jira_deps_handler(id)
}

/// List all tickets, optionally filtered by --status and/or --section.
#[verb("list", "jira")]
fn jira_list(
    status: Option<String>,
    section: Option<String>,
) -> Result<cng::jira::TicketListReport> {
    cng::jira::handlers::jira_list_handler(status, section)
}

/// Summary counts of tickets per status (SPARQL GROUP BY/COUNT).
#[verb("report", "jira")]
fn jira_report() -> Result<cng::jira::TicketReport> {
    cng::jira::handlers::jira_report_handler()
}

/// Case-insensitive full-text search over title and evidence for one search term.
#[verb("search", "jira")]
fn jira_search(term: String) -> Result<cng::jira::TicketListReport> {
    cng::jira::handlers::jira_search_handler(term)
}

/// Show full detail (title, section, status, evidence, transitive dependencies) for one ticket id.
#[verb("show", "jira")]
fn jira_show(id: String) -> Result<cng::jira::TicketDetail> {
    cng::jira::handlers::jira_show_handler(id)
}

/// Print just the status line for one ticket id.
#[verb("status", "jira")]
fn jira_status(id: String) -> Result<cng::jira::TicketStatus> {
    cng::jira::handlers::jira_status_handler(id)
}

// ---------------------------------------------------------------------
// Noun `--help` description, generated from the `cnv:Noun` individual's
// `rdfs:comment` — same first-writer-wins registration rationale as
// clap-noun-verb-pack's own template (see that file's matching comment
// block for the full explanation of why this beats the macro's runtime
// `file!()`-based scrape for a distributed/installed binary).
// ---------------------------------------------------------------------

#[linkme::distributed_slice(::clap_noun_verb::cli::registry::__NOUN_REGISTRY)]
static REGISTER_JIRA_NOUN: fn() = register_jira_noun;
fn register_jira_noun() {
    ::clap_noun_verb::cli::registry::CommandRegistry::register_noun(
        "jira",
        "Query milestone ticket-tracking data generated from docs/jira/*/tickets/index.md.",
    );
}
