//! `jira` noun-verb library logic: real SPARQL queries
//! (`crates/cng/src/queries/jira-*.rq`, generated by `jira-tracking-pack`
//! via `ggen sync`) executed against the ticket-tracking data compiled
//! into this binary (`crates/cng/src/jira-data.ttl`, generated by
//! `packs/jira-tracking-pack/make-ontology.py` from the real
//! `docs/jira/v26.7.11/tickets/index.md` markdown table — never
//! hand-typed).
//!
//! `crates/cng/src/jira_routes.rs` (also `ggen sync`-generated) is the
//! only caller of this module's [`handlers`] functions; see that file's
//! own header for why it lives in the binary crate while this module
//! lives in the library.
//!
//! No inline SPARQL: every query is `include_str!`-compiled from a `.rq`
//! file (`crates/cng/tests/no_inline_ttl_guard.rs` enforces this
//! crate-wide by grepping every `.rs` file for a literal SPARQL SELECT or
//! CONSTRUCT clause opener — deliberately not spelled out verbatim in this
//! sentence, for the same self-matching reason that guard test's own
//! needles are assembled from string parts rather than written literally).

use std::collections::BTreeMap;
use std::fmt;

use oxigraph::io::{RdfFormat, RdfParser};
use oxigraph::model::Term;
use oxigraph::sparql::{QueryResults, SparqlEvaluator};
use oxigraph::store::Store;
use serde::Serialize;

/// Compiled-in ticket-tracking ontology (schema + real parsed ticket
/// instances). GENERATED — see the file's own header for regeneration.
const JIRA_DATA_TTL: &str = include_str!("jira-data.ttl");

const Q_LIST: &str = include_str!("queries/jira-list.rq");
const Q_EVIDENCE: &str = include_str!("queries/jira-evidence.rq");
const Q_DEPS: &str = include_str!("queries/jira-deps.rq");
const Q_REPORT: &str = include_str!("queries/jira-report.rq");

/// Typed refusal taxonomy for the `jira` noun-verb commands (repo
/// invariant #1: no panics/silent defaults — every error here is one of
/// these variants; [`handlers`] converts to `clap_noun_verb::NounVerbError`
/// only at the CLI boundary).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum JiraRefusal {
    /// `jira-data.ttl` failed to parse as Turtle. Should be unreachable
    /// outside development: the file is `ggen`-generated and
    /// `rapper -i turtle -c`-validated by `make-ontology.py`'s own
    /// generation step, never hand-edited.
    DataUnparseable(String),
    /// A compiled-in `.rq` query failed to parse.
    QueryParseFailed { query: &'static str, reason: String },
    /// A compiled-in `.rq` query executed but oxigraph reported a runtime
    /// error.
    QueryExecutionFailed { query: &'static str, reason: String },
    /// A query yielded a solution row missing an expected `?var` binding —
    /// would indicate the compiled-in `.rq` and `jira-data.ttl` have
    /// drifted out of sync with `schema.ttl`'s vocabulary.
    RowMissingBinding {
        query: &'static str,
        var: &'static str,
    },
    /// `jira show`/`status`/`deps` given an id with zero matching ticket.
    /// Carries the known-id range (`min`/`max` of the sorted id list
    /// [`find_ticket_row`] already fetched to search) and `count` so the
    /// refusal is actionable instead of a bare "not found" — points the
    /// caller at `jira list` rather than making them guess the valid range.
    TicketNotFound {
        id: String,
        count: usize,
        min: String,
        max: String,
    },
    /// `jira list --status`/`--section` given a non-empty value that does
    /// not match any ticket's real `statusLabel`/`section` in the
    /// compiled-in data. Refused instead of silently filtering down to
    /// `count: 0`, which would be indistinguishable from "this value is
    /// real but currently has zero matching tickets".
    UnknownFilterValue {
        kind: &'static str,
        value: String,
        known: Vec<String>,
    },
}

impl fmt::Display for JiraRefusal {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::DataUnparseable(reason) => write!(f, "jira-data.ttl failed to parse: {reason}"),
            Self::QueryParseFailed { query, reason } => {
                write!(f, "query {query:?} failed to parse: {reason}")
            }
            Self::QueryExecutionFailed { query, reason } => {
                write!(f, "query {query:?} failed to execute: {reason}")
            }
            Self::RowMissingBinding { query, var } => {
                write!(f, "query {query:?} row missing ?{var} binding")
            }
            Self::TicketNotFound {
                id,
                count,
                min,
                max,
            } => write!(
                f,
                "no ticket with id {id:?} ({count} known tickets, ids {min}-{max}); \
                 run `cng jira list` to see all"
            ),
            Self::UnknownFilterValue { kind, value, known } => {
                write!(f, "unknown {kind} {value:?}; valid: {}", known.join(", "))
            }
        }
    }
}

/// Builds a fresh in-memory store from the compiled-in ticket data.
///
/// # Complexity
/// O(n) in the byte length of `jira-data.ttl` — a single parse-and-insert
/// pass, oxigraph's own cost, not looped over here.
fn open_store() -> Result<Store, JiraRefusal> {
    let store = Store::new().map_err(|e| JiraRefusal::DataUnparseable(e.to_string()))?;
    store
        .load_from_slice(
            RdfParser::from_format(RdfFormat::Turtle),
            JIRA_DATA_TTL.as_bytes(),
        )
        .map_err(|e| JiraRefusal::DataUnparseable(e.to_string()))?;
    Ok(store)
}

fn term_value(term: &Term) -> String {
    match term {
        Term::Literal(l) => l.value().to_string(),
        Term::NamedNode(n) => n.as_str().to_string(),
        other => other.to_string(),
    }
}

/// Runs one compiled-in `.rq` SELECT query and returns its solutions as
/// `(var -> value-string)` rows, in the query's own `ORDER BY` order, for
/// exactly the caller-declared `vars` (matching `measurement.rs`'s proven
/// `solution.get("varname")` idiom, generalized to a caller-supplied var
/// list instead of two hardcoded names).
///
/// # Complexity
/// O(r * v) where r is the row count oxigraph's query execution returns
/// and v = `vars.len()` (no additional sorting/filtering here).
fn run_select(
    store: &Store,
    query: &'static str,
    vars: &[&'static str],
) -> Result<Vec<BTreeMap<String, String>>, JiraRefusal> {
    let prepared =
        SparqlEvaluator::new()
            .parse_query(query)
            .map_err(|e| JiraRefusal::QueryParseFailed {
                query,
                reason: e.to_string(),
            })?;
    let results =
        prepared
            .on_store(store)
            .execute()
            .map_err(|e| JiraRefusal::QueryExecutionFailed {
                query,
                reason: e.to_string(),
            })?;
    let mut rows = Vec::new();
    match results {
        QueryResults::Solutions(solutions) => {
            for solution in solutions {
                let solution = solution.map_err(|e| JiraRefusal::QueryExecutionFailed {
                    query,
                    reason: e.to_string(),
                })?;
                let mut row = BTreeMap::new();
                for var in vars {
                    let value = solution
                        .get(*var)
                        .map(term_value)
                        .ok_or(JiraRefusal::RowMissingBinding { query, var })?;
                    row.insert((*var).to_string(), value);
                }
                rows.push(row);
            }
        }
        _ => {
            return Err(JiraRefusal::QueryExecutionFailed {
                query,
                reason: "query did not yield SELECT solutions".to_string(),
            })
        }
    }
    Ok(rows)
}

/// Confirms `id` names a real ticket (runs [`Q_LIST`] filtered client-side
/// to `id`) so `jira show`/`status`/`deps` refuse [`JiraRefusal::TicketNotFound`]
/// instead of silently returning an empty result for a typo'd id — deps
/// in particular would otherwise be indistinguishable from "0
/// dependencies" (zero property-path hops and zero non-existence both
/// yield zero rows from `Q_DEPS` alone). On a miss, the refusal is built
/// from the same `rows` this function already fetched to search — no
/// second query — with a `BTreeSet` sort of the known ids so `min`/`max`
/// are deterministic regardless of `Q_LIST`'s own row order.
///
/// # Complexity
/// O(r log r) where r = `rows.len()` — the linear search from the prior
/// version, plus a sort of the id set on the (cold) not-found path only.
fn find_ticket_row(store: &Store, id: &str) -> Result<BTreeMap<String, String>, JiraRefusal> {
    let rows = run_select(store, Q_LIST, &["id", "title", "section", "statusLabel"])?;
    if let Some(row) = rows
        .iter()
        .find(|r| r.get("id").map(String::as_str) == Some(id))
    {
        return Ok(row.clone());
    }
    let known_ids: std::collections::BTreeSet<&str> = rows
        .iter()
        .filter_map(|r| r.get("id").map(String::as_str))
        .collect();
    let count = known_ids.len();
    // `<none>` is not a silent default: it only surfaces if `Q_LIST` itself
    // returned zero rows, which would mean `jira-data.ttl` is empty — a
    // data-corruption case, not a normal "id not found" miss, and one that
    // `min`/`max` alone cannot represent as a real id.
    let min = known_ids.first().map_or("<none>", |s| s).to_string();
    let max = known_ids.last().map_or("<none>", |s| s).to_string();
    Err(JiraRefusal::TicketNotFound {
        id: id.to_string(),
        count,
        min,
        max,
    })
}

/// Reads a required field from a row [`run_select`] produced. Returns
/// [`JiraRefusal::RowMissingBinding`] instead of panicking/indexing if the
/// field is somehow absent — defensive even though `run_select`'s own
/// construction already guarantees every requested `var` is present in
/// every row it returns (invariant #1: no panics on data-derived paths,
/// even ones a nearby function already proves safe).
///
/// # Complexity
/// O(1) — a single `BTreeMap` lookup.
fn must<'a>(
    row: &'a BTreeMap<String, String>,
    query: &'static str,
    key: &'static str,
) -> Result<&'a String, JiraRefusal> {
    row.get(key)
        .ok_or(JiraRefusal::RowMissingBinding { query, var: key })
}

#[derive(Debug, Clone, Serialize)]
pub struct TicketSummary {
    pub id: String,
    pub title: String,
    pub section: String,
    pub status: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct TicketListReport {
    pub count: usize,
    pub tickets: Vec<TicketSummary>,
}

#[derive(Debug, Clone, Serialize)]
pub struct TicketDetail {
    pub id: String,
    pub title: String,
    pub section: String,
    pub status: String,
    pub evidence: String,
    pub depends_on: Vec<String>,
}

#[derive(Debug, Clone, Serialize)]
pub struct TicketStatus {
    pub id: String,
    pub status: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct TicketDeps {
    pub id: String,
    pub depends_on: Vec<String>,
}

#[derive(Debug, Clone, Serialize)]
pub struct StatusCount {
    pub status: String,
    pub count: u64,
}

#[derive(Debug, Clone, Serialize)]
pub struct TicketReport {
    pub total: u64,
    pub by_status: Vec<StatusCount>,
}

/// Real, non-generated command handlers — `jira_routes.rs` (`ggen`
/// generated) is this module's only caller. Each handler builds a fresh
/// [`Store`] from the compiled-in ticket data, runs one or more real
/// compiled-in `.rq` queries, and maps the solutions into a typed report.
pub mod handlers {
    use std::collections::BTreeSet;

    use super::{
        find_ticket_row, must, open_store, run_select, JiraRefusal, StatusCount, TicketDeps,
        TicketDetail, TicketListReport, TicketReport, TicketStatus, TicketSummary, Q_DEPS,
        Q_EVIDENCE, Q_LIST, Q_REPORT,
    };
    use std::collections::BTreeMap;

    fn to_cli_error(e: JiraRefusal) -> clap_noun_verb::NounVerbError {
        clap_noun_verb::NounVerbError::execution_error(format!("CNG_JIRA: {e}"))
    }

    /// Lists all tickets, optionally filtered by `--status`/`--section`
    /// (exact string match against the SPARQL-projected `statusLabel`/
    /// `section` values; filtering happens in Rust over an already-fetched
    /// real result set, not by hand-typing a second SPARQL query per
    /// filter combination). A non-empty `--status`/`--section` value that
    /// does not match any ticket's real value is refused
    /// ([`JiraRefusal::UnknownFilterValue`]) rather than silently
    /// producing `count: 0`, which would otherwise be indistinguishable
    /// from "this value is real but currently has zero matching tickets".
    ///
    /// # Complexity
    /// O(n) in `rows.len()` — one pass to collect the known
    /// `statusLabel`/`section` value sets (`BTreeSet` for deterministic
    /// `known` ordering in any refusal), one pass to filter.
    pub fn jira_list_handler(
        status: Option<String>,
        section: Option<String>,
    ) -> clap_noun_verb::Result<TicketListReport> {
        let store = open_store().map_err(to_cli_error)?;
        let rows = run_select(&store, Q_LIST, &["id", "title", "section", "statusLabel"])
            .map_err(to_cli_error)?;

        let mut known_statuses: BTreeSet<String> = BTreeSet::new();
        let mut known_sections: BTreeSet<String> = BTreeSet::new();
        for row in &rows {
            known_statuses.insert(
                must(row, Q_LIST, "statusLabel")
                    .map_err(to_cli_error)?
                    .clone(),
            );
            known_sections.insert(must(row, Q_LIST, "section").map_err(to_cli_error)?.clone());
        }
        if let Some(want) = status.as_deref() {
            if !want.is_empty() && !known_statuses.contains(want) {
                return Err(to_cli_error(JiraRefusal::UnknownFilterValue {
                    kind: "status",
                    value: want.to_string(),
                    known: known_statuses.into_iter().collect(),
                }));
            }
        }
        if let Some(want) = section.as_deref() {
            if !want.is_empty() && !known_sections.contains(want) {
                return Err(to_cli_error(JiraRefusal::UnknownFilterValue {
                    kind: "section",
                    value: want.to_string(),
                    known: known_sections.into_iter().collect(),
                }));
            }
        }

        let mut tickets = Vec::new();
        for row in &rows {
            let st = must(row, Q_LIST, "statusLabel").map_err(to_cli_error)?;
            let sect = must(row, Q_LIST, "section").map_err(to_cli_error)?;
            if status.as_deref().is_some_and(|want| want != st) {
                continue;
            }
            if section.as_deref().is_some_and(|want| want != sect) {
                continue;
            }
            tickets.push(TicketSummary {
                id: must(row, Q_LIST, "id").map_err(to_cli_error)?.clone(),
                title: must(row, Q_LIST, "title").map_err(to_cli_error)?.clone(),
                section: sect.clone(),
                status: st.clone(),
            });
        }
        Ok(TicketListReport {
            count: tickets.len(),
            tickets,
        })
    }

    /// Full detail for one ticket id: title/section/status, the complete
    /// evidence text, and its full transitive dependency chain.
    pub fn jira_show_handler(id: String) -> clap_noun_verb::Result<TicketDetail> {
        let store = open_store().map_err(to_cli_error)?;
        let row = find_ticket_row(&store, &id).map_err(to_cli_error)?;

        let ev_rows = run_select(&store, Q_EVIDENCE, &["id", "evidence"]).map_err(to_cli_error)?;
        let evidence = match ev_rows
            .iter()
            .find(|r| r.get("id").map(String::as_str) == Some(id.as_str()))
        {
            Some(r) => must(r, Q_EVIDENCE, "evidence")
                .map_err(to_cli_error)?
                .clone(),
            // A ticket with zero evidence text is not expected in real data
            // (every parsed row has a non-empty Scope cell) but is not an
            // error either — an empty string is the honest representation.
            None => String::new(),
        };

        let dep_rows = run_select(&store, Q_DEPS, &["id", "dep"]).map_err(to_cli_error)?;
        let mut depends_on = Vec::new();
        for r in dep_rows
            .iter()
            .filter(|r| r.get("id").map(String::as_str) == Some(id.as_str()))
        {
            depends_on.push(must(r, Q_DEPS, "dep").map_err(to_cli_error)?.clone());
        }

        Ok(TicketDetail {
            id: must(&row, Q_LIST, "id").map_err(to_cli_error)?.clone(),
            title: must(&row, Q_LIST, "title").map_err(to_cli_error)?.clone(),
            section: must(&row, Q_LIST, "section").map_err(to_cli_error)?.clone(),
            status: must(&row, Q_LIST, "statusLabel")
                .map_err(to_cli_error)?
                .clone(),
            evidence,
            depends_on,
        })
    }

    /// Just the status line for one ticket id.
    pub fn jira_status_handler(id: String) -> clap_noun_verb::Result<TicketStatus> {
        let store = open_store().map_err(to_cli_error)?;
        let row = find_ticket_row(&store, &id).map_err(to_cli_error)?;
        Ok(TicketStatus {
            id: must(&row, Q_LIST, "id").map_err(to_cli_error)?.clone(),
            status: must(&row, Q_LIST, "statusLabel")
                .map_err(to_cli_error)?
                .clone(),
        })
    }

    /// The full transitive dependency chain for one ticket id (real
    /// SPARQL 1.1 `jira:dependsOn+` property path, not a Rust-side
    /// graph walk).
    pub fn jira_deps_handler(id: String) -> clap_noun_verb::Result<TicketDeps> {
        let store = open_store().map_err(to_cli_error)?;
        // Confirms the id itself is real before reporting an (otherwise
        // ambiguous) empty dependency list.
        find_ticket_row(&store, &id).map_err(to_cli_error)?;
        let rows = run_select(&store, Q_DEPS, &["id", "dep"]).map_err(to_cli_error)?;
        let mut depends_on = Vec::new();
        for r in rows
            .iter()
            .filter(|r| r.get("id").map(String::as_str) == Some(id.as_str()))
        {
            depends_on.push(must(r, Q_DEPS, "dep").map_err(to_cli_error)?.clone());
        }
        Ok(TicketDeps { id, depends_on })
    }

    /// Summary counts of tickets per status (real SPARQL `GROUP BY`/
    /// `COUNT`, not a Rust-side tally).
    pub fn jira_report_handler() -> clap_noun_verb::Result<TicketReport> {
        let store = open_store().map_err(to_cli_error)?;
        let rows = run_select(&store, Q_REPORT, &["statusLabel", "count"]).map_err(to_cli_error)?;
        let mut by_status = Vec::new();
        let mut total: u64 = 0;
        for row in &rows {
            let count_text = must(row, Q_REPORT, "count").map_err(to_cli_error)?;
            let count: u64 = count_text.parse().map_err(|e| {
                to_cli_error(JiraRefusal::QueryExecutionFailed {
                    query: Q_REPORT,
                    reason: format!("count {count_text:?} did not parse as u64: {e}"),
                })
            })?;
            total += count;
            by_status.push(StatusCount {
                status: must(row, Q_REPORT, "statusLabel")
                    .map_err(to_cli_error)?
                    .clone(),
                count,
            });
        }
        Ok(TicketReport { total, by_status })
    }

    /// Case-insensitive full-text search over title and evidence: fetches
    /// [`Q_LIST`] and [`Q_EVIDENCE`] exactly as [`jira_show_handler`] does,
    /// joins them by `id` into a `BTreeMap` (deterministic join order), and
    /// keeps tickets whose title or joined evidence contains `term`
    /// case-insensitively — the same Rust-side-filter-over-already-fetched-
    /// rows idiom [`jira_list_handler`]'s own doc comment describes, not a
    /// third `.rq` file. A `term` matching zero tickets is not an error: an
    /// empty [`TicketListReport`] (`count: 0`) is the honest answer to "no
    /// ticket mentions this", the same way `jira list --status` on a
    /// currently-empty-but-known status would be (unlike
    /// [`JiraRefusal::UnknownFilterValue`], which only fires for a filter
    /// value that isn't a real value at all, not an absence of matches).
    ///
    /// # Complexity
    /// O(e) to build the id->evidence join map (e = evidence row count) +
    /// O(l) to scan the title/evidence-joined list rows (l = list row
    /// count) — two linear passes, no nested loop.
    pub fn jira_search_handler(term: String) -> clap_noun_verb::Result<TicketListReport> {
        let store = open_store().map_err(to_cli_error)?;
        let list_rows = run_select(&store, Q_LIST, &["id", "title", "section", "statusLabel"])
            .map_err(to_cli_error)?;
        let ev_rows = run_select(&store, Q_EVIDENCE, &["id", "evidence"]).map_err(to_cli_error)?;

        let mut evidence_by_id: BTreeMap<String, String> = BTreeMap::new();
        for r in &ev_rows {
            evidence_by_id.insert(
                must(r, Q_EVIDENCE, "id").map_err(to_cli_error)?.clone(),
                must(r, Q_EVIDENCE, "evidence")
                    .map_err(to_cli_error)?
                    .clone(),
            );
        }

        let needle = term.to_lowercase();
        let mut tickets = Vec::new();
        for row in &list_rows {
            let id = must(row, Q_LIST, "id").map_err(to_cli_error)?;
            let title = must(row, Q_LIST, "title").map_err(to_cli_error)?;
            let evidence = evidence_by_id.get(id).map(String::as_str).unwrap_or("");
            let title_hit = title.to_lowercase().contains(&needle);
            let evidence_hit = evidence.to_lowercase().contains(&needle);
            if !title_hit && !evidence_hit {
                continue;
            }
            tickets.push(TicketSummary {
                id: id.clone(),
                title: title.clone(),
                section: must(row, Q_LIST, "section").map_err(to_cli_error)?.clone(),
                status: must(row, Q_LIST, "statusLabel")
                    .map_err(to_cli_error)?
                    .clone(),
            });
        }
        Ok(TicketListReport {
            count: tickets.len(),
            tickets,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::handlers::*;
    use super::{open_store, run_select, JiraRefusal, Q_EVIDENCE};
    use oxigraph::io::{RdfFormat, RdfParser};
    use oxigraph::store::Store;

    /// [`run_select`] refuses [`JiraRefusal::RowMissingBinding`] when a
    /// caller-declared `var` is absent from a solution row. `Q_LIST`'s own
    /// four vars (`id`/`title`/`section`/`statusLabel`) can never actually
    /// exercise this: they are all mandatory conjuncts of one connected
    /// SPARQL BGP, so a store missing one of those triples simply drops the
    /// whole ticket from `Q_LIST`'s results (a SPARQL solution mapping's
    /// domain is exactly the pattern's own variables — never a partial
    /// binding) rather than yielding a row with a hole in it. What
    /// genuinely produces a missing binding is a `vars` entry disconnected
    /// from the *executed* query's own WHERE clause entirely (SPARQL
    /// projects a disconnected `SELECT` variable as always-unbound in
    /// every solution) — so this runs the real compiled-in [`Q_EVIDENCE`]
    /// (projects only `?id` and `?evidence`, no `?section` anywhere in its
    /// WHERE clause) against a minimal one-ticket fixture, requesting
    /// `section` as one of `run_select`'s caller-declared vars.
    #[test]
    fn run_select_refuses_row_missing_binding() {
        let store = Store::new().expect("in-memory store");
        let ttl = r#"
<http://seanchatmangpt.github.io/packs/jira-tracking#PROJTEST>
    <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://seanchatmangpt.github.io/packs/jira-tracking#Ticket> ;
    <http://seanchatmangpt.github.io/packs/jira-tracking#id> "TEST" ;
    <http://seanchatmangpt.github.io/packs/jira-tracking#evidence> "evidence text, no section anywhere in this fixture" .
"#;
        store
            .load_from_slice(RdfParser::from_format(RdfFormat::Turtle), ttl.as_bytes())
            .expect("fixture parses");
        let err = run_select(&store, Q_EVIDENCE, &["id", "section"]).unwrap_err();
        assert!(matches!(
            err,
            JiraRefusal::RowMissingBinding { var: "section", .. }
        ));
    }

    /// [`run_select`] refuses [`JiraRefusal::QueryExecutionFailed`] when
    /// the compiled-in query is syntactically valid SPARQL but not a
    /// `SELECT` at all — the real compiled-in `.rq` files are always
    /// `SELECT`, so this is otherwise-unreachable defensive coverage of
    /// the `run_select` match arm's non-`Solutions` branch, exercised with
    /// a hand-written `ASK` query string (a `&'static str` literal, same
    /// as any `Q_*` constant — `run_select`'s own signature takes
    /// `query: &'static str`, not necessarily one of the `include_str!`
    /// constants) against the real compiled-in ticket data.
    #[test]
    fn run_select_refuses_non_select_query() {
        let store = open_store().expect("real compiled-in data must load");
        let err = run_select(&store, "ASK { ?s ?p ?o }", &["id"]).unwrap_err();
        match err {
            JiraRefusal::QueryExecutionFailed { reason, .. } => {
                assert!(
                    reason.contains("did not yield SELECT solutions"),
                    "unexpected reason: {reason}"
                );
            }
            other => panic!("expected QueryExecutionFailed, got {other:?}"),
        }
    }

    #[test]
    fn list_returns_all_49_real_tickets() {
        let report = jira_list_handler(None, None).expect("real compiled-in data must query");
        assert_eq!(report.count, 49);
        assert_eq!(report.tickets.len(), 49);
    }

    #[test]
    fn list_filters_by_status() {
        let report = jira_list_handler(Some("ALIVE".to_string()), None).expect("query");
        assert_eq!(report.count, 33);
        assert!(report.tickets.iter().all(|t| t.status == "ALIVE"));
    }

    #[test]
    fn list_filters_by_section() {
        let report = jira_list_handler(None, Some("A".to_string())).expect("query");
        assert!(report.tickets.iter().all(|t| t.section == "A"));
        assert!(!report.tickets.is_empty());
    }

    #[test]
    fn list_refuses_unknown_status() {
        let err = jira_list_handler(Some("Alive".to_string()), None).unwrap_err();
        assert!(format!("{err}").contains("unknown status"));
    }

    #[test]
    fn list_refuses_unknown_section() {
        let err = jira_list_handler(None, Some("ZZZ".to_string())).unwrap_err();
        assert!(format!("{err}").contains("unknown section"));
    }

    #[test]
    fn show_returns_full_detail_for_a_real_ticket() {
        let detail = jira_show_handler("750".to_string()).expect("750 is real");
        assert_eq!(detail.id, "750");
        assert!(detail.title.contains("POWL v2"));
        assert_eq!(detail.status, "ALIVE");
        assert!(!detail.evidence.is_empty());
        assert!(
            detail.depends_on.is_empty(),
            "750 has no declared dependencies"
        );
    }

    #[test]
    fn show_refuses_unknown_id() {
        let err = jira_show_handler("999999".to_string()).unwrap_err();
        let message = format!("{err}");
        assert!(message.contains("CNG_JIRA"));
        assert!(message.contains("known tickets"));
        assert!(message.contains("jira list"));
    }

    #[test]
    fn status_returns_just_the_status_line() {
        let status = jira_status_handler("777".to_string()).expect("777 is real");
        assert_eq!(status.id, "777");
        assert_eq!(status.status, "ALIVE");
    }

    #[test]
    fn deps_returns_the_real_transitive_chain() {
        // 753 -> 752 -> 751 -> 750 (direct chain per the real table).
        let deps = jira_deps_handler("753".to_string()).expect("753 is real");
        assert!(deps.depends_on.contains(&"752".to_string()));
        assert!(deps.depends_on.contains(&"751".to_string()));
        assert!(deps.depends_on.contains(&"750".to_string()));
    }

    #[test]
    fn deps_on_dependency_free_ticket_is_empty_not_refused() {
        let deps = jira_deps_handler("750".to_string()).expect("750 is real, zero deps");
        assert!(deps.depends_on.is_empty());
    }

    #[test]
    fn deps_refuses_unknown_id() {
        let err = jira_deps_handler("999999".to_string()).unwrap_err();
        let message = format!("{err}");
        assert!(message.contains("known tickets"));
        assert!(message.contains("jira list"));
    }

    #[test]
    fn report_totals_match_the_real_49_tickets() {
        let report = jira_report_handler().expect("query");
        assert_eq!(report.total, 49);
        let alive = report
            .by_status
            .iter()
            .find(|s| s.status == "ALIVE")
            .expect("ALIVE present");
        assert_eq!(alive.count, 33);
    }

    #[test]
    fn list_is_deterministic_across_two_calls() {
        let a = jira_list_handler(None, None).expect("query");
        let b = jira_list_handler(None, None).expect("query");
        assert_eq!(
            a.tickets.iter().map(|t| t.id.clone()).collect::<Vec<_>>(),
            b.tickets.iter().map(|t| t.id.clone()).collect::<Vec<_>>(),
        );
    }

    #[test]
    fn search_matches_by_title_or_evidence() {
        // "POWL v2" is real title text on ticket 750 (see
        // show_returns_full_detail_for_a_real_ticket above); a title-only
        // match proves the title half of the join without relying on
        // evidence content.
        let by_title = jira_search_handler("powl v2".to_string()).expect("query");
        assert!(by_title.tickets.iter().any(|t| t.id == "750"));

        // "TOCTOU" is real evidence text on ticket 758 (docs/jira/v26.7.11/
        // tickets/index.md), not present in that ticket's title — proves
        // the evidence half of the join, and case-insensitivity.
        let by_evidence = jira_search_handler("toctou".to_string()).expect("query");
        assert!(by_evidence.tickets.iter().any(|t| t.id == "758"));
        assert_eq!(by_evidence.count, by_evidence.tickets.len());
    }

    #[test]
    fn search_with_no_matches_returns_empty_not_error() {
        let report =
            jira_search_handler("no_ticket_could_possibly_contain_this_token_zzz".to_string())
                .expect("a term matching nothing is not a refusal");
        assert_eq!(report.count, 0);
        assert!(report.tickets.is_empty());
    }
}
