#!/usr/bin/env python3
"""Build the admitted repository code inventory consumed by ggen.

The builder observes tracked source/control surfaces, emits deterministic RDF,
and seals the observation with BLAKE3. It does not rewrite application code.
Migration dispositions are diagnostic until a bounded equivalence proof exists.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

try:
    import blake3  # type: ignore[import-not-found]
except ImportError as exc:
    raise SystemExit(
        "build-ggen-code-inventory: REFUSED: Python package 'blake3' is required"
    ) from exc

ROOT = Path(__file__).resolve().parents[1]
PACK = ROOT / "packs" / "code-modernization-pack"
INSTANCES = PACK / "instances.ttl"
RECEIPT = PACK / "instances.receipt.json"
GENERATED_REGISTRY = "crates/ggen/tests/ggen_code_inventory.rs"
GENERATED_REPORT = "docs/standing/GGEN_CODE_MODERNIZATION.md"

CODE_LANGUAGES = {
    ".rs": "Rust",
    ".py": "Python",
    ".sh": "Shell",
    ".bash": "Shell",
    ".zsh": "Shell",
    ".ts": "TypeScript",
    ".tsx": "TypeScript",
    ".js": "JavaScript",
    ".mjs": "JavaScript",
    ".cjs": "JavaScript",
    ".erl": "Erlang",
    ".hrl": "Erlang",
    ".ex": "Elixir",
    ".exs": "Elixir",
    ".lean": "Lean",
    ".c": "C",
    ".h": "C",
    ".cpp": "C++",
    ".hpp": "C++",
    ".java": "Java",
    ".kt": "Kotlin",
    ".kts": "Kotlin",
    ".go": "Go",
    ".wat": "WebAssembly Text",
}
TEMPLATE_SUFFIXES = {".tmpl", ".j2", ".tera"}
DECLARATIVE_SUFFIXES = {
    ".ttl": "Turtle",
    ".n3": "Notation3",
    ".rq": "SPARQL",
    ".sparql": "SPARQL",
    ".pddl": "PDDL",
    ".toml": "TOML",
    ".yaml": "YAML",
    ".yml": "YAML",
    ".json": "JSON",
}
CONTROL_NAMES = {
    "Cargo.toml",
    "ggen.toml",
    "ggen.lock",
    "justfile",
    "Makefile",
    "Dockerfile",
}
EXCLUDED = (
    ".git/",
    "target/",
    ".agents/",
    ".cargo-cicd/",
    ".ggen-v2/",
    "vendor/",
    "node_modules/",
)
EXCLUDED_EXACT = {
    "packs/code-modernization-pack/instances.ttl",
    "packs/code-modernization-pack/instances.receipt.json",
    GENERATED_REGISTRY,
    GENERATED_REPORT,
}

GENERATED_MARKER = re.compile(
    r"(?i)(generated\s+by\s+ggen|ggen[- ]rendered|@generated|do\s+not\s+edit|"
    r"generated\s+file|autogenerated|auto-generated)"
)
SOURCE_HINT = re.compile(
    r"(?im)^\s*(?://|#|--|/\*)?\s*(?:source|generated\s+from|ontology|template)\s*[:=]\s*([^\n*]+)"
)
STATIC_TABLE = re.compile(
    r"(?m)\b(?:const|static)\s+[A-Z][A-Z0-9_]{2,}\b|"
    r"\b(?:REGISTRY|CATEGORIES|ROUTES|COMMANDS|STATUSES|BREEDS|ALGORITHMS|"
    r"CAPABILITIES|PREDICATES|VOCABULARY|SCHEMAS)\b"
)
CLI_MARKER = re.compile(
    r"#\[(?:noun|verb|command|arg|derive\([^\]]*(?:Parser|Subcommand))"
)
URL_OR_URN = re.compile(r"(?:https?://|urn:)[^\s\"'<>]+")
MATCH_ARM = re.compile(r"(?m)^\s*(?:[A-Za-z0-9_:|(){}.,\s]+)\s*=>")
LITERAL_ID = re.compile(r"[\"'](?:[A-Z][A-Z0-9_-]{2,}|[a-z][a-z0-9_-]{3,})[\"']")
PANIC_SITE = re.compile(
    r"\.(?:unwrap|expect)\s*\(|\bpanic!\s*\(|\.unwrap_or_default\s*\("
)
TODO_SITE = re.compile(r"(?i)\b(?:TODO|FIXME|HACK)\b")


@dataclass(frozen=True)
class Surface:
    path: str
    language: str
    owner: str
    kind: str
    disposition: str
    lines: int
    bytes: int
    content_hash: str
    score: int
    reasons: tuple[str, ...]
    projection_source: str | None
    panic_sites: int
    todo_sites: int


def run(*args: str) -> str:
    completed = subprocess.run(
        args,
        cwd=ROOT,
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    return completed.stdout.strip()


def digest(data: bytes) -> str:
    return blake3.blake3(data).hexdigest()


def canonical_json(value: object) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()


def ttl(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def tracked_paths() -> list[str]:
    raw = subprocess.run(
        ["git", "ls-files", "-z"], cwd=ROOT, check=True, stdout=subprocess.PIPE
    ).stdout
    paths: list[str] = []
    for item in raw.split(b"\0"):
        if not item:
            continue
        path = item.decode("utf-8", errors="surrogateescape")
        if path in EXCLUDED_EXACT or path.startswith(EXCLUDED):
            continue
        paths.append(path)
    return sorted(paths)


def read_text(path: Path) -> tuple[bytes, str] | None:
    try:
        data = path.read_bytes()
    except OSError:
        return None
    if b"\0" in data[:8192]:
        return None
    try:
        return data, data.decode("utf-8")
    except UnicodeDecodeError:
        return None


def declarative_source(path: str, suffix: str) -> bool:
    if suffix not in DECLARATIVE_SUFFIXES:
        return False
    parts = set(Path(path).parts)
    return (
        path.startswith(("packs/", "schema/", "ontology/", ".github/"))
        or bool(parts & {"ontology", "ontologies", "rules", "queries", "registry", "shapes"})
        or Path(path).name in CONTROL_NAMES
    )


def is_surface(path: str) -> bool:
    suffix = Path(path).suffix.lower()
    return (
        suffix in CODE_LANGUAGES
        or suffix in TEMPLATE_SUFFIXES
        or declarative_source(path, suffix)
        or Path(path).name in CONTROL_NAMES
    )


def language(path: str) -> str:
    suffix = Path(path).suffix.lower()
    if suffix in CODE_LANGUAGES:
        return CODE_LANGUAGES[suffix]
    if suffix in TEMPLATE_SUFFIXES:
        return "ggen/Tera Template"
    if suffix in DECLARATIVE_SUFFIXES:
        return DECLARATIVE_SUFFIXES[suffix]
    return "Build Control"


def owner(path: str) -> str:
    parts = Path(path).parts
    if len(parts) >= 2 and parts[0] in {"crates", "apps", "clients", "packs"}:
        return f"{parts[0]}/{parts[1]}"
    if parts and parts[0] == ".github":
        return ".github"
    return "repository-root"


def is_test(path: str) -> bool:
    lower = path.lower()
    name = Path(path).name.lower()
    return (
        "/tests/" in f"/{lower}"
        or "/test/" in f"/{lower}"
        or name.endswith(("_test.rs", "_tests.rs", ".test.ts", ".test.js"))
        or "/fixtures/" in f"/{lower}"
        or "/examples/" in f"/{lower}"
    )


def is_control(path: str) -> bool:
    suffix = Path(path).suffix.lower()
    return (
        suffix in TEMPLATE_SUFFIXES
        or path.startswith(("packs/", "schema/", "ontology/", ".github/"))
        or Path(path).name in CONTROL_NAMES
        or path.startswith("scripts/build-ggen")
    )


def score(text: str, lines: int) -> tuple[int, tuple[str, ...]]:
    value = 0
    reasons: list[str] = []
    static_hits = len(STATIC_TABLE.findall(text))
    if static_hits:
        value += min(35, 8 + static_hits * 3)
        reasons.append(f"static-registry:{static_hits}")
    cli_hits = len(CLI_MARKER.findall(text))
    if cli_hits:
        value += min(30, 10 + cli_hits * 2)
        reasons.append(f"cli-schema:{cli_hits}")
    url_hits = len(URL_OR_URN.findall(text))
    if url_hits >= 4:
        value += min(25, 5 + url_hits // 2)
        reasons.append(f"embedded-vocabulary:{url_hits}")
    match_hits = len(MATCH_ARM.findall(text))
    if match_hits >= 8:
        value += min(20, match_hits // 2)
        reasons.append(f"match-table:{match_hits}")
    literal_hits = len(LITERAL_ID.findall(text))
    if literal_hits >= 16:
        value += min(20, literal_hits // 8)
        reasons.append(f"literal-id-density:{literal_hits}")
    if lines >= 1200:
        value += 18
        reasons.append(f"large-surface:{lines}")
    elif lines >= 500:
        value += 12
        reasons.append(f"large-surface:{lines}")
    elif lines >= 250:
        value += 6
        reasons.append(f"large-surface:{lines}")
    if "include_str!(" in text or "include_bytes!(" in text:
        value += 8
        reasons.append("embedded-artifact")
    if "serde" in text and ("enum " in text or "struct " in text):
        value += 4
        reasons.append("serializable-schema")
    return value, tuple(reasons)


def infer_source(text: str) -> str | None:
    match = SOURCE_HINT.search("\n".join(text.splitlines()[:100]))
    return match.group(1).strip().strip("*/ ") if match else None


def disposition(path: str, text: str, candidate_score: int) -> tuple[str, str]:
    if GENERATED_MARKER.search(text):
        return "Generated", "GENERATED_PROJECTION"
    if is_control(path):
        return "ControlSurface", "CONTROL_SURFACE"
    if is_test(path):
        return "TestSurface", "TEST_SURFACE"
    if candidate_score >= 40:
        return "HighCandidate", "HAND_AUTHORED_CODE"
    if candidate_score >= 20:
        return "MediumCandidate", "HAND_AUTHORED_CODE"
    return "HandAuthoredRuntime", "HAND_AUTHORED_CODE"


def observe() -> list[Surface]:
    observed: dict[str, Surface] = {}
    for rel in tracked_paths():
        if not is_surface(rel):
            continue
        payload = read_text(ROOT / rel)
        if payload is None:
            continue
        data, text = payload
        line_count = text.count("\n") + 1
        candidate_score, reasons = score(text, line_count)
        disp, kind = disposition(rel, text, candidate_score)
        source = infer_source(text) if disp == "Generated" else None
        observed[rel] = Surface(
            path=rel,
            language=language(rel),
            owner=owner(rel),
            kind=kind,
            disposition=disp,
            lines=line_count,
            bytes=len(data),
            content_hash=f"blake3:{digest(data)}",
            score=candidate_score if kind == "HAND_AUTHORED_CODE" else 0,
            reasons=reasons if kind == "HAND_AUTHORED_CODE" else (),
            projection_source=source,
            panic_sites=len(PANIC_SITE.findall(text)) if rel.endswith(".rs") else 0,
            todo_sites=len(TODO_SITE.findall(text)),
        )

    # Self-description without a hash cycle: the generated verifier is governed
    # by its template and determinism check, not folded into its own input hash.
    observed[GENERATED_REGISTRY] = Surface(
        path=GENERATED_REGISTRY,
        language="Rust",
        owner="crates/ggen",
        kind="GENERATED_PROJECTION",
        disposition="Generated",
        lines=0,
        bytes=0,
        content_hash="projection-bound-by-ggen-determinism",
        score=0,
        reasons=(),
        projection_source="packs/code-modernization-pack/templates/ggen_code_inventory.rs.tmpl",
        panic_sites=0,
        todo_sites=0,
    )
    return [observed[path] for path in sorted(observed)]


def source_tree_hash(surfaces: list[Surface]) -> str:
    rows = [
        {
            "path": item.path,
            "content_hash": item.content_hash,
            "disposition": item.disposition,
            "score": item.score,
            "reasons": item.reasons,
        }
        for item in surfaces
    ]
    return digest(canonical_json(rows))


def render_instances(surfaces: list[Surface], head: str, tree_hash: str) -> bytes:
    inventory_iri = f"gmod:inventory-{tree_hash[:20]}"
    lines = [
        "@prefix gmod: <https://praxis.chatman.io/ontology/ggen-modernization#> .",
        "@prefix dcterms: <http://purl.org/dc/terms/> .",
        "@prefix prov: <http://www.w3.org/ns/prov#> .",
        "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
        "",
        "# Generated by scripts/build-ggen-code-inventory.py. Do not edit.",
        f"# source-tree-blake3: {tree_hash}",
        "",
        f"{inventory_iri} a gmod:Inventory ;",
        f"    gmod:headSha {ttl(head)} ;",
        f"    gmod:surfaceCount {len(surfaces)} ;",
        f"    gmod:contentHash {ttl('blake3:' + tree_hash)} ;",
    ]
    for index, surface in enumerate(surfaces):
        terminal = "." if index == len(surfaces) - 1 else ";"
        lines.append(f"    gmod:hasSurface gmod:surface-{digest(surface.path.encode())[:24]} {terminal}")
    lines.append("")

    for surface in surfaces:
        iri = f"gmod:surface-{digest(surface.path.encode())[:24]}"
        classes = "gmod:SourceSurface, gmod:CodeSurface"
        if surface.disposition == "Generated":
            classes += ", gmod:GeneratedProjection"
        lines.extend(
            [
                f"{iri} a {classes} ;",
                f"    dcterms:identifier {ttl(surface.path)} ;",
                f"    gmod:path {ttl(surface.path)} ;",
                f"    gmod:language {ttl(surface.language)} ;",
                f"    gmod:owner {ttl(surface.owner)} ;",
                f"    gmod:kind {ttl(surface.kind)} ;",
                f"    gmod:disposition gmod:{surface.disposition} ;",
                f"    gmod:lineCount {surface.lines} ;",
                f"    gmod:byteCount {surface.bytes} ;",
                f"    gmod:contentHash {ttl(surface.content_hash)} ;",
                f"    gmod:candidateScore {surface.score} ;",
            ]
        )
        for reason in surface.reasons:
            lines.append(f"    gmod:candidateReason {ttl(reason)} ;")
        if surface.projection_source:
            lines.append(f"    gmod:projectionSource {ttl(surface.projection_source)} ;")
        lines.extend(
            [
                f"    gmod:candidateReason {ttl('panic-sites:' + str(surface.panic_sites))} ;",
                f"    gmod:candidateReason {ttl('todo-sites:' + str(surface.todo_sites))} .",
                "",
            ]
        )
    return ("\n".join(lines).rstrip() + "\n").encode()


def build() -> int:
    PACK.mkdir(parents=True, exist_ok=True)
    surfaces = observe()
    tree_hash = source_tree_hash(surfaces)
    head = run("git", "rev-parse", "HEAD")
    payload = render_instances(surfaces, head, tree_hash)
    INSTANCES.write_bytes(payload)

    counts: dict[str, int] = {}
    for surface in surfaces:
        counts[surface.disposition] = counts.get(surface.disposition, 0) + 1
    envelope = {
        "schema": "praxis-ggen-code-inventory-receipt.v1",
        "observed_head_sha": head,
        "source_tree_blake3": tree_hash,
        "instances_blake3": digest(payload),
        "surface_count": len(surfaces),
        "disposition_counts": dict(sorted(counts.items())),
        "builder": "scripts/build-ggen-code-inventory.py",
        "projection_outputs": [GENERATED_REGISTRY, GENERATED_REPORT],
    }
    receipt = dict(envelope)
    receipt["receipt_blake3"] = digest(canonical_json(envelope))
    RECEIPT.write_bytes(canonical_json(receipt) + b"\n")

    print("build-ggen-code-inventory: PARTIAL_ALIVE")
    print(json.dumps(receipt, sort_keys=True))
    print("highest_candidates:")
    for surface in sorted(surfaces, key=lambda item: (-item.score, item.path))[:40]:
        if surface.score:
            print(
                f"  {surface.score:>3} {surface.path} "
                f"[{','.join(surface.reasons)}]"
            )
    return 0


def verify() -> int:
    if not INSTANCES.is_file() or not RECEIPT.is_file():
        print(
            "build-ggen-code-inventory: REFUSED: instances or receipt missing",
            file=sys.stderr,
        )
        return 1
    receipt = json.loads(RECEIPT.read_text(encoding="utf-8"))
    received_envelope_hash = receipt.pop("receipt_blake3", None)
    if received_envelope_hash != digest(canonical_json(receipt)):
        print("build-ggen-code-inventory: REFUSED: receipt envelope drift", file=sys.stderr)
        return 1
    actual_instances = digest(INSTANCES.read_bytes())
    if actual_instances != receipt.get("instances_blake3"):
        print(
            "build-ggen-code-inventory: REFUSED: instances.ttl drift",
            file=sys.stderr,
        )
        return 1
    current_tree = source_tree_hash(observe())
    if current_tree != receipt.get("source_tree_blake3"):
        print(
            "build-ggen-code-inventory: REFUSED: tracked source tree changed; rebuild inventory",
            file=sys.stderr,
        )
        return 1
    print(
        "build-ggen-code-inventory: ALIVE: source tree, instances, and receipt recompute"
    )
    return 0


def parse_args(argv: Iterable[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("build", "verify"))
    return parser.parse_args(list(argv))


def main(argv: Iterable[str] = sys.argv[1:]) -> int:
    args = parse_args(argv)
    return build() if args.command == "build" else verify()


if __name__ == "__main__":
    raise SystemExit(main())
