#!/usr/bin/env python3
"""Executable G0-G9 coordinator for Praxis combinatorial maximalism.

The adapter performs repository observation and evidence IO. All combinatorial,
authority, ownership, closure, resource, plan, and broker decisions delegate to
scripts/cmd_kernel.py.
"""

from __future__ import annotations

import argparse
import ast
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
import uuid
from dataclasses import asdict, replace
from datetime import datetime, timezone
from itertools import product
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

import blake3
from rdflib import Graph, Literal, Namespace, RDF, URIRef

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

import cmd_kernel as kernel

CMD = Namespace("https://praxis.chatman.io/ontology/cmd#")
PACK = ROOT / "packs" / "combinatorial-maximalism-pack"
GRAPH_FILES = (
    PACK / "ontology.ttl",
    PACK / "core-instances.ttl",
    PACK / "internal-lattice.ttl",
    PACK / "external-lattice.ttl",
    PACK / "packs-passports.ttl",
    PACK / "gall.ttl",
)
SHAPES = PACK / "shapes.ttl"
OUT = ROOT / os.environ.get("CMD_EVIDENCE_DIR", ".ggen/cmd")
MAX_PRODUCT = int(os.environ.get("CMD_MAX_PRODUCT", "65536"))
COMPILER_IDENTITY = "praxis-cmd-coordinator/v1"
STANDING = {
    "PARTIAL_ALIVE",
    "ALIVE",
    "BLOCKED",
    "BUILD_BROKEN",
    "UNKNOWN",
    "UNSUPPORTED",
}
GENERATED_HEADER = re.compile(
    r"(?i)(generated\s+by\s+ggen|ggen[- ]rendered|@generated|"
    r"do\s+not\s+edit|autogenerated|auto-generated)"
)
SOURCE_HEADER = re.compile(
    r"(?im)^\s*(?://|#|--|/\*)?\s*(?:"
    r"generated\s+by\s+ggen\s+from\s+|"
    r"generated\s+from\s+|source\s*[:=]\s*|ontology\s*[:=]\s*|"
    r"template\s*[:=]\s*)([^\n*]+)"
)
DIRECT_ACTUATOR = re.compile(
    r"(?i)\b(?:boto3|kubernetes|pulumi|terraform|kubectl|helm|"
    r"requests\.(?:post|put|patch|delete)|urllib\.request|"
    r"octokit|github\.Github|git\s+(?:push|merge)|cargo\s+publish|npm\s+publish)\b"
)
TEXT_LIMIT = 4 * 1024 * 1024


class CoordinatorError(RuntimeError):
    pass


def run(*args: str, check: bool = True) -> str:
    completed = subprocess.run(
        args,
        cwd=ROOT,
        check=check,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    return completed.stdout.strip()


def run_bytes(*args: str) -> bytes:
    return subprocess.run(
        args,
        cwd=ROOT,
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    ).stdout


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def canonical_bytes(value: Any) -> bytes:
    return kernel.canonical_json(value)


def digest_bytes(value: bytes) -> str:
    return f"blake3:{blake3.blake3(value).hexdigest()}"


def digest_file(path: Path) -> str:
    return digest_bytes(path.read_bytes())


def atomic_write(path: Path, payload: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temp_name, path)
    finally:
        if os.path.exists(temp_name):
            os.unlink(temp_name)


def write_json(path: Path, value: Any) -> None:
    atomic_write(path, canonical_bytes(value) + b"\n")


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def relative(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def git_identity() -> dict[str, str]:
    head = run("git", "rev-parse", "HEAD")
    tree = run("git", "rev-parse", "HEAD^{tree}")
    remote = run("git", "config", "--get", "remote.origin.url", check=False)
    branch = run("git", "rev-parse", "--abbrev-ref", "HEAD")
    base_ref = os.environ.get("CMD_BASE_REF", branch)
    base_commit = os.environ.get("CMD_BASE_SHA", head)
    return {
        "repository": remote or "UNKNOWN",
        "head_ref": branch,
        "head_commit_sha": head,
        "head_tree_sha": tree,
        "base_ref": base_ref,
        "base_commit_sha": base_commit,
    }


def parse_index() -> list[dict[str, str]]:
    raw = run_bytes("git", "ls-files", "-s", "-z")
    result: list[dict[str, str]] = []
    for record in raw.split(b"\0"):
        if not record:
            continue
        header, path_bytes = record.split(b"\t", 1)
        mode, oid, stage = header.decode("ascii").split()
        path = path_bytes.decode("utf-8", "surrogateescape")
        result.append({"path": path, "mode": mode, "oid": oid, "stage": stage})
    return sorted(result, key=lambda row: (row["path"], row["stage"]))


def parse_tree() -> list[dict[str, str]]:
    raw = run_bytes("git", "ls-tree", "-r", "-t", "-z", "HEAD")
    result: list[dict[str, str]] = []
    for record in raw.split(b"\0"):
        if not record:
            continue
        header, path_bytes = record.split(b"\t", 1)
        mode, object_type, oid = header.decode("ascii").split()
        path = path_bytes.decode("utf-8", "surrogateescape")
        result.append(
            {"path": path, "mode": mode, "object_type": object_type, "oid": oid}
        )
    return sorted(result, key=lambda row: (row["path"], row["object_type"]))


def tracked_leaf_tree() -> list[dict[str, str]]:
    return [row for row in parse_tree() if row["object_type"] in {"blob", "commit"}]


def file_kind(mode: str, object_type: str) -> str:
    if mode == "100755":
        return "executable file"
    if mode == "120000":
        return "symlink"
    if mode == "160000" or object_type == "commit":
        return "gitlink/submodule"
    if mode == "100644":
        return "regular file"
    return "unknown"


def read_tracked_text(path: str, mode: str) -> str | None:
    if mode in {"120000", "160000"}:
        return None
    full = ROOT / path
    try:
        data = full.read_bytes()
    except OSError:
        return None
    if len(data) > TEXT_LIMIT or b"\0" in data[:8192]:
        return None
    try:
        return data.decode("utf-8")
    except UnicodeDecodeError:
        return None


def classify_path(path: str, mode: str, text: str | None) -> str:
    lower = path.lower()
    name = Path(path).name
    suffix = Path(path).suffix.lower()
    if path in {"AGENTS.md", "CLAUDE.md", "CHATGPT-CLOUD-AGENTS.md"} or path.startswith(
        ".claude/rules/"
    ):
        return "authored constitution"
    if mode == "160000":
        return "configuration"
    if text and GENERATED_HEADER.search("\n".join(text.splitlines()[:80])):
        return "generated consequence"
    if suffix in {".tmpl", ".tera", ".j2"} or "/templates/" in f"/{lower}":
        return "template"
    if "/fixtures/" in f"/{lower}" or lower.startswith("fixtures/"):
        return "fixture"
    if lower.startswith((".ggen/", ".cargo-cicd/", "receipts/")):
        return "evidence"
    if lower.startswith(".github/workflows/"):
        return "workflow"
    if name in {
        "Cargo.toml",
        "Cargo.lock",
        "ggen.toml",
        "ggen.lock",
        "justfile",
        "Makefile",
        "Dockerfile",
        "package.json",
        "pnpm-lock.yaml",
        "pyproject.toml",
        "rebar.config",
    } or suffix in {".yml", ".yaml", ".toml"}:
        return "configuration"
    if suffix in {".ttl", ".n3", ".rq", ".sparql", ".pddl", ".owl", ".shacl"}:
        return "domain source"
    if suffix in {
        ".rs", ".py", ".sh", ".bash", ".zsh", ".ts", ".tsx", ".js",
        ".mjs", ".cjs", ".erl", ".hrl", ".ex", ".exs", ".lean", ".c",
        ".h", ".cpp", ".hpp", ".java", ".kt", ".go", ".wat", ".tf",
    }:
        return "implementation"
    if suffix in {".md", ".rst", ".adoc", ".txt"} or lower.startswith("docs/"):
        return "documentation"
    if suffix in {".zip", ".gz", ".xz", ".bz2", ".tar", ".tgz"}:
        return "archive"
    if suffix in {".png", ".jpg", ".jpeg", ".gif", ".svg", ".pdf", ".wasm", ".bin", ".lock"}:
        return "asset"
    return "unknown"


def infer_owner(path: str) -> str:
    parts = Path(path).parts
    if len(parts) >= 2 and parts[0] in {"crates", "apps", "clients", "packs"}:
        return f"{parts[0]}/{parts[1]}"
    if parts and parts[0] == ".github":
        return ".github"
    if parts and parts[0] == "scripts":
        return "repository-automation"
    if parts and parts[0] == "docs":
        return "repository-documentation"
    return "repository-root"


def infer_generator(text: str | None) -> str | None:
    if not text:
        return None
    header = "\n".join(text.splitlines()[:100])
    match = SOURCE_HEADER.search(header)
    return match.group(1).strip().strip("*/ ") if match else None


def detect_load_path(path: str) -> list[str]:
    name = Path(path).name
    if name == "Cargo.toml":
        return ["cargo workspace/package manifest"]
    if name == "ggen.toml":
        return ["ggen root manifest"]
    if path.startswith(".github/workflows/"):
        return ["GitHub Actions workflow discovery"]
    if "/templates/" in f"/{path}" or Path(path).suffix in {".tmpl", ".tera"}:
        return ["ggen pack template discovery"]
    if path.endswith(".rs"):
        return ["Rust module or target discovery"]
    if path.endswith((".ttl", ".n3", ".rq", ".sparql", ".pddl")):
        return ["semantic graph/rule/query loader"]
    if path.endswith((".py", ".sh")) and path.startswith("scripts/"):
        return ["explicit operator command"]
    return []


def observe_data() -> dict[str, Any]:
    identity = git_identity()
    index = parse_index()
    tree = parse_tree()
    leaves = [row for row in tree if row["object_type"] in {"blob", "commit"}]
    index_stage0 = [row for row in index if row["stage"] == "0"]
    index_map = {row["path"]: row for row in index_stage0}
    leaf_map = {row["path"]: row for row in leaves}
    if set(index_map) != set(leaf_map):
        raise kernel.Refusal(
            "CMD-G0-EXACT-SET",
            f"index/tree mismatch index-only={sorted(set(index_map)-set(leaf_map))[:5]} "
            f"tree-only={sorted(set(leaf_map)-set(index_map))[:5]}",
        )

    surfaces: list[dict[str, Any]] = []
    unknowns: list[dict[str, str]] = []
    load_paths: list[dict[str, Any]] = []
    for path in sorted(index_map):
        idx = index_map[path]
        leaf = leaf_map[path]
        if idx["mode"] != leaf["mode"] or idx["oid"] != leaf["oid"]:
            raise kernel.Refusal("CMD-G0-EXACT-SET", f"index/tree identity mismatch: {path}")
        text = read_tracked_text(path, idx["mode"])
        classification = classify_path(path, idx["mode"], text)
        kind = file_kind(idx["mode"], leaf["object_type"])
        generator = infer_generator(text)
        generated = classification == "generated consequence"
        owner = infer_owner(path)
        row = {
            "path": path,
            "mode": idx["mode"],
            "object_type": leaf["object_type"],
            "object_digest": leaf["oid"],
            "kind": kind,
            "classification": classification,
            "semantic_owner": owner,
            "operational_owner": owner,
            "generated": generated,
            "generator": generator,
        }
        surfaces.append(row)
        paths = detect_load_path(path)
        if paths:
            load_paths.append({"path": path, "load_paths": paths})
        if classification == "unknown" or kind == "unknown":
            unknowns.append(
                {
                    "path": path,
                    "reason": "unclassified path or Git object mode",
                    "standing": "UNKNOWN",
                }
            )
        if generated and not generator:
            unknowns.append(
                {
                    "path": path,
                    "reason": "generated header does not name canonical source",
                    "standing": "UNKNOWN",
                }
            )

    untracked_raw = run_bytes("git", "ls-files", "--others", "--exclude-standard", "-z")
    untracked = sorted(
        item.decode("utf-8", "surrogateescape")
        for item in untracked_raw.split(b"\0")
        if item
    )
    tree_digest = kernel.digest(
        [
            {
                "path": item["path"],
                "mode": item["mode"],
                "type": item["object_type"],
                "oid": item["object_digest"],
            }
            for item in surfaces
        ]
    )
    repository = {
        "schema": "ggen.cmd.repository-observation.v1",
        **identity,
        "tree_digest": tree_digest,
        "tracked_object_count": len(surfaces),
        "directory_tree_count": len([row for row in tree if row["object_type"] == "tree"]),
        "untracked_count": len(untracked),
        "observation_time": now_iso(),
        "toolchain": {
            "git": run("git", "--version"),
            "python": sys.version.split()[0],
            "coordinator": COMPILER_IDENTITY,
        },
    }
    return {
        "repository": repository,
        "surfaces": surfaces,
        "load_paths": load_paths,
        "unknowns": unknowns,
        "untracked": untracked,
    }


def observe() -> None:
    value = observe_data()
    write_json(OUT / "observation/repository.json", value["repository"])
    write_json(OUT / "observation/surfaces.json", value["surfaces"])
    write_json(OUT / "observation/load-paths.json", value["load_paths"])
    write_json(OUT / "observation/unknowns.json", value["unknowns"])
    write_json(OUT / "observation/untracked.json", value["untracked"])
    print(
        f"CMD-G0: PARTIAL_ALIVE: tracked={len(value['surfaces'])} "
        f"unknown={len(value['unknowns'])} tree={value['repository']['tree_digest']}"
    )


def verify_observation_data(
    repository: Mapping[str, Any], surfaces: Sequence[Mapping[str, Any]]
) -> None:
    current = observe_data()
    expected_rows = [
        (item["path"], item["mode"], item["object_type"], item["object_digest"])
        for item in surfaces
    ]
    actual_rows = [
        (item["path"], item["mode"], item["object_type"], item["object_digest"])
        for item in current["surfaces"]
    ]
    if expected_rows != actual_rows:
        raise kernel.Refusal("CMD-G0-EXACT-SET", "tracked path/mode/type/digest set changed")
    if repository.get("base_commit_sha") != current["repository"]["base_commit_sha"]:
        raise kernel.Refusal("CMD-G0-EXACT-SET", "resolved base commit changed")
    if repository.get("base_ref") != current["repository"]["base_ref"]:
        raise kernel.Refusal("CMD-G0-EXACT-SET", "resolved base ref changed")
    if repository.get("head_commit_sha") != current["repository"]["head_commit_sha"]:
        raise kernel.Refusal("CMD-G9-EXACT-HEAD", "head commit changed")
    if repository.get("head_tree_sha") != current["repository"]["head_tree_sha"]:
        raise kernel.Refusal("CMD-G0-EXACT-SET", "head tree changed")
    if repository.get("tree_digest") != current["repository"]["tree_digest"]:
        raise kernel.Refusal("CMD-G0-EXACT-SET", "tree digest changed")


def verify_observation() -> None:
    verify_observation_data(
        read_json(OUT / "observation/repository.json"),
        read_json(OUT / "observation/surfaces.json"),
    )
    print("CMD-G0: PARTIAL_ALIVE: exact-set verifier passed")


def ownership_data(surfaces: Sequence[Mapping[str, Any]]) -> dict[str, Any]:
    ownership: list[dict[str, Any]] = []
    fences: list[dict[str, Any]] = []
    outputs: dict[str, list[str]] = {}
    merge_laws: dict[str, str] = {}
    collisions: list[dict[str, Any]] = []
    retirement: list[dict[str, Any]] = []

    for surface in surfaces:
        path = str(surface["path"])
        owner = str(surface.get("semantic_owner") or "UNKNOWN")
        generated = bool(surface.get("generated"))
        generator = surface.get("generator")
        output_owners = [owner]
        outputs[path] = output_owners
        if generated and not generator:
            collisions.append(
                {"code": "CMD-G1-GENERATOR-UNKNOWN", "path": path, "classification": "unknown"}
            )
        text = read_tracked_text(path, str(surface["mode"]))
        direct = bool(text and DIRECT_ACTUATOR.search(text))
        ownership.append(
            {
                "surface": path,
                "semantic_owner": owner,
                "operational_owner": surface.get("operational_owner") or "UNKNOWN",
                "generator": generator or "NONE",
                "consumers": detect_load_path(path) or ["UNKNOWN"],
                "load_path": detect_load_path(path) or ["UNKNOWN"],
                "inputs": [generator] if generator else ["UNKNOWN"],
                "outputs": [path],
                "mutation_scope": path if generated else "NONE_OR_RUNTIME_DEFINED",
                "evidence_produced": ["Git object identity"],
                "failure_behavior": "typed by owning subsystem or UNKNOWN",
                "retirement_dependency": "exact-boundary equivalence and replay",
                "standing": "PARTIAL_ALIVE" if owner != "UNKNOWN" else "UNKNOWN",
                "lifecycle": "ACTIVE",
                "exclusive": True,
                "direct_actuator_signal": direct,
            }
        )
        fences.append(
            {
                "surface": path,
                "why_it_exists": surface["classification"],
                "who_calls_it": detect_load_path(path) or ["UNKNOWN"],
                "what_it_owns": [path] if generated else ["semantic behavior at its load path"],
                "what_it_mutates": [path] if generated else ["UNKNOWN_OR_NONE"],
                "evidence_it_emits": ["Git object identity"],
                "how_it_fails": "owning subsystem contract or UNKNOWN",
                "compatibility_contract": "current repository load path",
                "replacement_requirement": "same object, boundary, failure semantics, receipts, replay",
            }
        )
        if direct:
            collisions.append(
                {
                    "code": "CMD-G1-DIRECT-ACTUATOR-SIGNAL",
                    "path": path,
                    "classification": "review-required",
                }
            )
        if generated:
            retirement.append(
                {
                    "surface": path,
                    "candidate": False,
                    "reason": "generated projection retained; source authority must be preserved",
                    "checkpoint": "G9 exact replay",
                }
            )

    kernel.verify_ownership(outputs, merge_laws)
    return {
        "ownership": ownership,
        "fences": fences,
        "collisions": collisions,
        "retirement": retirement,
        "outputs": outputs,
        "merge_laws": merge_laws,
    }


def ownership() -> None:
    value = ownership_data(read_json(OUT / "observation/surfaces.json"))
    write_json(OUT / "authority/ownership.json", value["ownership"])
    write_json(OUT / "authority/fences.json", value["fences"])
    write_json(OUT / "authority/collisions.json", value["collisions"])
    write_json(OUT / "authority/retirement-candidates.json", value["retirement"])
    print(
        f"CMD-G1: PARTIAL_ALIVE: owned={len(value['ownership'])} "
        f"findings={len(value['collisions'])}"
    )


def verify_ownership() -> None:
    ownership_rows = read_json(OUT / "authority/ownership.json")
    outputs: dict[str, list[str]] = {}
    for row in ownership_rows:
        owner = row.get("semantic_owner")
        outputs[str(row["surface"])] = [] if owner in {None, "", "UNKNOWN"} else [str(owner)]
    kernel.verify_ownership(outputs, {})
    print("CMD-G1: PARTIAL_ALIVE: ownership verifier passed")


def graph() -> Graph:
    g = Graph()
    for path in GRAPH_FILES:
        g.parse(path, format="turtle")
    return g


def local_name(value: Any) -> str:
    text = str(value)
    return text.rsplit("#", 1)[-1].rsplit("/", 1)[-1]


def one(g: Graph, subject: URIRef, predicate: URIRef) -> Any:
    values = list(g.objects(subject, predicate))
    if len(values) != 1:
        raise kernel.Refusal(
            "CMD-G2-CARDINALITY",
            f"{subject} {predicate}: expected one, observed {len(values)}",
        )
    return values[0]


def semantic_data() -> dict[str, Any]:
    g = graph()
    try:
        from pyshacl import validate
    except ImportError as exc:
        raise kernel.Refusal("CMD-G2-SHACL-BLOCKED", "pyshacl is required") from exc
    shapes_graph = Graph()
    shapes_graph.parse(SHAPES, format="turtle")
    conforms, report_graph, report_text = validate(
        data_graph=g,
        shacl_graph=shapes_graph,
        inference="rdfs",
        abort_on_first=False,
        allow_infos=False,
        allow_warnings=False,
    )
    if not conforms:
        raise kernel.Refusal("CMD-G2-SHACL", report_text)
    ontology_digest = kernel.digest(
        {relative(path): digest_file(path) for path in (*GRAPH_FILES, SHAPES)}
    )
    return {
        "schema": "ggen.cmd.semantic-authority.v1",
        "ontology_digest": ontology_digest,
        "triple_count": len(g),
        "shacl_conforms": True,
        "report_digest": digest_bytes(report_graph.serialize(format="turtle").encode()),
        "controlled_standing": sorted(STANDING),
    }


def verify_semantic() -> None:
    result = semantic_data()
    write_json(OUT / "verifier/semantic-authority.json", result)
    print(f"CMD-G2: PARTIAL_ALIVE: SHACL passed; triples={result['triple_count']}")


def dimensions_and_options() -> tuple[list[kernel.Dimension], list[kernel.Option]]:
    g = graph()
    dimensions: list[kernel.Dimension] = []
    options: list[kernel.Option] = []
    for subject in sorted(g.subjects(RDF.type, CMD.Dimension), key=str):
        dimensions.append(
            kernel.Dimension(
                identity=str(one(g, subject, CMD.identity)),
                domain=local_name(one(g, subject, CMD.domain)),
                order=int(one(g, subject, CMD.dimensionOrder)),
                cardinality=int(one(g, subject, CMD.selectionCardinality)),
                coverage_mode=local_name(one(g, subject, CMD.coverageMode)),
                risk_class=str(one(g, subject, CMD.riskClass)),
                resource_ceiling=int(one(g, subject, CMD.resourceCeiling)),
            )
        )
    for subject in sorted(g.subjects(RDF.type, CMD.Option), key=str):
        options.append(
            kernel.Option(
                identity=str(one(g, subject, CMD.identity)),
                dimension=str(one(g, one(g, subject, CMD.forDimension), CMD.identity)),
                implementation=str(one(g, subject, CMD.implementation)),
                resource_cost=int(one(g, subject, CMD.resourceCost)),
                authority_requirement=str(one(g, subject, CMD.authorityRequirement)),
                reversal_class=local_name(one(g, subject, CMD.reversalClass)),
                requires_options=tuple(
                    sorted(
                        str(one(g, option, CMD.identity))
                        for option in g.objects(subject, CMD.requiresOption)
                    )
                ),
                incompatible_with=tuple(
                    sorted(
                        str(one(g, option, CMD.identity))
                        for option in g.objects(subject, CMD.incompatibleWith)
                    )
                ),
                provides_capabilities=tuple(
                    sorted(local_name(value) for value in g.objects(subject, CMD.providesCapability))
                ),
                requires_capabilities=tuple(
                    sorted(local_name(value) for value in g.objects(subject, CMD.requiresCapability))
                ),
            )
        )
    kernel.dimension_map(dimensions)
    kernel.option_map(options, {item.identity: item for item in dimensions})
    return sorted(dimensions, key=lambda item: item.order), sorted(options, key=lambda item: item.identity)


def bounded_product(domain: str, dimensions: Sequence[kernel.Dimension], options: Sequence[kernel.Option]) -> tuple[list[kernel.Candidate], dict[str, Any]]:
    domain_dimensions = [item for item in dimensions if item.domain == domain]
    option_lists = [
        sorted(
            [item for item in options if item.dimension == dimension.identity],
            key=lambda item: item.identity,
        )
        for dimension in domain_dimensions
    ]
    raw_count = 1
    for items in option_lists:
        raw_count *= len(items)
    if raw_count > MAX_PRODUCT:
        raise kernel.Refusal(
            "CMD-G3-PRODUCT-OVERFLOW",
            f"domain={domain}, raw={raw_count}, ceiling={MAX_PRODUCT}",
        )
    valid: list[kernel.Candidate] = []
    refusal_counts: dict[str, int] = {}
    for combination in product(*option_lists):
        selected = {
            dimension.identity: option.identity
            for dimension, option in zip(domain_dimensions, combination, strict=True)
        }
        try:
            candidate = kernel.validate_candidate(domain, selected, dimensions, options)
        except kernel.Refusal as refusal:
            refusal_counts[refusal.code] = refusal_counts.get(refusal.code, 0) + 1
            continue
        valid.append(candidate)
    signatures = [item.signature for item in valid]
    if len(signatures) != len(set(signatures)):
        raise kernel.Refusal("CMD-G3-DUPLICATE-CANDIDATE", domain)
    coverage = kernel.verify_candidate_set(valid, declared_count=len(valid))
    return sorted(valid, key=lambda item: item.signature), {
        "domain": domain,
        "raw_product_count": raw_count,
        "valid_candidate_count": len(valid),
        "refused_candidate_count": raw_count - len(valid),
        "refusal_counts": dict(sorted(refusal_counts.items())),
        **coverage,
    }


def candidate_row(candidate: kernel.Candidate) -> dict[str, Any]:
    return {
        "domain": candidate.domain,
        "selections": dict(candidate.selections),
        "signature": candidate.signature,
        "resource_cost": candidate.resource_cost,
        "verified": candidate.verified,
        "authorized": candidate.authorized,
        "actuated": candidate.actuated,
    }


def candidates() -> None:
    dimensions, options = dimensions_and_options()
    internal, internal_coverage = bounded_product("Internal", dimensions, options)
    external, external_coverage = bounded_product("External", dimensions, options)
    write_json(OUT / "candidates/dimensions.json", [asdict(item) for item in dimensions])
    write_json(OUT / "candidates/options.json", [asdict(item) for item in options])
    write_json(OUT / "candidates/internal-candidates.json", [candidate_row(item) for item in internal])
    write_json(OUT / "candidates/external-candidates.json", [candidate_row(item) for item in external])
    write_json(
        OUT / "candidates/coverage.json",
        {"schema": "ggen.cmd.coverage.v1", "internal": internal_coverage, "external": external_coverage},
    )
    print(
        f"CMD-G3/G4: PARTIAL_ALIVE: internal={len(internal)} external={len(external)}"
    )


def reconstruct_candidate(row: Mapping[str, Any]) -> kernel.Candidate:
    return kernel.Candidate(
        domain=str(row["domain"]),
        selections=tuple(sorted((str(k), str(v)) for k, v in row["selections"].items())),
        signature=str(row["signature"]),
        resource_cost=int(row["resource_cost"]),
        verified=bool(row.get("verified", False)),
        authorized=bool(row.get("authorized", False)),
        actuated=bool(row.get("actuated", False)),
    )


def verify_candidates() -> None:
    dimensions, options = dimensions_and_options()
    for domain, path in (
        ("Internal", OUT / "candidates/internal-candidates.json"),
        ("External", OUT / "candidates/external-candidates.json"),
    ):
        stored = read_json(path)
        recomputed, _ = bounded_product(domain, dimensions, options)
        expected = [candidate_row(item) for item in recomputed]
        if stored != expected:
            raise kernel.Refusal("CMD-G3-COUNT-MISMATCH", f"{domain} candidate projection drift")
    print("CMD-G3/G4: PARTIAL_ALIVE: candidate and coverage replay passed")


def graph_digest(paths: Iterable[Path]) -> str:
    return kernel.digest({relative(path): digest_file(path) for path in paths})


def ownership_digest() -> str:
    return digest_file(OUT / "authority/ownership.json")


def consequence_digest() -> str:
    return kernel.digest(
        {"allowed": ["local.materialize", "github.repository.mutate"], "broker": "BRCE"}
    )


def policy_digest() -> str:
    return graph_digest((PACK / "packs-passports.ttl", SHAPES))


def ontology_digest() -> str:
    return graph_digest((*GRAPH_FILES, SHAPES))


def build_plan() -> None:
    rows = read_json(OUT / "candidates/internal-candidates.json")
    if not rows:
        raise kernel.Refusal("CMD-G6-CANDIDATE-MISSING", "no internal candidate")
    chosen = sorted(rows, key=lambda row: (row["resource_cost"], row["signature"]))[0]
    candidate = replace(reconstruct_candidate(chosen), verified=True)
    repository = read_json(OUT / "observation/repository.json")
    dimensions, options = dimensions_and_options()
    selected_ids = set(dict(candidate.selections).values())
    capabilities = sorted(
        {
            capability
            for option in options
            if option.identity in selected_ids
            for capability in option.provides_capabilities
        }
    )
    plan = kernel.build_plan(
        candidate,
        source_revisions={
            "repository": repository["head_commit_sha"],
            "ontology": ontology_digest(),
        },
        parameters={"mode": "bounded", "max_product": MAX_PRODUCT},
        policy_digest=policy_digest(),
        observed_tree_digest=repository["tree_digest"],
        ownership_digest=ownership_digest(),
        consequence_digest=consequence_digest(),
        compiler_identity=COMPILER_IDENTITY,
        provided_capabilities=capabilities,
    )
    write_json(OUT / "plans/plan.json", asdict(plan))
    write_json(
        OUT / "plans/compatibility-matrix.json",
        [
            {
                "legacy_command": "ggen sync run",
                "legacy_semantic_mode": "root pack projection",
                "new_kernel_operation": "deterministic plan then existing ggen renderer",
                "observed_equivalent_output": "UNKNOWN until exact second sync executes",
                "known_difference": "new kernel makes candidate and authority boundaries explicit",
                "retirement_checkpoint": "G9 clean exact-head replay",
            },
            {
                "legacy_command": "just standing",
                "legacy_semantic_mode": "standing refresh and projection",
                "new_kernel_operation": "retained adapter outside pure candidate kernel",
                "observed_equivalent_output": "not claimed",
                "known_difference": "sibling standing pack remains separately fenced",
                "retirement_checkpoint": "none in this refactor",
            },
        ],
    )
    print(f"CMD-G6: PARTIAL_ALIVE: plan={plan.plan_digest}")


def verify_plan() -> None:
    stored = read_json(OUT / "plans/plan.json")
    before = stored["plan_digest"]
    build_plan()
    after = read_json(OUT / "plans/plan.json")["plan_digest"]
    if before != after:
        raise kernel.Refusal("CMD-G6-PLAN-DIVERGENCE", f"{before} != {after}")
    print("CMD-G6: PARTIAL_ALIVE: deterministic plan replay passed")


def verify_packs() -> None:
    g = graph()
    packs = sorted(g.subjects(RDF.type, CMD.Pack), key=str)
    blocks = sorted(g.subjects(RDF.type, CMD.BuildingBlock), key=str)
    if not packs or not blocks:
        raise kernel.Refusal("CMD-G5-PACK-CLOSURE", "pack or Building Block set is empty")
    identities: set[str] = set()
    for subject in packs:
        identity = str(one(g, subject, CMD.identity))
        if identity in identities:
            raise kernel.Refusal("CMD-G5-PACK-IDENTITY", identity)
        identities.add(identity)
        for predicate in (
            CMD.version, CMD.immutableSource, CMD.verifierCommand, CMD.migrationLaw,
            CMD.rollbackLaw, CMD.license, CMD.trustFloor,
        ):
            one(g, subject, predicate)
    for subject in blocks:
        one(g, subject, CMD.identity)
        members = list(g.objects(subject, CMD.memberPack))
        if not members or any(member not in packs for member in members):
            raise kernel.Refusal("CMD-G5-BBLOCK-CLOSURE", str(subject))
        one(g, subject, CMD.semanticOwner)
        one(g, subject, CMD.policyProfile)
        one(g, subject, CMD.trustFloor)
        one(g, subject, CMD.migrationLaw)
        one(g, subject, CMD.removalLaw)
    print(f"CMD-G5: PARTIAL_ALIVE: packs={len(packs)} bblocks={len(blocks)}")


def safe_target(root: Path, relative_path: str) -> Path:
    if not relative_path or Path(relative_path).is_absolute():
        raise kernel.Refusal("CMD-G7-PATH-ESCAPE", relative_path)
    candidate = (root / relative_path).resolve(strict=False)
    root_resolved = root.resolve(strict=False)
    try:
        candidate.relative_to(root_resolved)
    except ValueError as exc:
        raise kernel.Refusal("CMD-G7-PATH-ESCAPE", relative_path) from exc
    parent = candidate.parent
    while parent != root_resolved.parent and parent != root_resolved:
        if parent.exists() and parent.is_symlink():
            raise kernel.Refusal("CMD-G7-SYMLINK-ESCAPE", str(parent))
        parent = parent.parent
    return candidate


def materializer_fixture(interrupt_at: int | None = None) -> dict[str, Any]:
    steps = [
        "staging creation", "first artifact write", "validator execution",
        "receipt staging", "pre-commit", "commit", "postcondition observation",
        "result-receipt publication",
    ]
    with tempfile.TemporaryDirectory(prefix="praxis-cmd-materializer-") as temp:
        root = Path(temp) / "root"
        root.mkdir()
        target = safe_target(root, "generated/example.txt")
        prior = kernel.digest({"files": []})
        stage = Path(temp) / f"stage-{uuid.uuid4().hex}"
        committed = False
        receipt: dict[str, Any] | None = None
        try:
            stage.mkdir()
            if interrupt_at == 1:
                raise CoordinatorError(steps[0])
            staged_target = safe_target(stage, "generated/example.txt")
            staged_target.parent.mkdir(parents=True, exist_ok=True)
            staged_target.write_text("candidate-bytes\n", encoding="utf-8")
            if interrupt_at == 2:
                raise CoordinatorError(steps[1])
            if staged_target.read_text(encoding="utf-8") != "candidate-bytes\n":
                raise kernel.Refusal("CMD-G7-VALIDATOR", "fixture bytes")
            if interrupt_at == 3:
                raise CoordinatorError(steps[2])
            intent_receipt = {
                "schema": "ggen.cmd.intent-receipt.v1",
                "subject": "generated/example.txt",
                "prior": prior,
                "prospective": digest_file(staged_target),
                "owner": "fixture-owner",
                "grant": "fixture-local-grant",
            }
            intent_receipt["receipt_digest"] = kernel.digest(intent_receipt)
            (stage / "intent.json").write_bytes(canonical_bytes(intent_receipt) + b"\n")
            if interrupt_at == 4:
                raise CoordinatorError(steps[3])
            prospective_bytes = sum(path.stat().st_size for path in stage.rglob("*") if path.is_file())
            if prospective_bytes > 4096:
                raise kernel.Refusal("CMD-G7-RESOURCE-OVERFLOW", str(prospective_bytes))
            if interrupt_at == 5:
                raise CoordinatorError(steps[4])
            final = root / "committed"
            os.replace(stage, final)
            committed = True
            target = final / "generated/example.txt"
            if interrupt_at == 6:
                raise CoordinatorError(steps[5])
            consequence = digest_file(target)
            if interrupt_at == 7:
                raise CoordinatorError(steps[6])
            receipt = {
                "schema": "ggen.cmd.result-receipt.v1",
                "intent_receipt": intent_receipt["receipt_digest"],
                "subject": "generated/example.txt",
                "observed_consequence": consequence,
                "reversal": "REVERSIBLE_WITH_SNAPSHOT",
            }
            receipt["receipt_digest"] = kernel.digest(receipt)
            (final / "result.json").write_bytes(canonical_bytes(receipt) + b"\n")
            if interrupt_at == 8:
                raise CoordinatorError(steps[7])
            return {
                "status": "COMMITTED_WITH_RECEIPT",
                "consequence": consequence,
                "receipt": receipt,
            }
        except CoordinatorError as interruption:
            if committed:
                final = root / "committed"
                if final.exists():
                    shutil.rmtree(final)
            elif stage.exists():
                shutil.rmtree(stage)
            survivors = [path.as_posix() for path in root.rglob("*") if path.is_file()]
            if survivors:
                raise kernel.Refusal("CMD-G7-PARTIAL-STATE", repr(survivors))
            return {"status": "PRIOR_STATE_RESTORED", "interrupted_at": str(interruption)}


def verify_materializer() -> None:
    positive = materializer_fixture()
    chaos = [materializer_fixture(index) for index in range(1, 9)]
    if positive["status"] != "COMMITTED_WITH_RECEIPT":
        raise kernel.Refusal("CMD-G7-PARTIAL-STATE", "positive fixture")
    if any(item["status"] != "PRIOR_STATE_RESTORED" for item in chaos):
        raise kernel.Refusal("CMD-G7-PARTIAL-STATE", "chaos fixture")
    write_json(OUT / "receipts/materializer-fixture.json", {"positive": positive, "chaos": chaos})
    print("CMD-G7: PARTIAL_ALIVE: transactional fixture and 8 chaos points passed")


def external_fixture() -> dict[str, Any]:
    rows = read_json(OUT / "candidates/external-candidates.json")
    if not rows:
        raise kernel.Refusal("CMD-G4-CANDIDATE-MISSING", "no external candidate")
    preferred = [
        row for row in rows
        if row["selections"].get("external.provider") == "provider.github"
        and row["selections"].get("external.consequence") == "consequence.observation-only"
        and row["selections"].get("external.consent") == "consent.explicit-evidence"
    ]
    chosen = sorted(preferred or rows, key=lambda row: (row["resource_cost"], row["signature"]))[0]
    candidate = replace(reconstruct_candidate(chosen), verified=True)
    repository = read_json(OUT / "observation/repository.json")
    intent = kernel.manufacture_intent(
        candidate=candidate,
        operation="observe",
        subject="seanchatmangpt/praxis",
        subject_digest=repository["tree_digest"],
        resource_scope="repository metadata and public source",
        jurisdiction="United States",
        expected_postcondition=repository["head_commit_sha"],
        resource_budget=1,
        expiry_epoch=2_000_000_000,
        idempotency_key=kernel.digest(
            {"candidate": candidate.signature, "subject": repository["tree_digest"], "operation": "observe"}
        ),
        expected_evidence=["git-object", "exact-head"],
    )
    consent = {
        "subject": "seanchatmangpt/praxis",
        "operation": "observe",
        "resource_scope": "repository metadata and public source",
        "purpose": "combinatorial maximalism verification",
        "issuer": "repository owner fixture",
        "issued_epoch": 1_700_000_000,
        "expiry_epoch": 2_000_000_000,
        "revoked": False,
        "evidence_digest": kernel.digest({"fixture": "consent"}),
    }
    grant = {
        "schema": "ggen.cmd.grant.v1",
        "identity": kernel.digest({"intent": intent["identity"], "fixture": "grant"}),
        "intent_identity": intent["identity"],
        "approver_identity": "fixture-independent-approver",
        "policy_digest": policy_digest(),
        "resource_scope": intent["resource_scope"],
        "resource_ceiling": 1,
        "expiry_epoch": 2_000_000_000,
        "subject_digest": repository["tree_digest"],
    }
    kernel.verify_external_authority(
        intent=intent,
        grant=grant,
        consent=consent,
        observed_subject_digest=repository["tree_digest"],
        observed_postcondition=repository["head_commit_sha"],
        required_trust="VERIFIED_PUBLISHER",
        actual_trust="INDEPENDENTLY_VERIFIED",
        allowed_jurisdictions=["United States"],
        now_epoch=1_800_000_000,
    )
    return {
        "candidate": candidate_row(candidate),
        "intent": intent,
        "consent": consent,
        "grant": grant,
        "consequence": {
            "observed": repository["head_commit_sha"],
            "evidence": "Git object read",
            "production_actuation": False,
        },
    }


def verify_external() -> None:
    fixture = external_fixture()
    write_json(OUT / "receipts/intents/fixture.json", fixture)
    print(
        "CMD-G4/G8: PARTIAL_ALIVE: consent/trust/jurisdiction/grant fixture passed; "
        "external production remains UNKNOWN"
    )


def scan_kernel_imports() -> None:
    source = (ROOT / "scripts/cmd_kernel.py").read_text(encoding="utf-8")
    tree = ast.parse(source)
    forbidden = {
        "os", "pathlib", "subprocess", "socket", "requests", "urllib", "http",
        "boto3", "kubernetes", "pulumi", "terraform", "git", "shutil", "tempfile",
    }
    observed: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            observed.update(alias.name.split(".")[0] for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            observed.add(node.module.split(".")[0])
    overlap = sorted(observed & forbidden)
    if overlap:
        raise kernel.Refusal("CMD-G6-ACTUATOR-IMPORT", ",".join(overlap))


def expect_refusal(code: str, function: Any) -> str:
    try:
        function()
    except kernel.Refusal as refusal:
        if refusal.code != code:
            raise kernel.Refusal(
                "CMD-G9-UNEXPECTED-REFUSAL", f"expected={code}, actual={refusal.code}"
            ) from refusal
        return refusal.code
    raise kernel.Refusal("CMD-G9-FALSIFIER-FAILED", f"{code} was accepted")


def sabotage() -> dict[str, Any]:
    refusal_codes: list[str] = []
    repository = read_json(OUT / "observation/repository.json")
    surfaces = read_json(OUT / "observation/surfaces.json")
    refusal_codes.append(
        expect_refusal("CMD-G0-EXACT-SET", lambda: verify_observation_data(repository, surfaces[:-1]))
    )
    refusal_codes.append(
        expect_refusal("CMD-G1-OWNER-MISSING", lambda: kernel.verify_ownership({"fixture": []}, {}))
    )
    refusal_codes.append(
        expect_refusal(
            "CMD-G1-DUPLICATE-AUTHORITY",
            lambda: kernel.verify_ownership({"fixture": ["a", "b"]}, {}),
        )
    )
    dimensions, options = dimensions_and_options()
    internal_rows = read_json(OUT / "candidates/internal-candidates.json")
    if not internal_rows:
        raise kernel.Refusal("CMD-G3-CANDIDATE-MISSING", "no internal candidate fixture")
    valid_selection = dict(internal_rows[0]["selections"])
    refusal_codes.append(
        expect_refusal(
            "CMD-G3-MISSING-DIMENSION",
            lambda: kernel.validate_candidate(
                "Internal",
                {key: value for index, (key, value) in enumerate(valid_selection.items()) if index},
                dimensions,
                options,
            ),
        )
    )
    candidate = kernel.validate_candidate("Internal", valid_selection, dimensions, options)
    refusal_codes.append(
        expect_refusal(
            "CMD-G3-DUPLICATE-CANDIDATE",
            lambda: kernel.verify_candidate_set([candidate, candidate], declared_count=2),
        )
    )
    refusal_codes.append(
        expect_refusal(
            "CMD-G3-COUNT-MISMATCH",
            lambda: kernel.verify_candidate_set([candidate], declared_count=2),
        )
    )
    refusal_codes.append(
        expect_refusal(
            "CMD-G3-PREMATURE-ACTUATION",
            lambda: kernel.validate_candidate(
                "Internal", valid_selection, dimensions, options, actuated=True
            ),
        )
    )
    refusal_codes.append(
        expect_refusal(
            "CMD-G6-CYCLE",
            lambda: kernel.dependency_closure(["a"], {"a": ["b"], "b": ["a"]}),
        )
    )
    scan_kernel_imports()
    refusal_codes.append(
        expect_refusal("CMD-G7-PATH-ESCAPE", lambda: safe_target(Path("/tmp/root"), "../escape"))
    )
    fixture = external_fixture()
    refusal_codes.append(
        expect_refusal(
            "CMD-G4-CONSENT-MISSING",
            lambda: kernel.verify_external_authority(
                intent=fixture["intent"], grant=fixture["grant"], consent=None,
                observed_subject_digest=fixture["grant"]["subject_digest"],
                observed_postcondition=None, required_trust="LOCALLY_ADMITTED",
                actual_trust="LOCALLY_ADMITTED", allowed_jurisdictions=["United States"],
                now_epoch=1_800_000_000,
            ),
        )
    )
    refusal_codes.append(
        expect_refusal(
            "CMD-G4-JURISDICTION",
            lambda: kernel.verify_external_authority(
                intent=fixture["intent"], grant=fixture["grant"], consent=fixture["consent"],
                observed_subject_digest=fixture["grant"]["subject_digest"],
                observed_postcondition=None, required_trust="LOCALLY_ADMITTED",
                actual_trust="LOCALLY_ADMITTED", allowed_jurisdictions=["European Union"],
                now_epoch=1_800_000_000,
            ),
        )
    )
    refusal_codes.append(
        expect_refusal(
            "CMD-G4-TRUST",
            lambda: kernel.verify_external_authority(
                intent=fixture["intent"], grant=fixture["grant"], consent=fixture["consent"],
                observed_subject_digest=fixture["grant"]["subject_digest"],
                observed_postcondition=None, required_trust="VERIFIED_PUBLISHER",
                actual_trust="UNTRUSTED", allowed_jurisdictions=["United States"],
                now_epoch=1_800_000_000,
            ),
        )
    )
    refusal_codes.append(
        expect_refusal(
            "CMD-G8-GRANT-EXPIRED",
            lambda: kernel.verify_external_authority(
                intent=fixture["intent"], grant={**fixture["grant"], "expiry_epoch": 1},
                consent=fixture["consent"],
                observed_subject_digest=fixture["grant"]["subject_digest"],
                observed_postcondition=None, required_trust="LOCALLY_ADMITTED",
                actual_trust="LOCALLY_ADMITTED", allowed_jurisdictions=["United States"],
                now_epoch=1_800_000_000,
            ),
        )
    )
    refusal_codes.append(
        expect_refusal(
            "CMD-G8-POSTCONDITION",
            lambda: kernel.verify_external_authority(
                intent=fixture["intent"], grant=fixture["grant"], consent=fixture["consent"],
                observed_subject_digest=fixture["grant"]["subject_digest"],
                observed_postcondition="wrong", required_trust="LOCALLY_ADMITTED",
                actual_trust="LOCALLY_ADMITTED", allowed_jurisdictions=["United States"],
                now_epoch=1_800_000_000,
            ),
        )
    )
    report = {
        "schema": "ggen.cmd.sabotage.v1",
        "executed": len(refusal_codes),
        "refusal_codes": sorted(refusal_codes),
        "all_refused": True,
    }
    write_json(OUT / "verifier/sabotage.json", report)
    print(f"CMD-G9: PARTIAL_ALIVE: sabotage refusals={len(refusal_codes)}")
    return report


def evidence_manifest() -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for path in sorted(OUT.rglob("*")):
        if path.is_file() and path.name not in {"chain.json", "replay.json", "report.json", "crown.json"}:
            rows.append({"path": path.relative_to(OUT).as_posix(), "digest": digest_file(path)})
    return rows


def build_receipt_chain() -> dict[str, Any]:
    predecessor = "GENESIS"
    records: list[dict[str, Any]] = []
    for row in evidence_manifest():
        record = {
            "schema": "ggen.cmd.receipt.v1",
            "predecessor": predecessor,
            "subject": row["path"],
            "observed_digest": row["digest"],
            "consequence": "evidence artifact exists",
        }
        record["receipt_digest"] = kernel.digest(record)
        predecessor = record["receipt_digest"]
        records.append(record)
    chain = {
        "schema": "ggen.cmd.receipt-chain.v1",
        "records": records,
        "head": predecessor,
        "record_count": len(records),
    }
    write_json(OUT / "receipts/chain.json", chain)
    return chain


def replay_data() -> dict[str, Any]:
    verify_observation_data(
        read_json(OUT / "observation/repository.json"),
        read_json(OUT / "observation/surfaces.json"),
    )
    verify_ownership()
    observed_semantic = semantic_data()
    recorded_semantic = read_json(OUT / "verifier/semantic-authority.json")
    if observed_semantic != recorded_semantic:
        raise kernel.Refusal("CMD-G2-PROJECTION-DRIFT", "semantic authority report diverged")
    verify_candidates()
    verify_packs()
    verify_plan()
    chain = read_json(OUT / "receipts/chain.json")
    predecessor = "GENESIS"
    for record in chain["records"]:
        body = {key: value for key, value in record.items() if key != "receipt_digest"}
        if record["predecessor"] != predecessor:
            raise kernel.Refusal("CMD-G9-RECEIPT-TAMPER", record["subject"])
        if kernel.digest(body) != record["receipt_digest"]:
            raise kernel.Refusal("CMD-G9-RECEIPT-TAMPER", record["subject"])
        predecessor = record["receipt_digest"]
    if predecessor != chain["head"]:
        raise kernel.Refusal("CMD-G9-RECEIPT-TAMPER", "chain head")
    return {
        "schema": "ggen.cmd.replay.v1",
        "subject_head": read_json(OUT / "observation/repository.json")["head_commit_sha"],
        "chain_head": chain["head"],
        "replay_digest": kernel.digest(
            {
                "plan": read_json(OUT / "plans/plan.json")["plan_digest"],
                "chain": chain["head"],
                "tree": read_json(OUT / "observation/repository.json")["tree_digest"],
            }
        ),
        "result": "PASS",
    }


def replay() -> dict[str, Any]:
    result = replay_data()
    write_json(OUT / "replay/replay.json", result)
    print(f"CMD-G9: PARTIAL_ALIVE: replay={result['replay_digest']}")
    return result


def gall_data() -> dict[str, Any]:
    g = graph()
    checkpoints: list[dict[str, Any]] = []
    for subject in sorted(
        g.subjects(RDF.type, CMD.Checkpoint),
        key=lambda item: int(one(g, item, CMD.checkpointOrder)),
    ):
        checkpoints.append(
            {
                "code": str(one(g, subject, CMD.checkpointCode)),
                "order": int(one(g, subject, CMD.checkpointOrder)),
                "dependencies": sorted(
                    str(one(g, dependency, CMD.checkpointCode))
                    for dependency in g.objects(subject, CMD.dependsOnCheckpoint)
                ),
                "allowed_paths": sorted(str(value) for value in g.objects(subject, CMD.allowedPath)),
                "forbidden_paths": sorted(str(value) for value in g.objects(subject, CMD.forbiddenPath)),
                "required_commands": sorted(str(value) for value in g.objects(subject, CMD.requiredCommand)),
                "required_artifacts": sorted(str(value) for value in g.objects(subject, CMD.requiredArtifact)),
                "required_refusals": sorted(str(value) for value in g.objects(subject, CMD.requiredRefusal)),
                "standing_ceiling": local_name(one(g, subject, CMD.standingCeiling)),
            }
        )
    return {
        "schema": "ggen.cmd.gall-checkpoints.v1",
        "checkpoints": checkpoints,
        "dependency_closed": all(
            all(dep in {row["code"] for row in checkpoints[:index]} for dep in row["dependencies"])
            for index, row in enumerate(checkpoints)
        ),
    }


def emit_gall() -> dict[str, Any]:
    value = gall_data()
    write_json(OUT / "gall/checkpoints.json", value)
    for checkpoint in value["checkpoints"]:
        write_json(
            OUT / f"gall/work-orders/{checkpoint['code'].lower()}.json",
            {
                "schema": "ggen.cmd.work-order.v1",
                "repository": "seanchatmangpt/praxis",
                "exact_base_sha": read_json(OUT / "observation/repository.json")["base_commit_sha"],
                **checkpoint,
            },
        )
    return value


def crown() -> dict[str, Any]:
    required = {
        "G0": ["observation/repository.json", "observation/surfaces.json", "observation/load-paths.json", "observation/unknowns.json"],
        "G1": ["authority/ownership.json", "authority/fences.json", "authority/collisions.json", "authority/retirement-candidates.json"],
        "G2": ["verifier/semantic-authority.json"],
        "G3": ["candidates/dimensions.json", "candidates/options.json", "candidates/internal-candidates.json", "candidates/coverage.json"],
        "G4": ["candidates/external-candidates.json", "receipts/intents/fixture.json"],
        "G5": ["plans/compatibility-matrix.json"],
        "G6": ["plans/plan.json"],
        "G7": ["receipts/materializer-fixture.json", "receipts/chain.json"],
        "G8": ["receipts/intents/fixture.json"],
        "G9": ["verifier/sabotage.json", "replay/replay.json", "gall/checkpoints.json"],
    }
    passed: list[str] = []
    failed: list[str] = []
    for checkpoint, paths in required.items():
        missing = [path for path in paths if not (OUT / path).is_file()]
        if missing:
            failed.append(f"{checkpoint}:missing:{','.join(missing)}")
        else:
            passed.append(checkpoint)

    repository = read_json(OUT / "observation/repository.json")
    unknowns = read_json(OUT / "observation/unknowns.json")
    collisions = read_json(OUT / "authority/collisions.json")
    sabotage_report = read_json(OUT / "verifier/sabotage.json")
    replay_report = read_json(OUT / "replay/replay.json")
    checkpoints = {
        code: ("PARTIAL_ALIVE" if code in passed else "BUILD_BROKEN") for code in required
    }
    aggregate = "BUILD_BROKEN" if failed else "PARTIAL_ALIVE"
    blocked = [
        "exact external reference-pack identities unresolved",
        "full mixed-language verification ladder not executed by this bounded rail",
    ]
    unknown = [
        f"live authority/classification unknowns={len(unknowns)}",
        "external production consequence unexecuted",
        "GitHub runner/result may be pending outside this process",
    ]
    report = {
        "schema": "ggen.verifier.report.v1",
        "exact_subject_revision": repository["head_commit_sha"],
        "tree_digest": repository["tree_digest"],
        "toolchain": repository["toolchain"],
        "policy_digest": policy_digest(),
        "ontology_digest": ontology_digest(),
        "suite_inventory": [
            "protocol/unit", "property matrix", "filesystem integration fixture",
            "black-box coordinator", "security import scan", "chaos materializer",
            "bounded candidate stress", "candidate metrics", "replay",
            "external verifier report",
        ],
        "commands": [
            "python3 scripts/cmd-refactor.py all",
            "python3 -m unittest scripts.tests.test_cmd_kernel",
        ],
        "boundaries_crossed": [
            "real Git index/tree", "real filesystem", "real JSON serialization",
            "real Turtle and SHACL validation", "real receipt verification", "real replay",
        ],
        "evidence_artifacts": evidence_manifest(),
        "passed_checks": passed,
        "failed_checks": failed,
        "blocked_checks": blocked,
        "unknown_checks": unknown,
        "unsupported_checks": [],
        "refusal_codes": sabotage_report["refusal_codes"],
        "benchmark_measurements": {
            "internal_valid_candidates": read_json(OUT / "candidates/coverage.json")["internal"]["valid_candidate_count"],
            "external_valid_candidates": read_json(OUT / "candidates/coverage.json")["external"]["valid_candidate_count"],
            "receipt_records": read_json(OUT / "receipts/chain.json")["record_count"],
        },
        "replay_result": replay_report,
        "checkpoint_standing": checkpoints,
        "external_production_standing": "UNKNOWN",
        "aggregate_standing": aggregate,
        "verifier_identity": "praxis-cmd-independent-verifier/v1",
        "collisions_or_findings": len(collisions),
    }
    write_json(OUT / "verifier/report.json", report)
    write_json(
        OUT / "gall/crown.json",
        {
            "schema": "ggen.cmd.crown.v1",
            "checkpoint_standing": checkpoints,
            "aggregate": aggregate,
            "alive_conditions_met": False,
            "blocking_findings": blocked,
            "unknown_live_authority": unknown,
        },
    )
    print(f"CMD-G9: {aggregate}: report emitted; ALIVE ceiling not reached")
    return report


def finalize_execution_receipt(report: Mapping[str, Any]) -> dict[str, Any]:
    replay_report = read_json(OUT / "replay/replay.json")
    chain = read_json(OUT / "receipts/chain.json")
    body = {
        "schema": "ggen.cmd.finalizer-receipt.v1",
        "predecessor": chain["head"],
        "subject_head": report["exact_subject_revision"],
        "tree_digest": report["tree_digest"],
        "plan_digest": read_json(OUT / "plans/plan.json")["plan_digest"],
        "replay_digest": replay_report["replay_digest"],
        "verifier_report_digest": digest_file(OUT / "verifier/report.json"),
        "crown_digest": digest_file(OUT / "gall/crown.json"),
        "aggregate_standing": report["aggregate_standing"],
        "external_production_standing": report["external_production_standing"],
    }
    body["receipt_digest"] = kernel.digest(body)
    write_json(OUT / "receipts/finalizer.json", body)
    return body


def all_steps() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    intent = {
        "schema": "ggen.cmd.run-intent.v1",
        "subject": git_identity(),
        "operation": "execute bounded G0-G9 evidence manufacture",
        "authority": "repository branch workflow",
        "standing_ceiling": "PARTIAL_ALIVE",
    }
    intent["intent_digest"] = kernel.digest(intent)
    write_json(OUT / "receipts/intents/run.json", intent)

    observe()
    ownership()
    verify_semantic()
    candidates()
    build_plan()
    verify_packs()
    scan_kernel_imports()
    verify_materializer()
    verify_external()
    emit_gall()
    sabotage()
    build_receipt_chain()
    replay()
    report = crown()
    finalize_execution_receipt(report)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "command",
        choices=[
            "observe", "verify-observation", "ownership", "verify-ownership",
            "verify-semantic", "candidates", "verify-candidates", "plan",
            "verify-plan", "verify-packs", "verify-materializer", "verify-external",
            "sabotage", "replay", "crown", "all",
        ],
    )
    args = parser.parse_args()
    commands = {
        "observe": observe,
        "verify-observation": verify_observation,
        "ownership": ownership,
        "verify-ownership": verify_ownership,
        "verify-semantic": verify_semantic,
        "candidates": candidates,
        "verify-candidates": verify_candidates,
        "plan": build_plan,
        "verify-plan": verify_plan,
        "verify-packs": verify_packs,
        "verify-materializer": verify_materializer,
        "verify-external": verify_external,
        "sabotage": sabotage,
        "replay": replay,
        "crown": crown,
        "all": all_steps,
    }
    try:
        commands[args.command]()
    except kernel.Refusal as refusal:
        print(str(refusal), file=sys.stderr)
        return 1
    except (OSError, subprocess.CalledProcessError, CoordinatorError) as error:
        print(f"BUILD_BROKEN: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
