#!/usr/bin/env python3
"""Inventory Praxis source surfaces for ggen modernization.

This tool is read-only with respect to tracked repository files. It classifies
all tracked text surfaces, discovers existing ggen packs/templates/ontologies,
ranks hand-authored code that is structurally suitable for graph projection,
and emits a BLAKE3-bound receipt.

Standing boundary: this is an audit and admission rail. It does not claim that a
candidate is safe to generate, and it never edits a generated output.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import subprocess
import sys
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable

try:
    import blake3  # type: ignore[import-not-found]
except ImportError as exc:  # pragma: no cover - exercised by workflow bootstrap
    raise SystemExit(
        "ggen-modernization-audit: REFUSED: Python package 'blake3' is required"
    ) from exc

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = ROOT / "target" / "ggen-modernization"

CODE_SUFFIXES = {
    ".rs",
    ".py",
    ".sh",
    ".bash",
    ".zsh",
    ".ts",
    ".tsx",
    ".js",
    ".mjs",
    ".cjs",
    ".erl",
    ".hrl",
    ".ex",
    ".exs",
    ".lean",
    ".c",
    ".h",
    ".cpp",
    ".hpp",
    ".java",
    ".kt",
    ".kts",
    ".go",
    ".wasm",
    ".wat",
}

DECLARATIVE_SUFFIXES = {
    ".toml",
    ".yaml",
    ".yml",
    ".json",
    ".jsonl",
    ".ttl",
    ".n3",
    ".rq",
    ".sparql",
    ".pddl",
    ".owl",
    ".rdf",
    ".xml",
    ".md",
    ".tex",
}

TEXT_SUFFIXES = CODE_SUFFIXES | DECLARATIVE_SUFFIXES | {".tmpl", ".j2", ".tera"}

GENERATED_MARKERS = re.compile(
    r"(?i)(generated\s+by\s+ggen|ggen[- ]rendered|@generated|do\s+not\s+edit|"
    r"generated\s+file|autogenerated|auto-generated)"
)
GGEN_MARKERS = re.compile(r"(?i)\bggen\b|\.ggen-v2|ggen\.lock")
TEMPLATE_SUFFIXES = (".tmpl", ".j2", ".tera")
OUTPUT_KEY = re.compile(
    r"(?im)^\s*(?:output|target|destination|path|file|output_path)\s*[:=]\s*[\"']?([^\"'\s#]+)"
)
SOURCE_HINT = re.compile(
    r"(?im)^\s*(?://|#|--|/\*)?\s*(?:source|generated\s+from|ontology|template)\s*[:=]\s*([^\n*]+)"
)
STATIC_TABLE = re.compile(
    r"(?m)\b(?:const|static)\s+[A-Z][A-Z0-9_]{2,}\b|"
    r"\b(?:REGISTRY|CATEGORIES|ROUTES|COMMANDS|STATUSES|BREEDS|ALGORITHMS|"
    r"CAPABILITIES|PREDICATES|VOCABULARY|SCHEMAS)\b"
)
CLI_MARKER = re.compile(r"#\[(?:noun|verb|command|arg|derive\([^\]]*(?:Parser|Subcommand))")
URL_OR_URN = re.compile(r"(?:https?://|urn:)[^\s\"'<>]+")
MATCH_ARM = re.compile(r"(?m)^\s*(?:[A-Za-z0-9_:|(){}.,\s]+)\s*=>")
LITERAL_ID = re.compile(r"[\"'](?:[A-Z][A-Z0-9_-]{2,}|[a-z][a-z0-9_-]{3,})[\"']")
PANIC_PATTERN = re.compile(r"\.(?:unwrap|expect)\s*\(|\bpanic!\s*\(|\.unwrap_or_default\s*\(")
TODO_PATTERN = re.compile(r"(?i)\b(?:TODO|FIXME|HACK)\b")

EXCLUDED_PREFIXES = (
    ".git/",
    "target/",
    ".agents/",
    ".cargo-cicd/",
    ".ggen-v2/",
    "vendor/",
    "node_modules/",
)


@dataclass(frozen=True)
class Surface:
    path: str
    suffix: str
    kind: str
    bytes: int
    lines: int
    generated_marker: bool
    ggen_marker: bool
    inferred_source: str | None
    candidate_score: int
    candidate_reasons: tuple[str, ...]
    panic_sites: int
    todo_sites: int


def run(*args: str) -> str:
    completed = subprocess.run(
        args,
        cwd=ROOT,
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    return completed.stdout.strip()


def tracked_files() -> list[Path]:
    raw = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=ROOT,
        check=True,
        stdout=subprocess.PIPE,
    ).stdout
    paths: list[Path] = []
    for item in raw.split(b"\0"):
        if not item:
            continue
        rel = item.decode("utf-8", errors="surrogateescape")
        if rel.startswith(EXCLUDED_PREFIXES):
            continue
        paths.append(ROOT / rel)
    return paths


def read_text(path: Path) -> str | None:
    try:
        data = path.read_bytes()
    except OSError:
        return None
    if b"\0" in data[:8192]:
        return None
    try:
        return data.decode("utf-8")
    except UnicodeDecodeError:
        return None


def classify(path: Path, text: str) -> str:
    rel = path.relative_to(ROOT).as_posix()
    suffix = path.suffix.lower()
    if rel == "ggen.toml" or rel == "ggen.lock":
        return "GGEN_CONTROL"
    if rel.startswith("packs/") and path.name == "pack.toml":
        return "PACK_CONTROL"
    if rel.startswith("packs/") and "/templates/" in rel:
        return "TEMPLATE"
    if suffix in TEMPLATE_SUFFIXES:
        return "TEMPLATE"
    if suffix in {".ttl", ".n3", ".owl", ".rdf"}:
        return "ONTOLOGY_OR_RULE"
    if GENERATED_MARKERS.search(text):
        return "GENERATED_PROJECTION"
    if suffix in CODE_SUFFIXES:
        return "HAND_AUTHORED_CODE"
    if suffix in DECLARATIVE_SUFFIXES:
        return "DECLARATIVE_SOURCE"
    return "OTHER_TEXT"


def infer_template_output(text: str) -> str | None:
    head = "\n".join(text.splitlines()[:100])
    match = OUTPUT_KEY.search(head)
    return match.group(1).strip() if match else None


def infer_generated_source(text: str) -> str | None:
    head = "\n".join(text.splitlines()[:80])
    match = SOURCE_HINT.search(head)
    if match:
        return match.group(1).strip().strip("*/ ")
    return None


def score_candidate(path: Path, text: str, kind: str) -> tuple[int, tuple[str, ...]]:
    if kind != "HAND_AUTHORED_CODE":
        return 0, ()
    rel = path.relative_to(ROOT).as_posix()
    lower_rel = rel.lower()
    if any(token in lower_rel for token in ("/tests/", "_test.", "/fixtures/", "/examples/")):
        test_penalty = 12
    else:
        test_penalty = 0

    score = 0
    reasons: list[str] = []
    line_count = text.count("\n") + 1

    static_hits = len(STATIC_TABLE.findall(text))
    if static_hits:
        points = min(35, 8 + static_hits * 3)
        score += points
        reasons.append(f"static-registry:{static_hits}")

    cli_hits = len(CLI_MARKER.findall(text))
    if cli_hits:
        score += min(30, 10 + cli_hits * 2)
        reasons.append(f"cli-schema:{cli_hits}")

    url_hits = len(URL_OR_URN.findall(text))
    if url_hits >= 4:
        score += min(25, 5 + url_hits // 2)
        reasons.append(f"embedded-vocabulary:{url_hits}")

    match_hits = len(MATCH_ARM.findall(text))
    if match_hits >= 8:
        score += min(20, match_hits // 2)
        reasons.append(f"match-table:{match_hits}")

    literal_hits = len(LITERAL_ID.findall(text))
    if literal_hits >= 16:
        score += min(20, literal_hits // 8)
        reasons.append(f"literal-id-density:{literal_hits}")

    if line_count >= 1200:
        score += 18
        reasons.append(f"large-surface:{line_count}")
    elif line_count >= 500:
        score += 12
        reasons.append(f"large-surface:{line_count}")
    elif line_count >= 250:
        score += 6
        reasons.append(f"large-surface:{line_count}")

    if "include_str!(" in text or "include_bytes!(" in text:
        score += 8
        reasons.append("embedded-artifact")

    if "serde" in text and ("enum " in text or "struct " in text):
        score += 4
        reasons.append("serializable-schema")

    score = max(0, score - test_penalty)
    if test_penalty:
        reasons.append("test-surface-penalty")
    return score, tuple(reasons)


def digest_bytes(data: bytes) -> str:
    return blake3.blake3(data).hexdigest()


def digest_file(path: Path) -> str:
    return digest_bytes(path.read_bytes())


def canonical_json(value: object) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()


def audit(out_dir: Path) -> int:
    out_dir.mkdir(parents=True, exist_ok=True)
    files = tracked_files()
    surfaces: list[Surface] = []
    template_outputs: dict[str, str | None] = {}
    pack_roots: list[str] = []

    for path in files:
        rel = path.relative_to(ROOT).as_posix()
        if path.name == "pack.toml" and rel.startswith("packs/"):
            pack_roots.append(str(Path(rel).parent))

        text = read_text(path)
        if text is None:
            continue
        suffix = path.suffix.lower()
        if suffix not in TEXT_SUFFIXES and path.name not in {
            "Cargo.toml",
            "justfile",
            "Makefile",
            "Dockerfile",
            "ggen.toml",
            "ggen.lock",
        }:
            continue

        kind = classify(path, text)
        score, reasons = score_candidate(path, text, kind)
        inferred_source = infer_generated_source(text) if kind == "GENERATED_PROJECTION" else None
        if kind == "TEMPLATE":
            template_outputs[rel] = infer_template_output(text)

        surfaces.append(
            Surface(
                path=rel,
                suffix=suffix or path.name,
                kind=kind,
                bytes=path.stat().st_size,
                lines=text.count("\n") + 1,
                generated_marker=bool(GENERATED_MARKERS.search(text)),
                ggen_marker=bool(GGEN_MARKERS.search(text)),
                inferred_source=inferred_source,
                candidate_score=score,
                candidate_reasons=reasons,
                panic_sites=len(PANIC_PATTERN.findall(text)) if suffix == ".rs" else 0,
                todo_sites=len(TODO_PATTERN.findall(text)),
            )
        )

    surfaces.sort(key=lambda item: item.path)
    candidates = sorted(
        (surface for surface in surfaces if surface.candidate_score > 0),
        key=lambda item: (-item.candidate_score, item.path),
    )

    kind_counts = Counter(surface.kind for surface in surfaces)
    suffix_counts = Counter(surface.suffix for surface in surfaces if surface.kind == "HAND_AUTHORED_CODE")
    generated_without_source = [
        surface.path
        for surface in surfaces
        if surface.kind == "GENERATED_PROJECTION" and not surface.inferred_source
    ]
    unmapped_templates = sorted(path for path, output in template_outputs.items() if output is None)
    panic_files = sorted(
        ((surface.path, surface.panic_sites) for surface in surfaces if surface.panic_sites),
        key=lambda pair: (-pair[1], pair[0]),
    )
    todo_files = sorted(
        ((surface.path, surface.todo_sites) for surface in surfaces if surface.todo_sites),
        key=lambda pair: (-pair[1], pair[0]),
    )

    inventory = {
        "schema": "praxis-ggen-modernization-inventory.v1",
        "repository": run("git", "config", "--get", "remote.origin.url") or "unknown",
        "head_sha": run("git", "rev-parse", "HEAD"),
        "base_sha": os.environ.get("GGEN_AUDIT_BASE_SHA", "UNKNOWN"),
        "tracked_file_count": len(files),
        "text_surface_count": len(surfaces),
        "pack_roots": sorted(pack_roots),
        "template_outputs": dict(sorted(template_outputs.items())),
        "kind_counts": dict(sorted(kind_counts.items())),
        "code_suffix_counts": dict(sorted(suffix_counts.items())),
        "generated_without_source": generated_without_source,
        "templates_without_inferred_output": unmapped_templates,
        "panic_files": [{"path": path, "sites": sites} for path, sites in panic_files],
        "todo_files": [{"path": path, "sites": sites} for path, sites in todo_files],
        "surfaces": [asdict(surface) for surface in surfaces],
    }

    inventory_path = out_dir / "inventory.json"
    inventory_path.write_bytes(canonical_json(inventory) + b"\n")

    candidates_path = out_dir / "candidates.tsv"
    with candidates_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, delimiter="\t", lineterminator="\n")
        writer.writerow(["score", "path", "lines", "reasons", "panic_sites", "todo_sites"])
        for candidate in candidates:
            writer.writerow(
                [
                    candidate.candidate_score,
                    candidate.path,
                    candidate.lines,
                    ",".join(candidate.candidate_reasons),
                    candidate.panic_sites,
                    candidate.todo_sites,
                ]
            )

    top = candidates[:80]
    report_lines = [
        "# Praxis ggen Modernization Audit",
        "",
        "## Standing",
        "",
        "**PARTIAL_ALIVE** — the exact tracked tree was inventoried and the audit outputs are",
        "BLAKE3-bound. Candidate ranking is diagnostic; it is not migration authority.",
        "",
        "## Exact tree",
        "",
        f"- Head: `{inventory['head_sha']}`",
        f"- Base: `{inventory['base_sha']}`",
        f"- Tracked files: **{len(files)}**",
        f"- Text surfaces classified: **{len(surfaces)}**",
        f"- ggen pack roots: **{len(pack_roots)}**",
        f"- Templates discovered: **{len(template_outputs)}**",
        f"- Generated projections discovered: **{kind_counts.get('GENERATED_PROJECTION', 0)}**",
        f"- Ranked hand-authored code candidates: **{len(candidates)}**",
        "",
        "## Classification",
        "",
        "| Kind | Count |",
        "|---|---:|",
    ]
    report_lines.extend(f"| `{kind}` | {count} |" for kind, count in sorted(kind_counts.items()))
    report_lines.extend(
        [
            "",
            "## Drift-risk findings",
            "",
            f"- Generated projections without an inferred source header: **{len(generated_without_source)}**",
            f"- Templates without an inferred output in frontmatter: **{len(unmapped_templates)}**",
            f"- Rust files containing panic/default shortcuts: **{len(panic_files)}**",
            f"- Text files containing TODO/FIXME/HACK markers: **{len(todo_files)}**",
            "",
            "## Highest-value ggen candidates",
            "",
            "| Score | Path | Lines | Reasons |",
            "|---:|---|---:|---|",
        ]
    )
    for candidate in top:
        report_lines.append(
            f"| {candidate.candidate_score} | `{candidate.path}` | {candidate.lines} | "
            f"{', '.join(candidate.candidate_reasons)} |"
        )

    report_lines.extend(
        [
            "",
            "## Admission rules for migration",
            "",
            "1. Preserve the current code path and its owning tests before projection.",
            "2. Admit a graph/spec source and closed vocabulary for the surface.",
            "3. Add a deterministic ggen template and explicit output mapping.",
            "4. Render twice and require a clean second diff.",
            "5. Run positive, negative, and mutation fixtures at the real boundary.",
            "6. Remove hand-authored authority only after generated equivalence is observed.",
            "",
            "## Exclusions",
            "",
            "This audit does not classify semantic suitability, prove runtime equivalence,",
            "rewrite application code, or promote any subsystem to ALIVE.",
            "",
            "## Falsifier",
            "",
            "Receipt verification must refuse if any emitted audit artifact changes.",
            "The CI tamper control mutates a copy and requires that refusal.",
            "",
        ]
    )
    report_path = out_dir / "GGEN_MODERNIZATION_AUDIT.md"
    report_path.write_text("\n".join(report_lines), encoding="utf-8")

    payload = {
        "schema": "praxis-ggen-modernization-receipt.v1",
        "head_sha": inventory["head_sha"],
        "base_sha": inventory["base_sha"],
        "artifacts": {
            "inventory.json": digest_file(inventory_path),
            "candidates.tsv": digest_file(candidates_path),
            "GGEN_MODERNIZATION_AUDIT.md": digest_file(report_path),
        },
        "counts": {
            "tracked_files": len(files),
            "text_surfaces": len(surfaces),
            "packs": len(pack_roots),
            "templates": len(template_outputs),
            "generated_projections": kind_counts.get("GENERATED_PROJECTION", 0),
            "candidates": len(candidates),
        },
    }
    receipt = dict(payload)
    receipt["receipt_blake3"] = digest_bytes(canonical_json(payload))
    receipt_path = out_dir / "receipt.json"
    receipt_path.write_bytes(canonical_json(receipt) + b"\n")

    print("ggen-modernization-audit: PARTIAL_ALIVE")
    print(json.dumps(receipt["counts"], sort_keys=True))
    print(f"receipt_blake3={receipt['receipt_blake3']}")
    print("top_candidates:")
    for candidate in candidates[:30]:
        print(
            f"  {candidate.candidate_score:>3} {candidate.path} "
            f"[{','.join(candidate.candidate_reasons)}]"
        )
    return 0


def verify(out_dir: Path) -> int:
    receipt_path = out_dir / "receipt.json"
    if not receipt_path.is_file():
        print("ggen-modernization-audit: REFUSED: receipt.json is missing", file=sys.stderr)
        return 1
    receipt = json.loads(receipt_path.read_text(encoding="utf-8"))
    received_digest = receipt.pop("receipt_blake3", None)
    expected_digest = digest_bytes(canonical_json(receipt))
    if received_digest != expected_digest:
        print("ggen-modernization-audit: REFUSED: receipt envelope drift", file=sys.stderr)
        return 1
    for name, expected in receipt.get("artifacts", {}).items():
        path = out_dir / name
        if not path.is_file():
            print(f"ggen-modernization-audit: REFUSED: missing artifact {name}", file=sys.stderr)
            return 1
        actual = digest_file(path)
        if actual != expected:
            print(
                f"ggen-modernization-audit: REFUSED: artifact drift {name}: "
                f"expected={expected} actual={actual}",
                file=sys.stderr,
            )
            return 1
    print(
        "ggen-modernization-audit: ALIVE: receipt and all emitted artifacts recompute"
    )
    return 0


def parse_args(argv: Iterable[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("audit", "verify"))
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    return parser.parse_args(list(argv))


def main(argv: Iterable[str] = sys.argv[1:]) -> int:
    args = parse_args(argv)
    out = args.out if args.out.is_absolute() else ROOT / args.out
    if args.command == "audit":
        return audit(out)
    return verify(out)


if __name__ == "__main__":
    raise SystemExit(main())
