#!/usr/bin/env python3
"""Stable entrypoint for the ggen code-inventory builder.

`ggen.lock` records the rendered pack graph and therefore changes as a
consequence of this inventory. It cannot also be an input to the inventory
content hash without creating a self-invalidating cycle. Tracked inventory is
bound to the filtered BLAKE3 source tree, while the separate execution receipt
binds to the exact Git head. This wrapper also completes the polyglot vocabulary
and narrows generated authority to explicit headers.
"""

from __future__ import annotations

import importlib.util
import json
import re
import sys
from pathlib import Path
from types import ModuleType

ROOT = Path(__file__).resolve().parents[1]
BUILDER = ROOT / "scripts" / "build-ggen-code-inventory.py"

ADDITIONAL_CODE_LANGUAGES = {
    ".adb": "Ada",
    ".ads": "Ada",
    ".asm": "Assembly",
    ".awk": "AWK",
    ".bicep": "Bicep",
    ".cbl": "COBOL",
    ".clj": "Clojure",
    ".cljs": "ClojureScript",
    ".cob": "COBOL",
    ".cr": "Crystal",
    ".cs": "C#",
    ".css": "CSS",
    ".cue": "CUE",
    ".dart": "Dart",
    ".dhall": "Dhall",
    ".el": "Emacs Lisp",
    ".elm": "Elm",
    ".fish": "Fish Shell",
    ".fs": "F#",
    ".fsx": "F#",
    ".gleam": "Gleam",
    ".gql": "GraphQL",
    ".graphql": "GraphQL",
    ".groovy": "Groovy",
    ".hcl": "HCL",
    ".hs": "Haskell",
    ".html": "HTML",
    ".hx": "Haxe",
    ".jl": "Julia",
    ".jsx": "JavaScript",
    ".less": "Less",
    ".lhs": "Literate Haskell",
    ".lisp": "Lisp",
    ".lua": "Lua",
    ".mdx": "MDX",
    ".ml": "OCaml",
    ".mli": "OCaml",
    ".move": "Move",
    ".nim": "Nim",
    ".nix": "Nix",
    ".php": "PHP",
    ".pl": "Perl",
    ".pm": "Perl",
    ".proto": "Protocol Buffers",
    ".ps1": "PowerShell",
    ".qml": "QML",
    ".r": "R",
    ".rb": "Ruby",
    ".rego": "Rego",
    ".rkt": "Racket",
    ".s": "Assembly",
    ".scala": "Scala",
    ".scm": "Scheme",
    ".scss": "SCSS",
    ".sol": "Solidity",
    ".sql": "SQL",
    ".sv": "SystemVerilog",
    ".svelte": "Svelte",
    ".swift": "Swift",
    ".tcl": "Tcl",
    ".tf": "Terraform",
    ".tfvars": "Terraform",
    ".v": "Verilog",
    ".vb": "Visual Basic",
    ".vhd": "VHDL",
    ".vhdl": "VHDL",
    ".vue": "Vue",
    ".zig": "Zig",
}

ADDITIONAL_CONTROL_NAMES = {
    "BUILD",
    "BUILD.bazel",
    "CMakeLists.txt",
    "Gemfile",
    "MODULE.bazel",
    "Podfile",
    "Procfile",
    "Rakefile",
    "WORKSPACE",
    "build.gradle",
    "build.gradle.kts",
    "build.zig",
    "composer.json",
    "deno.json",
    "deno.jsonc",
    "flake.lock",
    "flake.nix",
    "go.mod",
    "go.sum",
    "lakefile.lean",
    "meson.build",
    "mix.exs",
    "mix.lock",
    "package-lock.json",
    "package.json",
    "pnpm-lock.yaml",
    "pnpm-workspace.yaml",
    "poetry.lock",
    "pyproject.toml",
    "rebar.config",
    "requirements.txt",
    "settings.gradle",
    "settings.gradle.kts",
    "tsconfig.json",
    "yarn.lock",
}

EXPLICIT_GENERATED_HEADER = re.compile(
    r"(?i)(generated\s+by\s+ggen|ggen[- ]rendered|@generated|"
    r"do\s+not\s+edit|autogenerated|auto-generated)"
)

CANONICAL_SOURCE_HEADER = re.compile(
    r"(?im)^\s*(?://|#|--|/\*)?\s*(?:"
    r"generated\s+by\s+ggen\s+from\s+|"
    r"generated\s+from\s+|"
    r"source\s*[:=]\s*|"
    r"ontology\s*[:=]\s*|"
    r"template\s*[:=]\s*"
    r")([^\n*]+)"
)


def load_builder() -> ModuleType:
    spec = importlib.util.spec_from_file_location("praxis_ggen_inventory_builder", BUILDER)
    if spec is None or spec.loader is None:
        raise SystemExit(
            "ggen-code-inventory: REFUSED: unable to load governed inventory builder"
        )
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)

    module.EXCLUDED_EXACT.add("ggen.lock")
    module.CODE_LANGUAGES.update(ADDITIONAL_CODE_LANGUAGES)
    module.CONTROL_NAMES.update(ADDITIONAL_CONTROL_NAMES)
    module.GENERATED_MARKER = EXPLICIT_GENERATED_HEADER
    module.SOURCE_HINT = CANONICAL_SOURCE_HEADER

    def bounded_disposition(path: str, text: str, candidate_score: int) -> tuple[str, str]:
        header = "\n".join(text.splitlines()[:80])
        if module.GENERATED_MARKER.search(header):
            return "Generated", "GENERATED_PROJECTION"
        if module.is_control(path):
            return "ControlSurface", "CONTROL_SURFACE"
        if module.is_test(path):
            return "TestSurface", "TEST_SURFACE"
        if candidate_score >= 40:
            return "HighCandidate", "HAND_AUTHORED_CODE"
        if candidate_score >= 20:
            return "MediumCandidate", "HAND_AUTHORED_CODE"
        return "HandAuthoredRuntime", "HAND_AUTHORED_CODE"

    module.disposition = bounded_disposition

    # A tracked projection cannot embed the commit that contains itself. Capture
    # the filtered source-tree hash first, then use that as the observation
    # binding consumed by the builder's existing head field.
    hash_state: dict[str, str] = {}
    original_source_tree_hash = module.source_tree_hash
    original_run = module.run
    original_render_instances = module.render_instances
    original_build = module.build

    def observed_source_tree_hash(surfaces: list[object]) -> str:
        value = original_source_tree_hash(surfaces)
        hash_state["value"] = value
        return value

    def observation_bound_run(*args: str) -> str:
        if args == ("git", "rev-parse", "HEAD"):
            value = hash_state.get("value")
            if value is None:
                raise SystemExit(
                    "ggen-code-inventory: REFUSED: source-tree hash unavailable"
                )
            return f"blake3:{value}"
        return original_run(*args)

    def observation_bound_instances(
        surfaces: list[object], head: str, tree_hash: str
    ) -> bytes:
        rendered = original_render_instances(surfaces, head, tree_hash)
        return rendered.replace(b"gmod:headSha", b"gmod:observationBinding")

    def observation_bound_build() -> int:
        result = original_build()
        receipt = json.loads(module.RECEIPT.read_text(encoding="utf-8"))
        receipt.pop("receipt_blake3", None)
        binding = receipt.pop("observed_head_sha", None)
        if not isinstance(binding, str) or not binding.startswith("blake3:"):
            raise SystemExit(
                "ggen-code-inventory: REFUSED: invalid observation binding"
            )
        receipt["observation_binding"] = binding
        receipt["receipt_blake3"] = module.digest(module.canonical_json(receipt))
        module.RECEIPT.write_bytes(module.canonical_json(receipt) + b"\n")
        return result

    module.source_tree_hash = observed_source_tree_hash
    module.run = observation_bound_run
    module.render_instances = observation_bound_instances
    module.build = observation_bound_build
    return module


def main() -> int:
    module = load_builder()
    if len(sys.argv) != 2 or sys.argv[1] not in {"build", "verify"}:
        print("usage: ggen-code-inventory.py {build|verify}", file=sys.stderr)
        return 2
    return module.build() if sys.argv[1] == "build" else module.verify()


if __name__ == "__main__":
    raise SystemExit(main())
