#!/usr/bin/env python3
import os
import glob

# The 16 project directories
CRATES_DIR = os.path.join(os.path.dirname(__file__), "..", "crates")
JIRA_DIR = os.path.join(os.path.dirname(__file__), "..", "docs", "jira", "v26.7.8", "tickets")

crates = [
    "agent8",
    "cng",
    "ggen",
    "chatman-common",
    "praxis-core",
    "praxis-proposer",
    "praxis-retrofit",
    "rust-fable-testbed",
    "powl2-decompose",
    "pddl-index",
    "praxis-synthesis",
    "praxis-lean",
    "praxis-graphlaw",
    "praxis-graphlaw-wasm",
    "wasm4pm-arazzo",
    "multifractal-workflow"
]

def main():
    if not os.path.isdir(CRATES_DIR):
        print(f"Error: {CRATES_DIR} not found.")
        return
        
    ticket_files = glob.glob(os.path.join(JIRA_DIR, "*.md"))
    tickets = []
    
    for tf in ticket_files:
        basename = os.path.basename(tf)
        if basename == "index.md":
            continue
        with open(tf, "r", encoding="utf-8") as f:
            content = f.read()
            
        # extract title
        lines = content.splitlines()
        title = basename
        for line in lines:
            if line.startswith("# "):
                title = line[2:].strip()
                break
                
        tickets.append({
            "filename": basename,
            "title": title,
            "content": content,
            "path": tf
        })
        
    # Map tickets to crates
    crate_to_tickets = {c: [] for c in crates}
    
    for t in tickets:
        content_lower = t["content"].lower()
        matched = False
        for c in crates:
            # Look for the crate name, or crate name without prefix
            c_name = c.lower()
            c_short = c_name.replace("praxis-", "").replace("wasm4pm-", "").replace("rust-fable-", "")
            
            if c_name in content_lower:
                crate_to_tickets[c].append(t)
                matched = True
            elif c_short != c_name and (f" {c_short} " in content_lower or f"`{c_short}`" in content_lower or f"/{c_short}" in content_lower or f"{c_short}\n" in content_lower):
                crate_to_tickets[c].append(t)
                matched = True

    # Write GOALS.md to each crate
    for c in crates:
        crate_dir = os.path.join(CRATES_DIR, c)
        if not os.path.isdir(crate_dir):
            print(f"Warning: {crate_dir} is not a directory, skipping.")
            continue
            
        goals_path = os.path.join(crate_dir, "GOALS.md")
        
        with open(goals_path, "w", encoding="utf-8") as f:
            f.write(f"# Goals for `{c}`\n\n")
            f.write("This file is automatically generated from the Jira tracking ontology (v26.7.8).\n\n")
            
            ct = crate_to_tickets[c]
            seen = set()
            if not ct:
                f.write("No specific tickets map directly to this crate in the current milestone.\n")
                f.write("See `../../docs/jira/v26.7.8/tickets/index.md` for overall project goals.\n")
            else:
                f.write("## Assigned Tickets\n\n")
                # Avoid duplicates
                for t in ct:
                    if t['filename'] in seen:
                        continue
                    seen.add(t['filename'])
                    rel_path = f"../../docs/jira/v26.7.8/tickets/{t['filename']}"
                    f.write(f"- **[{t['title']}]({rel_path})**\n")
                    
        print(f"Wrote {goals_path} with {len(seen)} tickets.")
        
if __name__ == "__main__":
    main()
