import Mathlib.Data.Matrix.Basic
import Mathlib.Data.Rat.Cast.Order
import Mathlib.Data.Real.Basic
import Mathlib.Algebra.Order.Pi

/-!
def:reachcone

`N : ℤ^{p × |T|}` has columns `δ_t = m⁺_t - m⁻_t` (one column per
transition `t`); a firing sequence with Parikh vector `x ≥ 0` reaches
`m = m₀ + N x`. The reachable marking set is therefore the image of the
nonnegative integer vectors under `x ↦ m₀ + N.mulVec x`; it is contained
in the integer points of `m₀ + cone(N)`, the pointed cone generated by
`N`'s columns.

Composition over new axioms: `N` and `m₀` are plain `Matrix`/`Fin p → ℤ`
values (`Mathlib.Data.Matrix.Basic`), `N.mulVec x` is Mathlib's own
matrix-vector product, and the nonnegative Parikh vectors are just
`{x : Fin |T| → ℤ // 0 ≤ x}` using the pre-built pointwise order on
`Fin n → ℤ`. No opaque axiom is declared: everything here is either a
`Matrix`, a `Set`, or a rational/real cast of `N.mulVec`, all pre-built.
-/

namespace Praxis.Corpus

variable (p ntrans : ℕ)

/-- The reachability matrix `N`: one column `δ_t = m⁺_t - m⁻_t` per
transition, entries in `ℤ` (Mathlib's `Matrix`). -/
abbrev ReachMatrix := Matrix (Fin p) (Fin ntrans) ℤ

/-- The initial marking `m₀ : Fin p → ℤ`. -/
abbrev Marking := Fin p → ℤ

/-- A nonnegative integer Parikh vector `x ≥ 0`, using the pre-built
pointwise order on `Fin ntrans → ℤ`. -/
def IsParikh (x : Fin ntrans → ℤ) : Prop := 0 ≤ x

/-- The set of markings reachable from `m₀` by some nonnegative-integer
firing sequence: `{ m₀ + N x | x ≥ 0 }`. -/
def reachSet (N : ReachMatrix p ntrans) (m0 : Marking p) : Set (Marking p) :=
  { m | ∃ x : Fin ntrans → ℤ, IsParikh ntrans x ∧ m = m0 + N.mulVec x }

/-- The (real-)pointed cone generated by the columns of `N`, translated by
`m₀`: `m₀ + cone(N) = { m₀ + N c | c ≥ 0, c real }`. Cast to `ℝ` since a
cone requires nonnegative *real* (or at least rational) combinations,
not just integer ones; the reachable set (`reachSet`, integer `x ≥ 0`)
consists exactly of the integer points lying in this real cone. -/
def reachCone (N : ReachMatrix p ntrans) (m0 : Marking p) : Set (Fin p → ℝ) :=
  { v | ∃ c : Fin ntrans → ℝ, 0 ≤ c ∧
      v = (fun i => (m0 i : ℝ)) + (N.map (fun z : ℤ => (z : ℝ))).mulVec c }

end Praxis.Corpus
