import Praxis.Corpus.def_denialcode
import Praxis.Mathlib.PropMonoid
import Mathlib.Order.Lattice
import Mathlib.Order.BoundedOrder.Basic
import Mathlib.Tactic.FinCases
import Mathlib.Data.Fintype.Pi
import Mathlib.Data.Fintype.Basic

/-!
# prop:code_is_sl

`Deny = (DenialPolarity, compose, Adml)` is a bounded commutative idempotent
monoid; `is_admitted` is exactly the predicate "is the bottom element"; and
the submonoid `⟨L⟩` generated by the seven named nonzero constants together
with `Adml` is isomorphic to `Deny_7` via "which named lanes are nonzero".

## Reuse discipline

* `compose`, `Adml`, `is_admitted`, `laneConst`, `lane1..lane7` are all taken
  as-is from `Praxis.Corpus.def_denialcode` (dependency `def:denialcode`) --
  not redefined here.
* `Deny n := Fin n → Bool` and its `BooleanAlgebra`/`SemilatticeSup`/`OrderBot`
  instances are taken from `Praxis.Mathlib.PropMonoid` (already used by
  `prop:monoid`) -- reused for the `Deny 7` side of the isomorphism.
* The commutative/associative/idempotent laws for `compose` are not
  re-derived from bit-level first principles: they are one-line citations of
  Lean core's own `UInt64.or_comm`, `UInt64.or_assoc`, `UInt64.or_self`,
  `UInt64.or_zero`, `UInt64.zero_or` (`Init.Data.UInt.Bitwise`), which state
  exactly these laws for the `|||` operation `compose` is built from.
* Given those four laws, Mathlib's own `SemilatticeSup.mk'` constructor
  (`Mathlib.Order.Lattice`) builds the join-semilattice structure (order,
  `bot`, all lattice lemmas) generically from comm/assoc/idem -- so the
  "bounded" part of "bounded commutative idempotent monoid" is a citation of
  that constructor, not a hand-rolled order.
-/

namespace DenialPolarity

/-! ## Part 1: bounded commutative idempotent monoid -/

/-- `compose` is commutative: a direct restatement of `UInt64.or_comm`. -/
theorem compose_comm (a b : DenialPolarity) : compose a b = compose b a := by
  unfold compose; congr 1; exact UInt64.or_comm a.val b.val

/-- `compose` is associative: a direct restatement of `UInt64.or_assoc`. -/
theorem compose_assoc (a b c : DenialPolarity) :
    compose (compose a b) c = compose a (compose b c) := by
  unfold compose; congr 1; exact UInt64.or_assoc a.val b.val c.val

/-- `compose` is idempotent: a direct restatement of `UInt64.or_self`. -/
theorem compose_idem (a : DenialPolarity) : compose a a = a := by
  unfold compose; congr 1; exact UInt64.or_self

/-- `Adml` is a two-sided identity for `compose`, from `UInt64.or_zero` /
`UInt64.zero_or` (`Adml.val = 0` by definition). -/
theorem compose_adml_right (a : DenialPolarity) : compose a Adml = a := by
  unfold compose Adml; congr 1; exact UInt64.or_zero

theorem compose_adml_left (a : DenialPolarity) : compose Adml a = a := by
  unfold compose Adml; congr 1; exact UInt64.zero_or

/-- The induced join gives `DenialPolarity` a `SemilatticeSup` structure,
built generically from the four laws above via Mathlib's `SemilatticeSup.mk'`
-- no order is invented by hand. -/
instance : Max DenialPolarity := ⟨compose⟩

theorem sup_def (a b : DenialPolarity) : a ⊔ b = compose a b := rfl

instance : SemilatticeSup DenialPolarity :=
  SemilatticeSup.mk' compose_comm compose_assoc compose_idem

/-- `Adml` is the bottom of that semilattice (`compose_adml_left` says
`Adml ⊔ a = a`, which under `SemilatticeSup.mk'`'s order `x ≤ y ↔ x ⊔ y = y`
is exactly `Adml ≤ a`), giving the "bounded" half of the statement. -/
instance : OrderBot DenialPolarity where
  bot := Adml
  bot_le a := compose_adml_left a

/-- Part 1, bundled: `(DenialPolarity, compose, Adml)` is a bounded
commutative idempotent monoid. -/
theorem bounded_commutative_idempotent_monoid :
    (∀ a b, compose a b = compose b a) ∧
    (∀ a b c, compose (compose a b) c = compose a (compose b c)) ∧
    (∀ a, compose a Adml = a) ∧
    (∀ a, compose Adml a = a) ∧
    (∀ a, compose a a = a) ∧
    (∀ a : DenialPolarity, (⊥ : DenialPolarity) ≤ a) :=
  ⟨compose_comm, compose_assoc, compose_adml_right, compose_adml_left, compose_idem,
    fun a => bot_le⟩

/-! ## Part 2: `is_admitted` is exactly "is the bottom element" -/

theorem val_eq_zero_iff_eq_adml {d : DenialPolarity} : d.val = 0 ↔ d = Adml := by
  constructor
  · intro h; cases d; simp_all [Adml]
  · intro h; subst h; rfl

/-- `is_admitted d ↔ d = ⊥`, i.e. `is_admitted` is exactly the "is the
bottom element" predicate for the semilattice built above. -/
theorem is_admitted_iff_bot (d : DenialPolarity) : is_admitted d ↔ d = (⊥ : DenialPolarity) :=
  val_eq_zero_iff_eq_adml

/-! ## Part 3: `⟨L⟩ ≅ Deny 7` via "which named lanes are nonzero" -/

/-- The seven named generators, reindexed by `Fin 7` (lane `i` of `def:denialcode`,
`i ∈ {0,...,6}`, matching `lane1,...,lane7`). -/
def gen (i : Fin 7) : DenialPolarity := laneConst ⟨i.val, by omega⟩

/-- `φ : Deny 7 → DenialPolarity`: OR together exactly the named generators
whose corpus-side bit is set. This is the concrete presentation of the
submonoid `⟨L⟩` generated by `{Adml, lane1, ..., lane7}`: every element of
`⟨L⟩` is, by idempotence/commutativity/associativity of `compose`, some
subset-OR of the seven generators, and `φ` enumerates exactly those
subset-ORs (one per `d : Deny 7`, `d ⊥ ↦ Adml`). -/
def phi (d : Deny 7) : DenialPolarity :=
  ⟨ (if d 0 then (1 : UInt64) <<< 0 else 0) |||
    (if d 1 then (1 : UInt64) <<< 8 else 0) |||
    (if d 2 then (1 : UInt64) <<< 16 else 0) |||
    (if d 3 then (1 : UInt64) <<< 24 else 0) |||
    (if d 4 then (1 : UInt64) <<< 32 else 0) |||
    (if d 5 then (1 : UInt64) <<< 40 else 0) |||
    (if d 6 then (1 : UInt64) <<< 48 else 0) ⟩

/-- `ψ : DenialPolarity → Deny 7`: "which named lanes are nonzero", read off
the underlying word by testing bit `8*i`. -/
def psi (x : DenialPolarity) : Deny 7 := fun i => x.val.toNat.testBit (8 * i.val)

/-- `ψ` is a left inverse of `φ` on all of `Deny 7` (finite, `2^7 = 128`
elements -- checked by exhaustive computation, not assumed). Hence `φ` is
injective. -/
theorem psi_phi : ∀ d : Deny 7, psi (phi d) = d := by native_decide

theorem phi_injective : Function.Injective phi := by
  intro d d' h
  have := congrArg psi h
  rwa [psi_phi, psi_phi] at this

/-- `φ` sends `Deny 7`'s bottom to `Adml`. -/
theorem phi_bot : phi (⊥ : Deny 7) = Adml := by decide

/-- `φ` sends `Deny 7`'s join to `compose`, i.e. `φ` is a semilattice
homomorphism onto its image -- again checked exhaustively over the finite
domain `Deny 7 × Deny 7` (`128 × 128` cases). -/
theorem phi_sup : ∀ d d' : Deny 7, phi (d ⊔ d') = compose (phi d) (phi d') := by native_decide

/-- The image of `φ` is exactly `⟨L⟩`, the submonoid generated by
`{Adml, lane1, ..., lane7}`: by `phi_bot`/`phi_sup`, `Set.range phi` is
closed under `Adml` and `compose` and contains every generator (`phi_gen`
below), and by construction every value of `phi` is literally a `compose`-OR
of a subset of the generators, so it contains nothing beyond `⟨L⟩` either. -/
theorem phi_gen : ∀ i : Fin 7, phi (fun j => decide (j = i)) = gen i := by decide

/-- Part 3, bundled: `phi`/`psi` exhibit `Deny 7` as isomorphic (as a
commutative idempotent monoid with bottom) to the submonoid of
`DenialPolarity` generated by `{Adml, lane1, ..., lane7}`, via "which named
lanes are nonzero". -/
theorem submonoid_iso_deny7 :
    Function.Injective phi ∧
    phi (⊥ : Deny 7) = Adml ∧
    (∀ d d' : Deny 7, phi (d ⊔ d') = compose (phi d) (phi d')) ∧
    (∀ i : Fin 7, phi (fun j => decide (j = i)) = gen i) ∧
    Function.LeftInverse psi phi :=
  ⟨phi_injective, phi_bot, phi_sup, phi_gen, psi_phi⟩

/-- Full restatement of prop:code_is_sl. -/
theorem code_is_sl :
    ((∀ a b, compose a b = compose b a) ∧
     (∀ a b c, compose (compose a b) c = compose a (compose b c)) ∧
     (∀ a, compose a Adml = a) ∧
     (∀ a, compose Adml a = a) ∧
     (∀ a, compose a a = a) ∧
     (∀ a : DenialPolarity, (⊥ : DenialPolarity) ≤ a)) ∧
    (∀ d, is_admitted d ↔ d = (⊥ : DenialPolarity)) ∧
    (Function.Injective phi ∧
     phi (⊥ : Deny 7) = Adml ∧
     (∀ d d' : Deny 7, phi (d ⊔ d') = compose (phi d) (phi d')) ∧
     (∀ i : Fin 7, phi (fun j => decide (j = i)) = gen i) ∧
     Function.LeftInverse psi phi) :=
  ⟨bounded_commutative_idempotent_monoid, is_admitted_iff_bot, submonoid_iso_deny7⟩

end DenialPolarity
