import Praxis.Corpus.prop_cone
import Mathlib.Analysis.Convex.Cone.InnerDual
import Mathlib.Analysis.InnerProductSpace.PiL2

/-!
# thm:farkas

Fix `b = m† - m₀`. Exactly one holds: (a) there exists `x ≥ 0` with `N x = b`; or
(b) there exists `y` with `Nᵀ y ≤ 0` and `yᵀ b > 0` — a separating hyperplane
certifying `m† ∉ m₀ + cone(N)` — and if (b) holds no firing sequence reaches `m†`.

Attempted route: Mathlib's *topological* Farkas lemma
(`ProperCone.hyperplane_separation_point`, `Mathlib.Analysis.Convex.Cone.InnerDual`)
gives exactly the alternative in the statement once `cone(N)` is packaged as a
`ProperCone ℝ (EuclideanSpace ℝ (Fin p))`, i.e. once `IsClosed (cone(N))` is known.

That closedness fact — "a finitely generated cone in a finite-dimensional real
vector space is closed", the topological half of the Minkowski–Weyl theorem — is
not present in this Mathlib snapshot. `PointedCone.FG` and `PointedCone.DualFG`
(`Mathlib/Geometry/Convex/Cone/DualFinite.lean`) relate the two notions purely
algebraically (`DualFG.dual_of_fg : C.FG → (dual p C).DualFG p`,
`DualFG.dual_dual_flip : C.DualFG p → dual p (dual p.flip C) = C`), which only gives
`dual p (dual p.flip (dual p C)) = dual p C` for `C.FG` — i.e. the dual's double dual,
not `C`'s own double dual — because closing the loop back to `C` needs the FG ↔
DualFG equivalence itself, which the file's own module doc states is "by the
Minkowski-Weyl theorem" but does not prove. A repo-wide search (`grep -rl IsClosed
Mathlib/Analysis/Convex/Cone Mathlib/Geometry/Convex/Cone`) turns up no lemma
discharging closedness for `FG`/finitely-generated cones. Proving it from scratch
(conic Carathéodory + a finite union of closed simplicial cones) is an independent
real-analysis development, not a composition of existing Mathlib lemmas, so this is
reported `unformalized` rather than papered over with an axiom or `sorry`. The
attempt below is left in place up to the exact point that is missing, so the
kernel error names the actual gap.
-/

namespace Praxis.Corpus

variable (p ntrans : ℕ)

/-- The Euclidean marking space, the ambient type of Mathlib's topological Farkas
lemma (`ProperCone.hyperplane_separation_point`). -/
abbrev MarkingSpace := EuclideanSpace ℝ (Fin p)

/-- **thm:farkas**: exactly one of the primal feasibility of `N x = b` (`x ≥ 0`) or
the dual separating certificate `y` (`Nᵀ y ≤ 0`, `yᵀ b > 0`) holds, where
`b = m† - m₀`. -/
theorem farkas_alternative (N : ReachMatrix p ntrans) (m0 mDagger : Marking p) :
    (∃ x : Fin ntrans → ℝ, 0 ≤ x ∧
        (N.map (fun z : ℤ => (z : ℝ))).mulVec x =
          (fun i => ((mDagger i - m0 i : ℤ) : ℝ))) ∨
      (∃ y : Fin p → ℝ,
        (N.map (fun z : ℤ => (z : ℝ))).transpose.mulVec y ≤ 0 ∧
        0 < Finset.univ.sum (fun i => y i * ((mDagger i - m0 i : ℤ) : ℝ))) := by
  -- The cone generated by the columns of `N`, as a `PointedCone`.
  set Nr : Matrix (Fin p) (Fin ntrans) ℝ := N.map (fun z : ℤ => (z : ℝ)) with hNr
  set b : Fin p → ℝ := fun i => ((mDagger i - m0 i : ℤ) : ℝ) with hb
  set C : PointedCone ℝ (Fin p → ℝ) :=
    PointedCone.hull ℝ (Set.range fun t : Fin ntrans => Nr.mulVec (Pi.single t (1 : ℝ)))
    with hC
  -- Missing ingredient: `C` (equivalently its image in `EuclideanSpace ℝ (Fin p)`)
  -- needs to be closed to invoke `ProperCone.hyperplane_separation_point`; no such
  -- lemma for finitely-generated cones exists in this Mathlib snapshot.
  exact PointedCone.FG.isClosed (p := p) (C := C) ⟨_, hC⟩ b Nr

end Praxis.Corpus
