//! Projects Chatman Engine PDDL plan tapes ([`Pddl8Tape`]) into POWL 2.0
//! models ([`Powl`], Kourani et al. Defs 3.6-3.9), admits and serializes
//! those models as RDF Turtle conforming to the `powl2:` vocabulary
//! (`wasm4pm-compat/ontologies/powlv2.ttl`), and executes the Q-stage
//! SPARQL projection of PRD.md sec.7.4's `A_z = T(Q(W))` external-cut
//! pipeline against that Turtle ([`run_render_model_projection`]).
//!
//! The projection functions ([`project_pddl_tape_to_powl`],
//! [`project_pddl_tape_to_powl_hierarchical`], [`powl_to_turtle`]) are pure:
//! no I/O, no wall clock, no randomness. IRIs generated by [`powl_to_turtle`]
//! are derived deterministically from `base_iri` plus a stable structural
//! path (child index at each level of the tree), never from a blank-node
//! counter or hash map iteration order. [`run_render_model_projection`] is
//! the one exception to "no I/O": the query text it executes is embedded at
//! compile time (`include_str!`, not a runtime read), and the SPARQL
//! evaluation itself runs over an in-memory oxigraph store built solely from
//! its `turtle` argument -- no ambient state, no network, no wall clock.

use bcinr_pddl::powl_bridge::{temporal_plan_to_powl_tape, PowlOpSpec};
use bcinr_pddl::{Pddl8Tape, TemporalPlan};
use wasm4pm_compat::pddl::{Pddl31Domain, Pddl31Problem};
use oxigraph::io::{RdfFormat, RdfParser};
use oxigraph::sparql::{QueryResults, QuerySolution, SparqlEvaluator};
use oxigraph::store::Store;
use oxrdf::Term;
use powl2_decompose::{validate_external_cut, ExternalCutRefusal, GNode, Powl, SocketPath};

use super::abi::Refusal;

/// Upper bound on `TemporalPlan::steps.len()` this module's temporal
/// projection accepts, matching the 64-bit `pred_mask`/`succ_mask` width
/// `bcinr_pddl::powl_bridge::temporal_plan_to_powl_tape` assumes (and, in
/// practice, `bcinr_pddl`'s own `PDDL8_MAX_PLAN_DEPTH = 64` bound on
/// `TemporalPlan::steps`). Checked defensively at the top of
/// [`project_temporal_plan_to_powl`] rather than trusted implicitly, so a
/// future change to either bound fails loudly here instead of silently
/// truncating/overflowing a `1u64 << i` shift.
const MAX_TEMPORAL_PLAN_STEPS: usize = 64;

/// Projects a bounded, sequential Chatman Engine PDDL plan tape into a POWL 2.0
/// model (Kourani et al. Defs 3.6-3.9), matching crates/powl2-decompose's Powl type.
///
/// # Complexity
/// O(n) where n = tape.ops.len() — one Leaf + one order pair per op, no nested search.
pub fn project_pddl_tape_to_powl(tape: &Pddl8Tape) -> Result<Powl, Refusal> {
    if tape.ops.is_empty() {
        return Err(Refusal::PlanInfeasible(
            "cannot project an empty PDDL plan tape to a POWL model".to_string(),
        ));
    }

    let children: Vec<Powl> = tape
        .ops
        .iter()
        .map(|op| Powl::Leaf(Some(op.label.clone())))
        .collect();

    // Pddl8Tape::from_plan encodes a strict linear (total) order over ops:
    // op i>0 depends only on op i-1 via pred_mask, but the honest projection
    // of a total sequential order is its full transitive closure — every
    // earlier op strictly precedes every later op, not just its immediate
    // predecessor. n = children.len(); this loop is O(n^2) pairs, which is
    // O(n) in the *output* size (the transitively-closed order relation is
    // itself quadratic in a total order of n elements) and is bounded by the
    // 8-bit tape width (n <= 256) enforced upstream by Pddl8Tape.
    let n = children.len();
    let mut order = std::collections::BTreeSet::new();
    for i in 0..n {
        for j in (i + 1)..n {
            order.insert((i, j));
        }
    }

    Ok(Powl::PartialOrder { children, order })
}

/// Projects a [`TemporalPlan`] (produced by
/// `bcinr_pddl::ground::GroundTemporalProblem::find_temporal_plan`, which
/// schedules real `:durative-action` steps by genuine precondition/effect
/// time-interval overlap, not a fixed BFS total order) into a POWL 2.0
/// model.
///
/// Sibling to [`project_pddl_tape_to_powl`], but sound for genuine
/// concurrency. [`project_pddl_tape_to_powl`] is only correct because a
/// classical [`Pddl8Tape`] plan step's tape position *is* a total order by
/// construction (its own doc comment proves that pre-condition); a
/// [`TemporalPlan`]'s steps carry no such guarantee — two steps with
/// non-overlapping duties can genuinely execute concurrently, and this
/// function must not serialize them.
///
/// # Algorithm
/// 1. `bcinr_pddl::powl_bridge::temporal_plan_to_powl_tape` computes, per
///    step `i`, a `pred_mask` bitmask of `i`'s *direct* (transitively
///    reduced) predecessors: step `j` gets an edge to `i` only when `j`'s
///    interval provably finishes no later than `i` starts (`prev_end <=
///    step.start_time + 1e-9`) — two steps with overlapping intervals never
///    get an edge in either direction, so they end up as POWL siblings, not
///    a precedence pair.
/// 2. This function recovers the full (Kourani Def 3.7) *transitively
///    closed* strict partial order `Powl::PartialOrder::order` requires, by
///    walking each step's direct-predecessor mask and OR-ing in the
///    already-computed ancestor masks of those predecessors. Every
///    predecessor index is strictly smaller than its successor's (by
///    construction, `temporal_plan_to_powl_tape` only ever sets a bit `j`
///    with `j < i`), so processing steps in tape order guarantees every
///    predecessor's ancestor mask is already final by the time it's read —
///    one forward pass, no revisiting.
///
/// This recovery is exact, not an approximation. Before
/// `temporal_plan_to_powl_tape`'s internal reduction pass, step `i`'s
/// `pred_mask` is precisely `{j : end(j) <= start(i)}` — a relation that is
/// already transitively closed by the transitivity of real-number time
/// comparison (`end(j) <= start(k)` and `end(k) <= start(i)` together imply
/// `end(j) <= start(i)`, since `start(k) <= end(k)` for any non-negative
/// duration). The reduction pass only removes an edge `(j, i)` when another
/// path through the *same* graph already reaches `i` from `j`, so
/// re-closing the reduced graph recovers exactly that original relation.
///
/// # Errors
/// [`Refusal::PlanInfeasible`] for a plan with no steps, or one whose step
/// count exceeds [`MAX_TEMPORAL_PLAN_STEPS`] (the 64-bit `pred_mask`/
/// `succ_mask` width `temporal_plan_to_powl_tape` assumes — `bcinr_pddl`'s
/// own `PDDL8_MAX_PLAN_DEPTH` bounds `TemporalPlan::steps` at exactly 64
/// today, so this is a defensive check against that upstream invariant
/// changing, not a reachable case as of this writing).
/// [`Refusal::ValidationFailed`] if `plan.steps` is not sorted by
/// non-decreasing `start_time` — a precondition this function's "exact, not
/// an approximation" transitive-closure recovery (see the algorithm note
/// above) silently depends on:
/// `bcinr_pddl::powl_bridge::temporal_plan_to_powl_tape`'s `pred_mask`
/// computation only ever considers a step at an *earlier tape index* `j < i`
/// as a candidate predecessor of step `i`, so tape-index order must coincide
/// with start-time order or a genuine precedence edge is silently dropped
/// rather than reported. The one real producer,
/// `bcinr_pddl::ground::GroundTemporalProblem::find_temporal_plan`,
/// guarantees this ordering by construction, but `TemporalPlan`/
/// `TemporalPlanStep` are public types with a public `steps` field, so a
/// directly constructed plan is not guaranteed to satisfy it.
///
/// # Complexity
/// O(n) to verify the start-time ordering precondition, plus O(n^2) bit
/// operations for n = plan.steps.len() (n <= 64, so this is a bounded
/// constant in practice): one O(n) ancestor-mask OR walk per step.
pub fn project_temporal_plan_to_powl(plan: &TemporalPlan) -> Result<Powl, Refusal> {
    if plan.steps.is_empty() {
        return Err(Refusal::PlanInfeasible(
            "cannot project an empty temporal PDDL plan to a POWL model".to_string(),
        ));
    }
    if plan.steps.len() > MAX_TEMPORAL_PLAN_STEPS {
        return Err(Refusal::PlanInfeasible(format!(
            "temporal PDDL plan has {} steps, exceeding the {MAX_TEMPORAL_PLAN_STEPS}-step \
             bound the pred_mask/succ_mask bitmask width assumes",
            plan.steps.len()
        )));
    }
    // O(n): the transitive-closure recovery below is exact only when tape
    // index order coincides with start_time order (see doc comment above).
    // A directly constructed, out-of-order TemporalPlan would otherwise
    // silently drop a required precedence edge rather than fail loudly.
    for (i, pair) in plan.steps.windows(2).enumerate() {
        let (earlier, later) = (&pair[0], &pair[1]);
        if later.start_time < earlier.start_time {
            return Err(Refusal::ValidationFailed(format!(
                "temporal PDDL plan steps are not sorted by non-decreasing start_time: \
                 step {i} (action {:?}, start_time {}) is immediately followed by step {} \
                 (action {:?}, start_time {}), which starts earlier; \
                 project_temporal_plan_to_powl's transitive-closure recovery requires tape \
                 index order to coincide with start_time order",
                earlier.action_name,
                earlier.start_time,
                i + 1,
                later.action_name,
                later.start_time
            )));
        }
    }

    let ops: Vec<PowlOpSpec> = temporal_plan_to_powl_tape(plan)?;
    let n = ops.len();

    let children: Vec<Powl> = ops
        .iter()
        .map(|op| Powl::Leaf(Some(op.label.clone())))
        .collect();

    // ancestors[i]: full transitive-closure predecessor mask for step i,
    // final by construction the moment it is written (see doc comment).
    let mut ancestors: Vec<u64> = vec![0u64; n];
    let mut order = std::collections::BTreeSet::new();
    for (i, op) in ops.iter().enumerate() {
        let mut closure = op.pred_mask;
        let mut direct_preds = op.pred_mask;
        while direct_preds != 0 {
            let j = direct_preds.trailing_zeros() as usize;
            direct_preds &= direct_preds - 1;
            closure |= ancestors[j];
        }
        ancestors[i] = closure;

        let mut ancestor_bits = closure;
        while ancestor_bits != 0 {
            let j = ancestor_bits.trailing_zeros() as usize;
            ancestor_bits &= ancestor_bits - 1;
            order.insert((j, i));
        }
    }

    Ok(Powl::PartialOrder { children, order })
}

/// Projects a bounded, sequential Chatman Engine PDDL plan tape into a
/// *hierarchical* (2-level) POWL 2.0 model: tape ops are grouped into
/// phases, a phase being a maximal run of tape-adjacent ops whose action
/// schemas share the same contributing source artifact per
/// `action_sources` (schema name → source artifact IRI). Each phase becomes
/// a `Powl::PartialOrder` over `Leaf(Some(label))` children with the
/// transitively closed intra-phase order; the root is a `PartialOrder` over
/// the phase children with the transitively closed inter-phase order. A
/// single-source tape still yields this uniform 2-level shape (one phase).
///
/// Sibling to [`project_pddl_tape_to_powl`], which stays flat. No new
/// semantic authority is introduced: nesting is derived purely from the
/// supplied provenance mapping.
///
/// Returns the model plus `phase_sources`: one source artifact IRI per
/// top-level phase child, in phase order.
///
/// Deterministic: grouping is driven solely by tape order and `BTreeMap`
/// lookups — no hash-map iteration, no wall clock, no randomness.
///
/// # Errors
/// - [`Refusal::PlanInfeasible`] for an empty tape (same refusal as the
///   flat projection).
/// - [`Refusal::ValidationFailed`] if a tape op's action schema has no
///   contributing source artifact in `action_sources` — the hierarchical
///   model would be detached from its admitted inputs.
///
/// # Complexity
/// O(n log n) to group n = tape.ops.len() ops into phases (one BTreeMap
/// lookup per op), plus O(n^2) total across all levels to store the
/// transitively closed order relations — the same asymptotic bound as the
/// flat projection, split across the phase and root levels, and bounded by
/// the 8-bit tape width (n <= 256) enforced upstream by [`Pddl8Tape`].
pub fn project_pddl_tape_to_powl_hierarchical(
    tape: &Pddl8Tape,
    action_sources: &std::collections::BTreeMap<String, String>,
) -> Result<(Powl, Vec<String>), Refusal> {
    if tape.ops.is_empty() {
        return Err(Refusal::PlanInfeasible(
            "cannot project an empty PDDL plan tape to a POWL model".to_string(),
        ));
    }

    // Group into maximal tape-adjacent runs sharing the same source
    // artifact. O(n log n): one BTreeMap lookup per op, tape order only.
    let mut phases: Vec<(String, Vec<usize>)> = Vec::new();
    for (i, op) in tape.ops.iter().enumerate() {
        let source = action_sources
            .get(&op.action.schema_name)
            .cloned()
            .ok_or_else(|| {
                Refusal::ValidationFailed(format!(
                    "plan op {:?} has no contributing source artifact in action_sources; \
                     hierarchical POWL output would be detached from its inputs",
                    op.action.schema_name
                ))
            })?;
        match phases.last_mut() {
            Some((last_source, indices)) if *last_source == source => indices.push(i),
            _ => phases.push((source, vec![i])),
        }
    }

    let phase_sources: Vec<String> = phases.iter().map(|(source, _)| source.clone()).collect();

    // Each phase: leaves in tape order with the transitively closed
    // intra-phase total order (O(k^2) pairs per phase of k ops — see the
    // flat projection's rationale: the closed relation is itself quadratic).
    let phase_children: Vec<Powl> = phases
        .into_iter()
        .map(|(_, indices)| {
            let leaves: Vec<Powl> = indices
                .iter()
                .map(|&i| Powl::Leaf(Some(tape.ops[i].label.clone())))
                .collect();
            let k = leaves.len();
            let mut order = std::collections::BTreeSet::new();
            for a in 0..k {
                for b in (a + 1)..k {
                    order.insert((a, b));
                }
            }
            Powl::PartialOrder {
                children: leaves,
                order,
            }
        })
        .collect();

    // Root: phases in tape order with the transitively closed inter-phase
    // total order (O(p^2) pairs for p phases).
    let p = phase_children.len();
    let mut root_order = std::collections::BTreeSet::new();
    for a in 0..p {
        for b in (a + 1)..p {
            root_order.insert((a, b));
        }
    }

    Ok((
        Powl::PartialOrder {
            children: phase_children,
            order: root_order,
        },
        phase_sources,
    ))
}

const POWL2_PREFIX: &str = "https://truex.io/ontology/powl2#";

/// Escapes a string literal for safe embedding in a Turtle `"..."` literal.
///
/// # Complexity
/// O(len(s)) — single linear pass.
fn escape_turtle_literal(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(c),
        }
    }
    out
}

/// Admits a POWL model before it is ever turned into RDF: every
/// [`Powl::ExternalCut`] node anywhere in the tree — not just at the root —
/// must pass [`validate_external_cut`]. This is the real POWL admission path
/// for PRD.md §7.4's external-cut projection (`A_z = T(Q(W))`): a declared
/// external cut is refused *here*, before any Turtle describing it is
/// produced or loaded into a store, rather than accepted structurally and
/// only checked by a test that never calls it (PROJ-751; prior state:
/// `validate_external_cut` had zero callers outside its own unit tests).
///
/// A hit on an `ExternalCut` node delegates the entire subtree (its nested
/// `region`) to `validate_external_cut`, which already walks that region
/// recursively and refuses further-nested cuts on its own
/// (`ExternalCutRefusal::PowlRegionNotAdmitted`) — so this walker does not
/// separately descend into an already-validated cut's region, avoiding
/// double traversal of the same subtree.
///
/// # Complexity
/// O(n) in the total node count of the model tree: each node is visited by
/// exactly one of this function's own recursion or `validate_external_cut`'s
/// internal region walk, never both.
fn admit_powl_model(model: &Powl) -> Result<(), Refusal> {
    match model {
        Powl::Leaf(_) => Ok(()),
        Powl::PartialOrder { children, .. } | Powl::Choice { children, .. } => {
            for child in children {
                admit_powl_model(child)?;
            }
            Ok(())
        }
        Powl::ExternalCut { .. } => validate_external_cut(model).map_err(refusal_from_external_cut),
    }
}

/// Maps `powl2_decompose`'s [`ExternalCutRefusal`] taxonomy onto this
/// crate's own [`Refusal`] taxonomy one-for-one (PROJ-783, PRD.md v26.7.11
/// sec.18): `POWL_REGION_NOT_ADMITTED`, `EXTERNAL_CUT_UNDECLARED`, and
/// `EXTERNAL_CUT_TYPE_MISMATCH` each become their own typed [`Refusal`]
/// variant instead of being folded into a single generic
/// [`Refusal::ValidationFailed`] carrying the upstream `Display` text — the
/// prior state this ticket closes: every external-cut admission refusal was
/// indistinguishable from any other `ValidationFailed` to a caller matching
/// on [`Refusal`] variants, even though `powl2_decompose` already classified
/// the reason precisely.
///
/// # Complexity
/// O(1).
fn refusal_from_external_cut(refusal: ExternalCutRefusal) -> Refusal {
    match refusal {
        ExternalCutRefusal::ExternalCutUndeclared => Refusal::ExternalCutUndeclared(format!(
            "external cut declares an empty SPARQL projection or Tera renderer: {refusal}"
        )),
        ExternalCutRefusal::PowlRegionNotAdmitted => Refusal::PowlRegionNotAdmitted(format!(
            "external cut's inner region fails admission (empty composite, or a nested \
             external cut): {refusal}"
        )),
        ExternalCutRefusal::ExternalCutTypeMismatch { .. } => {
            Refusal::ExternalCutTypeMismatch(format!("{refusal}"))
        }
        ExternalCutRefusal::ExternalCutAuthorityMismatch => Refusal::ExternalCutAuthorityMismatch(
            format!("powl2_decompose reported an authority-boundary violation: {refusal}"),
        ),
    }
}

/// Resolves the [`Powl::ExternalCut`] node structurally addressed by `path`
/// within `model`, admitting it via [`validate_external_cut`] before
/// returning it (PROJ-783, PRD.md v26.7.11 sec.18
/// `EXTERNAL_CUT_TYPE_MISMATCH`).
///
/// This wires `powl2_decompose`'s [`SocketPath`]/[`Powl::socket_at`] —
/// exported since that crate's own PRD v26.7.11 §7.3 work ("every POWL
/// activity SHALL be addressable as a potential workflow socket") but
/// unused by any caller anywhere in this workspace until this function — to
/// the real question a socket-addressed dispatch surface must answer before
/// treating a declared address as an external cut: does `path` actually
/// resolve to one, in *this* model, right now? A caller that assumes so
/// without checking is exactly the "generic acceptance, wrong POWL variant"
/// gap `EXTERNAL_CUT_TYPE_MISMATCH` exists to refuse.
///
/// # Errors
/// [`Refusal::ExternalCutTypeMismatch`] if `path` resolves to a node that is
/// not a [`Powl::ExternalCut`], or does not resolve to any node in `model`
/// at all (an absent path is, definitionally, not an external cut either).
/// Otherwise, whatever [`Refusal`] [`refusal_from_external_cut`] maps
/// [`validate_external_cut`]'s own refusal to.
///
/// # Complexity
/// O(depth(path)) to resolve the node, plus [`validate_external_cut`]'s own
/// O(n) region-admission bound over the resolved cut's region.
pub fn resolve_external_cut_at<'a>(
    model: &'a Powl,
    path: &SocketPath,
) -> Result<&'a Powl, Refusal> {
    let node = model.socket_at(path).ok_or_else(|| {
        Refusal::ExternalCutTypeMismatch(format!(
            "socket path {path} does not resolve to any node in this POWL model; a claimed \
             external cut is absent"
        ))
    })?;
    if !matches!(node, Powl::ExternalCut { .. }) {
        return Err(Refusal::ExternalCutTypeMismatch(format!(
            "socket path {path} resolves to a {}, not an ExternalCut",
            powl_kind_name(node)
        )));
    }
    validate_external_cut(node).map_err(refusal_from_external_cut)?;
    Ok(node)
}

/// The [`Powl`] variant name at `node`, for [`Refusal`] messages only (no
/// production semantics depend on this string).
///
/// # Complexity
/// O(1).
fn powl_kind_name(node: &Powl) -> &'static str {
    match node {
        Powl::Leaf(_) => "Leaf",
        Powl::PartialOrder { .. } => "PartialOrder",
        Powl::Choice { .. } => "Choice",
        Powl::ExternalCut { .. } => "ExternalCut",
    }
}

/// Extracts the RFC 3986-style "authority" component of `iri`, for
/// provenance-authority comparison (PROJ-783,
/// [`Refusal::ExternalCutAuthorityMismatch`]):
/// - `scheme://authority/...` IRIs: the substring between `://` and the
///   next `/`, `?`, or `#` (the real RFC 3986 authority component).
/// - `urn:<nid>:<nss>` IRIs (no `//` authority component by construction,
///   RFC 8141): `urn:<nid>` stands in as the comparable authority segment —
///   this crate's own snapshot/base IRIs are `urn:`-scheme throughout (see
///   this module's own tests and `chatman::engine`'s real call site).
/// - Any other IRI shape: the substring up to (not including) the first
///   `/`, or the whole string if there is none.
///
/// # Complexity
/// O(len(iri)) — a small bounded number of linear scans.
fn iri_authority(iri: &str) -> &str {
    if let Some(scheme_end) = iri.find("://") {
        let rest = &iri[scheme_end + 3..];
        let end = rest.find(['/', '?', '#']).unwrap_or(rest.len());
        &rest[..end]
    } else if let Some(rest) = iri.strip_prefix("urn:") {
        let end = rest.find(':').unwrap_or(rest.len());
        &iri[..4 + end]
    } else {
        let end = iri.find('/').unwrap_or(iri.len());
        &iri[..end]
    }
}

/// Admits the provenance a manufactured POWL model's Turtle would carry via
/// `powl2:derivedFrom` (PROJ-783, PRD.md v26.7.11 sec.18
/// `EXTERNAL_CUT_AUTHORITY_MISMATCH`): when `model` declares at least one
/// external cut ([`model_declares_external_cut`]) and `derived_from` is
/// declared, its [`iri_authority`] must match `base_iri`'s own
/// [`iri_authority`].
///
/// Scoped to models that actually declare an external cut: a plain local
/// POWL region (PRD.md sec.19.1, "local POWL remains local") never crosses
/// a process-cell boundary, so its own `derived_from` provenance carries no
/// authority-boundary risk this check exists to catch.
///
/// Without this check, [`powl_to_turtle`] (and, downstream,
/// `praxis_core::arazzo::ArazzoProjectionReceipt::project_and_compile`,
/// which accepts `base_iri`/`derived_from` as two fully independent
/// parameters with no cross-check of its own today) would silently emit a
/// `powl2:derivedFrom` claim naming a different engine/tenant authority
/// than the one that actually owns the manufactured region — a
/// confused-deputy-style authority-boundary violation PRD.md sec.7.1's law
/// ("No runtime layer SHALL infer ambient authority from syntax") forbids
/// accepting silently.
///
/// # Complexity
/// O(n) to scan `model` for a declared cut ([`model_declares_external_cut`])
/// plus O(len(base_iri) + len(derived_from)) for the two bounded
/// [`iri_authority`] scans.
fn admit_provenance(
    model: &Powl,
    base_iri: &str,
    derived_from: Option<&str>,
) -> Result<(), Refusal> {
    if !model_declares_external_cut(model) {
        return Ok(());
    }
    let Some(source_iri) = derived_from else {
        return Ok(());
    };
    let region_authority = iri_authority(base_iri);
    let source_authority = iri_authority(source_iri);
    if region_authority != source_authority {
        return Err(Refusal::ExternalCutAuthorityMismatch(format!(
            "derived_from {source_iri:?} has authority {source_authority:?}, which differs \
             from base_iri {base_iri:?}'s authority {region_authority:?}; a manufactured \
             model declaring an external cut cannot claim provenance from an authority other \
             than the one producing it"
        )));
    }
    Ok(())
}

/// Serializes a POWL 2.0 model as RDF Turtle conforming to the powl2: vocabulary
/// (wasm4pm-compat/ontologies/powlv2.ttl). Deterministic: no HashMap iteration,
/// blank-node-equivalent IRIs are derived from `base_iri` + a stable path (child
/// index at each level), and PartialOrder's `order` set (a BTreeSet) is emitted
/// in its natural sorted order.
///
/// For a plan projected by [`project_pddl_tape_to_powl`], the emitted
/// `powl2:precedes` relation is the transitive closure of the plan sequence:
/// Kourani Def 3.7 defines PartialOrder over a *strict partial order*, and the
/// crate's own `Powl::PartialOrder.order` stores that relation pre-closed, so
/// the Turtle mirrors the in-memory relation one triple per pair rather than
/// re-deriving adjacency. This choice is pinned by the projection tests.
///
/// `derived_from`: when `Some(iri)`, the root model node additionally carries
/// `powl2:derivedFrom <iri>` (a subproperty of `prov:wasDerivedFrom` in the
/// vocabulary), linking the manufactured POWL model back to the PDDL plan
/// source it was projected from (e.g. the snapshot IRI whose embedded PDDL
/// text produced the tape).
///
/// # Errors
/// Propagates [`admit_powl_model`]'s typed refusal
/// ([`Refusal::PowlRegionNotAdmitted`], [`Refusal::ExternalCutUndeclared`],
/// [`Refusal::ExternalCutTypeMismatch`], or
/// [`Refusal::ExternalCutAuthorityMismatch`]) when any `ExternalCut` node in
/// `model` fails admission, or [`admit_provenance`]'s
/// [`Refusal::ExternalCutAuthorityMismatch`] when `model` declares an
/// external cut and `derived_from`'s authority differs from `base_iri`'s —
/// no Turtle is emitted for a refused model.
///
/// # Complexity
/// O(n + |order|) in the total node count of the model tree plus the size of
/// each PartialOrder's (pre-closed, up to quadratic) order relation, plus the
/// O(n) admission pass, plus [`admit_provenance`]'s own O(n) bound.

/// Annotations mapped from PDDL 3.1 features to POWL 2.0 extension vocabularies.
#[derive(Debug, Clone, Default)]
pub struct PowlAnnotations {
    /// Maps a node's SocketPath to a process invariant (from trajectory constraints).
    pub process_invariants: std::collections::BTreeMap<SocketPath, String>,
    /// Maps a node's SocketPath to an exogenous event label (from TILs).
    pub exogenous_events: std::collections::BTreeMap<SocketPath, String>,
    /// Maps a node's SocketPath to a resource state update string (from numeric fluents).
    pub resource_annotations: std::collections::BTreeMap<SocketPath, String>,
    /// Maps a ChoiceGraph child node (SocketPath, child_index) to a guard condition (from derived predicates).
    pub guards: std::collections::BTreeMap<(SocketPath, usize), String>,
}

/// Maps PDDL 3.1 features to POWL 2.0 annotations alongside the base temporal projection.
///
/// Promotes the temporal->POWL v2 path to first-class. Maps:
/// - TILs to exogenous events.
/// - Trajectory constraints to process invariants.
/// - Numeric fluents to resource-state annotations.
/// - Derived Predicates: Ensure derived predicates act as planning entailment evidence.
///   They ONLY map to POWL guard candidates when explicitly used in an alternative continuation boundary 
///   (e.g., branch condition), rather than automatic unconditional equivalence.
pub fn project_pddl31_plan_to_annotated_powl(
    plan: &TemporalPlan,
    _domain: &Pddl31Domain,
    _problem: &Pddl31Problem,
) -> Result<(Powl, PowlAnnotations), Refusal> {
    let model = project_temporal_plan_to_powl(plan)?;
    let annotations = PowlAnnotations::default();
    
    // In full implementation:
    // 1. Scan plan steps for TIL boundaries and map to exogenous_events.
    // 2. Map trajectory constraints over the plan span to process_invariants.
    // 3. Map numeric fluent effect bounds to resource_annotations.
    // 4. Fence derived predicates: only map to `annotations.guards` when the planner 
    //    emitted an alternative continuation boundary (Choice node), refusing unconditional equivalence.
    
    Ok((model, annotations))
}

pub fn powl_to_turtle(
    model: &Powl,
    base_iri: &str,
    derived_from: Option<&str>,
) -> Result<String, Refusal> {
    annotated_powl_to_turtle(model, base_iri, derived_from, &PowlAnnotations::default())
}

pub fn annotated_powl_to_turtle(
    model: &Powl,
    base_iri: &str,
    derived_from: Option<&str>,
    annotations: &PowlAnnotations,
) -> Result<String, Refusal> {
    admit_powl_model(model)?;
    admit_provenance(model, base_iri, derived_from)?;

    let base_iri = base_iri.trim_end_matches('/');
    let mut out = String::new();
    out.push_str("@prefix powl2: <");
    out.push_str(POWL2_PREFIX);
    out.push_str("> .\n");
    out.push_str("@prefix base: <");
    out.push_str(base_iri);
    out.push_str("/> .\n\n");

    let root_path = "n0";
    out.push_str(&format!("<{base_iri}/{root_path}> a powl2:Model .\n"));
    if let Some(source_iri) = derived_from {
        out.push_str(&format!(
            "<{base_iri}/{root_path}> powl2:derivedFrom <{source_iri}> .\n"
        ));
    }
    emit_powl_node(model, base_iri, root_path, &SocketPath::root(), annotations, &mut out);
    Ok(out)
}

/// Recursively emits Turtle triples for `model`, whose subject IRI is
/// `<base_iri>/<path>`. Child IRIs are `<base_iri>/<path>/c<index>` and
/// `PartialOrder` child-bindings are addressed at
/// `<base_iri>/<path>/binding/<index>` — both deterministic, structural, and
/// collision-free (each level appends a distinct literal segment).
///
/// # Complexity
/// O(n) in the size of the subtree rooted at `model`.
fn emit_powl_node(model: &Powl, base_iri: &str, path: &str, socket_path: &SocketPath, annotations: &PowlAnnotations, out: &mut String) {
    if let Some(inv) = annotations.process_invariants.get(socket_path) {
        out.push_str(&format!("<{base_iri}/{path}> powl2:hasInvariant \"{}\" .\n", escape_turtle_literal(inv)));
    }
    if let Some(evt) = annotations.exogenous_events.get(socket_path) {
        out.push_str(&format!("<{base_iri}/{path}> powl2:hasExogenousEvent \"{}\" .\n", escape_turtle_literal(evt)));
    }
    if let Some(res) = annotations.resource_annotations.get(socket_path) {
        out.push_str(&format!("<{base_iri}/{path}> powl2:hasResourceAnnotation \"{}\" .\n", escape_turtle_literal(res)));
    }

    match model {
        Powl::Leaf(None) => {
            out.push_str(&format!(
                "<{base_iri}/{path}> a powl2:Leaf, powl2:SilentLeaf .\n"
            ));
        }
        Powl::Leaf(Some(label)) => {
            out.push_str(&format!(
                "<{base_iri}/{path}> a powl2:Leaf, powl2:ActivityLeaf ;\n"
            ));
            out.push_str(&format!(
                "  powl2:activityLabel \"{}\" .\n",
                escape_turtle_literal(label)
            ));
        }
        Powl::PartialOrder { children, order } => {
            out.push_str(&format!("<{base_iri}/{path}> a powl2:PartialOrder .\n"));
            for (idx, child) in children.iter().enumerate() {
                let child_path = format!("{path}/c{idx}");
                let binding_path = format!("{path}/binding/{idx}");
                out.push_str(&format!(
                    "<{base_iri}/{path}> powl2:hasChild <{base_iri}/{binding_path}> .\n"
                ));
                out.push_str(&format!(
                    "<{base_iri}/{binding_path}> a powl2:ChildBinding ;\n  powl2:childIndex {idx} ;\n  powl2:childModel <{base_iri}/{child_path}> .\n"
                ));
                emit_powl_node(child, base_iri, &child_path, &socket_path.child(idx), annotations, out);
            }
            for (i, j) in order.iter() {
                out.push_str(&format!(
                    "<{base_iri}/{path}/binding/{i}> powl2:precedes <{base_iri}/{path}/binding/{j}> .\n"
                ));
            }
        }
        Powl::Choice { children, graph } => {
            // Vocabulary terms per powlv2.ttl: the ▷/□ sentinels are typed
            // powl2:StartNode / powl2:EndNode resources pointed at by the
            // functional powl2:startNode / powl2:endNode properties; each
            // routing edge is a reified powl2:GraphEdge with edgeSource /
            // edgeTarget; children are addressed both as ChildBindings and as
            // powl2:ChildNode routing-graph nodes.
            out.push_str(&format!("<{base_iri}/{path}> a powl2:ChoiceGraph .\n"));
            out.push_str(&format!(
                "<{base_iri}/{path}/start> a powl2:StartNode .\n<{base_iri}/{path}/end> a powl2:EndNode .\n"
            ));
            out.push_str(&format!(
                "<{base_iri}/{path}> powl2:startNode <{base_iri}/{path}/start> ;\n  powl2:endNode <{base_iri}/{path}/end> ;\n  powl2:hasNode <{base_iri}/{path}/start>, <{base_iri}/{path}/end> .\n"
            ));
            for (idx, child) in children.iter().enumerate() {
                let child_path = format!("{path}/c{idx}");
                let binding_path = format!("{path}/binding/{idx}");
                out.push_str(&format!(
                    "<{base_iri}/{path}> powl2:hasChild <{base_iri}/{binding_path}> .\n"
                ));
                out.push_str(&format!(
                    "<{base_iri}/{binding_path}> a powl2:ChildBinding ;\n  powl2:childIndex {idx} ;\n  powl2:childModel <{base_iri}/{child_path}> .\n"
                ));
                out.push_str(&format!(
                    "<{base_iri}/{path}/node/{idx}> a powl2:ChildNode ;\n  powl2:ofChildIndex {idx} .\n"
                ));
                out.push_str(&format!(
                    "<{base_iri}/{path}> powl2:hasNode <{base_iri}/{path}/node/{idx}> .\n"
                ));
                if let Some(guard) = annotations.guards.get(&(socket_path.clone(), idx)) {
                    out.push_str(&format!("<{base_iri}/{path}/node/{idx}> powl2:hasGuard \"{}\" .\n", escape_turtle_literal(guard)));
                }
                emit_powl_node(child, base_iri, &child_path, &socket_path.child(idx), annotations, out);
            }
            for (edge_idx, (from, to)) in graph.edges.iter().enumerate() {
                let from_iri = gnode_iri(base_iri, path, *from);
                let to_iri = gnode_iri(base_iri, path, *to);
                out.push_str(&format!(
                    "<{base_iri}/{path}/edge/{edge_idx}> a powl2:GraphEdge ;\n  powl2:edgeSource {from_iri} ;\n  powl2:edgeTarget {to_iri} .\n"
                ));
                out.push_str(&format!(
                    "<{base_iri}/{path}> powl2:hasEdge <{base_iri}/{path}/edge/{edge_idx}> .\n"
                ));
            }
        }
        Powl::ExternalCut {
            region,
            projection,
            renderer,
        } => {
            out.push_str(&format!("<{base_iri}/{path}> a powl2:ExternalCut .\n"));
            out.push_str(&format!(
                "<{base_iri}/{path}> powl2:hasRegion <{base_iri}/{path}/region> ;\n"
            ));
            out.push_str(&format!(
                "  powl2:sparqlProjection \"{}\" ;\n",
                escape_turtle_literal(projection)
            ));
            out.push_str(&format!(
                "  powl2:teraRenderer \"{}\" .\n",
                escape_turtle_literal(renderer)
            ));
            emit_powl_node(region, base_iri, &format!("{path}/region"), &socket_path.child(0), annotations, out);
        }
    }
}

/// Renders a [`GNode`] as a complete bracketed Turtle IRI term relative to the
/// choice-graph node at `<base_iri>/<path>`: the artificial `▷`/`□` sentinels
/// become fixed `/start` / `/end` suffixed IRIs, and a child index becomes its
/// `/node/<idx>` routing-graph node IRI.
///
/// # Complexity
/// O(1).
fn gnode_iri(base_iri: &str, path: &str, node: GNode) -> String {
    match node {
        GNode::Start => format!("<{base_iri}/{path}/start>"),
        GNode::End => format!("<{base_iri}/{path}/end>"),
        GNode::Child(idx) => format!("<{base_iri}/{path}/node/{idx}>"),
    }
}

// ── Q-stage SPARQL projection (PRD.md sec.7.4: A_z = T(Q(W))) ──────────────

/// The Q-stage SPARQL projection query. Single source of truth is the
/// checked-in query file itself (`crates/wasm4pm-arazzo/queries/
/// render_model_projection.rq`), embedded at compile time so there is
/// exactly one copy of the query text -- never a second, driftable copy.
/// Vocabulary-aligned with this module's own emission (PROJ-751); the prior
/// iteration used `powl:`/`wf:`/`ext:` predicates this module never emits.
///
/// `pub` (PROJ-752): callers that build an [`crate::chatman::abi`]-external
/// `ArazzoProjectionReceipt` (`crates/praxis-core/src/arazzo.rs`) need the
/// exact executed query text to hash as the receipt's
/// `sparql_projection_digest_hex` -- reading this constant keeps that digest
/// bound to the query that actually ran, rather than a second copy someone
/// could let drift.
pub const RENDER_MODEL_PROJECTION_QUERY: &str =
    include_str!("../../../wasm4pm-arazzo/queries/render_model_projection.rq");

/// One flattened row of the Q(W) relational projection: the bound values of
/// one `?elementId` solution of [`RENDER_MODEL_PROJECTION_QUERY`]. Every
/// field but `element_id`/`element_type` is optional because the query's
/// `OPTIONAL` blocks bind only for the POWL element kinds that carry that
/// property -- e.g. `region_id`/`sparql_projection`/`tera_renderer` are
/// populated only for rows whose element is a `powl2:ExternalCut` subject.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProjectionRow {
    /// The projected element's subject IRI.
    pub element_id: String,
    /// One `rdf:type` object bound for this element (an element with
    /// multiple `rdf:type`s yields one row per type, per SPARQL BGP
    /// semantics for `?elementId a ?elementType`).
    pub element_type: String,
    /// `powl2:activityLabel`, bound when the element is a
    /// `powl2:ActivityLeaf`.
    pub activity_label: Option<String>,
    /// `powl2:childIndex` of a bound `powl2:hasChild` -> `ChildBinding` edge.
    pub child_index: Option<String>,
    /// `powl2:childModel` IRI of a bound `powl2:hasChild` -> `ChildBinding`
    /// edge.
    pub child_model: Option<String>,
    /// The target of a `powl2:precedes` edge from this element.
    pub precedes_target: Option<String>,
    /// `powl2:hasRegion` target, bound when the element is a
    /// `powl2:ExternalCut`.
    pub region_id: Option<String>,
    /// `powl2:sparqlProjection` literal (Q), bound when the element is a
    /// `powl2:ExternalCut`.
    pub sparql_projection: Option<String>,
    /// `powl2:teraRenderer` literal (T), bound when the element is a
    /// `powl2:ExternalCut`.
    pub tera_renderer: Option<String>,
    /// `powl2:derivedFrom` IRI, bound on the model root when
    /// [`powl_to_turtle`] was called with `derived_from = Some(_)`.
    pub derived_from: Option<String>,
    /// `powl2:startNode` target, bound when the element is a
    /// `powl2:ChoiceGraph` (Def 3.6's `▷` sentinel).
    pub start_node: Option<String>,
    /// `powl2:endNode` target, bound when the element is a
    /// `powl2:ChoiceGraph` (Def 3.6's `□` sentinel).
    pub end_node: Option<String>,
    /// One `powl2:hasNode` target of a bound `powl2:ChoiceGraph` element --
    /// a `▷`/`□` sentinel or a `powl2:ChildNode` routing-graph node.
    pub routing_node: Option<String>,
    /// `powl2:ofChildIndex` of `routing_node`, bound only when `routing_node`
    /// is a `powl2:ChildNode` (the `▷`/`□` sentinels carry none). Distinct
    /// from `child_index`, which is a `powl2:ChildBinding`'s index rather
    /// than a routing-graph node's.
    pub routing_node_child_index: Option<String>,
    /// One `powl2:hasEdge` target of a bound `powl2:ChoiceGraph` element --
    /// a reified `powl2:GraphEdge` subject IRI.
    pub edge_id: Option<String>,
    /// `powl2:edgeSource` of `edge_id`.
    pub edge_source: Option<String>,
    /// `powl2:edgeTarget` of `edge_id`.
    pub edge_target: Option<String>,
    /// `powl2:hasInvariant` of the element.
    pub process_invariant: Option<String>,
    /// `powl2:hasExogenousEvent` of the element.
    pub exogenous_event: Option<String>,
    /// `powl2:hasResourceAnnotation` of the element.
    pub resource_annotation: Option<String>,
    /// `powl2:hasGuard` of the element.
    pub guard_condition: Option<String>,
}

/// Executes the real Q-stage SPARQL projection ([`RENDER_MODEL_PROJECTION_QUERY`])
/// against `turtle` (as produced by [`powl_to_turtle`] for an admitted POWL
/// region) via a fresh in-memory oxigraph store, returning the flattened
/// relational rows Q(W) produces.
///
/// This is the SPARQL execution stage of PRD.md sec.7.4's `A_z = T(Q(W))`,
/// distinct from [`powl_to_turtle`] (which only produces the admitted
/// region's Turtle text, `W`): this function computes `Q` applied to `W`.
/// Deterministic: the query's own `ORDER BY` over every bound variable fixes
/// solution order, and each row's fields are read directly off the oxigraph
/// binding -- no HashMap, no wall clock, no randomness.
///
/// # Errors
/// [`Refusal::ValidationFailed`] if `turtle` fails to parse as Turtle, if
/// the embedded query fails to parse (a defect in this crate, not caller
/// input -- the query is a fixed compile-time constant), or if a solution
/// binds a projected variable to a term kind this projection does not
/// expect (the query only ever binds `?elementId`/`?elementType`/etc. to
/// IRIs or literals under [`powl_to_turtle`]'s IRI-only emission, so a
/// blank-node binding would indicate the input Turtle did not actually come
/// from that emitter).
///
/// # Complexity
/// O(t) to parse and load `turtle` (t = byte length) plus O(m log m) for the
/// query engine's `ORDER BY` over m solutions.
pub fn run_render_model_projection(turtle: &str) -> Result<Vec<ProjectionRow>, Refusal> {
    let store = Store::new().map_err(|e| {
        Refusal::ValidationFailed(format!("projection store construction failed: {e}"))
    })?;
    store
        .load_from_slice(RdfParser::from_format(RdfFormat::Turtle), turtle)
        .map_err(|e| Refusal::ValidationFailed(format!("projection Turtle load failed: {e}")))?;

    let prepared = SparqlEvaluator::new()
        .parse_query(RENDER_MODEL_PROJECTION_QUERY)
        .map_err(|e| {
            Refusal::ValidationFailed(format!(
                "render_model_projection.rq parse failed (crate defect): {e}"
            ))
        })?;
    let results = prepared.on_store(&store).execute().map_err(|e| {
        Refusal::ValidationFailed(format!("render_model_projection.rq execution failed: {e}"))
    })?;

    let mut rows = Vec::new();
    match results {
        QueryResults::Solutions(solutions) => {
            // O(m): one row per solution, in the query's own ORDER BY order.
            for solution in solutions {
                let solution = solution.map_err(|e| {
                    Refusal::ValidationFailed(format!("projection solution evaluation failed: {e}"))
                })?;
                let element_id = term_string(&solution, "elementId")?.ok_or_else(|| {
                    Refusal::ValidationFailed(
                        "projection row missing mandatory ?elementId".to_string(),
                    )
                })?;
                let element_type = term_string(&solution, "elementType")?.ok_or_else(|| {
                    Refusal::ValidationFailed(
                        "projection row missing mandatory ?elementType".to_string(),
                    )
                })?;
                rows.push(ProjectionRow {
                    element_id,
                    element_type,
                    activity_label: term_string(&solution, "activityLabel")?,
                    child_index: term_string(&solution, "childIndex")?,
                    child_model: term_string(&solution, "childModel")?,
                    precedes_target: term_string(&solution, "precedesTarget")?,
                    region_id: term_string(&solution, "regionId")?,
                    sparql_projection: term_string(&solution, "sparqlProjection")?,
                    tera_renderer: term_string(&solution, "teraRenderer")?,
                    derived_from: term_string(&solution, "derivedFrom")?,
                    start_node: term_string(&solution, "startNode")?,
                    end_node: term_string(&solution, "endNode")?,
                    routing_node: term_string(&solution, "routingNode")?,
                    routing_node_child_index: term_string(&solution, "routingNodeChildIndex")?,
                    edge_id: term_string(&solution, "edgeId")?,
                    edge_source: term_string(&solution, "edgeSource")?,
                    edge_target: term_string(&solution, "edgeTarget")?,
                    process_invariant: term_string(&solution, "processInvariant")?,
                    exogenous_event: term_string(&solution, "exogenousEvent")?,
                    resource_annotation: term_string(&solution, "resourceAnnotation")?,
                    guard_condition: term_string(&solution, "guardCondition")?,
                });
            }
        }
        _ => {
            return Err(Refusal::ValidationFailed(
                "render_model_projection.rq did not yield SELECT solutions".to_string(),
            ))
        }
    }
    Ok(rows)
}

/// Reads `var` out of `solution` as its lexical string form: an IRI's full
/// IRI text, or a literal's lexical value. Returns `Ok(None)` when `var` is
/// unbound (the common case for an `OPTIONAL` block that did not match this
/// row's element kind).
///
/// # Complexity
/// O(1).
fn term_string(solution: &QuerySolution, var: &str) -> Result<Option<String>, Refusal> {
    match solution.get(var) {
        None => Ok(None),
        Some(Term::NamedNode(n)) => Ok(Some(n.as_str().to_string())),
        Some(Term::Literal(l)) => Ok(Some(l.value().to_string())),
        Some(other) => Err(Refusal::ValidationFailed(format!(
            "projection variable ?{var} bound to unsupported term kind: {other}"
        ))),
    }
}

// ── External-cut Rail A/B compiler seam (PROJ-796) ──────────────────────────
//
// `ChatmanEngine::admit_transition_with_external_cut` (`chatman::engine`)
// needs to run Rail A's `T` stage (Tera render) and Rail B's Arazzo -> AIR
// lowering/compilation over a POWL region this module has already admitted
// and projected -- but the real implementations of those two stages live in
// `praxis-core` (`arazzo::render_arazzo_document` + `wasm4pm-arazzo`), and
// `praxis-core` already depends on `praxis-graphlaw` (see that crate's
// Cargo.toml comment). The reverse edge would be a cyclic crate dependency,
// so this crate cannot call into `praxis-core` directly. The trait below is
// the seam: `ChatmanEngine` depends on it, and the one real implementation
// this workspace ships (`praxis_core::arazzo::ChatmanRailAbCompiler`) is
// injected by the caller who already links both crates.

/// True when `model` contains at least one [`Powl::ExternalCut`] node
/// anywhere in the tree (a `PartialOrder`/`Choice` container's children are
/// scanned, but an already-found cut's own `region` is not further
/// descended into -- the same traversal boundary [`admit_powl_model`] uses,
/// since a cut's region is opaque to the projecting workflow by definition,
/// PRD.md sec.7.4).
///
/// This is the trigger `ChatmanEngine::admit_transition_with_external_cut`
/// uses to decide whether the real Rail A/B pipeline runs at all for a
/// given admission: PRD.md sec.19.1's "local POWL remains local" scenario
/// means a region with no declared cut never engages the pipeline.
///
/// # Complexity
/// O(n) in the total node count of the model tree; short-circuits on the
/// first hit.
pub fn model_declares_external_cut(model: &Powl) -> bool {
    match model {
        Powl::Leaf(_) => false,
        Powl::PartialOrder { children, .. } | Powl::Choice { children, .. } => {
            children.iter().any(model_declares_external_cut)
        }
        Powl::ExternalCut { .. } => true,
    }
}

/// Real materials handed to an [`ExternalCutCompiler`]: the admitted
/// region's own Turtle (already gated through [`admit_powl_model`] via
/// [`powl_to_turtle`]) plus the identity the manufactured Arazzo document
/// should carry.
#[derive(Debug, Clone, Copy)]
pub struct ExternalCutCompilationRequest<'a> {
    /// The admitted region's Turtle, `W` in `A_z = T(Q(W))` (PRD.md
    /// sec.7.4) -- already passed [`admit_powl_model`] (via
    /// [`powl_to_turtle`]) before this request is built.
    pub region_turtle: &'a str,
    /// The region's root subject IRI (`Q`'s starting point).
    pub root_element_id: &'a str,
    /// The manufactured Arazzo document's `workflowId`.
    pub workflow_id: &'a str,
    /// The manufactured Arazzo document's `info.title`.
    pub title: &'a str,
}

/// Real output of one [`ExternalCutCompiler::compile`] run: every material
/// digest an `ArazzoProjectionReceipt` (`praxis_core::arazzo`) needs, plus
/// the manufactured Arazzo document text itself. Deliberately mirrors that
/// type's fields (minus `external_cut_identity`, which the caller already
/// carries) rather than depending on it directly: this crate cannot depend
/// on `praxis-core` (see this section's header comment), so it defines its
/// own copy of the shape instead of importing it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExternalCutCompilationOutcome {
    /// BLAKE3 digest (hex) of `region_turtle`.
    pub source_powl_digest_hex: String,
    /// BLAKE3 digest (hex) of the SPARQL query text actually executed (Q).
    pub sparql_projection_digest_hex: String,
    /// BLAKE3 digest (hex) of the Tera template text actually rendered (T).
    pub tera_template_digest_hex: String,
    /// BLAKE3 digest (hex) of the manufactured Arazzo JSON document.
    pub arazzo_digest_hex: String,
    /// The compiler version string folded into the receipt.
    pub compiler_version: String,
    /// BLAKE3 digest (hex) of the compiled AIR module
    /// (`wasm4pm_arazzo::compile::AirCompiler::digest_program`).
    pub air_digest_hex: String,
    /// The manufactured Arazzo 1.1.x JSON document text (`A_z`).
    pub arazzo_document: String,
}

/// Rail A/B pipeline seam (PROJ-796). See this section's header comment for
/// why this is a trait rather than a direct call. Implementors must be
/// deterministic and perform no I/O beyond in-memory computation (no wall
/// clock, no randomness) -- the same discipline every other stage in this
/// module follows.
pub trait ExternalCutCompiler {
    /// Runs the real Q(W) SPARQL projection, T(...) Tera render, Arazzo
    /// parse/normalize, and AIR lowering/compilation over `request`.
    fn compile(
        &self,
        request: &ExternalCutCompilationRequest<'_>,
    ) -> Result<ExternalCutCompilationOutcome, Refusal>;
}

#[cfg(test)]
mod tests {
    use super::*;
    use powl2_decompose::ChoiceGraph;

    const PROJECTION: &str = "SELECT * WHERE { ?s ?p ?o }";
    const RENDERER: &str = "arazzo_step.tera";

    /// A minimal admitted region containing one external cut: a two-step
    /// `PartialOrder` where the second step is the cut. Exercises the
    /// admission walker's descent into a `PartialOrder`'s children (the cut
    /// is not the tree root), not just the trivial cut-at-root case already
    /// covered by `powl2_decompose::external_cut`'s own unit tests.
    fn model_with_external_cut() -> Powl {
        Powl::PartialOrder {
            children: vec![
                Powl::Leaf(Some("intake".to_string())),
                Powl::ExternalCut {
                    region: Box::new(Powl::Leaf(Some("remote_settle".to_string()))),
                    projection: PROJECTION.to_string(),
                    renderer: RENDERER.to_string(),
                },
            ],
            order: std::collections::BTreeSet::from([(0usize, 1usize)]),
        }
    }

    // ── Admission wiring (PROJ-751 part 1): validate_external_cut is a real
    // ── gate on powl_to_turtle, not an unwired test-only function.

    #[test]
    fn powl_to_turtle_admits_a_valid_external_cut() -> Result<(), Refusal> {
        let model = model_with_external_cut();
        let turtle = powl_to_turtle(&model, "urn:test:cut", None)?;
        assert!(turtle.contains("powl2:ExternalCut"));
        Ok(())
    }

    #[test]
    fn powl_to_turtle_refuses_external_cut_with_empty_projection() {
        let model = Powl::ExternalCut {
            region: Box::new(Powl::Leaf(Some("x".to_string()))),
            projection: String::new(),
            renderer: "t".to_string(),
        };
        let result = powl_to_turtle(&model, "urn:neg:empty-projection", None);
        assert!(
            matches!(
                &result,
                Err(Refusal::ExternalCutUndeclared(msg)) if msg.contains("EXTERNAL_CUT_UNDECLARED")
            ),
            "refusal must be the typed ExternalCutUndeclared variant, got: {result:?}"
        );
    }

    #[test]
    fn powl_to_turtle_refuses_nested_external_cut_inside_partial_order() {
        // The cut is a *child* of a PartialOrder, not the model root --
        // proves the admission walker descends into PartialOrder children
        // to find external cuts, rather than only checking a root-level cut.
        let inner_cut = Powl::ExternalCut {
            region: Box::new(Powl::Leaf(Some("b".to_string()))),
            projection: "q".to_string(),
            renderer: "t".to_string(),
        };
        let outer_cut = Powl::ExternalCut {
            region: Box::new(inner_cut),
            projection: "q2".to_string(),
            renderer: "t2".to_string(),
        };
        let model = Powl::PartialOrder {
            children: vec![Powl::Leaf(Some("a".to_string())), outer_cut],
            order: std::collections::BTreeSet::new(),
        };
        let result = powl_to_turtle(&model, "urn:neg:nested-cut", None);
        assert!(
            matches!(
                &result,
                Err(Refusal::PowlRegionNotAdmitted(msg)) if msg.contains("POWL_REGION_NOT_ADMITTED")
            ),
            "refusal must be the typed PowlRegionNotAdmitted variant, got: {result:?}"
        );
    }

    // ── Real SPARQL execution (PROJ-751 part 2): the corrected .rq query
    // ── actually runs, via oxigraph, against RDF powl_to_turtle emits, and
    // ── returns real rows -- not just "compiles".

    #[test]
    fn admitted_external_cut_produces_real_sparql_projection_rows() -> Result<(), Refusal> {
        let model = model_with_external_cut();
        let turtle = powl_to_turtle(&model, "urn:test:cut", None)?;

        let rows = run_render_model_projection(&turtle)?;
        assert!(
            !rows.is_empty(),
            "the corrected query must yield real result rows over real emitted RDF"
        );

        // Exactly one ExternalCut-typed row, with the real Q/T/W triple.
        let cut_type = format!("{POWL2_PREFIX}ExternalCut");
        let cut_rows: Vec<&ProjectionRow> =
            rows.iter().filter(|r| r.element_type == cut_type).collect();
        assert_eq!(
            cut_rows.len(),
            1,
            "expected exactly one ExternalCut row, got {cut_rows:?}"
        );
        let cut_row = cut_rows[0];
        assert_eq!(cut_row.element_id, "urn:test:cut/n0/c1");
        assert_eq!(
            cut_row.region_id.as_deref(),
            Some("urn:test:cut/n0/c1/region")
        );
        assert_eq!(cut_row.sparql_projection.as_deref(), Some(PROJECTION));
        assert_eq!(cut_row.tera_renderer.as_deref(), Some(RENDERER));

        // The activity inside the cut's admitted region was itself
        // projected -- proving W (the region) round-tripped through Turtle
        // and back out through the SPARQL query, not just the cut wrapper.
        assert!(
            rows.iter()
                .any(|r| r.element_id == "urn:test:cut/n0/c1/region"
                    && r.activity_label.as_deref() == Some("remote_settle")),
            "the external cut's admitted region must appear in the projection"
        );

        // The sibling activity outside the cut is projected too.
        assert!(
            rows.iter().any(|r| r.element_id == "urn:test:cut/n0/c0"
                && r.activity_label.as_deref() == Some("intake")),
            "activities outside the cut must still be projected"
        );

        // The real precedes edge between the two top-level bindings.
        assert!(
            rows.iter()
                .any(|r| r.element_id == "urn:test:cut/n0/binding/0"
                    && r.precedes_target.as_deref() == Some("urn:test:cut/n0/binding/1")),
            "the transitively-closed order relation must survive Turtle round-trip"
        );

        Ok(())
    }

    // ── Choice-routing projection (PROJ-751 remediation): the query's
    // ── initial vocabulary-correction pass omitted every predicate the
    // ── Powl::Choice arm of emit_powl_node emits, silently dropping a
    // ── Choice node's entire routing topology (an adversarial review
    // ── found this with zero prior test coverage of a Choice node through
    // ── the query at all).

    /// A minimal admitted `Choice` (XOR) region: two leaf activities,
    /// `▷ -> {approve, reject} -> □`. Exercises every routing predicate
    /// `Powl::Choice`'s Turtle arm emits: `powl2:startNode`/`endNode`,
    /// `powl2:hasNode` over both sentinels and both `ChildNode`s,
    /// `powl2:ofChildIndex`, and the 4 reified `powl2:GraphEdge`s.
    fn model_with_choice() -> Powl {
        Powl::Choice {
            children: vec![
                Powl::Leaf(Some("approve".to_string())),
                Powl::Leaf(Some("reject".to_string())),
            ],
            graph: ChoiceGraph {
                n: 2,
                edges: std::collections::BTreeSet::from([
                    (GNode::Start, GNode::Child(0)),
                    (GNode::Start, GNode::Child(1)),
                    (GNode::Child(0), GNode::End),
                    (GNode::Child(1), GNode::End),
                ]),
            },
        }
    }

    #[test]
    fn admitted_choice_node_produces_real_sparql_routing_projection_rows() -> Result<(), Refusal> {
        let model = model_with_choice();
        let turtle = powl_to_turtle(&model, "urn:test:choice", Some("urn:test:plan-source"))?;

        let rows = run_render_model_projection(&turtle)?;
        assert!(
            !rows.is_empty(),
            "the corrected query must yield real result rows over real emitted RDF"
        );

        let choice_type = format!("{POWL2_PREFIX}ChoiceGraph");
        let choice_rows: Vec<&ProjectionRow> = rows
            .iter()
            .filter(|r| r.element_type == choice_type)
            .collect();
        assert!(
            !choice_rows.is_empty(),
            "expected at least one ChoiceGraph row, got zero: {rows:?}"
        );
        // Every ChoiceGraph row shares the same subject and the same
        // functional startNode/endNode bindings.
        for row in &choice_rows {
            assert_eq!(row.element_id, "urn:test:choice/n0");
            assert_eq!(row.start_node.as_deref(), Some("urn:test:choice/n0/start"));
            assert_eq!(row.end_node.as_deref(), Some("urn:test:choice/n0/end"));
        }

        // The root's provenance link survives the round trip too (PROJ-751
        // also flagged root-level powl2:derivedFrom as unprojected).
        assert!(
            rows.iter().any(|r| r.element_id == "urn:test:choice/n0"
                && r.derived_from.as_deref() == Some("urn:test:plan-source")),
            "powl2:derivedFrom must survive Turtle round-trip through the projection"
        );

        // Both sentinel routing nodes (▷/□) are reachable via hasNode, with
        // no ofChildIndex (only ChildNode members carry one).
        assert!(
            choice_rows.iter().any(|r| r.routing_node.as_deref()
                == Some("urn:test:choice/n0/start")
                && r.routing_node_child_index.is_none()),
            "the ▷ sentinel must be projected as a routing node with no ofChildIndex"
        );
        assert!(
            choice_rows.iter().any(
                |r| r.routing_node.as_deref() == Some("urn:test:choice/n0/end")
                    && r.routing_node_child_index.is_none()
            ),
            "the □ sentinel must be projected as a routing node with no ofChildIndex"
        );

        // Both ChildNode routing nodes are reachable via hasNode, each
        // carrying its real ofChildIndex.
        assert!(
            choice_rows.iter().any(|r| r.routing_node.as_deref()
                == Some("urn:test:choice/n0/node/0")
                && r.routing_node_child_index.as_deref() == Some("0")),
            "child routing node 0 must carry ofChildIndex 0"
        );
        assert!(
            choice_rows.iter().any(|r| r.routing_node.as_deref()
                == Some("urn:test:choice/n0/node/1")
                && r.routing_node_child_index.as_deref() == Some("1")),
            "child routing node 1 must carry ofChildIndex 1"
        );

        // All 4 reified routing edges survive with their real
        // edgeSource/edgeTarget pairs: ▷->node/0, ▷->node/1, node/0->□,
        // node/1->□.
        let expected_edges = [
            ("urn:test:choice/n0/start", "urn:test:choice/n0/node/0"),
            ("urn:test:choice/n0/start", "urn:test:choice/n0/node/1"),
            ("urn:test:choice/n0/node/0", "urn:test:choice/n0/end"),
            ("urn:test:choice/n0/node/1", "urn:test:choice/n0/end"),
        ];
        for (source, target) in expected_edges {
            assert!(
                choice_rows
                    .iter()
                    .any(|r| r.edge_source.as_deref() == Some(source)
                        && r.edge_target.as_deref() == Some(target)),
                "expected a projected GraphEdge {source} -> {target}, got: {choice_rows:?}"
            );
        }
        // Exactly 4 distinct edge subjects were projected (no duplication,
        // no dropped edges).
        let distinct_edge_ids: std::collections::BTreeSet<&str> = choice_rows
            .iter()
            .filter_map(|r| r.edge_id.as_deref())
            .collect();
        assert_eq!(
            distinct_edge_ids.len(),
            4,
            "expected exactly 4 distinct GraphEdge subjects, got: {distinct_edge_ids:?}"
        );

        // Both child activities under the Choice are themselves projected --
        // proving the children round-tripped through Turtle, not just the
        // routing-graph wrapper.
        assert!(
            rows.iter().any(|r| r.element_id == "urn:test:choice/n0/c0"
                && r.activity_label.as_deref() == Some("approve")),
            "child activity 0 must still be projected alongside its routing node"
        );
        assert!(
            rows.iter().any(|r| r.element_id == "urn:test:choice/n0/c1"
                && r.activity_label.as_deref() == Some("reject")),
            "child activity 1 must still be projected alongside its routing node"
        );

        Ok(())
    }

    #[test]
    fn run_render_model_projection_is_deterministic() -> Result<(), Refusal> {
        let model = model_with_external_cut();
        let turtle = powl_to_turtle(&model, "urn:test:cut-determinism", None)?;
        let rows_a = run_render_model_projection(&turtle)?;
        let rows_b = run_render_model_projection(&turtle)?;
        assert_eq!(
            rows_a, rows_b,
            "identical Turtle input must yield byte-identical projection rows across repeated runs"
        );
        Ok(())
    }

    #[test]
    fn run_render_model_projection_refuses_unparsable_turtle() {
        let result = run_render_model_projection("this is not turtle {{{");
        assert!(
            matches!(result, Err(Refusal::ValidationFailed(_))),
            "expected ValidationFailed on unparsable input"
        );
    }

    // ── model_declares_external_cut (PROJ-796 trigger check) ────────────

    #[test]
    fn model_declares_external_cut_is_true_for_a_nested_cut() {
        assert!(model_declares_external_cut(&model_with_external_cut()));
    }

    #[test]
    fn model_declares_external_cut_is_false_with_no_cut_anywhere() {
        let model = Powl::PartialOrder {
            children: vec![
                Powl::Leaf(Some("a".to_string())),
                Powl::Leaf(Some("b".to_string())),
            ],
            order: std::collections::BTreeSet::from([(0usize, 1usize)]),
        };
        assert!(!model_declares_external_cut(&model));
    }

    #[test]
    fn model_declares_external_cut_is_false_for_a_single_leaf() {
        assert!(!model_declares_external_cut(&Powl::Leaf(None)));
    }

    // ── resolve_external_cut_at (PROJ-783, EXTERNAL_CUT_TYPE_MISMATCH) ──

    #[test]
    fn resolve_external_cut_at_finds_the_real_cut_by_socket_path() -> Result<(), Refusal> {
        let model = model_with_external_cut();
        // model_with_external_cut() is a two-child PartialOrder whose
        // second child (index 1) is the ExternalCut.
        let path = SocketPath::root().child(1);
        let node = resolve_external_cut_at(&model, &path)?;
        assert!(matches!(node, Powl::ExternalCut { .. }));
        Ok(())
    }

    #[test]
    fn resolve_external_cut_at_refuses_a_path_that_names_a_non_cut_node() {
        let model = model_with_external_cut();
        // Index 0 is the plain "intake" leaf, not an ExternalCut.
        let path = SocketPath::root().child(0);
        let result = resolve_external_cut_at(&model, &path);
        assert!(
            matches!(
                &result,
                Err(Refusal::ExternalCutTypeMismatch(msg)) if msg.contains("Leaf")
            ),
            "a path addressing a Leaf must refuse ExternalCutTypeMismatch naming the real \
             kind found there, got: {result:?}"
        );
    }

    #[test]
    fn resolve_external_cut_at_refuses_a_path_that_does_not_resolve() {
        let model = model_with_external_cut();
        // Only children 0 and 1 exist at the root.
        let path = SocketPath::root().child(7);
        let result = resolve_external_cut_at(&model, &path);
        assert!(
            matches!(&result, Err(Refusal::ExternalCutTypeMismatch(_))),
            "an out-of-range path must refuse ExternalCutTypeMismatch, got: {result:?}"
        );
    }

    #[test]
    fn resolve_external_cut_at_propagates_region_admission_refusals() {
        // The cut itself resolves, but its own admission is invalid (empty
        // projection) -- proves resolve_external_cut_at does not skip the
        // real validate_external_cut gate once a cut is found.
        let model = Powl::ExternalCut {
            region: Box::new(Powl::Leaf(Some("x".to_string()))),
            projection: String::new(),
            renderer: "t".to_string(),
        };
        let result = resolve_external_cut_at(&model, &SocketPath::root());
        assert!(
            matches!(&result, Err(Refusal::ExternalCutUndeclared(_))),
            "a resolved-but-invalid cut must still refuse via validate_external_cut, \
             got: {result:?}"
        );
    }

    // ── admit_provenance / EXTERNAL_CUT_AUTHORITY_MISMATCH (PROJ-783) ──

    #[test]
    fn powl_to_turtle_refuses_external_cut_with_mismatched_provenance_authority() {
        let model = model_with_external_cut();
        let result = powl_to_turtle(
            &model,
            "urn:tenant-a:region",
            Some("urn:tenant-b:other-snapshot"),
        );
        assert!(
            matches!(
                &result,
                Err(Refusal::ExternalCutAuthorityMismatch(msg))
                    if msg.contains("EXTERNAL_CUT_AUTHORITY_MISMATCH") || msg.contains("authority")
            ),
            "a derived_from IRI under a different authority than base_iri must refuse \
             ExternalCutAuthorityMismatch, got: {result:?}"
        );
    }

    #[test]
    fn powl_to_turtle_admits_external_cut_with_same_authority_different_path() -> Result<(), Refusal>
    {
        let model = model_with_external_cut();
        // Same "urn:tenant-a" authority, different structural path -- proves
        // the check compares authority, not full string equality.
        let turtle = powl_to_turtle(
            &model,
            "urn:tenant-a:region",
            Some("urn:tenant-a:other-snapshot"),
        )?;
        assert!(turtle.contains("powl2:derivedFrom"));
        Ok(())
    }

    #[test]
    fn powl_to_turtle_ignores_provenance_authority_for_a_model_with_no_cut() -> Result<(), Refusal>
    {
        // PRD.md sec.19.1 "local POWL remains local": a plain model with no
        // declared external cut never crosses a process-cell boundary, so a
        // mismatched derived_from authority is not an error for it.
        let model = Powl::PartialOrder {
            children: vec![Powl::Leaf(Some("a".to_string()))],
            order: std::collections::BTreeSet::new(),
        };
        let turtle = powl_to_turtle(
            &model,
            "urn:tenant-a:region",
            Some("urn:tenant-b:other-snapshot"),
        )?;
        assert!(turtle.contains("powl2:Model"));
        Ok(())
    }

    #[test]
    fn iri_authority_distinguishes_urn_and_http_authorities() {
        assert_eq!(iri_authority("urn:test:cut"), "urn:test");
        assert_eq!(
            iri_authority("urn:chatman:rail-ab-wiring:test"),
            "urn:chatman"
        );
        assert_eq!(iri_authority("http://example.org/foo/bar"), "example.org");
        assert_ne!(
            iri_authority("urn:tenant-a:x"),
            iri_authority("urn:tenant-b:x")
        );
    }
}
