//! Projects Chatman Engine PDDL plan tapes ([`Pddl8Tape`]) into POWL 2.0
//! models ([`Powl`], Kourani et al. Defs 3.6-3.9), admits and serializes
//! those models as RDF Turtle conforming to the `powl2:` vocabulary
//! (`wasm4pm-compat/ontologies/powlv2.ttl`), and executes the Q-stage
//! SPARQL projection of PRD.md sec.7.4's `A_z = T(Q(W))` external-cut
//! pipeline against that Turtle ([`run_render_model_projection`]).
//!
//! The projection functions ([`project_pddl_tape_to_powl`],
//! [`project_pddl_tape_to_powl_hierarchical`], [`powl_to_turtle`]) are pure:
//! no I/O, no wall clock, no randomness. IRIs generated by [`powl_to_turtle`]
//! are derived deterministically from `base_iri` plus a stable structural
//! path (child index at each level of the tree), never from a blank-node
//! counter or hash map iteration order. [`run_render_model_projection`] is
//! the one exception to "no I/O": the query text it executes is embedded at
//! compile time (`include_str!`, not a runtime read), and the SPARQL
//! evaluation itself runs over an in-memory oxigraph store built solely from
//! its `turtle` argument -- no ambient state, no network, no wall clock.

use bcinr_pddl::Pddl8Tape;
use oxigraph::io::{RdfFormat, RdfParser};
use oxigraph::sparql::{QueryResults, QuerySolution, SparqlEvaluator};
use oxigraph::store::Store;
use oxrdf::Term;
use powl2_decompose::{validate_external_cut, GNode, Powl};

use super::abi::Refusal;

/// Projects a bounded, sequential Chatman Engine PDDL plan tape into a POWL 2.0
/// model (Kourani et al. Defs 3.6-3.9), matching crates/powl2-decompose's Powl type.
///
/// # Complexity
/// O(n) where n = tape.ops.len() — one Leaf + one order pair per op, no nested search.
pub fn project_pddl_tape_to_powl(tape: &Pddl8Tape) -> Result<Powl, Refusal> {
    if tape.ops.is_empty() {
        return Err(Refusal::PlanInfeasible(
            "cannot project an empty PDDL plan tape to a POWL model".to_string(),
        ));
    }

    let children: Vec<Powl> = tape
        .ops
        .iter()
        .map(|op| Powl::Leaf(Some(op.label.clone())))
        .collect();

    // Pddl8Tape::from_plan encodes a strict linear (total) order over ops:
    // op i>0 depends only on op i-1 via pred_mask, but the honest projection
    // of a total sequential order is its full transitive closure — every
    // earlier op strictly precedes every later op, not just its immediate
    // predecessor. n = children.len(); this loop is O(n^2) pairs, which is
    // O(n) in the *output* size (the transitively-closed order relation is
    // itself quadratic in a total order of n elements) and is bounded by the
    // 8-bit tape width (n <= 256) enforced upstream by Pddl8Tape.
    let n = children.len();
    let mut order = std::collections::BTreeSet::new();
    for i in 0..n {
        for j in (i + 1)..n {
            order.insert((i, j));
        }
    }

    Ok(Powl::PartialOrder { children, order })
}

/// Projects a bounded, sequential Chatman Engine PDDL plan tape into a
/// *hierarchical* (2-level) POWL 2.0 model: tape ops are grouped into
/// phases, a phase being a maximal run of tape-adjacent ops whose action
/// schemas share the same contributing source artifact per
/// `action_sources` (schema name → source artifact IRI). Each phase becomes
/// a `Powl::PartialOrder` over `Leaf(Some(label))` children with the
/// transitively closed intra-phase order; the root is a `PartialOrder` over
/// the phase children with the transitively closed inter-phase order. A
/// single-source tape still yields this uniform 2-level shape (one phase).
///
/// Sibling to [`project_pddl_tape_to_powl`], which stays flat. No new
/// semantic authority is introduced: nesting is derived purely from the
/// supplied provenance mapping.
///
/// Returns the model plus `phase_sources`: one source artifact IRI per
/// top-level phase child, in phase order.
///
/// Deterministic: grouping is driven solely by tape order and `BTreeMap`
/// lookups — no hash-map iteration, no wall clock, no randomness.
///
/// # Errors
/// - [`Refusal::PlanInfeasible`] for an empty tape (same refusal as the
///   flat projection).
/// - [`Refusal::ValidationFailed`] if a tape op's action schema has no
///   contributing source artifact in `action_sources` — the hierarchical
///   model would be detached from its admitted inputs.
///
/// # Complexity
/// O(n log n) to group n = tape.ops.len() ops into phases (one BTreeMap
/// lookup per op), plus O(n^2) total across all levels to store the
/// transitively closed order relations — the same asymptotic bound as the
/// flat projection, split across the phase and root levels, and bounded by
/// the 8-bit tape width (n <= 256) enforced upstream by [`Pddl8Tape`].
pub fn project_pddl_tape_to_powl_hierarchical(
    tape: &Pddl8Tape,
    action_sources: &std::collections::BTreeMap<String, String>,
) -> Result<(Powl, Vec<String>), Refusal> {
    if tape.ops.is_empty() {
        return Err(Refusal::PlanInfeasible(
            "cannot project an empty PDDL plan tape to a POWL model".to_string(),
        ));
    }

    // Group into maximal tape-adjacent runs sharing the same source
    // artifact. O(n log n): one BTreeMap lookup per op, tape order only.
    let mut phases: Vec<(String, Vec<usize>)> = Vec::new();
    for (i, op) in tape.ops.iter().enumerate() {
        let source = action_sources
            .get(&op.action.schema_name)
            .cloned()
            .ok_or_else(|| {
                Refusal::ValidationFailed(format!(
                    "plan op {:?} has no contributing source artifact in action_sources; \
                     hierarchical POWL output would be detached from its inputs",
                    op.action.schema_name
                ))
            })?;
        match phases.last_mut() {
            Some((last_source, indices)) if *last_source == source => indices.push(i),
            _ => phases.push((source, vec![i])),
        }
    }

    let phase_sources: Vec<String> = phases.iter().map(|(source, _)| source.clone()).collect();

    // Each phase: leaves in tape order with the transitively closed
    // intra-phase total order (O(k^2) pairs per phase of k ops — see the
    // flat projection's rationale: the closed relation is itself quadratic).
    let phase_children: Vec<Powl> = phases
        .into_iter()
        .map(|(_, indices)| {
            let leaves: Vec<Powl> = indices
                .iter()
                .map(|&i| Powl::Leaf(Some(tape.ops[i].label.clone())))
                .collect();
            let k = leaves.len();
            let mut order = std::collections::BTreeSet::new();
            for a in 0..k {
                for b in (a + 1)..k {
                    order.insert((a, b));
                }
            }
            Powl::PartialOrder {
                children: leaves,
                order,
            }
        })
        .collect();

    // Root: phases in tape order with the transitively closed inter-phase
    // total order (O(p^2) pairs for p phases).
    let p = phase_children.len();
    let mut root_order = std::collections::BTreeSet::new();
    for a in 0..p {
        for b in (a + 1)..p {
            root_order.insert((a, b));
        }
    }

    Ok((
        Powl::PartialOrder {
            children: phase_children,
            order: root_order,
        },
        phase_sources,
    ))
}

const POWL2_PREFIX: &str = "https://truex.io/ontology/powl2#";

/// Escapes a string literal for safe embedding in a Turtle `"..."` literal.
///
/// # Complexity
/// O(len(s)) — single linear pass.
fn escape_turtle_literal(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(c),
        }
    }
    out
}

/// Admits a POWL model before it is ever turned into RDF: every
/// [`Powl::ExternalCut`] node anywhere in the tree — not just at the root —
/// must pass [`validate_external_cut`]. This is the real POWL admission path
/// for PRD.md §7.4's external-cut projection (`A_z = T(Q(W))`): a declared
/// external cut is refused *here*, before any Turtle describing it is
/// produced or loaded into a store, rather than accepted structurally and
/// only checked by a test that never calls it (PROJ-751; prior state:
/// `validate_external_cut` had zero callers outside its own unit tests).
///
/// A hit on an `ExternalCut` node delegates the entire subtree (its nested
/// `region`) to `validate_external_cut`, which already walks that region
/// recursively and refuses further-nested cuts on its own
/// (`ExternalCutRefusal::PowlRegionNotAdmitted`) — so this walker does not
/// separately descend into an already-validated cut's region, avoiding
/// double traversal of the same subtree.
///
/// # Complexity
/// O(n) in the total node count of the model tree: each node is visited by
/// exactly one of this function's own recursion or `validate_external_cut`'s
/// internal region walk, never both.
fn admit_powl_model(model: &Powl) -> Result<(), Refusal> {
    match model {
        Powl::Leaf(_) => Ok(()),
        Powl::PartialOrder { children, .. } | Powl::Choice { children, .. } => {
            for child in children {
                admit_powl_model(child)?;
            }
            Ok(())
        }
        Powl::ExternalCut { .. } => validate_external_cut(model)
            .map_err(|e| Refusal::ValidationFailed(format!("external cut admission refused: {e}"))),
    }
}

/// Serializes a POWL 2.0 model as RDF Turtle conforming to the powl2: vocabulary
/// (wasm4pm-compat/ontologies/powlv2.ttl). Deterministic: no HashMap iteration,
/// blank-node-equivalent IRIs are derived from `base_iri` + a stable path (child
/// index at each level), and PartialOrder's `order` set (a BTreeSet) is emitted
/// in its natural sorted order.
///
/// For a plan projected by [`project_pddl_tape_to_powl`], the emitted
/// `powl2:precedes` relation is the transitive closure of the plan sequence:
/// Kourani Def 3.7 defines PartialOrder over a *strict partial order*, and the
/// crate's own `Powl::PartialOrder.order` stores that relation pre-closed, so
/// the Turtle mirrors the in-memory relation one triple per pair rather than
/// re-deriving adjacency. This choice is pinned by the projection tests.
///
/// `derived_from`: when `Some(iri)`, the root model node additionally carries
/// `powl2:derivedFrom <iri>` (a subproperty of `prov:wasDerivedFrom` in the
/// vocabulary), linking the manufactured POWL model back to the PDDL plan
/// source it was projected from (e.g. the snapshot IRI whose embedded PDDL
/// text produced the tape).
///
/// # Errors
/// Propagates [`admit_powl_model`]'s refusal (wrapped
/// [`powl2_decompose::ExternalCutRefusal`]) when any `ExternalCut` node in
/// `model` fails admission — no Turtle is emitted for a refused model.
///
/// # Complexity
/// O(n + |order|) in the total node count of the model tree plus the size of
/// each PartialOrder's (pre-closed, up to quadratic) order relation, plus the
/// O(n) admission pass.
pub fn powl_to_turtle(
    model: &Powl,
    base_iri: &str,
    derived_from: Option<&str>,
) -> Result<String, Refusal> {
    admit_powl_model(model)?;

    let base_iri = base_iri.trim_end_matches('/');
    let mut out = String::new();
    out.push_str("@prefix powl2: <");
    out.push_str(POWL2_PREFIX);
    out.push_str("> .\n");
    out.push_str("@prefix base: <");
    out.push_str(base_iri);
    out.push_str("/> .\n\n");

    let root_path = "n0";
    out.push_str(&format!("<{base_iri}/{root_path}> a powl2:Model .\n"));
    if let Some(source_iri) = derived_from {
        out.push_str(&format!(
            "<{base_iri}/{root_path}> powl2:derivedFrom <{source_iri}> .\n"
        ));
    }
    emit_powl_node(model, base_iri, root_path, &mut out);
    Ok(out)
}

/// Recursively emits Turtle triples for `model`, whose subject IRI is
/// `<base_iri>/<path>`. Child IRIs are `<base_iri>/<path>/c<index>` and
/// `PartialOrder` child-bindings are addressed at
/// `<base_iri>/<path>/binding/<index>` — both deterministic, structural, and
/// collision-free (each level appends a distinct literal segment).
///
/// # Complexity
/// O(n) in the size of the subtree rooted at `model`.
fn emit_powl_node(model: &Powl, base_iri: &str, path: &str, out: &mut String) {
    match model {
        Powl::Leaf(None) => {
            out.push_str(&format!(
                "<{base_iri}/{path}> a powl2:Leaf, powl2:SilentLeaf .\n"
            ));
        }
        Powl::Leaf(Some(label)) => {
            out.push_str(&format!(
                "<{base_iri}/{path}> a powl2:Leaf, powl2:ActivityLeaf ;\n"
            ));
            out.push_str(&format!(
                "  powl2:activityLabel \"{}\" .\n",
                escape_turtle_literal(label)
            ));
        }
        Powl::PartialOrder { children, order } => {
            out.push_str(&format!("<{base_iri}/{path}> a powl2:PartialOrder .\n"));
            for (idx, child) in children.iter().enumerate() {
                let child_path = format!("{path}/c{idx}");
                let binding_path = format!("{path}/binding/{idx}");
                out.push_str(&format!(
                    "<{base_iri}/{path}> powl2:hasChild <{base_iri}/{binding_path}> .\n"
                ));
                out.push_str(&format!(
                    "<{base_iri}/{binding_path}> a powl2:ChildBinding ;\n  powl2:childIndex {idx} ;\n  powl2:childModel <{base_iri}/{child_path}> .\n"
                ));
                emit_powl_node(child, base_iri, &child_path, out);
            }
            for (i, j) in order.iter() {
                out.push_str(&format!(
                    "<{base_iri}/{path}/binding/{i}> powl2:precedes <{base_iri}/{path}/binding/{j}> .\n"
                ));
            }
        }
        Powl::Choice { children, graph } => {
            // Vocabulary terms per powlv2.ttl: the ▷/□ sentinels are typed
            // powl2:StartNode / powl2:EndNode resources pointed at by the
            // functional powl2:startNode / powl2:endNode properties; each
            // routing edge is a reified powl2:GraphEdge with edgeSource /
            // edgeTarget; children are addressed both as ChildBindings and as
            // powl2:ChildNode routing-graph nodes.
            out.push_str(&format!("<{base_iri}/{path}> a powl2:ChoiceGraph .\n"));
            out.push_str(&format!(
                "<{base_iri}/{path}/start> a powl2:StartNode .\n<{base_iri}/{path}/end> a powl2:EndNode .\n"
            ));
            out.push_str(&format!(
                "<{base_iri}/{path}> powl2:startNode <{base_iri}/{path}/start> ;\n  powl2:endNode <{base_iri}/{path}/end> ;\n  powl2:hasNode <{base_iri}/{path}/start>, <{base_iri}/{path}/end> .\n"
            ));
            for (idx, child) in children.iter().enumerate() {
                let child_path = format!("{path}/c{idx}");
                let binding_path = format!("{path}/binding/{idx}");
                out.push_str(&format!(
                    "<{base_iri}/{path}> powl2:hasChild <{base_iri}/{binding_path}> .\n"
                ));
                out.push_str(&format!(
                    "<{base_iri}/{binding_path}> a powl2:ChildBinding ;\n  powl2:childIndex {idx} ;\n  powl2:childModel <{base_iri}/{child_path}> .\n"
                ));
                out.push_str(&format!(
                    "<{base_iri}/{path}/node/{idx}> a powl2:ChildNode ;\n  powl2:ofChildIndex {idx} .\n"
                ));
                out.push_str(&format!(
                    "<{base_iri}/{path}> powl2:hasNode <{base_iri}/{path}/node/{idx}> .\n"
                ));
                emit_powl_node(child, base_iri, &child_path, out);
            }
            for (edge_idx, (from, to)) in graph.edges.iter().enumerate() {
                let from_iri = gnode_iri(base_iri, path, *from);
                let to_iri = gnode_iri(base_iri, path, *to);
                out.push_str(&format!(
                    "<{base_iri}/{path}/edge/{edge_idx}> a powl2:GraphEdge ;\n  powl2:edgeSource {from_iri} ;\n  powl2:edgeTarget {to_iri} .\n"
                ));
                out.push_str(&format!(
                    "<{base_iri}/{path}> powl2:hasEdge <{base_iri}/{path}/edge/{edge_idx}> .\n"
                ));
            }
        }
        Powl::ExternalCut {
            region,
            projection,
            renderer,
        } => {
            out.push_str(&format!("<{base_iri}/{path}> a powl2:ExternalCut .\n"));
            out.push_str(&format!(
                "<{base_iri}/{path}> powl2:hasRegion <{base_iri}/{path}/region> ;\n"
            ));
            out.push_str(&format!(
                "  powl2:sparqlProjection \"{}\" ;\n",
                escape_turtle_literal(projection)
            ));
            out.push_str(&format!(
                "  powl2:teraRenderer \"{}\" .\n",
                escape_turtle_literal(renderer)
            ));
            emit_powl_node(region, base_iri, &format!("{path}/region"), out);
        }
    }
}

/// Renders a [`GNode`] as a complete bracketed Turtle IRI term relative to the
/// choice-graph node at `<base_iri>/<path>`: the artificial `▷`/`□` sentinels
/// become fixed `/start` / `/end` suffixed IRIs, and a child index becomes its
/// `/node/<idx>` routing-graph node IRI.
///
/// # Complexity
/// O(1).
fn gnode_iri(base_iri: &str, path: &str, node: GNode) -> String {
    match node {
        GNode::Start => format!("<{base_iri}/{path}/start>"),
        GNode::End => format!("<{base_iri}/{path}/end>"),
        GNode::Child(idx) => format!("<{base_iri}/{path}/node/{idx}>"),
    }
}

// ── Q-stage SPARQL projection (PRD.md sec.7.4: A_z = T(Q(W))) ──────────────

/// The Q-stage SPARQL projection query. Single source of truth is the
/// checked-in query file itself (`crates/wasm4pm-arazzo/queries/
/// render_model_projection.rq`), embedded at compile time so there is
/// exactly one copy of the query text -- never a second, driftable copy.
/// Vocabulary-aligned with this module's own emission (PROJ-751); the prior
/// iteration used `powl:`/`wf:`/`ext:` predicates this module never emits.
///
/// `pub` (PROJ-752): callers that build an [`crate::chatman::abi`]-external
/// `ArazzoProjectionReceipt` (`crates/praxis-core/src/arazzo.rs`) need the
/// exact executed query text to hash as the receipt's
/// `sparql_projection_digest_hex` -- reading this constant keeps that digest
/// bound to the query that actually ran, rather than a second copy someone
/// could let drift.
pub const RENDER_MODEL_PROJECTION_QUERY: &str =
    include_str!("../../../wasm4pm-arazzo/queries/render_model_projection.rq");

/// One flattened row of the Q(W) relational projection: the bound values of
/// one `?elementId` solution of [`RENDER_MODEL_PROJECTION_QUERY`]. Every
/// field but `element_id`/`element_type` is optional because the query's
/// `OPTIONAL` blocks bind only for the POWL element kinds that carry that
/// property -- e.g. `region_id`/`sparql_projection`/`tera_renderer` are
/// populated only for rows whose element is a `powl2:ExternalCut` subject.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProjectionRow {
    /// The projected element's subject IRI.
    pub element_id: String,
    /// One `rdf:type` object bound for this element (an element with
    /// multiple `rdf:type`s yields one row per type, per SPARQL BGP
    /// semantics for `?elementId a ?elementType`).
    pub element_type: String,
    /// `powl2:activityLabel`, bound when the element is a
    /// `powl2:ActivityLeaf`.
    pub activity_label: Option<String>,
    /// `powl2:childIndex` of a bound `powl2:hasChild` -> `ChildBinding` edge.
    pub child_index: Option<String>,
    /// `powl2:childModel` IRI of a bound `powl2:hasChild` -> `ChildBinding`
    /// edge.
    pub child_model: Option<String>,
    /// The target of a `powl2:precedes` edge from this element.
    pub precedes_target: Option<String>,
    /// `powl2:hasRegion` target, bound when the element is a
    /// `powl2:ExternalCut`.
    pub region_id: Option<String>,
    /// `powl2:sparqlProjection` literal (Q), bound when the element is a
    /// `powl2:ExternalCut`.
    pub sparql_projection: Option<String>,
    /// `powl2:teraRenderer` literal (T), bound when the element is a
    /// `powl2:ExternalCut`.
    pub tera_renderer: Option<String>,
}

/// Executes the real Q-stage SPARQL projection ([`RENDER_MODEL_PROJECTION_QUERY`])
/// against `turtle` (as produced by [`powl_to_turtle`] for an admitted POWL
/// region) via a fresh in-memory oxigraph store, returning the flattened
/// relational rows Q(W) produces.
///
/// This is the SPARQL execution stage of PRD.md sec.7.4's `A_z = T(Q(W))`,
/// distinct from [`powl_to_turtle`] (which only produces the admitted
/// region's Turtle text, `W`): this function computes `Q` applied to `W`.
/// Deterministic: the query's own `ORDER BY` over every bound variable fixes
/// solution order, and each row's fields are read directly off the oxigraph
/// binding -- no HashMap, no wall clock, no randomness.
///
/// # Errors
/// [`Refusal::ValidationFailed`] if `turtle` fails to parse as Turtle, if
/// the embedded query fails to parse (a defect in this crate, not caller
/// input -- the query is a fixed compile-time constant), or if a solution
/// binds a projected variable to a term kind this projection does not
/// expect (the query only ever binds `?elementId`/`?elementType`/etc. to
/// IRIs or literals under [`powl_to_turtle`]'s IRI-only emission, so a
/// blank-node binding would indicate the input Turtle did not actually come
/// from that emitter).
///
/// # Complexity
/// O(t) to parse and load `turtle` (t = byte length) plus O(m log m) for the
/// query engine's `ORDER BY` over m solutions.
pub fn run_render_model_projection(turtle: &str) -> Result<Vec<ProjectionRow>, Refusal> {
    let store = Store::new().map_err(|e| {
        Refusal::ValidationFailed(format!("projection store construction failed: {e}"))
    })?;
    store
        .load_from_slice(RdfParser::from_format(RdfFormat::Turtle), turtle)
        .map_err(|e| Refusal::ValidationFailed(format!("projection Turtle load failed: {e}")))?;

    let prepared = SparqlEvaluator::new()
        .parse_query(RENDER_MODEL_PROJECTION_QUERY)
        .map_err(|e| {
            Refusal::ValidationFailed(format!(
                "render_model_projection.rq parse failed (crate defect): {e}"
            ))
        })?;
    let results = prepared.on_store(&store).execute().map_err(|e| {
        Refusal::ValidationFailed(format!("render_model_projection.rq execution failed: {e}"))
    })?;

    let mut rows = Vec::new();
    match results {
        QueryResults::Solutions(solutions) => {
            // O(m): one row per solution, in the query's own ORDER BY order.
            for solution in solutions {
                let solution = solution.map_err(|e| {
                    Refusal::ValidationFailed(format!("projection solution evaluation failed: {e}"))
                })?;
                let element_id = term_string(&solution, "elementId")?.ok_or_else(|| {
                    Refusal::ValidationFailed(
                        "projection row missing mandatory ?elementId".to_string(),
                    )
                })?;
                let element_type = term_string(&solution, "elementType")?.ok_or_else(|| {
                    Refusal::ValidationFailed(
                        "projection row missing mandatory ?elementType".to_string(),
                    )
                })?;
                rows.push(ProjectionRow {
                    element_id,
                    element_type,
                    activity_label: term_string(&solution, "activityLabel")?,
                    child_index: term_string(&solution, "childIndex")?,
                    child_model: term_string(&solution, "childModel")?,
                    precedes_target: term_string(&solution, "precedesTarget")?,
                    region_id: term_string(&solution, "regionId")?,
                    sparql_projection: term_string(&solution, "sparqlProjection")?,
                    tera_renderer: term_string(&solution, "teraRenderer")?,
                });
            }
        }
        _ => {
            return Err(Refusal::ValidationFailed(
                "render_model_projection.rq did not yield SELECT solutions".to_string(),
            ))
        }
    }
    Ok(rows)
}

/// Reads `var` out of `solution` as its lexical string form: an IRI's full
/// IRI text, or a literal's lexical value. Returns `Ok(None)` when `var` is
/// unbound (the common case for an `OPTIONAL` block that did not match this
/// row's element kind).
///
/// # Complexity
/// O(1).
fn term_string(solution: &QuerySolution, var: &str) -> Result<Option<String>, Refusal> {
    match solution.get(var) {
        None => Ok(None),
        Some(Term::NamedNode(n)) => Ok(Some(n.as_str().to_string())),
        Some(Term::Literal(l)) => Ok(Some(l.value().to_string())),
        Some(other) => Err(Refusal::ValidationFailed(format!(
            "projection variable ?{var} bound to unsupported term kind: {other}"
        ))),
    }
}

// ── External-cut Rail A/B compiler seam (PROJ-796) ──────────────────────────
//
// `ChatmanEngine::admit_transition_with_external_cut` (`chatman::engine`)
// needs to run Rail A's `T` stage (Tera render) and Rail B's Arazzo -> AIR
// lowering/compilation over a POWL region this module has already admitted
// and projected -- but the real implementations of those two stages live in
// `praxis-core` (`arazzo::render_arazzo_document` + `wasm4pm-arazzo`), and
// `praxis-core` already depends on `praxis-graphlaw` (see that crate's
// Cargo.toml comment). The reverse edge would be a cyclic crate dependency,
// so this crate cannot call into `praxis-core` directly. The trait below is
// the seam: `ChatmanEngine` depends on it, and the one real implementation
// this workspace ships (`praxis_core::arazzo::ChatmanRailAbCompiler`) is
// injected by the caller who already links both crates.

/// True when `model` contains at least one [`Powl::ExternalCut`] node
/// anywhere in the tree (a `PartialOrder`/`Choice` container's children are
/// scanned, but an already-found cut's own `region` is not further
/// descended into -- the same traversal boundary [`admit_powl_model`] uses,
/// since a cut's region is opaque to the projecting workflow by definition,
/// PRD.md sec.7.4).
///
/// This is the trigger `ChatmanEngine::admit_transition_with_external_cut`
/// uses to decide whether the real Rail A/B pipeline runs at all for a
/// given admission: PRD.md sec.19.1's "local POWL remains local" scenario
/// means a region with no declared cut never engages the pipeline.
///
/// # Complexity
/// O(n) in the total node count of the model tree; short-circuits on the
/// first hit.
pub fn model_declares_external_cut(model: &Powl) -> bool {
    match model {
        Powl::Leaf(_) => false,
        Powl::PartialOrder { children, .. } | Powl::Choice { children, .. } => {
            children.iter().any(model_declares_external_cut)
        }
        Powl::ExternalCut { .. } => true,
    }
}

/// Real materials handed to an [`ExternalCutCompiler`]: the admitted
/// region's own Turtle (already gated through [`admit_powl_model`] via
/// [`powl_to_turtle`]) plus the identity the manufactured Arazzo document
/// should carry.
#[derive(Debug, Clone, Copy)]
pub struct ExternalCutCompilationRequest<'a> {
    /// The admitted region's Turtle, `W` in `A_z = T(Q(W))` (PRD.md
    /// sec.7.4) -- already passed [`admit_powl_model`] (via
    /// [`powl_to_turtle`]) before this request is built.
    pub region_turtle: &'a str,
    /// The region's root subject IRI (`Q`'s starting point).
    pub root_element_id: &'a str,
    /// The manufactured Arazzo document's `workflowId`.
    pub workflow_id: &'a str,
    /// The manufactured Arazzo document's `info.title`.
    pub title: &'a str,
}

/// Real output of one [`ExternalCutCompiler::compile`] run: every material
/// digest an `ArazzoProjectionReceipt` (`praxis_core::arazzo`) needs, plus
/// the manufactured Arazzo document text itself. Deliberately mirrors that
/// type's fields (minus `external_cut_identity`, which the caller already
/// carries) rather than depending on it directly: this crate cannot depend
/// on `praxis-core` (see this section's header comment), so it defines its
/// own copy of the shape instead of importing it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExternalCutCompilationOutcome {
    /// BLAKE3 digest (hex) of `region_turtle`.
    pub source_powl_digest_hex: String,
    /// BLAKE3 digest (hex) of the SPARQL query text actually executed (Q).
    pub sparql_projection_digest_hex: String,
    /// BLAKE3 digest (hex) of the Tera template text actually rendered (T).
    pub tera_template_digest_hex: String,
    /// BLAKE3 digest (hex) of the manufactured Arazzo JSON document.
    pub arazzo_digest_hex: String,
    /// The compiler version string folded into the receipt.
    pub compiler_version: String,
    /// BLAKE3 digest (hex) of the compiled AIR module
    /// (`wasm4pm_arazzo::compile::AirCompiler::digest_program`).
    pub air_digest_hex: String,
    /// The manufactured Arazzo 1.1.x JSON document text (`A_z`).
    pub arazzo_document: String,
}

/// Rail A/B pipeline seam (PROJ-796). See this section's header comment for
/// why this is a trait rather than a direct call. Implementors must be
/// deterministic and perform no I/O beyond in-memory computation (no wall
/// clock, no randomness) -- the same discipline every other stage in this
/// module follows.
pub trait ExternalCutCompiler {
    /// Runs the real Q(W) SPARQL projection, T(...) Tera render, Arazzo
    /// parse/normalize, and AIR lowering/compilation over `request`.
    fn compile(
        &self,
        request: &ExternalCutCompilationRequest<'_>,
    ) -> Result<ExternalCutCompilationOutcome, Refusal>;
}

#[cfg(test)]
mod tests {
    use super::*;

    const PROJECTION: &str = "SELECT * WHERE { ?s ?p ?o }";
    const RENDERER: &str = "arazzo_step.tera";

    /// A minimal admitted region containing one external cut: a two-step
    /// `PartialOrder` where the second step is the cut. Exercises the
    /// admission walker's descent into a `PartialOrder`'s children (the cut
    /// is not the tree root), not just the trivial cut-at-root case already
    /// covered by `powl2_decompose::external_cut`'s own unit tests.
    fn model_with_external_cut() -> Powl {
        Powl::PartialOrder {
            children: vec![
                Powl::Leaf(Some("intake".to_string())),
                Powl::ExternalCut {
                    region: Box::new(Powl::Leaf(Some("remote_settle".to_string()))),
                    projection: PROJECTION.to_string(),
                    renderer: RENDERER.to_string(),
                },
            ],
            order: std::collections::BTreeSet::from([(0usize, 1usize)]),
        }
    }

    // ── Admission wiring (PROJ-751 part 1): validate_external_cut is a real
    // ── gate on powl_to_turtle, not an unwired test-only function.

    #[test]
    fn powl_to_turtle_admits_a_valid_external_cut() -> Result<(), Refusal> {
        let model = model_with_external_cut();
        let turtle = powl_to_turtle(&model, "urn:test:cut", None)?;
        assert!(turtle.contains("powl2:ExternalCut"));
        Ok(())
    }

    #[test]
    fn powl_to_turtle_refuses_external_cut_with_empty_projection() {
        let model = Powl::ExternalCut {
            region: Box::new(Powl::Leaf(Some("x".to_string()))),
            projection: String::new(),
            renderer: "t".to_string(),
        };
        let result = powl_to_turtle(&model, "urn:neg:empty-projection", None);
        assert!(
            matches!(
                &result,
                Err(Refusal::ValidationFailed(msg)) if msg.contains("EXTERNAL_CUT_UNDECLARED")
            ),
            "refusal must carry the typed ExternalCutRefusal reason, got: {result:?}"
        );
    }

    #[test]
    fn powl_to_turtle_refuses_nested_external_cut_inside_partial_order() {
        // The cut is a *child* of a PartialOrder, not the model root --
        // proves the admission walker descends into PartialOrder children
        // to find external cuts, rather than only checking a root-level cut.
        let inner_cut = Powl::ExternalCut {
            region: Box::new(Powl::Leaf(Some("b".to_string()))),
            projection: "q".to_string(),
            renderer: "t".to_string(),
        };
        let outer_cut = Powl::ExternalCut {
            region: Box::new(inner_cut),
            projection: "q2".to_string(),
            renderer: "t2".to_string(),
        };
        let model = Powl::PartialOrder {
            children: vec![Powl::Leaf(Some("a".to_string())), outer_cut],
            order: std::collections::BTreeSet::new(),
        };
        let result = powl_to_turtle(&model, "urn:neg:nested-cut", None);
        assert!(
            matches!(
                &result,
                Err(Refusal::ValidationFailed(msg)) if msg.contains("POWL_REGION_NOT_ADMITTED")
            ),
            "refusal must name the nested-cut reason, got: {result:?}"
        );
    }

    // ── Real SPARQL execution (PROJ-751 part 2): the corrected .rq query
    // ── actually runs, via oxigraph, against RDF powl_to_turtle emits, and
    // ── returns real rows -- not just "compiles".

    #[test]
    fn admitted_external_cut_produces_real_sparql_projection_rows() -> Result<(), Refusal> {
        let model = model_with_external_cut();
        let turtle = powl_to_turtle(&model, "urn:test:cut", None)?;

        let rows = run_render_model_projection(&turtle)?;
        assert!(
            !rows.is_empty(),
            "the corrected query must yield real result rows over real emitted RDF"
        );

        // Exactly one ExternalCut-typed row, with the real Q/T/W triple.
        let cut_type = format!("{POWL2_PREFIX}ExternalCut");
        let cut_rows: Vec<&ProjectionRow> =
            rows.iter().filter(|r| r.element_type == cut_type).collect();
        assert_eq!(
            cut_rows.len(),
            1,
            "expected exactly one ExternalCut row, got {cut_rows:?}"
        );
        let cut_row = cut_rows[0];
        assert_eq!(cut_row.element_id, "urn:test:cut/n0/c1");
        assert_eq!(
            cut_row.region_id.as_deref(),
            Some("urn:test:cut/n0/c1/region")
        );
        assert_eq!(cut_row.sparql_projection.as_deref(), Some(PROJECTION));
        assert_eq!(cut_row.tera_renderer.as_deref(), Some(RENDERER));

        // The activity inside the cut's admitted region was itself
        // projected -- proving W (the region) round-tripped through Turtle
        // and back out through the SPARQL query, not just the cut wrapper.
        assert!(
            rows.iter()
                .any(|r| r.element_id == "urn:test:cut/n0/c1/region"
                    && r.activity_label.as_deref() == Some("remote_settle")),
            "the external cut's admitted region must appear in the projection"
        );

        // The sibling activity outside the cut is projected too.
        assert!(
            rows.iter().any(|r| r.element_id == "urn:test:cut/n0/c0"
                && r.activity_label.as_deref() == Some("intake")),
            "activities outside the cut must still be projected"
        );

        // The real precedes edge between the two top-level bindings.
        assert!(
            rows.iter()
                .any(|r| r.element_id == "urn:test:cut/n0/binding/0"
                    && r.precedes_target.as_deref() == Some("urn:test:cut/n0/binding/1")),
            "the transitively-closed order relation must survive Turtle round-trip"
        );

        Ok(())
    }

    #[test]
    fn run_render_model_projection_is_deterministic() -> Result<(), Refusal> {
        let model = model_with_external_cut();
        let turtle = powl_to_turtle(&model, "urn:test:cut-determinism", None)?;
        let rows_a = run_render_model_projection(&turtle)?;
        let rows_b = run_render_model_projection(&turtle)?;
        assert_eq!(
            rows_a, rows_b,
            "identical Turtle input must yield byte-identical projection rows across repeated runs"
        );
        Ok(())
    }

    #[test]
    fn run_render_model_projection_refuses_unparsable_turtle() {
        let result = run_render_model_projection("this is not turtle {{{");
        assert!(
            matches!(result, Err(Refusal::ValidationFailed(_))),
            "expected ValidationFailed on unparsable input"
        );
    }

    // ── model_declares_external_cut (PROJ-796 trigger check) ────────────

    #[test]
    fn model_declares_external_cut_is_true_for_a_nested_cut() {
        assert!(model_declares_external_cut(&model_with_external_cut()));
    }

    #[test]
    fn model_declares_external_cut_is_false_with_no_cut_anywhere() {
        let model = Powl::PartialOrder {
            children: vec![
                Powl::Leaf(Some("a".to_string())),
                Powl::Leaf(Some("b".to_string())),
            ],
            order: std::collections::BTreeSet::from([(0usize, 1usize)]),
        };
        assert!(!model_declares_external_cut(&model));
    }

    #[test]
    fn model_declares_external_cut_is_false_for_a_single_leaf() {
        assert!(!model_declares_external_cut(&Powl::Leaf(None)));
    }
}
