//! Projects Chatman Engine PDDL plan tapes ([`Pddl8Tape`]) into POWL 2.0
//! models ([`Powl`], Kourani et al. Defs 3.6-3.9) and serializes those models
//! as RDF Turtle conforming to the `powl2:` vocabulary
//! (`wasm4pm-compat/ontologies/powlv2.ttl`).
//!
//! Both functions are pure: no I/O, no wall clock, no randomness. IRIs
//! generated by [`powl_to_turtle`] are derived deterministically from
//! `base_iri` plus a stable structural path (child index at each level of
//! the tree), never from a blank-node counter or hash map iteration order.

use bcinr_pddl::Pddl8Tape;
use powl2_decompose::{GNode, Powl};

use super::abi::Refusal;

/// Projects a bounded, sequential Chatman Engine PDDL plan tape into a POWL 2.0
/// model (Kourani et al. Defs 3.6-3.9), matching crates/powl2-decompose's Powl type.
///
/// # Complexity
/// O(n) where n = tape.ops.len() — one Leaf + one order pair per op, no nested search.
pub fn project_pddl_tape_to_powl(tape: &Pddl8Tape) -> Result<Powl, Refusal> {
    if tape.ops.is_empty() {
        return Err(Refusal::PlanInfeasible(
            "cannot project an empty PDDL plan tape to a POWL model".to_string(),
        ));
    }

    let children: Vec<Powl> = tape
        .ops
        .iter()
        .map(|op| Powl::Leaf(Some(op.label.clone())))
        .collect();

    // Pddl8Tape::from_plan encodes a strict linear (total) order over ops:
    // op i>0 depends only on op i-1 via pred_mask, but the honest projection
    // of a total sequential order is its full transitive closure — every
    // earlier op strictly precedes every later op, not just its immediate
    // predecessor. n = children.len(); this loop is O(n^2) pairs, which is
    // O(n) in the *output* size (the transitively-closed order relation is
    // itself quadratic in a total order of n elements) and is bounded by the
    // 8-bit tape width (n <= 256) enforced upstream by Pddl8Tape.
    let n = children.len();
    let mut order = std::collections::BTreeSet::new();
    for i in 0..n {
        for j in (i + 1)..n {
            order.insert((i, j));
        }
    }

    Ok(Powl::PartialOrder { children, order })
}

/// Projects a bounded, sequential Chatman Engine PDDL plan tape into a
/// *hierarchical* (2-level) POWL 2.0 model: tape ops are grouped into
/// phases, a phase being a maximal run of tape-adjacent ops whose action
/// schemas share the same contributing source artifact per
/// `action_sources` (schema name → source artifact IRI). Each phase becomes
/// a `Powl::PartialOrder` over `Leaf(Some(label))` children with the
/// transitively closed intra-phase order; the root is a `PartialOrder` over
/// the phase children with the transitively closed inter-phase order. A
/// single-source tape still yields this uniform 2-level shape (one phase).
///
/// Sibling to [`project_pddl_tape_to_powl`], which stays flat. No new
/// semantic authority is introduced: nesting is derived purely from the
/// supplied provenance mapping.
///
/// Returns the model plus `phase_sources`: one source artifact IRI per
/// top-level phase child, in phase order.
///
/// Deterministic: grouping is driven solely by tape order and `BTreeMap`
/// lookups — no hash-map iteration, no wall clock, no randomness.
///
/// # Errors
/// - [`Refusal::PlanInfeasible`] for an empty tape (same refusal as the
///   flat projection).
/// - [`Refusal::ValidationFailed`] if a tape op's action schema has no
///   contributing source artifact in `action_sources` — the hierarchical
///   model would be detached from its admitted inputs.
///
/// # Complexity
/// O(n log n) to group n = tape.ops.len() ops into phases (one BTreeMap
/// lookup per op), plus O(n^2) total across all levels to store the
/// transitively closed order relations — the same asymptotic bound as the
/// flat projection, split across the phase and root levels, and bounded by
/// the 8-bit tape width (n <= 256) enforced upstream by [`Pddl8Tape`].
pub fn project_pddl_tape_to_powl_hierarchical(
    tape: &Pddl8Tape,
    action_sources: &std::collections::BTreeMap<String, String>,
) -> Result<(Powl, Vec<String>), Refusal> {
    if tape.ops.is_empty() {
        return Err(Refusal::PlanInfeasible(
            "cannot project an empty PDDL plan tape to a POWL model".to_string(),
        ));
    }

    // Group into maximal tape-adjacent runs sharing the same source
    // artifact. O(n log n): one BTreeMap lookup per op, tape order only.
    let mut phases: Vec<(String, Vec<usize>)> = Vec::new();
    for (i, op) in tape.ops.iter().enumerate() {
        let source = action_sources
            .get(&op.action.schema_name)
            .cloned()
            .ok_or_else(|| {
                Refusal::ValidationFailed(format!(
                    "plan op {:?} has no contributing source artifact in action_sources; \
                     hierarchical POWL output would be detached from its inputs",
                    op.action.schema_name
                ))
            })?;
        match phases.last_mut() {
            Some((last_source, indices)) if *last_source == source => indices.push(i),
            _ => phases.push((source, vec![i])),
        }
    }

    let phase_sources: Vec<String> = phases.iter().map(|(source, _)| source.clone()).collect();

    // Each phase: leaves in tape order with the transitively closed
    // intra-phase total order (O(k^2) pairs per phase of k ops — see the
    // flat projection's rationale: the closed relation is itself quadratic).
    let phase_children: Vec<Powl> = phases
        .into_iter()
        .map(|(_, indices)| {
            let leaves: Vec<Powl> = indices
                .iter()
                .map(|&i| Powl::Leaf(Some(tape.ops[i].label.clone())))
                .collect();
            let k = leaves.len();
            let mut order = std::collections::BTreeSet::new();
            for a in 0..k {
                for b in (a + 1)..k {
                    order.insert((a, b));
                }
            }
            Powl::PartialOrder {
                children: leaves,
                order,
            }
        })
        .collect();

    // Root: phases in tape order with the transitively closed inter-phase
    // total order (O(p^2) pairs for p phases).
    let p = phase_children.len();
    let mut root_order = std::collections::BTreeSet::new();
    for a in 0..p {
        for b in (a + 1)..p {
            root_order.insert((a, b));
        }
    }

    Ok((
        Powl::PartialOrder {
            children: phase_children,
            order: root_order,
        },
        phase_sources,
    ))
}

const POWL2_PREFIX: &str = "https://truex.io/ontology/powl2#";

/// Escapes a string literal for safe embedding in a Turtle `"..."` literal.
///
/// # Complexity
/// O(len(s)) — single linear pass.
fn escape_turtle_literal(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(c),
        }
    }
    out
}

/// Serializes a POWL 2.0 model as RDF Turtle conforming to the powl2: vocabulary
/// (wasm4pm-compat/ontologies/powlv2.ttl). Deterministic: no HashMap iteration,
/// blank-node-equivalent IRIs are derived from `base_iri` + a stable path (child
/// index at each level), and PartialOrder's `order` set (a BTreeSet) is emitted
/// in its natural sorted order.
///
/// For a plan projected by [`project_pddl_tape_to_powl`], the emitted
/// `powl2:precedes` relation is the transitive closure of the plan sequence:
/// Kourani Def 3.7 defines PartialOrder over a *strict partial order*, and the
/// crate's own `Powl::PartialOrder.order` stores that relation pre-closed, so
/// the Turtle mirrors the in-memory relation one triple per pair rather than
/// re-deriving adjacency. This choice is pinned by the projection tests.
///
/// `derived_from`: when `Some(iri)`, the root model node additionally carries
/// `powl2:derivedFrom <iri>` (a subproperty of `prov:wasDerivedFrom` in the
/// vocabulary), linking the manufactured POWL model back to the PDDL plan
/// source it was projected from (e.g. the snapshot IRI whose embedded PDDL
/// text produced the tape).
///
/// # Complexity
/// O(n + |order|) in the total node count of the model tree plus the size of
/// each PartialOrder's (pre-closed, up to quadratic) order relation.
pub fn powl_to_turtle(model: &Powl, base_iri: &str, derived_from: Option<&str>) -> String {
    let base_iri = base_iri.trim_end_matches('/');
    let mut out = String::new();
    out.push_str("@prefix powl2: <");
    out.push_str(POWL2_PREFIX);
    out.push_str("> .\n");
    out.push_str("@prefix base: <");
    out.push_str(base_iri);
    out.push_str("/> .\n\n");

    let root_path = "n0";
    out.push_str(&format!("<{base_iri}/{root_path}> a powl2:Model .\n"));
    if let Some(source_iri) = derived_from {
        out.push_str(&format!(
            "<{base_iri}/{root_path}> powl2:derivedFrom <{source_iri}> .\n"
        ));
    }
    emit_powl_node(model, base_iri, root_path, &mut out);
    out
}

/// Recursively emits Turtle triples for `model`, whose subject IRI is
/// `<base_iri>/<path>`. Child IRIs are `<base_iri>/<path>/c<index>` and
/// `PartialOrder` child-bindings are addressed at
/// `<base_iri>/<path>/binding/<index>` — both deterministic, structural, and
/// collision-free (each level appends a distinct literal segment).
///
/// # Complexity
/// O(n) in the size of the subtree rooted at `model`.
fn emit_powl_node(model: &Powl, base_iri: &str, path: &str, out: &mut String) {
    match model {
        Powl::Leaf(None) => {
            out.push_str(&format!(
                "<{base_iri}/{path}> a powl2:Leaf, powl2:SilentLeaf .\n"
            ));
        }
        Powl::Leaf(Some(label)) => {
            out.push_str(&format!(
                "<{base_iri}/{path}> a powl2:Leaf, powl2:ActivityLeaf ;\n"
            ));
            out.push_str(&format!(
                "  powl2:activityLabel \"{}\" .\n",
                escape_turtle_literal(label)
            ));
        }
        Powl::PartialOrder { children, order } => {
            out.push_str(&format!("<{base_iri}/{path}> a powl2:PartialOrder .\n"));
            for (idx, child) in children.iter().enumerate() {
                let child_path = format!("{path}/c{idx}");
                let binding_path = format!("{path}/binding/{idx}");
                out.push_str(&format!(
                    "<{base_iri}/{path}> powl2:hasChild <{base_iri}/{binding_path}> .\n"
                ));
                out.push_str(&format!(
                    "<{base_iri}/{binding_path}> a powl2:ChildBinding ;\n  powl2:childIndex {idx} ;\n  powl2:childModel <{base_iri}/{child_path}> .\n"
                ));
                emit_powl_node(child, base_iri, &child_path, out);
            }
            for (i, j) in order.iter() {
                out.push_str(&format!(
                    "<{base_iri}/{path}/binding/{i}> powl2:precedes <{base_iri}/{path}/binding/{j}> .\n"
                ));
            }
        }
        Powl::Choice { children, graph } => {
            // Vocabulary terms per powlv2.ttl: the ▷/□ sentinels are typed
            // powl2:StartNode / powl2:EndNode resources pointed at by the
            // functional powl2:startNode / powl2:endNode properties; each
            // routing edge is a reified powl2:GraphEdge with edgeSource /
            // edgeTarget; children are addressed both as ChildBindings and as
            // powl2:ChildNode routing-graph nodes.
            out.push_str(&format!("<{base_iri}/{path}> a powl2:ChoiceGraph .\n"));
            out.push_str(&format!(
                "<{base_iri}/{path}/start> a powl2:StartNode .\n<{base_iri}/{path}/end> a powl2:EndNode .\n"
            ));
            out.push_str(&format!(
                "<{base_iri}/{path}> powl2:startNode <{base_iri}/{path}/start> ;\n  powl2:endNode <{base_iri}/{path}/end> ;\n  powl2:hasNode <{base_iri}/{path}/start>, <{base_iri}/{path}/end> .\n"
            ));
            for (idx, child) in children.iter().enumerate() {
                let child_path = format!("{path}/c{idx}");
                let binding_path = format!("{path}/binding/{idx}");
                out.push_str(&format!(
                    "<{base_iri}/{path}> powl2:hasChild <{base_iri}/{binding_path}> .\n"
                ));
                out.push_str(&format!(
                    "<{base_iri}/{binding_path}> a powl2:ChildBinding ;\n  powl2:childIndex {idx} ;\n  powl2:childModel <{base_iri}/{child_path}> .\n"
                ));
                out.push_str(&format!(
                    "<{base_iri}/{path}/node/{idx}> a powl2:ChildNode ;\n  powl2:ofChildIndex {idx} .\n"
                ));
                out.push_str(&format!(
                    "<{base_iri}/{path}> powl2:hasNode <{base_iri}/{path}/node/{idx}> .\n"
                ));
                emit_powl_node(child, base_iri, &child_path, out);
            }
            for (edge_idx, (from, to)) in graph.edges.iter().enumerate() {
                let from_iri = gnode_iri(base_iri, path, *from);
                let to_iri = gnode_iri(base_iri, path, *to);
                out.push_str(&format!(
                    "<{base_iri}/{path}/edge/{edge_idx}> a powl2:GraphEdge ;\n  powl2:edgeSource {from_iri} ;\n  powl2:edgeTarget {to_iri} .\n"
                ));
                out.push_str(&format!(
                    "<{base_iri}/{path}> powl2:hasEdge <{base_iri}/{path}/edge/{edge_idx}> .\n"
                ));
            }
        }
    }
}

/// Renders a [`GNode`] as a complete bracketed Turtle IRI term relative to the
/// choice-graph node at `<base_iri>/<path>`: the artificial `▷`/`□` sentinels
/// become fixed `/start` / `/end` suffixed IRIs, and a child index becomes its
/// `/node/<idx>` routing-graph node IRI.
///
/// # Complexity
/// O(1).
fn gnode_iri(base_iri: &str, path: &str, node: GNode) -> String {
    match node {
        GNode::Start => format!("<{base_iri}/{path}/start>"),
        GNode::End => format!("<{base_iri}/{path}/end>"),
        GNode::Child(idx) => format!("<{base_iri}/{path}/node/{idx}>"),
    }
}
