# GENERATED by `ggen sync` from packs/azure-terraform-pack/ontology.ttl --
# do not edit by hand. Resource SHAPE (argument names, `container` block
# structure, `timeouts` block) is adapted from
# Azure/terraform-azurerm-avm-res-containerinstance-containergroup's main.tf
# (MIT License; resource "azurerm_container_group" "this", verified this
# session via
# https://raw.githubusercontent.com/Azure/terraform-azurerm-avm-res-containerinstance-containergroup/main/main.tf).
# `os_type`/`restart_policy`/`ip_address_type` and each `container` block's
# `name`/`cpu`/`memory`/`commands` below are bound from
# packs/azure-terraform-pack/ontology.ttl (plus, when a deployment's
# individual lives in its own file, an extra_ontologies-unioned
# packs/azure-terraform-pack/instances/*.ttl -- see that individual's own
# aztf:deploymentSlug) real, grounded facts -- never hand-edited here. This
# file renders once per aztf:ContainerGroup individual in the graph (Tera
# per-row rendering keyed on aztf:deploymentSlug, see this template's `to:`
# frontmatter), so multiple deployments can coexist in one graph without
# colliding.
#
# DISCLOSED DIVERGENCE from the AVM source (full ledger:
# packs/azure-terraform-pack/SOURCE_ATTRIBUTION.md): that module accepts an
# arbitrary runtime `containers` map(object) variable and renders it via a
# Terraform-native `dynamic "container"` block (its main.tf lines 17-108),
# because it is a general-purpose reusable module whose container topology
# is a caller-supplied runtime value. This pack's container topology is
# instead fixed by the ontology graph at *generate* time -- M&A case study — ggen graph validate compliance check (packs/ma-case-study-pack ontology + shapes + case fixture)
# -- so the loop below runs in Tera at generation time instead of in HCL
# `dynamic` at plan time. `azurerm_role_assignment "this"` (main.tf lines
# 160-171) is not ported for either individual this pack currently
# generates: no managed-identity/Key-Vault requirement is evidenced for
# crown-bribery-case (grep for std::env::var in
# crates/multifractal-workflow/src/ returns zero hits) or for the M&A case
# study validator (a local `ggen graph validate` CLI invocation needs no
# Azure credential).
#
# `commands` below is rendered as `["/bin/sh", "-c", "<aztf:command>"]`
# rather than a single argv element: aztf:command now holds a full shell
# command line (see that property's own rdfs:comment in ontology.ttl for
# why this was generalized from an earlier single-argv-element rendering).
resource "azurerm_resource_group" "this" {
  name     = var.resource_group_name
  location = var.location
  tags     = local.tags
}

resource "azurerm_container_group" "this" {
  name                = var.name
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  os_type             = "Linux"
  restart_policy      = "Never"
  ip_address_type     = "None"
  tags                = local.tags

  container {
    name     = "ma-case-validator"
    image    = var.container_image
    cpu      = 1
    memory   = 1
    commands = ["/bin/sh", "-c", "/app/ggen graph validate --files /app/packs/ma-case-study-pack/fixtures/case.ttl,/app/packs/ma-case-study-pack/ontology.ttl --shapes /app/packs/ma-case-study-pack/shapes.ttl"]
  }

  timeouts {
    create = "2h"
    update = "2h"
  }
}
