# GENERATED by `ggen sync` from packs/azure-terraform-pack/templates/providers.tf.tmpl
# -- do not edit by hand. Renders once per aztf:ContainerGroup individual;
# this file's own content is workload-agnostic boilerplate, identical
# across every deployment.
#
# CUSTOM, not adapted from the AVM source: Terraform CHILD modules (like
# Azure/terraform-azurerm-avm-res-containerinstance-containergroup) declare
# no `terraform{}`/`provider{}` block of their own -- they inherit the
# caller's provider configuration -- so there is no real source to adapt
# for this file. See packs/azure-terraform-pack/SOURCE_ATTRIBUTION.md.
#
# required_version >= 1.7.1: the minimum Terraform core version at which
# `mock_provider "azurerm" {}` plus a root `provider "azurerm" { features {} }`
# block is confirmed to work together (hashicorp/terraform#34489, fixed by
# PR hashicorp/terraform#34481, shipped in Terraform 1.7.0/1.7.1 -- verified
# via that issue's own GitHub comment thread this session, not a blog
# summary). This pack's own tests/container_group.tftest.hcl depends
# on that fix.

terraform {
  required_version = ">= 1.7.1"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.90"
    }
  }
}

provider "azurerm" {
  features {}
}
