//! Generative Typestates & Integrity Primitives for `my-conforming-project`.
//! Generated by ggen-first pipeline. Do not edit manually.

use std::{fmt, marker::PhantomData};

use serde::{Deserialize, Serialize};

// --- Content Addressing ---

/// A BLAKE3 content hash encoded as a lowercase hex string.
///
/// Used throughout the crate to uniquely identify byte payloads by content.
/// Two values are equal iff they were produced from identical bytes.
///
/// # Examples
///
/// ```
/// use praxis::types::Blake3Hash;
///
/// let hash = Blake3Hash::content_address(b"hello world");
/// assert_eq!(hash.as_hex().len(), 64); // 32 bytes → 64 hex chars
///
/// let roundtrip = Blake3Hash::from_hex(hash.as_hex());
/// assert_eq!(hash, roundtrip);
/// ```
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct Blake3Hash(pub String);

impl Blake3Hash {
    /// Hash `bytes` with BLAKE3 and return the digest as a hex-encoded [`Blake3Hash`].
    ///
    /// This is the primary constructor for content-addressed values; use it any time
    /// you need a stable, collision-resistant identifier for a byte payload.
    ///
    /// # Examples
    ///
    /// ```
    /// use praxis::types::Blake3Hash;
    ///
    /// let h1 = Blake3Hash::content_address(b"foo");
    /// let h2 = Blake3Hash::content_address(b"foo");
    /// assert_eq!(h1, h2);
    ///
    /// let h3 = Blake3Hash::content_address(b"bar");
    /// assert_ne!(h1, h3);
    /// ```
    pub fn content_address(bytes: &[u8]) -> Self {
        Blake3Hash(blake3::hash(bytes).to_hex().to_string())
    }

    /// Construct a [`Blake3Hash`] from an existing hex string without re-hashing.
    ///
    /// No validation is performed; the caller must ensure `hex` is a valid 64-char
    /// lowercase BLAKE3 hex digest if round-trip correctness is required.
    pub fn from_hex(hex: impl Into<String>) -> Self {
        Blake3Hash(hex.into())
    }

    /// Return the hex-encoded digest as a string slice.
    pub fn as_hex(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for Blake3Hash {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl From<String> for Blake3Hash {
    fn from(s: String) -> Self {
        Blake3Hash(s)
    }
}

impl From<Blake3Hash> for String {
    fn from(h: Blake3Hash) -> Self {
        h.0
    }
}

// --- Object References (OCEL Conformant) ---

/// A typed, optionally-qualified reference to a process object (OCEL-conformant).
///
/// Encodes the triple `(id, type, qualifier?)` used in Object-Centric Event Logs
/// to cross-reference objects from different object types within a single event.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ObjectRef {
    /// Unique identifier of the referenced object within its type namespace.
    pub id: String,
    /// OCEL object type name (serialized as `"type"` in JSON).
    #[serde(rename = "type")]
    pub type_: String,
    /// Optional role qualifier disambiguating multiple refs of the same type in one event.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub qualifier: Option<String>,
}

impl fmt::Display for ObjectRef {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match &self.qualifier {
            Some(q) => write!(f, "{}:{}:{}", self.id, self.type_, q),
            None => write!(f, "{}:{}", self.id, self.type_),
        }
    }
}

// --- Canonical Serialization (Key-sorted JSON) ---

/// Serialize `value` to JSON with all object keys sorted lexicographically.
///
/// Canonical serialization ensures that two structurally identical values always
/// produce the same byte representation, enabling stable content addressing via
/// [`Blake3Hash::content_address`].
pub fn canonical_bytes<T: Serialize>(value: &T) -> Result<Vec<u8>, serde_json::Error> {
    let v = serde_json::to_value(value)?;
    let sorted = sort_value(v);
    serde_json::to_vec(&sorted)
}

fn sort_value(value: serde_json::Value) -> serde_json::Value {
    use serde_json::Value;
    match value {
        Value::Object(map) => {
            let sorted: std::collections::BTreeMap<String, Value> =
                map.into_iter().map(|(k, v)| (k, sort_value(v))).collect();
            let mut out = serde_json::Map::new();
            for (k, v) in sorted {
                out.insert(k, v);
            }
            Value::Object(out)
        }
        Value::Array(arr) => Value::Array(arr.into_iter().map(sort_value).collect()),
        other => other,
    }
}

// --- ZST Lifecycle State Markers ---
mod sealed {
    pub trait LifecycleState {}
}

/// Zero-sized typestate marker for evidence that has not yet been validated.
pub struct Raw;
impl sealed::LifecycleState for Raw {}

/// Zero-sized typestate marker for evidence that has passed schema/rule validation.
pub struct Validated;
impl sealed::LifecycleState for Validated {}

/// Zero-sized typestate marker for evidence that has been cryptographically admitted.
pub struct Admitted;
impl sealed::LifecycleState for Admitted {}

// --- Zero-Overhead Evidence Carriage ---

/// A zero-overhead typestate wrapper that tracks the lifecycle stage of a value `T`.
///
/// The three lifecycle states — [`Raw`], [`Validated`], and [`Admitted`] — are encoded
/// as phantom type parameters so the compiler rejects out-of-order transitions at compile
/// time with no runtime cost.  `Witness` is an additional phantom marker that records
/// *which* admission policy was applied.
///
/// # Type Parameters
///
/// - `T` — the wrapped payload type.
/// - `State` — current lifecycle stage; one of [`Raw`], [`Validated`], or [`Admitted`].
/// - `Witness` — zero-sized type identifying the admitter that approved the transition.
///
/// # Examples
///
/// ```
/// use praxis::types::{Evidence, Raw};
///
/// struct MyWitness;
///
/// let ev: Evidence<u32, Raw, MyWitness> = Evidence::new(42u32);
/// assert_eq!(*ev.inner(), 42);
/// ```
pub struct Evidence<T, State: sealed::LifecycleState, Witness> {
    inner: T,
    _state: PhantomData<State>,
    _witness: PhantomData<Witness>,
}

impl<T, Witness> Evidence<T, Raw, Witness> {
    /// Wrap `inner` in the [`Raw`] lifecycle stage.
    pub fn new(inner: T) -> Self {
        Self { inner, _state: PhantomData, _witness: PhantomData }
    }

    /// Return a shared reference to the wrapped value.
    pub fn inner(&self) -> &T {
        &self.inner
    }
}

impl<T, Witness> Evidence<T, Validated, Witness> {
    /// Return a shared reference to the validated payload.
    pub fn inner(&self) -> &T {
        &self.inner
    }

    pub(crate) fn validate_unchecked(inner: T) -> Self {
        Self { inner, _state: PhantomData, _witness: PhantomData }
    }
}

impl<T, Witness> Evidence<T, Admitted, Witness> {
    /// Return a shared reference to the admitted payload.
    pub fn inner(&self) -> &T {
        &self.inner
    }

    pub(crate) fn admit_unchecked(inner: T) -> Self {
        Self { inner, _state: PhantomData, _witness: PhantomData }
    }
}

// --- Convenience aliases for evidence ---

/// Shorthand for [`Evidence`] in the [`Raw`] (unvalidated) lifecycle stage.
pub type RawEvidence<T, W> = Evidence<T, Raw, W>;

/// Shorthand for [`Evidence`] in the [`Validated`] lifecycle stage.
pub type ValidatedEvidence<T, W> = Evidence<T, Validated, W>;

/// Shorthand for [`Evidence`] in the [`Admitted`] (fully approved) lifecycle stage.
pub type AdmittedEvidence<T, W> = Evidence<T, Admitted, W>;

// --- One-Way Admission Trait ---

/// A one-way gate that promotes [`Raw`] evidence to [`Admitted`] evidence.
///
/// Implementors define the admission policy for a specific payload type.  The
/// transition is one-directional: once evidence is admitted, it cannot revert
/// to [`Raw`].  The `Witness` associated type brands the output so call sites
/// can prove *which* policy admitted it.
///
/// # Examples
///
/// ```ignore
/// use praxis::types::{Admit, Evidence, Raw, Admitted};
///
/// struct AlwaysAdmit;
/// struct AlwaysAdmitWitness;
///
/// impl Admit for AlwaysAdmit {
///     type Input = u32;
///     type Witness = AlwaysAdmitWitness;
///     type Error = std::convert::Infallible;
///
///     fn admit(
///         input: Evidence<u32, Raw, AlwaysAdmitWitness>,
///     ) -> Result<Evidence<u32, Admitted, AlwaysAdmitWitness>, Self::Error> {
///         // In real code use the crate-internal admit_unchecked after performing checks.
///         todo!()
///     }
/// }
/// ```
pub trait Admit {
    /// The payload type being admitted.
    type Input;
    /// Zero-sized type that brands admitted evidence with the policy identity.
    type Witness;
    /// Error returned when admission is refused.
    type Error;

    /// Attempt to promote `input` from [`Raw`] to [`Admitted`].
    ///
    /// Returns `Ok(admitted)` on success or `Err(Self::Error)` if the policy rejects
    /// the input.
    fn admit(
        input: Evidence<Self::Input, Raw, Self::Witness>,
    ) -> Result<Evidence<Self::Input, Admitted, Self::Witness>, Self::Error>;
}

// --- Sealed Cryptographic Admission Receipt ---

/// An unforgeable receipt proving that a chain of evidence was admitted at `timestamp`.
///
/// The `_seal` field is private, preventing construction outside this module; use
/// the crate-internal [`AdmittedReceipt::new`] constructor.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AdmittedReceipt {
    /// BLAKE3 chain hash over the admitted evidence payload.
    pub chain_hash: [u8; 32],
    /// Unix timestamp (seconds) at which admission was recorded.
    pub timestamp: u64,
    #[serde(skip)]
    _seal: (), // Private seal field
}

impl AdmittedReceipt {
    pub(crate) fn new(chain_hash: [u8; 32], timestamp: u64) -> Self {
        Self { chain_hash, timestamp, _seal: () }
    }
}

// --- Forward Compatibility (non_exhaustive) ---

/// Identifies the conformance profile version used to validate an event log.
///
/// Marked `#[non_exhaustive]` so that new profile variants can be added in
/// future minor releases without breaking downstream match arms.
#[non_exhaustive]
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProfileId {
    /// The first stable core profile (`"core/v1"`).
    CoreV1,
}

impl ProfileId {
    /// Return the canonical string identifier for this profile (e.g. `"core/v1"`).
    pub fn as_str(&self) -> &'static str {
        match self {
            ProfileId::CoreV1 => "core/v1",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_blake3_hash_is_deterministic() {
        let h1 = Blake3Hash::content_address(b"hello world");
        let h2 = Blake3Hash::content_address(b"hello world");
        assert_eq!(h1, h2);
        let h3 = Blake3Hash::content_address(b"different input");
        assert_ne!(h1, h3);
    }

    #[test]
    fn test_evidence_new_creates_raw() {
        let ev = Evidence::<String, Raw, ()>::new("hello".to_string());
        assert_eq!(ev.inner(), "hello");
    }

    #[test]
    fn test_validation_chain_finish_ok() {
        use crate::error::ValidationChain;
        assert!(ValidationChain::new().finish().is_ok());
    }
}

// --- Compile-time ZST Layout Asserts ---
#[allow(dead_code)]
mod layout_assertions {
    use std::mem::size_of;

    use super::*;

    const _RAW_IS_ZST: () = {
        assert!(size_of::<Raw>() == 0, "Raw marker must stay ZST");
    };
    const _VALIDATED_IS_ZST: () = {
        assert!(size_of::<Validated>() == 0, "Validated marker must stay ZST");
    };
    const _ADMITTED_IS_ZST: () = {
        assert!(size_of::<Admitted>() == 0, "Admitted marker must stay ZST");
    };

    const _EVIDENCE_NO_OVERHEAD: () = {
        assert!(
            size_of::<Evidence<u64, Raw, Raw>>() == size_of::<u64>(),
            "Evidence must be zero-overhead over T when State/Witness are ZSTs"
        );
    };
}
